### PR TITLE
fix license headers

### PR DESCRIPTION
**Pull request by maggu2810**
As documented it would be good practice to run `mvn license:format` in front of a commit, so new files use the correct license headers.

### CODE REVIEW

**Comment by maggu2810** [comment]
Should we exclude the `tools/archetype` directory or at least `tools/archetype/binding/src/main/resources/archetype-resources/OSGI-INF/__bindingIdCamelCase__HandlerFactory.xml`?

**Comment by kaikreuzer** [comment]
> Should we exclude the tools/archetype directory

I guess so, yes.

**Comment by maggu2810** [comment]
IMHO we should use "Rebase and merge" for this PR. If you have a look at the first commit, it clean up the include and exclude section first.
The second one applies the correct license header update itself.

**Comment by kaikreuzer** [comment]
done, thanks.

**Pull request merged**
