### PR TITLE
[Homematic] BINRPC changed to XMLRPC protocol due to CCU firmware 3.41.x

### PR DESCRIPTION
**Pull request by gerrieg**
Signed-off-by: Gerhard Riegler <gerhard.riegler@gmail.com>

see https://github.com/eclipse/smarthome/issues/6446

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Shall we wait with the merge until you (or someone else) had a chance to test it? Or does it anyhow not harm as the feature is broken right now in any case?

**Comment by gerrieg** [comment]
It doesn't harm, this works safely with the current firmwares and maybe with the newest too.

**Comment by bottkars** [comment]
Just set up a brand new 2.4.0-M5 System with CCU3.
Can i download a patched Plugin somewhere to test ?

**Comment by kaikreuzer** [comment]
Should be included in https://ci.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/3093/artifact/distribution/target/eclipsesmarthome-incubation-0.10.0-SNAPSHOT-repo.zip

**Comment by bottkars** [comment]
Great ! Will give it a try !!!

**Comment by ptweety** [comment]
The bindings docs should also be updated ;)

**Comment by alexreinert** [comment]
As far as I understand it, CUxD currently only supports BinRPC, so this PR would break the communication with CUxD.

**Comment by exo1987** [comment]
CUxD is not working anymore. Any chances to get this working?

**Comment by kaikreuzer** [comment]
@gerrieg Any suggestion how to solve this?

@exo1987 Could you please open a new issue for it, so that the discussion does not happen on a merged PR? Thanks!

**Comment by alexreinert** [comment]
Short term solution: Set CUxD back to BinRPC, this shouldvwork this the Relaxed security setting and an additional configured port in the CCU firewall.
Long term solution: Make it all configurable: Type of RPC transport, SSL/unencrypted (which also involves changed ports), Username/Password.

**Comment by exo1987** [comment]
Thank you guys. I opened a new issue:

https://github.com/eclipse/smarthome/issues/6493

@alexreinert Would be great if you describe this way of setting back to BinRPC.

**Comment by gerrieg** [comment]
I changed CUxD back to BinRPC with https://github.com/eclipse/smarthome/pull/6494

Everything else when the next RaspberryMatic is released and I can test it myself.

**Pull request merged**
