### PR TITLE
Added SafeMethodCaller to allow safe method calls and integrated it i…

### PR DESCRIPTION
**Pull request by dnobel**
…n ThingManager and OSGiEventManager.

Bug: 472406
Signed-off-by: Dennis Nobel <d.nobel@external.telekom.de>

### CODE REVIEW

**Comment by dnobel** [comment]
We could definitely discuss about the default timeout. I have set it to 5 seconds. But maybe there are good reasons to set it to 30 seconds as OSGi does.

Moreover I´m not 100% sure, if the used thread pool is the best choice and if there might be any problems regarding multithreading.

**Comment by kgoderis** [comment]
I would love to test this in my operational environment. Basically, you render this part of the core asynchronous. It is "pure" protection you wanted, then maybe newSingleThreadExecutor() was a better choice to keep things in sync/line.

Dennis, nowhere you manage the core pool size (cfr http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html)?

For now, and to see the effects, I would certainly use a  beforeExecute() to add an additional entry to TRACE logs so that we can better understand the effects of all this, no?

**Comment by kaikreuzer** [comment]
Karel, I am currently working on https://bugs.eclipse.org/bugs/show_bug.cgi?id=471763 and should have it by the end of this week. I synchronizing this implementation with Dennis' PR, so the management of the pool sizes will be available then.

**Comment by dnobel** [comment]
@kgoderis My plan for this PR was not having a better thread management, but just to recover from situations where caller (usually bindings or event listener) have bad implementations. Especially if an Error is thrown or the implementation blocks or for whatever reason takes too long, now the whole framework is blocked.

As this PR opens a new thread for each request into "third party code", we can now recover from such situations. But I discussed with Kai that it makes sense to also limit the threads here. But we assume that they are not that much parallel calls, as most of the framework is working synchronous.

**Comment by kgoderis** [comment]
Indeed, very often, also in the bindings I wrote myself, and mostly due to the reverse-engineering-nature of the development process, you can have NPE that crash the given thread. Maybe it would be good practice to use the same helper classes in the bindings themselves cfr Kai's upcoming PR. The only thing you can not guess is the time that will be spend in a call to handleCommand() as that depends on the binding implementation. If it takes long, you could end up with handleCommand() Futures running in parallel, so bindings should be aware of that. It  could *potentially* be a problem for some users with specific Rules in which a sequence of Commands are meant to be executed in order, and whereby commands might be out of order in their bindings. I guess those things can be worked around with a Thread::sleep or alike in the Rule.

**Comment by kgoderis** [comment]
Maybe https://github.com/openhab/openhab2/tree/master/addons/binding/org.openhab.binding.tesla/src/main/java/org/openhab/binding/tesla/internal/throttler could be source of ideas as well.

**Comment by maggu2810** [comment]
Sorry, have ATM not the time to have a deeper look at this changes, but a little question:
If I realized your changes, you are using a asynchronous processing for every command / state update.
If there are multiple updates e.g. a => b => c => d => e => f => g ... is the ordering still granted? So, we does not process the handling routine of "g" before "c" is done...

**Comment by dnobel** [comment]
This PR did not change anything in the execution behavior. Since the beginning of ESH and I guess also since the beginning of openHAB commands and state updates were sent asynchronously (if using the post method).

Not sure if the event admin guarantees the order of events?

But this PR does nothing else then just opening a thread to have better control over third party code, but everything is still executed synchronously. The get-Method in the SafeMethodCaller blocks the current thread until the newly opened thread is terminated or timed out.

**Pull request merged**
