### PR TITLE
first pull of enocean bindings

### PR DESCRIPTION
**Pull request by NicolasLingois**
example of an EnOcean binding for 2 devices : 
Eltako smoke detector and a G-media switch plug

Note that those devices don't follow exactly the rorg /func/type defined by the EEPs.
This is just an example using the EnOcean base driver in the protocol part and don't cover the EEPs.

Open to any refactoring /architecture suggestions

### CODE REVIEW

**Comment by maggu2810** [comment]
Shouldn't you remove the bundled jar files?
* extensions/binding/org.eclipse.smarthome.binding.enocean/lib/org.osgi.service.enocean-1.0.0.jar
* protocols/enocean/maven_dependencies/nrjavaserial-3.9.3.jar

**Comment by maggu2810** [comment]
@kaikreuzer Should we start with a code review or is this just a purpose for discussion?

**Comment by kaikreuzer** [comment]
> Should we start with a code review or is this just a purpose for discussion?

If I understand @NicolasLingois right, it is rather a prototype/example for some discussion than a ready-to-be-used feature, so I would tend to only discuss the general approach and architecture and not the code style and details.

**Comment by NicolasLingois** [comment]
sure i should remove 
extensions/binding/org.eclipse.smarthome.binding.enocean/lib/org.osgi.service.enocean-1.0.0.jar
protocols/enocean/maven_dependencies/nrjavaserial-3.9.3.jar
May have done some commit errors here ... just saw that I let the  README.md test in the PR 

Yes It's more an example than a "ready to use" feature, I agree. This helps to understand how to bind with the baseDriver with 2 examples more than covers a  large amout of EnOcean devices.

**Comment by maggu2810** [comment]
@kaikreuzer Should we move (close and create a new PR) this preview PR to the EnOcean repo?

**Comment by kaikreuzer** [comment]
No, this is an ESH binding, so it belongs in this repo, not in the the EnOcean one.
But as this PR is currently not further pursued, I'd be ok to close it.

**Comment by maggu2810** [comment]
Sure, you are right, it is a new binding (at least a dev. preview), my mistake.

**Comment by maggu2810** [comment]
Let's close as long as there is no active development anymore.

**Pull request closed without merging**
