### PR TITLE
Bundles import their exported packages themselves

### PR DESCRIPTION
**Pull request by BenediktNiehues**
https://bugs.eclipse.org/bugs/show_bug.cgi?id=478783

Signed-off-by: Benedikt Niehues <b.niehues@external.telekom.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Is everybody ok with this PR? If not speak up - otherwise I will merge it tomorrow!

**Comment by maggu2810** [comment]
IIRC we tried to use alphabetical order for the imports and exports.

**Comment by kaikreuzer** [comment]
Did we? I guess it was mainly PDE who created it this way. But you are right - when using the PDE editor, it is automatically sorted alphabetically. This means if this PR does not introduce them alphabetically ordered, we will see many changes in future, which are no real changes, which should be avoided.

@BenediktNiehues Would it be possible for you to order them correctly (should only be necessary on a few bundles as it seems)?

**Comment by BenediktNiehues** [comment]
Some manifest files also contain these compact import packages blocks (not each imported package in a new line) this will automatically be changed when using the PDE editor as well.
I will change the format of them, too. But only the ones which were affected with this PR!

**Comment by BenediktNiehues** [comment]
I updated the PR with an alphabetical ordering of imported packages.

**Comment by kaikreuzer** [comment]
Thanks, @BenediktNiehues!

**Pull request merged**
