### PR TITLE
Remove org.osgi.service.component.annotations import from manifests

### PR DESCRIPTION
**Pull request by wborn**
See https://github.com/openhab/openhab2-addons/pull/2880

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hm, Travis fails with
```
[ERROR] /home/travis/build/eclipse/smarthome/bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttService.java:[49] 
[ERROR] 	@Component(immediate = true, service = { MqttService.class }, configurationPid = {
[ERROR]         "org.eclipse.smarthome.mqtt" }, property = "service.pid=org.eclipse.smarthome.mqtt")
[ERROR] 	                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Type mismatch: cannot convert from String[] to String
```
Seems we have a different annotation definition now?

From the error, it seems the MqttService should be defined as 
```
@Component(immediate = true, service = { MqttService.class }, configurationPid = {
        "org.eclipse.smarthome.mqtt" }, property = { "service.pid=org.eclipse.smarthome.mqtt" })
```
i.e. adding curly brackets around the property. Do you want to give that fix a try?

**Comment by wborn** [comment]
Thanks for the suggestion. I'll give it a try later this weekend!

**Comment by kaikreuzer** [comment]
Argh. Now I am completely puzzled:

```
[ERROR] /home/travis/build/eclipse/smarthome/bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttService.java:[49] 
[ERROR] 	@Component(immediate = true, service = { MqttService.class }, configurationPid = {
[ERROR]         "org.eclipse.smarthome.mqtt" }, property = { "service.pid=org.eclipse.smarthome.mqtt" })
[ERROR] 	                                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Type mismatch: cannot convert from String[] to String
```

**Comment by sjka** [comment]
The problem here is the `configurationPid` - that one is expected to be a plain string and _not_ an array (i.e. drop the curly brackets there).

**Comment by kaikreuzer** [comment]
Before merging, we should make sure that it does not break the XML generation, see https://github.com/openhab/openhab2-addons/pull/2880#issuecomment-346931292.

**Comment by wborn** [comment]
This PR has been rebased on the most recent master. The compilation errors got fixed using @sjka proposed fix. 

I've had a look inside the JARs and see that XML is properly generated using the annotations. However after also having a look inside the JARs resulting from https://github.com/openhab/openhab2-addons/pull/2880 these also have properly generated XML. So most likely something else will still cause issues when the imports are removed.

**Comment by wborn** [comment]
Apparently the OSGI-INF directories inside the JARs produced by Jenkins for the online-repo of the [openHAB build # 1096](https://openhab.jfrog.io/openhab/webapp/#/builds/openHAB-Distribution/1096/1511563757684/published/org.openhab.distro:online-repo:2.2.0-SNAPSHOT) do not contain generated XML.

There is however generated XML inside my local build of an online-repo after building openhab2-addons with [PR #2280](https://github.com/openhab/openhab2-addons/pull/2880) applied.

So the missing generated XML files may be due to an issue with the openHAB Jenkins setup.

**Comment by kaikreuzer** [comment]
> I've had a look inside the JARs and see that XML is properly generated using the annotations. 

Which jars did you look at exactly? The ones produced by a local Maven build? If so, did you make sure that you closed your IDE before running the build and that you had deleted the IDE-generated XMLs? Otherwise the local build simply packages those and all seems fine (even if the maven-scr plugin fails to generated them).

**Comment by wborn** [comment]
> Which jars did you look at exactly? The ones produced by a local Maven build? If so, did you make sure that you closed your IDE before running the build and that you had deleted the IDE-generated XMLs? 

I've looked into the JARs produced by my local Maven build after closing Eclipse and deleting the IDE-generated XML files.

**Comment by kaikreuzer** [comment]
Ok, thanks. So all we have to find out is why the XML generation isn't working on openhab2-addons then - it all looks pretty much the same to me 😲

**Comment by wborn** [comment]
It would be nice to see if the [ESH Nightly](https://ci.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/buildTimeTrend) Jenkins build correctly adds the generated XML. However it seems to have been stalled for hours.

**Comment by sjka** [comment]
I gave it the needed kick. Let's see...

**Comment by wborn** [comment]
I've checked several Nighlty builds and haven't found any artifacts without generated XML. :smiley:

**Pull request merged**
