### PR TITLE
Paper UI: show slider only if item is not read only

### PR DESCRIPTION
**Pull request by maggu2810**
Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
A slider does is always enabled and allows to change the values.
This does not make sense for read only values.

**Comment by maggu2810** [comment]
@kaikreuzer Have you any concerns?

**Comment by kaikreuzer** [comment]
Err, no, just no time to test it yet...
So what does the Paper UI now show in the read-only case?

**Comment by maggu2810** [comment]
The current value as a number.

**Comment by kaikreuzer** [comment]
I hoped for a screenshot ;-)
Ok then...

**Comment by maggu2810** [comment]
I will do it next time on PR creation. This will improve the review process and makes it much easier.

**Pull request merged**
