### PR TITLE
changed Designer to use gson 2.2.4

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
gson

**Comment by maggu2810** [comment]
It seems gson 2.2.4 cannot be located by Eclipse PDE

**Comment by maggu2810** [comment]
It seems gson 2.2.4 cannot be located by Eclipse PDE.

Using the current master Eclipse PDE cannot resolve my target platform and so there are a lot of build errors in my IDE.
To get a usable IDE again I have to revert that commit locally.

Could you please check it again?

**Comment by kaikreuzer** [comment]
I think all that is missing is that your IDE needs to re-resolve the target platform. https://github.com/eclipse/smarthome/pull/1594 should make this happen.

**Pull request merged**
