### PR TITLE
Rest API Demo impl

### PR DESCRIPTION
**Pull request by adimova**
Signed-off-by: Ana Dimova <a.dimova@prosyst.bg>

### CODE REVIEW

**Comment by adimova** [comment]
This PR resolves the issue New rule engine: Add rest api demo for new rule engine. #693

**Comment by marinmitev** [comment]
lgtm. A second review is needed ( @kaikreuzer @maggu2810  )

**Comment by marinmitev** [comment]
Demo can be loaded from the following URL
http://localhost:8080/esh/automation/restdemo/index.html

**Comment by maggu2810** [comment]
Will have a look at tomorrow.

**Comment by adimova** [comment]
The automation pom.xml file is not updated. It will be after the merging "Change the name of the Java API Demo to the Rule Engine Extensions Demo #980", "automation json schemas #972" and this PRs.

**Comment by kaikreuzer** [comment]
> Will have a look at tomorrow.

I had a brief glance and overall it lgtm. So waiting for @maggu2810's feedback.
Note that this needs to be merged afterwards by someone from ProSyst as the PR has more than 1000 lines - otherwise we would require a CQ.

**Comment by marinmitev** [comment]
ok

**Comment by maggu2810** [comment]
LGTM for me.

One question:
If I select on the left navigation bar "module types" / "templates" and then click on the main page on "GET ALL Module Types" / "GET ALL Templates" the main page shows the result (as expected) and on the navigation frame "rules" is selected now.
Has this done by intention?

I think it is okay to merge.

BTW why don't we need a CQ for >= 1000 lines if ProSyst merges?

**Comment by adimova** [comment]
> If I select on the left navigation bar "module types" / "templates" and then ...

no, this is copy-paste mistake, i will fix it

**Comment by adimova** [comment]
done

**Pull request merged**
