### PR TITLE
Fixed item name validation to also work with ChannelGroups

### PR DESCRIPTION
**Pull request by gerrieg**
Signed-off-by: Gerhard Riegler <gerhard.riegler@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
This is a very wide-reaching change that can have impact on many areas (DSL parsing, REST API, MQTT events etc.) ChannelGroups are not items, so there should not be the need for this change. In openHAB 2, "#"s are mapped to "_" for dynamic item creation, isn't that solving the issue?

**Comment by gerrieg** [comment]
Unfortunately, no:
```
2015-01-01 14:17:20.011 [WARN ] [.c.c.registry.AbstractRegistry] - Could not add element: Ignoring item 'astro_sun_home_sunRise#start' as it does not comply with the naming convention.
java.lang.IllegalArgumentException: Ignoring item 'astro_sun_home_eclipse#partial' as it does not comply with the naming convention.
	at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.initializeItem(ItemRegistryImpl.java:216) ~[na:na]
	at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.onAddElement(ItemRegistryImpl.java:237) ~[na:na]
	at org.eclipse.smarthome.core.internal.items.ItemRegistryImpl.onAddElement(ItemRegistryImpl.java:1) ~[na:na]
	at org.eclipse.smarthome.core.common.registry.AbstractRegistry.addProvider(AbstractRegistry.java:138) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_71]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_71]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_71]
	at org.eclipse.equinox.internal.ds.model.ComponentReference.bind(ComponentReference.java:376) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.bindReference(ServiceComponentProp.java:444) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.dynamicBind(InstanceProcess.java:416) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:334) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [org.eclipse.osgi_3.10.0.v20140606-1445.jar:na]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:914) [org.eclipse.osgi_3.10.0.v20140606-1445.jar:na]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi_3.10.0.v20140606-1445.jar:na]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [org.eclipse.osgi_3.10.0.v20140606-1445.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862) [org.eclipse.osgi_3.10.0.v20140606-1445.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801) [org.eclipse.osgi_3.10.0.v20140606-1445.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) [org.eclipse.osgi_3.10.0.v20140606-1445.jar:na]
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225) [org.eclipse.osgi_3.10.0.v20140606-1445.jar:na]
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:464) [org.eclipse.osgi_3.10.0.v20140606-1445.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.registerService(InstanceProcess.java:536) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:260) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89) [org.eclipse.equinox.ds_1.4.200.v20131126-2331.jar:na]
	at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70) [org.eclipse.equinox.util_1.0.500.v20130404-1337.jar:na]
```
your changes to the ThingItem providers only solves this exception:
```
java.lang.IllegalArgumentException: invalid topic: smarthome/update/astro_sun_home_sunRise#start
	at org.osgi.service.event.Event.validateTopicName(Event.java:232) ~[na:na]
```

**Comment by kaikreuzer** [comment]
ok, but then this is still an issue of the ThingItemUIProvider of openHAB 2.

**Comment by gerrieg** [comment]
OK, now it works for me: https://github.com/openhab/openhab2/pull/93

I still have to learn how everything works in version 2, so sorry for this PR.

**Pull request closed without merging**
