### PR TITLE
GenericItemUIProvider: get item from registry instead of model repository

### LINKED ISSUE #4716: Starred interaction on config and rules changes
Whenever I change an items or rules file, to process this update in OH can take up to 2 or 3 minutes (for a 1k lines rules file on a Pi2). java is runnning at 100% CPU (i.e. 1 core@100%, but 3 idle cores).
Meanwhile, the interaction via REST or Web UI is apparently HALTED until the current file is processed.
As requested by @kaikreuzer, here's a large rules file to help you reproduce it, but it happens on _any_ rule und items file (re)load: it takes the API and UI to react exactly as long as it takes to process the updated file, UI comes back to life as soon as the 'refreshing xxx.rules' log entry shows up.

[reloadtest.TXT](https://github.com/eclipse/smarthome/files/1547661/reloadtest.TXT)

### PR DESCRIPTION
**Pull request by htreu**
Fixes #4716.

Signed-off-by: Henning Treu <henning.treu@telekom.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Let's take a step back here:
The "Generic" part of the name of GenericItemUIProvider was supposed to tell that it takes its wisdom from DSL files. With this PR, it does not at all depend on the model repository anymore.
Looking a bit closer, it merely proxies to the item registry for category and label and it returns null for the default widget. Sounds pretty useless, doesn't it?
Having had a short look in the code, I would claim that the ItemUIRegistryImpl could be made fully independent of ItemUIProvider as it can instead directly access the item registry.

**Comment by htreu** [comment]
From what I understand from the code the ItemUIRegistryImpl holds a list of ItemUIProviders and tries to resolve label & category from this provider list. To me this looks like an extension point where implementations could hook up ItemUIProviders to resole those properties on their own.
Maybe I got you wrong but I don't see how we could live w/o this connection.

**Comment by kaikreuzer** [comment]
> tries to resolve label & category from this provider list

Right, but meanwhile label & category are part of the item (which wasn't the case at the time when the ItemUIProvider interface was defined). So I do not really see a point in that interface anymore.

**Comment by htreu** [comment]
I'm happily removing the whole ItemUIProvider interface infrastructure but this sounds API breaking as the `org.eclipse.smarthome.ui.items` package gets exported (and with it the ItemUIProvider interface). My suggestion is to merge this first, then decide on how to proceed. wdyt?

**Comment by kaikreuzer** [comment]
Well, would you agree that you can at least remove the GenericItemUIProvider without breaking the API? As mentioned initially, with the current code of this PR, it isn't doing anymore what its name suggests.

**Comment by htreu** [comment]
This would already imply that the ItemUIProvider infrastructure is dead. It will then not be used anymore to resolve label & category.
I will add a second commit which makes these change.

**Comment by kaikreuzer** [comment]
> This would already imply that the ItemUIProvider infrastructure is dead.

No, it would only imply that we have one instance less. IF there is anybody else registering such services, they would still be used, i.e. no API/behavior would be broken.

**Comment by htreu** [comment]
Thanks for the feedback, I was about to remove the _dependency_ on itemUIProviders in the registry. So only the useless GenericItemUIProvider will be gone then.

**Pull request merged**
