### PR TITLE
[WIP][LIFX] Add light effects

### PR DESCRIPTION
**Pull request by wborn**
This PR is a WIP to add functionality for using light effects with the LIFX binding (#4199).

A list of completed/uncompleted tasks follows below:
- [x] Implement SetWaveform and SetWaveformOptional protocol packets
- [x] Add an effect channel that allows for easily testing the new packets
- [ ] Test how waveforms behave with whites only and MultiZone lights
- [ ] Rework the new effect channel so presets can be used and users still have room for customizing the effects
- [ ] Update translations
- [ ] Update documentation

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hey @wborn, is this still on your radar?

**Comment by wborn** [comment]
Yes I'll be picking this up soon now I've finished polishing some other bindings. :-)

The LIFX App has different configuration parameters per effect. What would be the best way to implement several effects with different customization options in a binding @kaikreuzer ?

E.g. one effect channel to switch between the effects and several a channel configuration parameter groups per effect on this channel for user customization?

In the issue https://github.com/eclipse/smarthome/issues/4199 I also wrote:
> Is the Hue Binding effects implementation a good reference for implementing effects? It seems to use a channel per effect (alert/effect channels). That would also allow effect configuration options using channel configurations. However it seems like enabling one effect would automatically switch off the other effects. So such effect channels would not be fully independent of each other.

**Comment by kaikreuzer** [comment]
I am not sure about the best way to model effects.
You are right, if only one effect is enabled at a time, there should not be multiple channels, but only a single one. The problem probably is that the configuration parameters will depend on the specific channel, so we won't be able to define a useful config description...
Any ideas and suggestions are welcome 😎 .

**Comment by wborn** [comment]
We can group effect configurations with parameter groups. So I created a channel configuration using all effects and themes in the LIFX App to see what that would look like. I also added a description to each configuration group but it doesn't show up in Paper UI. WDYT @kaikreuzer?

## Channels

<table>
  <tr>
    <td>
      <a href="https://user-images.githubusercontent.com/12213581/39367108-2c4e53b8-4a36-11e8-8bb2-82509837002d.png">
        
      </a>
    </td>
  </tr>
</table>

## Control

<table>
  <tr>
    <td>
      <a href="https://user-images.githubusercontent.com/12213581/39367115-2f3c1966-4a36-11e8-9d9c-fa376b81d077.png">
        
      </a>
    </td>
    <td>
      <a href="https://user-images.githubusercontent.com/12213581/39367119-31477b10-4a36-11e8-8fd3-16c42c71edca.png">
      
      </a>
    </td>
  </tr>
</table>

## Channel Configuration

<table>
  <tr>
    <td>
      <a href="https://user-images.githubusercontent.com/12213581/39367142-3acb941e-4a36-11e8-99a0-032cc3b8b17a.png">
        
      </a>
    </td>
    <td>
      <a href="https://user-images.githubusercontent.com/12213581/39367147-3ce252b0-4a36-11e8-809a-d88a5021ab3b.png">
      
      </a>
    </td>
  </tr>
  <tr>
    <td>
      <a href="https://user-images.githubusercontent.com/12213581/39367151-3eb8cf42-4a36-11e8-86fc-1e35c555b0fc.png">
        
      </a>
    </td>
    <td>
    </td>
  </tr>
</table>

**Comment by kaikreuzer** [comment]
Quite a decent approach with the means that are available - I like it!

**Comment by kaikreuzer** [comment]
> Now the days are getting shorter we definitely need some effects to fill the darkness. :-)

@wborn Just as a reminder: In a bit more than 3 weeks, the days start getting LONGER again, so hurry up!

**Comment by kaikreuzer** [comment]
Once you're done, may I ask you to move this to https://github.com/openhab/openhab2-addons?

**Pull request closed without merging**
