### PR TITLE
added missing model runtime bundles to designer

### LINKED ISSUE #2190: Item resolution broken in Designer
Items are not resolved in the Designer, i.e. when trying to use content completion e.g. in sitemaps, no proposals show up.

### PR DESCRIPTION
**Pull request by sjka**
...in order to fix the registry population with elements.

fixes #2190
Signed-off-by: Simon Kaufmann <simon.kfm@googlemail.com>

### CODE REVIEW

**Comment by lolodomo** [comment]
That would be really cool to include this fix in final 2.0 ;)

**Comment by kaikreuzer** [comment]
There is no openHAB 2.0 Designer!
And it won't really be any better than released version 0.8.0, will it?

**Comment by lolodomo** [comment]
I am probably using release 0.8.0 but few actions like say or interpret are not recognized. I imagine they are in more recent releases ?
What would be cool is a designer version that would fully support the eclipse smarthome version used by final OH 2.

**Comment by kaikreuzer** [comment]
Right. For this, we will "only" have to solve https://github.com/eclipse/smarthome/issues/997.
Note that many actions are defined in openHAB1 as add-ons, so the Designer naturally cannot know about them, which is a problem :-(

**Comment by kaikreuzer** [comment]
Thanks, @sjka, I just tested this. I can indeed now see the items in the "Items" window and they are nicely resolved in persist files and sitemaps. BUT my rules still look like shown in https://github.com/eclipse/smarthome/issues/2190#issuecomment-253628627.
Do you have the same? If so, there is still some other "resolution" issue to be fixed...

**Comment by lolodomo** [comment]
@kaikreuzer could you please thing releasing a new designer official version because version 0.8 is outdated and recent snapshots look ok.

**Comment by kaikreuzer** [comment]
Snapshots aren't ok as mentioned in https://github.com/eclipse/smarthome/issues/2190#issuecomment-275096251.
And Designer cannot be released independently. It will be part of an ESH 0.9.0 release.

**Comment by lolodomo** [comment]
Ok
At least, designer smapshot is now usable, that is already a first step.
0.8 seems to be icompatible with defining channels properties in thing.

**Pull request merged**
