### PR TITLE
New rule action: interpret with HLI parameter (enh #2501)

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

I recommend a serious review because the change was not tested (don't know exactly how to test it).
At least, everything is compiling and the change is small.

### CODE REVIEW

**Comment by lolodomo** [comment]
@kaikreuzer : without considering this patch, I tried "interpret" in my rule file:
```
rule "Controle par la voix"
when
    Item VoiceCommand received command
then
		interpret(VoiceCommand.state.toString)
end
```
but it leads to this error:
```
23:21:21.366 [ERROR] [.script.engine.ScriptExecutionThread] - Rule 'Controle par la voix': org.eclipse.smarthome.core.voice.VoiceManager.interpret(Ljava/lang/String;)V
```
Could it be due to the fact that the interpret method is delcared with Object as parameter and not String ?
Shall we replace Object by String ?

**Comment by watou** [comment]
> interpret(VoiceCommand.state.toString)

Wouldn't you rather

> interpret(receivedCommand.toString)

**Comment by lolodomo** [comment]
@watou: no change when I use "receivedCommand".
The error is not "talking" but my feeling is that it simply does not find the interpret method.

**Comment by watou** [comment]
I see; I just jumped at commenting on a construct I saw giving someone problems on the forum.  

Is it possible to cast the String argument `as Object` in the scripting language?

**Comment by lolodomo** [comment]
I tried this but it failed too:
```
		var String msg = VoiceCommand.state.toString
		interpret(msg)
```
@kaikreuzer : please comment.

**Comment by kaikreuzer** [comment]
> Could it be due to the fact that the interpret method is delcared with Object as parameter and not String ?

No, it seems to correctly resolve and call the Voice.interpret method, because the error shows that it is something within VoiceManager.interpret that goes wrong. Did you debug to check if some exception is thrown some where within it?

**Comment by lolodomo** [comment]
No, that was with my production environment on RPI.

**Comment by kaikreuzer** [comment]
Then this sounds to me as if you might not have a matching core.voice bundle installed.

**Comment by lolodomo** [comment]
I have of course a core voice bundle loaded (through a new jar file corresponding to the current enhancement), and only one is loaded.
The voice manager is working as the interpret command in console is working as expected and the say action in rule is working well too.

**Comment by lolodomo** [comment]
What jar file has to be deployed to have a rule engine considering my code change in voice action?

**Comment by lolodomo** [comment]
@watou : I tried again with the snapshot 627 and the interpret command in my rule is now working well .
My problem was probably due to the fact that I was loading the voice manager through an additional jar file in my directory addons.
@kaikreuzer : could you review my PR please ?

**Comment by lolodomo** [comment]
I could even enhance this enhancement with what I propose in #2588. Let me know.

**Comment by kaikreuzer** [comment]
#2588 can be treated separately.

**Pull request merged**
