### PR TITLE
WU: bridge/thing refactoring

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
I think everything is working better now except the background discovery which seems to be not running. I will take a look later. Manual discovery is working well.

Problem with language is fixed too.
As requested by @mhilbush, discovered things are now created with language code set from the current locale language (when found in the table).

**Comment by maggu2810** [comment]
> except the background discovery which seems to be not running. I will take a look later.

So, would it make sense to mark the PR title with a leading "WIP" to ensure it is not merged by accident?

**Comment by mhilbush** [comment]
@lolodomo Thanks for this. If you publish a jar, I'd be happy to test it.

**Comment by GiovannaTheo** [comment]
It does look better, thanks! However, shouldn't the communication to the WU service be solely handled by the bridge, as mentioned by @htreu in #5501 ? This was our motive for moving the `getWeatherData` function to the `BridgeHandler` class. With the changes this PR introduces, now both the thing and the bridge connect to the WU service at some point. Imo it makes more sense to have the bridge taking care of all the API jobs, and the thing only "rendering" the data. Wdyt ?

**Comment by lolodomo** [comment]
We are talking about simple HTTP calls, I don't understand the logic to run them only in the bridge handler. By the way, the only call done by the bridge handler is a control of the API key, the "real" calls are run by the thing handler.
If we moved all the HTTP calls to the same class, we will have to create a new object to return information needed by each caller to set a proper thing status, something you bypassed in your code probably due to this difficulty.
I think we should keep with a simple code and avoid adding complexity for no valid reason.

**Comment by lolodomo** [comment]
@htreu ! I considered all your review comments.

I fixed the example in the documentation too.

**Comment by lolodomo** [comment]
Ready for merge.

**Comment by lolodomo** [comment]
@mhilbush : while it takes time to merge this PR and because some users like you are blocked, here is [a jar file ](http://lg.hc.free.fr/openHAB/org.eclipse.smarthome.binding.weatherunderground-0.10.0-SNAPSHOT.jar) you can use.

**Comment by lolodomo** [comment]
Independently of this PR, I discovered during my tests that the WU language codes are not very reliable. As an example, for italian, the WU code should be IY but I got weather conditions in italian when I use IT, not when I use IY.
In fact, there are two pages:
* https://www.wunderground.com/weather/api/d/docs?d=language-support
* https://www.wunderground.com/weather/api/d/docs?d=resources/country-to-iso-matching
We are now relying on the second page but my feeling now is that it was a mistake because this page is titled "Country to ISO Matching" and provides this description:
`Weather Underground uses different country codes than standard ISO. Here is the matching from Weather Underground counties to ISO countries. `
It is relative to country and not language !
So I think I should move back to the list of languages defined on this page: https://www.wunderground.com/weather/api/d/docs?d=language-support

**Comment by lolodomo** [comment]
As a consequence, I removed my very last commit as the list of languages in the XML file was the right language codes.
Just remains now to update the table in the code.

**Comment by lolodomo** [comment]
I finally fixed the language table and made a little change to the automatic discovery to consider change of the system language.
Everything seems to work well now.

@mhilbush : I updated the jar file you can download.

**Comment by lolodomo** [comment]
There is only one little thing that would need an enhancement. Currently, the binding is not able to select automatically british english or french canadian from the system locale. English and French will be rather selected. But of course, the user can select these languages using the thing setting.
This enhancement is possible but out of the scope of this PR.

**Comment by mhilbush** [comment]
Thanks for the changes and thanks for the jar.

**Pull request merged**
