### PR TITLE
[MQTT] Update ReadMe

### PR DESCRIPTION
**Pull request by JueBag**
Corrected Item syntax and added a note about the difference syntax when creating the things via PaperUI or files.

Signed-off-by: Juergen Baginski <opus42@gmx.de>

### CODE REVIEW

**Comment by JueBag** [comment]
Second try, same result :-(

**Comment by yozik04** [comment]
In my setup channel should be without broker. This is the only way it works.

mqtt:topic:<thing_id>:<channel_id>

```
Switch Kitchen_Light "Kitchen Light" {channel="mqtt:topic:mything:lamp" }
Rollershutter shutter "Blind" {channel="mqtt:topic:mything:blind" }
```

**Comment by yozik04** [comment]
```
Bridge mqtt:broker:myUnsecureBroker [ host="192.168.0.42", secure=false ]
{
    Thing mqtt:topic:mything {
Channels:
        Type switch : lamp "Kitchen Lamp" [ stateTopic="lamp/enabled", commandTopic="lamp/enabled/set" ]
        Type switch : fancylamp "Fancy Lamp" [ stateTopic="fancy/lamp/state", commandTopic="fancy/lamp/command", on="i-am-on", off="i-am-off" ]
        Type string : alarmpanel "Alarm system" [ stateTopic="alarm/panel/state", commandTopic="alarm/panel/set", allowedStates="ARMED_HOME,ARMED_AWAY,UNARMED" ]
        Type color : lampcolor "Kitchen Lamp color" [ stateTopic="lamp/color", commandTopic="lamp/color/set", rgb=true ]
        Type dimmer : blind "Blind" [ stateTopic="blind/state", commandTopic="blind/set", min=0, max=5, step=1 ]
    }
}
```

And thing must be defined via: `Thing mqtt:topic:mything`

**Comment by yozik04** [comment]
But if you define `Thing topic mything`

Then Items will need include broker in channel:
`channel="mqtt:topic:myUnsecureBroker:mything:blind"`

**Comment by JueBag** [comment]
The Readme seems to be updated otherwise.
The discussion about the different ways to thing can be defined has to be discussed elsewhere.
Closing this PR.

**Pull request closed without merging**
