### PR TITLE
Refactor thing properties display in PaperUI

### PR DESCRIPTION
**Pull request by cdjackson**
The primary change here is to split the thing properties table into a separate partial so that it can be overridden in a fragment. I've also modified the styling of the properties slightly as I personally think it looks a bit better, but if y'all disagree I can always change it back.

Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
Would be great to have "before" and "after" screenshots so we can discuss without the need to build and check the UI.

**Comment by cdjackson** [comment]
The original...
image


And the proposal...
image

I've basically just got rid of the vertical lines in the table, and made them extend uniformly across the page (uniformly, as in it's the same for every thing).

**Comment by kaikreuzer** [comment]
Looks much nicer indeed :-)

**Comment by maggu2810** [comment]
Okay for me

**Comment by maggu2810** [comment]
@aounhaider1 Would you like to review this changes?

**Comment by aounhaider1** [comment]
Looks good.

**Pull request merged**
