### PR TITLE
Fix #1211

### LINKED ISSUE #1211: org.eclipse.smarthome.automation.core.util.ConnectionValidator throws exception when optional inputs are left unconnected
The validation of unconnected inputs must be allowed if they are not required. This will allow the definition of more general module types

### PR DESCRIPTION
**Pull request by adimova**
Signed-off-by: Ana Dimova <a.dimova@prosyst.bg>

### CODE REVIEW

**Comment by maggu2810** [comment]
@marinmitev, @YordanDZhelev, all fine from your side?

**Comment by maggu2810** [comment]
@marinmitev, @danchom , all fine from your side?

**Comment by danchom** [comment]
Yes, it looks ok for me.

**Comment by kaikreuzer** [comment]
@adimova Could you have a look at https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/903/ and check if this is related to this PR?

**Comment by maggu2810** [comment]
Same on my machine: https://gist.github.com/maggu2810/de8c491fb8bee21ed684

**Pull request merged**
