### PR TITLE
Set configurationPid instead of service name on archetype

### PR DESCRIPTION
**Pull request by triller-telekom**
Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by hakan42** [comment]
stupid question, is the configurationPolicy important to set?

**Comment by triller-telekom** [comment]
@hakan42 if the binding has a configuration which will be stored in configadmin and that should appear as a section in paperui, then yes :)

**Comment by kaikreuzer** [comment]
@hakan42 The `configurationPid` is now used as a replacement for `name`, see [this discussion](https://github.com/openhab/openhab2-addons/pull/2559#issuecomment-324055141).

**Comment by hakan42** [comment]
o.k., I will adapt this in the senseBox binding immediately.

**Pull request merged**
