### PR TITLE
Added nginx proxy buffering fix to SitemapResource.java as well.

### PR DESCRIPTION
**Pull request by kolkoo**
Signed-off-by: IVAN GEORGIEV ILIEV <ivan.iliev@musala.com>

### CODE REVIEW

**Comment by BClark09** [comment]
Can confirm that sitemap events now come through a buffered proxy with this PR. Thank you!!

**Comment by kaikreuzer** [comment]
Wow, @BClark09, you are a quick tester!

**Comment by BClark09** [comment]
hah, @kaikreuzer, in reality I had my own branch with the [exact same changes](https://github.com/BClark09/smarthome/commit/495ac49d21a22652d5501bc546bcb1ee16d214c0).

Unfortunately I did not create the PR because:

1. It's a copy of @kolkoo's changes from another PR, so felt he should have the second PR.
2. I am a little unconfident with java, so wanted to make sure what I was doing was correct.
3. I have been trying for a couple of weeks to get approval for an account with eclipse but with no response. I should probably contact webmaster.

**Comment by kaikreuzer** [comment]
@BClark09 (3) is unusual, there should be no problems. Feel free to contact me through PM and I can see what I can do to help solving the issues you encounter.

**Pull request merged**
