### PR TITLE
Removed OSGI-INF and fixed Karaf requirement

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
Shame on me, sorry

**Comment by maggu2810** [comment]
You've got a PR.

**Comment by kaikreuzer** [comment]
Shame on me 🙄 .

**Comment by kaikreuzer** [comment]
But now: Who will merge this...?

**Comment by maggu2810** [comment]
Do you need it for a build for OH soon?
If we are strict, then one of the other committers (@htreu, @sjka, @adimova),
if we are lazy, then the first one that identifies that Travis CI succeeds...

**Comment by kaikreuzer** [comment]
No, I don't need it urgently. I only came across it by chance and did the cleanup. I can wait.

**Pull request merged**
