### PR TITLE
Allow thing label to be changed

### PR DESCRIPTION
**Pull request by cdjackson**
There's currently no way to update the thing label - I assume that this should be allowed and this is just an oversight...
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@sjka Did you miss this in https://github.com/eclipse/smarthome/pull/1054 or is it expected to work differently?

**Comment by sjka** [comment]
indeed, as this functionality was deliberately "broken" in the PaperUI by #963 I actually missed that place. Thanks for fixing it!

**Comment by satish-nikam** [comment]
Today I checked this using latest snapshot and it still seems not working. Can you confirm if all PRs are merged?

**Comment by kaikreuzer** [comment]
I can confirm that it is NOT working.
It seems as if the Paper UI never calls ThingResource.update() when changing the label. The only call that is done is to "updateConfiguration" (even if nothing has been changed).
@sjka, can you confirm?

**Comment by satish-nikam** [comment]
Thanks Kai for confirmation. Can we open the PR to track this issue?

**Comment by kaikreuzer** [comment]
Done! https://github.com/eclipse/smarthome/issues/1168

**Pull request merged**
