### PR TITLE
wait for file to be written in JsonStorageTest

### LINKED ISSUE #3854: Test failure(s): JSonStorageTest failed
Full log: https://travis-ci.org/eclipse/smarthome/builds/255223132?utm_source=github_status&utm_medium=notification

```text
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.storage.json.JSonStorageTest
Tests run: 5, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.182 sec <<< FAILURE! - in org.eclipse.smarthome.storage.json.JSonStorageTest
testIntegerScale_fromCache(org.eclipse.smarthome.storage.json.JSonStorageTest)  Time elapsed: 0.052 sec
allInsertedNumbersAreLoadedAsBigDecimal_fromCache(org.eclipse.smarthome.storage.json.JSonStorageTest)  Time elapsed: 0.003 sec
testStableOutput(org.eclipse.smarthome.storage.json.JSonStorageTest)  Time elapsed: 0.081 sec
allInsertedNumbersAreLoadedAsBigDecimal_fromDisk(org.eclipse.smarthome.storage.json.JSonStorageTest)  Time elapsed: 0.005 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.eclipse.smarthome.storage.json.JSonStorageTest$DummyObject.access$0(JSonStorageTest.java:120)
	at org.eclipse.smarthome.storage.json.JSonStorageTest.allInsertedNumbersAreLoadedAsBigDecimal_fromDisk(JSonStorageTest.java:67)
testIntegerScale_fromDisk(org.eclipse.smarthome.storage.json.JSonStorageTest)  Time elapsed: 0.003 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.eclipse.smarthome.storage.json.JSonStorageTest$DummyObject.access$0(JSonStorageTest.java:120)
	at org.eclipse.smarthome.storage.json.JSonStorageTest.testIntegerScale_fromDisk(JSonStorageTest.java:95)
Running org.eclipse.smarthome.storage.json.JsonStorageServiceOSGiTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.021 sec - in org.eclipse.smarthome.storage.json.JsonStorageServiceOSGiTest
testSerialization(org.eclipse.smarthome.storage.json.JsonStorageServiceOSGiTest)  Time elapsed: 0.01 sec
testClassloader(org.eclipse.smarthome.storage.json.JsonStorageServiceOSGiTest)  Time elapsed: 0.004 sec
testConfiguration(org.eclipse.smarthome.storage.json.JsonStorageServiceOSGiTest)  Time elapsed: 0.002 sec
testOverride(org.eclipse.smarthome.storage.json.JsonStorageServiceOSGiTest)  Time elapsed: 0.002 sec
Results :
Tests in error: 
  JSonStorageTest.allInsertedNumbersAreLoadedAsBigDecimal_fromDisk:67 » NullPointer
  JSonStorageTest.testIntegerScale_fromDisk:95 » NullPointer
Tests run: 9, Failures: 0, Errors: 2, Skipped: 0
```

### PR DESCRIPTION
**Pull request by sjka**
...and thereby factored out the non-OSGi related method from JavaOSGiTest into a new JavaTest class.

fixes #3854
Signed-off-by: Simon Kaufmann <simon.kfm@googlemail.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
> and thereby factored out the non-OSGi related method from JavaOSGiTest into a new JavaTest class

I like it :wink:

**Comment by maggu2810** [comment]
Should the JsonStorage implementation of `writeDatabase` be changed to call a flush after a write?

```Java
        try (FileOutputStream outputStream = new FileOutputStream(dataFile, false)) {
            outputStream.write(data.getBytes());
            outputStream.flush();
        } catch (Exception e) {
```

I see no statement in the JavaDoc that close calls a flush at all (but I am pretty sure the data will be written in every implementation some time), immediately or delayed.

**Comment by sjka** [comment]
I had the same thought about flushing initially, but then my expectation was that you would reject that 😉  My assumption so far was that a flush is implicit when closing a file output stream. But in fact you are right, nothing says that it actually happens at that moment. Therefore I agree, it can't hurt!

**Comment by sjka** [comment]
FTR: the PR is updated

**Comment by maggu2810** [comment]
> I had the same thought about flushing initially, but then my expectation was that you would reject that 😉 

For databases / storage that contains such "important" data, I would really expect that "all" is done to grant as much integrity as possible. So `flush` is IMHO not only optional but required.

**Pull request merged**
