### PR TITLE
LSP requires Gson 2.7 that exports internal packages

### PR DESCRIPTION
**Pull request by maggu2810**
Fixes: https://github.com/eclipse/smarthome/issues/6250

### CODE REVIEW

**Comment by maggu2810** [comment]
```
karaf@root()> bundle:list -t 0 -l | grep -i gson
 14 │ Active   │  80 │ 2.3.1                  │ mvn:com.google.code.gson/gson/2.3.1

karaf@root()> feature:install esh-model-lsp 

karaf@root()> bundle:list -t 0 -l | grep -i gson
165 │ Active   │  80 │ 2.7.0.v20170129-0911   │ mvn:org.eclipse.orbit.bundles/com.google.gson/2.7.0.v20170129-0911
```

**Comment by kaikreuzer** [comment]
What happens to bundle 14? Does it get uninstalled automatically? What magic is that? 😲

**Comment by maggu2810** [comment]
That's the same black magic we use for Guava since years :wink: 
Let me try to explain it again...

**Comment by kaikreuzer** [comment]
> `dependency="true"` states: install that bundle only if it is necessary to fulfill the requirements

Right, this much I was aware. What I missed is that it implicitly also says "once the bundle is not required anymore (because some other bundle meanwhile fulfills the requirements), deinstall this bundle again".

A not-so-nice side effect of that mechanism is that bundle X has to be restarted as it then gets resolved against A2. This is rather unexpected when another unrelated feature is installed in a running system.

**Comment by maggu2810** [comment]
... then 
* we have to remove all the `dependency="true"` flags and keep multiple versions installed
* we have to use only one version of the respective bundles (Gson, Guava, ...) and use the best fit in all features

First solution will increase the size as soon as both feature that brings in two different versions are installed.
Second solution will increase the size for products that don't need the bigger bundle because already the bundle with the lower size fulfill their requirements.

**Comment by kaikreuzer** [comment]
No, no - I think for the situation here, it is exactly what we want. I was just pointing out a behavior that one must be aware of (and I am specifically sensible to it as I see the current openhab distro more or less completely restarting itself, when certain Karaf features are installed on it - so this might give me a hint what to look for).

**Pull request merged**
