### PR TITLE
Swagger annotations added to all bundles containing REST resources.

### PR DESCRIPTION
**Pull request by dnobel**
Also-by: YordanDZhelev <zhelev.yordan@gmail.com>
Signed-off-by: Dennis Nobel <d.nobel@external.telekom.de>

### CODE REVIEW

**Comment by dnobel** [comment]
This PR contains the swagger annotations only, but not the documentation generation, as we have some problem with that.

**Comment by kaikreuzer** [comment]
I think you still need to add the swagger lib to the about.html.

**Comment by dnobel** [comment]
Updated PR: library is mentioned in the about file and license is added.

**Comment by kaikreuzer** [comment]
thanks!

**Pull request merged**
