### PR TITLE
ColorItem control fix

### PR DESCRIPTION
**Pull request by aounhaider1**
Signed-off-by: Aoun Bukhari <bukhari@itemis.de>

### CODE REVIEW

**Comment by sjka** [comment]
@afuechsel since you discovered it (and I don't have any hue here...) can you please confirm this fixes the issue you observed?

**Comment by afuechsel** [comment]
I can confirm, that it id working again.

**Comment by kaikreuzer** [comment]
Was there any related bug report about what was broken?

**Comment by aounhaider1** [comment]
I don't think there is any related github issue. @afuechsel reported that to me. I can edit my comment to describe what was broken.

**Comment by maggu2810** [comment]
If my reading of the code has been correct, after sending a new value for hue, saturation of brightness, the old instead the new value has been assigned to the object. This PR fixes this and sets the new value instead of the old one. Is this correct?

**Comment by aounhaider1** [comment]
Yes, previously the old values were not updated.

**Pull request merged**
