### PR TITLE
LIFX: Add brightness channel to colorlight

### PR DESCRIPTION
**Pull request by kgoderis**
Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
There seems to be something wrong with Github-Eclipse-automatic-CLA-check.

```text
The following users do not have valid CLA. Please see this page for details, or to sign a CLA.
noreply@github.com
```
Don't know why noreply@github.com is used.

As you have a valud CLA, I merged it.

**Comment by kaikreuzer** [comment]
Can we please revert this? A brightness channel does not make any sense when there is already a color channel. We do not have that in the hue binding either.

**Comment by kgoderis** [comment]
@kaikreuzer Well, the brightness channel takes ON/OFF or PercentTypes and is handy to switch off the lamp. Of course, we can also add a separate "power" channel to switch the lamp (as that is part of the API), but that aspect is interwoven with the brightness/color channels already. I just refer to https://community.lifx.com/t/0-brightness-vs-power-off-effect-on-the-bulb-life-and-power-consumption/500/3 where this is discussed. Maybe I am stating something stupid here, but color/RGB is not the same as brightness; this is also exposed as such in the API. So, why should a color lamp not have a brightness channel?

**Comment by kgoderis** [comment]
@maggu2810 hey, I oppose this reversion. see my comment

**Comment by maggu2810** [comment]
@kgoderis The comment of Kai has been 6 hours before (from now), the revert has been 5 hours (from now). Your comment / oppose has been 26 minutes (from now). The reversion has been done before your comment has been written. So sorry about that. Perhaps we should wait for every merge / revert a few hours?

**Comment by maggu2810** [comment]
> Doing it all via the HSBK color means that - in Rules - you first have to fetch the color of the lamp, make a new HSBK type, put the B to 0, and send the HSBK as command back to the lamp. This is complicated IMO.

Your are right, but I don't think that we want to add channels to a thing to make the usage more easily.
IMHO the channels of a thing represent the outside world in the system - not more not less. The interaction using rules, UIs are another point of view.

**Comment by kgoderis** [comment]
> Your are right, but I don't think that we want to add channels to a thing to make the usage more easily.
> IMHO the channels of a thing represent the outside world in the system - not more not less. The interaction using rules, UIs are another point of view.

Are you serious? If really think this, then I will find you a bunch of bindings with a bunch of channels to delete! (btw, the LIFX app also has a separate control for the brightness)

**Comment by kaikreuzer** [comment]
@kgoderis: The Color channel supports HSB, where the B is for brightness. So the Color channel already provides everything a brightness channel would offer plus more.

> Doing it all via the HSBK color means that - in Rules - you first have to fetch the color of the lamp

Not at all, because a ColorItem also accepts PercentTypes as commands and when doing so, it adjusts the brightness. So it behaves exactly the same way as a DimmerItem.

**Comment by kgoderis** [comment]
> he comment of Kai has been 6 hours before (from now), the revert has been 5 hours (from now). Your comment / oppose has been 26 minutes (from now). The reversion has been done before your comment has been written. So sorry about that. Perhaps we should wait for every merge / revert a few hours?

Yeah - I took me some time to read it - I am not following github in realtime....

**Comment by kgoderis** [comment]
> Not at all, because a ColorItem also accepts PercentTypes as commands and when doing so, it adjusts the brightness. So it behaves exactly the same way as a DimmerItem.

true true.... I was rather thinking ON / OFF...

**Comment by kaikreuzer** [comment]
Color and Dimmer are both also Switches, so they also support ON/OFF. For ESH, we do not make a difference between OFF and brightness=0 though, since your link to the LIFX thread nicely shows that this rather causes issues for users....

**Comment by kgoderis** [comment]
Weird... this afternoon when testing LIFX on the Karaf distro the ON OFF was not working anymore, hence my action to add the channel... WTF

**Comment by kaikreuzer** [comment]
Didn't you say in another issue (about aries) that the LIFX binding didn't work AT ALL?

**Comment by kgoderis** [comment]
Solved that, It was me copying over an older .things with the old ThingTypeUIDs

**Pull request merged**
