### PR TITLE
Addresses a NPE in PersistentInbox

### PR DESCRIPTION
**Pull request by DaHoC**
when an appropriate storage service is not (yet) registered
Addresses #5920 

Signed-off-by: Jan Hendriks <Jan.Hendriks@telekom.de>

### CODE REVIEW

**Comment by htreu** [comment]
@maggu2810 could you have a look, please? This looks good to me but since you added the `DYNAMIC` reference for the storage service you might want to have a look.
Btw: Why did you change the reference to `DYNAMIC` here but others (like `ManagedItemProvider`)  are still static?

**Comment by htreu** [comment]
Also, Travis is unhappy due to tabs in the edited file:

```
[ERROR] org.eclipse.smarthome.config.discovery.internal.PersistentInbox.java:[303]
File contains tab characters (this is the first instance).
```

@DaHoC please review your formatter settings.

**Comment by htreu** [comment]
friendly ping @maggu2810, did you see https://github.com/eclipse/smarthome/pull/5921#issuecomment-405256156?

**Comment by maggu2810** [comment]
@htreu Will have a look at. Have been rather busy...

**Comment by maggu2810** [comment]
> Btw: Why did you change the reference to `DYNAMIC` here but others (like `ManagedItemProvider`)  are still static?

It has been changed for the `ManagedItemProvider` to `DYNAMIC`, too.
It seems someone break it again.

See: https://github.com/eclipse/smarthome/commit/a0ebb170eb5831902fc20b841e1f070d065747fb#diff-e86573af23ebce3da0894d6929c1d3a4R19


@DaHoC, @htreu, @triller-telekom Can you share your findings? The storage is dymanic but should be still mandatory. So as long as the component is active and allowed to be used, there shouldn't be a NPE. Can you explain me the current situation?

**Comment by maggu2810** [comment]
@sjka It seems you removed the dynamic reference in your the commit 914ce11135

https://github.com/eclipse/smarthome/commit/914ce11135#diff-e86573af23ebce3da0894d6929c1d3a4L19
has been replaced by
https://github.com/eclipse/smarthome/commit/914ce11135#diff-10d1b28481ffb9aa7a2c7a6de4917192R287
and the dynamic got lost

Has this done by intention?

**Comment by htreu** [comment]
Thanks @maggu2810 for clarification!
My guess is that the `DYNAMIC` annotation from ManagedItemProvider got lost by accident.
With the NPE reported at `PersistentInbox.java:303` and the StorageService being mandatory the `getValues()` method is the next candidate to provide a null reference.
@DaHoC which StorageService implementation are you using? Please check the behaviour of `getValues`.

**Comment by maggu2810** [comment]
@DaHoC Would it be okay for you to change the code to (e.g.)

```Java
    @Override
    @NonNullByDefault({})
    public Stream<DiscoveryResult> stream() {
        final Storage<DiscoveryResult> discoveryResultStorage = this.discoveryResultStorage;
        if (discoveryResultStorage == null) {
            final ScheduledFuture<?> timeToLiveChecker = this.timeToLiveChecker;
            logger.warn("The OSGi lifecycle has been violated (storage: {}, ttl checker cancelled: {}).",
                    this.discoveryResultStorage, timeToLiveChecker == null ? "null" : timeToLiveChecker.isCancelled());
            return Stream.empty();
        }
        final Collection<@Nullable DiscoveryResult> values = discoveryResultStorage.getValues();
        if (values == null) {
            logger.warn(
                    "The storage service violates the nullness requirements (get values must not return null) (storage class: {}).",
                    discoveryResultStorage.getClass());
            return Stream.empty();
        }
        return values.stream().filter(Objects::nonNull);
    }
```

For me it would be okay to add that lines of code to be more robust and at least log warnings that there went something wrong.

**Comment by DaHoC** [comment]
Yes that would be a good option, to make the code more robust and to provide additional information in the error case - Going to update the PR with your suggestions

**Pull request merged**
