### PR TITLE
Fix Classic UI CSS issues mentioned in #375

### PR DESCRIPTION
**Pull request by resetnow**
Tested with several sitemaps, issue mentioned in #375 should be fixed.

Signed-off-by: Vlad Ivanov <vlad-mbx@ya.ru>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Wonderful - it all looks good now! Thank you so much :-)

Now the only enhancement that is left is to change the CSS from iOS 1 to iOS 8 style :-D

**Comment by resetnow** [comment]
Well, since both iOS and Android have native OpenHAB applications, it would be great to have a design that doesn't try to mimic any mobile OS. We need to ask a designer about this... if we had one. Also, isn't PaperUI meant to replace ClassicUI in OpenHAB 2?

**Comment by kaikreuzer** [comment]
> it would be great to have a design that doesn't try to mimic any mobile OS

I agree - but at the moment it mimicks a very old mobile OS and thus provokes comments like https://twitter.com/cODAR/status/606095486974623744.
I am still looking for a designer who would want to take care about that - difficult to find one :-|

It'll take a while until the Paper UI can be a full replacement for the Classic UI. It requires more CPU power and thus is not ideal for older phones, it does not have any sitemap support yet, etc. So still some way to go and having different UI options is anyhow a nice thing.

**Comment by resetnow** [comment]
As a start, do you think it would be usable to have an option for Classic UI plugin allowing to change theme by specifying CSS file name?

**Comment by kaikreuzer** [comment]
We would first need an alternative CSS theme, before such a switch option makes sense. Would you want to try prototyping one?

**Comment by resetnow** [comment]
It is unlikely I can prototype something good-looking. I can implement a layout from a template, though.

**Comment by kaikreuzer** [comment]
Maybe go towards material design as well and use something like https://home-assistant.io/demo/ as a template?

**Comment by resetnow** [comment]
This is a good idea. Google recently released [Material Design Light](http://www.getmdl.io/), it should be less intensive on CPU than Angular + Polymer. I'll give it a try next week (as soon as my notebook is returned from service).

**Comment by kaikreuzer** [comment]
Didn't hear about MDL yet - sounds like a perfect fit!

**Comment by resetnow** [comment]
@kaikreuzer please take a look — http://resetnow.ru/temp/esh-material/ — what do you think?

**Comment by kaikreuzer** [comment]
Wow, that is incredibly cool!!! I cannot wait to see the Classic UI being updated to such a style!

**Comment by kaikreuzer** [comment]
Any progress? Sorry for asking, but I simply get too excited when looking at your prototype :-D

**Comment by resetnow** [comment]
@kaikreuzer I'm pushing changes to [resetnow/smarthome/classic-ui-mdl](https://github.com/resetnow/smarthome/tree/classic-ui-mdl). As for now, some widgets work (buttons, slider, switch, selection) and ajax load is somewhat implemented. All the WebApp stuff had to be removed because it quite old and does not suit well for MDL. Current TODO list looks like this:

- [ ] Implement AJAX history control (HistoryStack)
- [ ] Implement remaining widgets
- [ ] Implement live update using Websockets and REST API
- [ ] First PR — test across browsers
- [ ] Fix bugs found in first PR
- [ ] Add Grunt build system (less, eslint, ets)
- [ ] Second PR — merge (at least I hope so)
- [ ] \(maybe\) Add some fallbacks for older browsers — weak points are Websockets and Flexbox

**Comment by kaikreuzer** [comment]
Oh hell, this sounds like a lot more effort than I would have ever dared to ask you for! Million thanks for still getting deeper into it!

A question about

> Implement live update using Websockets and REST API

Do you plan a partial updates here of single widgets and not do the current long-polling mechanism anymore? Note that there is no Websockets support in ESH, but this has been replaced by SSE (https://www.eclipse.org/smarthome/documentation/features/rest.html#server-sent-events-sse). There are no events for anything sitemap related though for the moment as we are planning to introduce a new sitemap concept. That's why I would not suggest heading this way at the moment, but rather stick with long-polling the whole sitemap page.

**Comment by resetnow** [comment]
Honestly I didn't try to use Websockets, I just checked if that's possible. However, I used Openhab API wiki page as a reference. 

Is it possible to use long-polling with REST API in esh? For instance, with JSON? I would like to avoid reloading the whole page because it's bad for performance and end user experience (reloading the page resets scroll, controls have to be re-initialized, etc).

Server-sent events look good though. They aren't supported by IE at all, so they will be a second option then.

**Comment by resetnow** [comment]
>There are no events for anything sitemap related though for the moment as we are planning to introduce a new sitemap concept

As long as there is an event when item state changes, it is possible to use them as event source. Items are mapped to widgets in javascript (not yet, but at least I plan to do so).

**Comment by kaikreuzer** [comment]
> I used Openhab API wiki page as a reference.

Better don't :-) To see what the REST-API offers, you might like this link: http://demo.openhab.org:9080/doc/index.html
No events covered there, though.

> Is it possible to use long-polling with REST API in esh? For instance, with JSON?

Yes, there is a simple, event-between-requests-losing long-polling implementation on the /rest/sitemap resource, which I did specifically for keeping the Classic UI compatible, see https://github.com/eclipse/smarthome/pull/61.

> I would like to avoid reloading the whole page

I know about the problems of this approach and any other approach is definitely better, but means a complete revamp of the Classic UI - but if you are willing to do this, I won't stop you...

>  They aren't supported by IE at all

Well, there might be ways around that: https://github.com/rwaldron/jquery.eventsource

> As long as there is an event when item state changes, it is possible to use SSE as event source. 

Yes, these events are available - and yes, I agree that this will probably suffice for most cases. Some features might be lost, like the conditional visibility and coloring (as this decides on the server whether a widget for an item is shown or not and in which color), but I think this is acceptible, if this is only updated through a manual reload.

What I would want to make sure though is that the Classic UI stays lean and fast, so that it is also usable on older phones with not much CPU power - so the use of client-side javascript should not be too extensive; otherwise we might directly go for the Paper UI, which follows the pure HTML5/Javascript approach.

**Comment by resetnow** [comment]
>Well, there might be ways around that: https://github.com/rwaldron/jquery.eventsource

Interesting, I'll take a look at it. We don't use jQuery, though.

>What I would want to make sure though is that the Classic UI stays lean and fast, so that it is also usable on older phones with not much CPU power

Well, switching to event-based updating will, in fact, improve performance, because DOM operations (like reloading the whole page) usually act as a bottleneck. I'm testing it on Samsung i9100 (2011), maybe somebody could test it on an older phone later (as for now there are Android < 4.3 compatibility issues). Besides, there is an app for both Android and iOS, which is native and thus probably faster.

>Paper UI, which follows the pure HTML5/Javascript approach

As far as I understand, Paper UI is not so pure — it actively uses Angular and Polymer framework. In best case MDL implementation of Classic UI will not be using any external libraries (except for MDL components).

**Comment by kaikreuzer** [comment]
> Interesting, I'll take a look at it. We don't use jQuery, though.

Maybe this is the better option: https://github.com/Yaffle/EventSource

**Comment by cdjackson** [comment]
One problem with using event source is that it won’t allow you to use the dynamic features of the sitemap. So, when a widget appears, or disappears, or the color changes, then this can’t be re-evaluated since it is only done on the server (unless I’ve not understood what you’re doing)

**Comment by resetnow** [comment]
Can we implement some kind of message for ClassicUI saying that sitemap has changed and needs reloading?

**Pull request merged**
