### PR TITLE
Reworked XML bundle processing and thing handler initialization

### PR DESCRIPTION
**Pull request by kaikreuzer**
This PR includes a lot of improvements on how unfinished XML loading is recognized.
What needs to be made sure though, is that the core.thing.xml bundle is started early. As it is an optional bundle (and in theory there can be solutions not supporting any XML declarations), I didn't want to introduce a hard dependency from core.thing to it, so this needs to be solved through bundle start levels.

Another change I made is the check whether a bundle contains resources. It used to check the classpath in order to also regard fragments correctly. Unfortunately, this brought up many false positives, which potentially has quite some bad impact on startup time. Now it is only checked that the bundle contains the according folder (like "ESH-INF/thing" or "ESH-INF/config"). This means that if a fragment contains files in those folders, the host bundle should at least have an empty folder as well.

I also remove the accidential dependency from core.xml to core.thing.

fixes https://github.com/eclipse/smarthome/issues/1796
fixes https://github.com/eclipse/smarthome/issues/1847

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
Do you think this could be used for #1550, too?

**Comment by kaikreuzer** [comment]
> Do you think this could be used for #1550, too?

Potentially, yes. But I didn't want to include it in the scope here as well, it was already painful enough today :-/

**Comment by maggu2810** [comment]
> But I didn't want to include it in the scope here as well

Me, too. Just want to know if it could be an option.

**Comment by kaikreuzer** [comment]
Failing test was due to git not adding empty folders - now added a dummy file to the empty folder, which should fix the problem.

**Comment by maggu2810** [comment]
I am using ".keep" files for that use case.
The name states that it should be kept and the dot in front of the name should make it hidden for Unix based systems.

Thanks @kaikreuzer for your work.

**Comment by kaikreuzer** [comment]
> I am using ".keep" files for that use case.

Ok, will try to remember doing the same in future then!

**Comment by maggu2810** [comment]
One remaining question from my side:
What about org.eclipse.smarthome.config.xml?
I assume that XMLs needs to be processed before the thing handler is called, too.
Shouldn't it also be activated, the the async loader (bundle processor) can veto the thing handler initialization?

**Comment by maggu2810** [comment]
Just an idea:
If a new bundle processor is registered later (e.g. a new processor is installed) wouldn't it be an option to reinitialize the thing handler (perhaps for non-online things only) if this processor handles at least one XML of the binding containing the handler? This would allow to be independent of the startup order. Or I am missing something here?

**Comment by kaikreuzer** [comment]
> What about org.eclipse.smarthome.config.xml?

core.thing.xml has a dependency on it, so it should automatically be activated as well. But if you like, we can also change the startlevel for it, just to be clear.

> Shouldn't it also be activated

Actually, we should add the lazy-bundle activation again to all bundles that we once removed to make sure that this happens...

> wouldn't it be an option to reinitialize the thing handler

Maybe, but I think this would all add too much further complexity. And having handlers being initialized multiple times during startup might cause many new issues, so don't think we should do this.

**Comment by maggu2810** [comment]
From my side it is okay to merge your work and remove the currently critical bug.
If there are further improvements we can do this in follow up PRs.

Any comments from others?

**Comment by kaikreuzer** [comment]
There is still a failing test on travis, I am currently fixing it and will update the PR - please wait with the merge until then.

**Comment by kaikreuzer** [comment]
renamed the file to .keep, fixed the failing test and changed the start level of config.xml as well.
If travis is green this time, we should be good to merge!

**Comment by kgoderis** [comment]
I am catching up with a lot of issues/PR and so forth. /me thinks that this PR here is related to my point 4. in https://github.com/eclipse/smarthome/issues/1847#issuecomment-241850965 (note, the github editor screws up the numbering of the things I listed, it is the one about KNX)

**Pull request merged**
