### PR TITLE
Fix PaperUI to allow editing of thing parameters

### PR DESCRIPTION
**Pull request by cdjackson**
This updates PaperUI to allow editing of thing configuration parameters which is currently not possible.
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
@aounhaider1 Can you have a look at?

**Comment by aounhaider1** [comment]
I don't understand what problem is this PR fixing. PaperUI already supports editing of thing configuration parameters. The only difference I see is that now instead of getting config description of parameters from thingType, this PR is getting it from config-descriptions. @cdjackson Can you please explain?

**Comment by cdjackson** [comment]
Paper UI currently only allows editing of configuration that is defined in the thing-type - not the thing. This allows editing of configuration that is defined in the thing as well as the thing type.

Basically, as it currently stands, PaperUI doesn’t show any configuration of parameters that are defined dynamically in a ConfigProvider.

**Comment by cdjackson** [comment]
To add - the important point here is not that we’re getting the config from the other REST endpoint - but we’re defining this with “thing” scope - not “thing-type” which is the default if you go through the thing endpoint.

**Comment by aounhaider1** [comment]
Ok. The rest looks fine.

**Pull request merged**
