### PR TITLE
Fix #1243 - WeMo LED lights not going ONLINE

### LINKED ISSUE #1243: WeMo Binding; Newly discovered LED lights don't go ONLINE
but stay "INITIALIZING" forever.
After a restart, they come online

### PR DESCRIPTION
**Pull request by hmerk**
Signed-off-by: Hans-Jörg Merk <hans-joerg.merk@t-online.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hm, this looks like a strange fix to me. Actually, the Thing should be online, even if no channel is linked. So I would expect a fix rather in the initializing phase.

**Comment by hmerk** [comment]
You convinced me :-)
I hope this looks better.

**Comment by kaikreuzer** [comment]
Yes, looks better.
Another question: Are you aware of this method? https://github.com/eclipse/smarthome/blob/master/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java#L538
You might want to react on this as well, in case the bridge is offline when the light handler is initialized and thus set to OFFLINE, but the bridge comes online later on.

**Comment by hmerk** [comment]
No, was not aware of that method. It is implemented now as well.

**Comment by kaikreuzer** [comment]
Perfect, thanks!

**Comment by hmerk** [comment]
That was quick :-)

**Pull request merged**
