### PR TITLE
JSonstorage without internal Gson packages

### PR DESCRIPTION
**Pull request by triller-telekom**
Work in progress for issue #2697

### CODE REVIEW

**Comment by maggu2810** [comment]
Can you change the title of the PR to start with e.g. "WIP: ", so the "work in profess" comment is more present?

**Comment by maggu2810** [comment]
@cdjackson As you started the JSON storage implementation, would you like to have a look at?

**Comment by cdjackson** [comment]
Ok - it will be tomorrow.

**Comment by cdjackson** [comment]
Looks good to me - tested ok here.

**Comment by maggu2810** [comment]
Thank you both

**Pull request merged**
