### PR TITLE
fix failing tests because of default locale

### PR DESCRIPTION
**Pull request by BenediktNiehues**
Signed-off-by: Benedikt Niehues <benedikt.niehues@itemis.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
So can we sure that the default is always English?

**Comment by BenediktNiehues** [comment]
not the default was always English, but the expectation.

**Comment by kaikreuzer** [comment]
I mean can the tests fail if I execute them on a system that does not have english as a locale?

**Comment by BenediktNiehues** [comment]
yes, on systems with german locale the tests are failing.

**Comment by kaikreuzer** [comment]
Then I do not understand this PR. `moduleTypeRegistry.get(trigger1)` means to get the trigger in the default locale, but the tests now expect english. It looked better to me before?

So imho the tests should set the default locale to english and then test against this. But this does not seem to be the case here.

**Comment by BenediktNiehues** [comment]
@kaikreuzer you are right, I updated the PR accordingly.

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
