### PR TITLE
Automation API and JSON files - initial contribution by ProSyst

### PR DESCRIPTION
**Pull request by mmitev-prosyst**
added automation Java API and JSON files to /smarthome/bundles/automation

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Does this replace #190 ?

**Comment by mmitev-prosyst** [comment]
I have created second commit just for the missing import package, but in 
the mean time I have changed my  git email address, and then github 
complained with:
"Failure, The Pull request did not pass Eclipse validaton ...", because 
of missing Eclipse account for the new email address - see attached picture
So I  have returned my original email address and reverted the commit, 
but I am not sure now if these two commits are part of the pull request 
that you see...

Best regards,
Marin

**Comment by mmitev-prosyst** [comment]
After my second look, please discard this request, lets all continue to 
use the first one #190 <https://github.com/eclipse/smarthome/pull/190>

**Comment by kaikreuzer** [comment]
Don't worry about CLA validation, number of commits etc for the moment - once we are through with review and discussions, we will anyhow have to clean up the PR. I did my review on #191, but I hope #190 is codewise identical. So let's continue with #190.

**Pull request closed without merging**
