### PR TITLE
Send only one request per thingType on control page

### PR DESCRIPTION
**Pull request by aounhaider1**
fixes https://github.com/eclipse/smarthome/issues/3010
Signed-off-by: Aoun Bukhari <bukhari@itemis.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
Now there is only one request per control page load.
So far so good.

A site navigation to another page and then back to the control page again will trigger a reload of all used thing-types. Is this done by intention? Do we expect that a thing-type can be changed all the time?
Or shouldn't it be cached for the whole "session"?

@aounhaider1 Can you explain me how you test it?
I used the recent master and your changes.
I see that for the 36 thing of the same type the thing-type is only requested once, but the control page does not show any of the 36 things at all.

**Comment by aounhaider1** [comment]
Yes, the thing-types will be loaded again on navigation. We can change that to load thing-types from local repo but then any changes in thing-types will only be shown if a browser refresh is done.
´´´´Do we expect that a thing-type can be changed all the time?´´´´
I think @kaikreuzer can answer it better.

´´´´but the control page does not show any of the 36 things at all.´´´´
You should clear the cache. The js might be cached. The other reason can be a unresponsive script error if you have large number of things.

**Comment by maggu2810** [comment]
> @aounhaider1 Can you explain me how you test it?

Would be great if you give me some details how I should test it.

This is what I am doing:

---

* Checkout PR into a new branch

```
$ git checkout -b pr3026 eclipse-pull/3026
Branch pr3026 set up to track remote ref refs/pull/3026/head.
Switched to a new branch 'pr3026'
```

* Ensure working copy does not contain any local changes

```
$ git status
On branch pr3026
Your branch is up-to-date with 'eclipse-pull/3026'.
nothing to commit, working tree clean
```

* Start the Eclipse IDE installed by the Eclipse Installer and the Eclipse SmartHome setup
* Change the content of: Other Projects, distribution, smarthome/conf/things/demo.things` to look like

```text
yahooweather:weather:berlin [ location=638242 ]
yahooweather:weather:losangeles "Los Angeles" [ location=2442047, refresh=120 ]

yahooweather:weather:berlinA [ location=638242 ]
yahooweather:weather:berlinB [ location=638242 ]
yahooweather:weather:berlinC [ location=638242 ]
yahooweather:weather:berlinD [ location=638242 ]
yahooweather:weather:berlinE [ location=638242 ]
yahooweather:weather:berlinF [ location=638242 ]
yahooweather:weather:berlinG [ location=638242 ]
yahooweather:weather:berlinH [ location=638242 ]
yahooweather:weather:berlinI [ location=638242 ]
yahooweather:weather:berlinJ [ location=638242 ]
yahooweather:weather:berlinK [ location=638242 ]
yahooweather:weather:berlinL [ location=638242 ]
yahooweather:weather:berlinM [ location=638242 ]
yahooweather:weather:berlinN [ location=638242 ]
yahooweather:weather:berlinO [ location=638242 ]
yahooweather:weather:berlinP [ location=638242 ]
yahooweather:weather:berlinQ [ location=638242 ]
yahooweather:weather:berlinR [ location=638242 ]
yahooweather:weather:berlinS [ location=638242 ]
yahooweather:weather:berlinT [ location=638242 ]
yahooweather:weather:berlinU [ location=638242 ]
yahooweather:weather:berlinV [ location=638242 ]
yahooweather:weather:berlinW [ location=638242 ]
yahooweather:weather:berlinX [ location=638242 ]
yahooweather:weather:berlinY [ location=638242 ]
yahooweather:weather:berlinZ [ location=638242 ]
yahooweather:weather:berlin0 [ location=638242 ]
yahooweather:weather:berlin1 [ location=638242 ]
yahooweather:weather:berlin2 [ location=638242 ]
yahooweather:weather:berlin3 [ location=638242 ]
yahooweather:weather:berlin4 [ location=638242 ]
yahooweather:weather:berlin5 [ location=638242 ]
yahooweather:weather:berlin6 [ location=638242 ]
yahooweather:weather:berlin7 [ location=638242 ]
yahooweather:weather:berlin8 [ location=638242 ]
yahooweather:weather:berlin9 [ location=638242 ]
```

* Edit the debug configuration for "SmartHome-Runtime" and remove `org.eclipse.smarthome.ui.paper` from the selected Plug-ins selection

* Launch the debug configuration

* Open terminal and use gulp to get an up-to-date PaperUI

```
$ (cd extensions/ui/org.eclipse.smarthome.ui.paper/; gulp serve --development)
[16:50:33] Using gulpfile ~/bin/pkgs/eclipse/esh/git/smarthome/extensions/ui/org.eclipse.smarthome.ui.paper/gulpfile.js
[16:50:33] Starting 'uglify'...
[16:50:33] Starting 'concat'...
[16:50:33] Finished 'concat' after 12 ms
[16:50:33] Starting 'copyCSSLibs'...
[16:50:33] Starting 'copyFontLibs'...
[16:50:33] Starting 'copyJSLibs'...
[16:50:33] Starting 'copyJQUI'...
[16:50:33] Finished 'copyJQUI' after 1.98 ms
[16:50:33] Starting 'copyJSMisc'...
[16:50:33] Starting 'copyStatic'...
[16:50:33] Starting 'copyPartials'...
[16:50:34] Finished 'copyJSMisc' after 506 ms
[16:50:34] Finished 'copyCSSLibs' after 559 ms
[16:50:35] Finished 'copyJSLibs' after 1.78 s
[16:50:35] Finished 'uglify' after 1.82 s
[16:50:35] Finished 'copyStatic' after 1.78 s
[16:50:35] Finished 'copyFontLibs' after 1.8 s
[16:50:35] Finished 'copyPartials' after 1.8 s
[16:50:35] Starting 'build'...
[16:50:35] Finished 'build' after 55 μs
[16:50:35] Starting 'inject'...
MODE:true
inject script = js/app.js
inject script = js/constants.js
inject script = js/controllers.configuration.js
inject script = js/controllers.system.js
inject script = js/controllers.items.js
inject script = js/controllers.control.js
inject script = js/controllers.extension.js
inject script = js/controllers.js
inject script = js/controllers.rules.js
inject script = js/controllers.module.js
inject script = js/controllers.setup.js
inject script = js/extensions.js
inject script = js/main.js
inject script = js/services.js
inject script = js/services.repositories.js
inject script = js/services.rest.js
inject script = js/shared.properties.js
[16:50:35] gulp-inject 17 files into index.html.
[16:50:35] Finished 'inject' after 41 ms
[16:50:35] Starting 'serve'...
[HPM] Proxy created: [ '/rest', '/icon', '/audio' ]  ->  http://localhost:8080
[16:50:35] Finished 'serve' after 45 ms
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:3000/
    External: http://10.10.10.14:3000/
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://10.10.10.14:3001
 -------------------------------------
[BS] Serving files from: ./web-src
[BS] Serving files from: ./web
```

* Test it in a private tab of a browser (e.g.: `firefox-bin --private http://localhost:3000/` or `google-chrome-stable --incognito http://localhost:3000/`)

---

Doesn't a private / incognite window start with an empty cache?

**Comment by maggu2810** [comment]
Okay, I realized that there is no channel linked visible for all the things...
Will change the items file, too and give you feedback.

**Comment by maggu2810** [comment]
One remaining question:
> A site navigation to another page and then back to the control page again will trigger a reload of all used thing-types. Is this done by intention? Do we expect that a thing-type can be changed all the time?
Or shouldn't it be cached for the whole "session"?

But this is perhaps another change...

**Pull request merged**
