### PR TITLE
Paper UI: render transformed item state in control page

### LINKED ISSUE #3821: Paper UI: display for Contact items with MAP transformation
What is the expected display in Paper UI for a contact channel ? I get no value and no control displayed.

### PR DESCRIPTION
**Pull request by htreu**
Fixes #3821.

Signed-off-by: Henning Treu <henning.treu@telekom.de>

### CODE REVIEW

**Comment by htreu** [comment]
@lolodomo would be nice to hear your feedback about this one.

**Comment by lolodomo** [comment]
Thanks, I will check that soon.

**Comment by lolodomo** [comment]
Oups, it looks like the state is no more updated in real time in Paper UI, I need z Ctrl+F5 in my browser to get an updated state.
I have to check if this is a general issue in Paper UI or if only a problem for contact widget with MAP transformation.

**Comment by lolodomo** [comment]
There is no general problem with refresh in Paper UI. So I can confirm that refresh of state is not working for contact item with a transformation.

**Comment by htreu** [comment]
Thanks for the feedback, I will look into it.

**Comment by htreu** [comment]
The problem is, that the `ItemSateChangedEvent` only contains old and new state but not the transformed state. Paper UI will not get an update for the transformed state and thus renders the current transformed state.

**Comment by kaikreuzer** [comment]
Closing by hoping that you agree to the compromise I outlined in https://github.com/eclipse/smarthome/issues/3821#issuecomment-399440142.

**Pull request closed without merging**
