### PR TITLE
Update the version of the SAT tool.

### PR DESCRIPTION
**Pull request by svilenvul**
See https://github.com/openhab/static-code-analysis/issues/293

Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Looks as if I have missed to publish it to Maven Central - just did so, it will take a moment until it is available there.

**Comment by kaikreuzer** [comment]
This time, the build exceeded 1 hour and travis failed...
@svilenvul Do we have any new checks that would heavily increase the build time? Or was that just bad luck, because something got stuck on Travis? I'll retry in any case.

**Comment by svilenvul** [comment]
I think I have an idea, I will update the PR.

**Comment by kaikreuzer** [comment]
That might be it :-)

**Pull request merged**
