### PR TITLE
created some initial coding guidelines

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@maggu2810 and others: Feel free to suggest further rules for this list!

**Comment by dnobel** [comment]
Kai, looks fine for me. Should I merge it directly or should we discuss additional rules on this PR?

**Comment by kaikreuzer** [comment]
I'd suggest to merge it and to create new PRs for any addition or changes.

**Comment by maggu2810** [comment]
Good stuff.
Should we add the ident rule (two spaces) for pom.xml?

**Comment by kaikreuzer** [comment]
now that all poms are in that format, people will probably automatically adopt it - not sure if it is relevant to mention

**Pull request merged**
