### PR TITLE
Adding MapView to display Location items in Sitemap as done in OH1

### PR DESCRIPTION
**Pull request by clinique**
Signed-off-by: Gaël L'hopital <glhopital@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Just tried it - that's pretty cool.
I only have one question: Do you know the legal details about whether it is ok to include this service in EPL licensed software (which means that it could also be used commercially)? Is the embedded copyright in the map all that is required and one can use it for any purpose or are there restrictions?

**Comment by clinique** [comment]
As far as I understood OSM license for usage of maps (§3 in http://wiki.openstreetmap.org/wiki/Legal_FAQ), yes the embedded copyright is enough. It would be another point if we used derivated informations (geocoding adress from LocationItem for exemple), but it is not the case...at least right now :)

**Comment by kaikreuzer** [comment]
Ok, thanks. I think I will nonetheless ask for approval by the PMC and the IP team for this dependency, so please allow a few days before this can be merged. Codewise it all looks good to me!

**Comment by kaikreuzer** [comment]
Good news, CQ 9638 has been approved as a works-with dependency for OpenStreetMap - I have thus added it to the about.html and we are ready to merge!

**Pull request merged**
