### PR TITLE
Start AnnotatedActionModuleTypeProvider service immediately

### PR DESCRIPTION
**Pull request by triller-telekom**
See https://github.com/openhab/openhab2-addons/pull/2926#issuecomment-443493064

Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Are you sure that this is the cause? Afaik, the provider should be activated automatically once the rule engine starts up (as the ModuleTypeRegistry depends on them).

**Comment by triller-telekom** [comment]
Can you please point me to the code where the `ModuleTypeRegistry` depends on my `AnnotatedActionModuleTypeProvider`?

I guess the `ProviderTracker` "collects" all running providers and calls `addProvider()` on the registry. And if my provider is not yet running, there is nothing to collect.

**Comment by kaikreuzer** [comment]
Hm, good point, I didn't remember that this was done through trackers and not DS references.

But do you have any explanation why it actually works for other actions (such as MQTT)?

**Comment by J-N-K** [comment]
It is not working for MQTT in my setup (not in Eclipse and not in my production environment).

**Comment by kaikreuzer** [comment]
It is for me and it also works for the Magic Action with which @triller-telekom had tested the provider.

**Comment by kaikreuzer** [comment]
According to my testing, this is not required, see https://github.com/openhab/openhab2-addons/pull/2926#issuecomment-443710164.

**Pull request closed without merging**
