### PR TITLE
Fixed timing issue in test case.

### PR DESCRIPTION
**Pull request by sbussweiler**
Signed-off-by: Stefan Bussweiler <s.bussweiler@external.telekom.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Does this fix https://github.com/eclipse/smarthome/issues/931?

**Comment by sbussweiler** [comment]
Yes.

**Comment by kaikreuzer** [comment]
Cool, thanks :+1:

**Comment by maggu2810** [comment]
@sbussweiler Thank you.

**Pull request merged**
