### PR TITLE
Hue: Add Lightify Flex Strips RGBW

### PR DESCRIPTION
**Pull request by bjornhamra**

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks! Could you please sign-off your commit and make sure that you have a CLA signed? See https://github.com/eclipse/smarthome/blob/master/CONTRIBUTING.md#legal-considerations.

**Comment by sjka** [comment]
Thanks, the commit ID looks much better now. However, you need to clean up the git history now a little bit. Could you please squash your commits, so you end up with only a single commit that contains your changes? You will have to force-push it to your remote branch then...

**Comment by kaikreuzer** [comment]
Thanks - with the new merge process I was able to squash the commits myself (after checking the CLA manually).

**Comment by bjornhamra** [comment]
Hi,

Sorry I missed the previous message. Will be sure to organize into single commit pulls next time!

**Pull request merged**
