### PR TITLE
New build profile added for JavaDoc generation.

### PR DESCRIPTION
**Pull request by VentsislavIliev**
Signed-off-by: VentsislavIliev <ventsislav.iliev@musala.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
How do I use it?
When doing a `mvn -P javadoc clean install`

I get
```
Generating /Users/kai/Documents/dev/esh/git/smarthome/target/apidocs/help-doc.html...
100 errors
100 warnings
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Eclipse SmartHome .................................. FAILURE [01:32 min]
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:32 min
[INFO] Finished at: 2015-09-28T18:17:41+02:00
[INFO] Final Memory: 158M/729M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:aggregate-jar (aggregate) on project smarthome: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - /Users/kai/Documents/dev/esh/git/smarthome/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/binding/BindingInfo.java:102: error: reference not found
[ERROR] * Returns {@code true} if a link to a concrete {@link ConfigDescription} exists,
[ERROR] ^
[ERROR] /Users/kai/Documents/dev/esh/git/smarthome/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/binding/BindingInfo.java:112: error: reference not found
[ERROR] * Returns the link to a concrete {@link ConfigDescription}.
[ERROR] ^
[ERROR] /Users/kai/Documents/dev/esh/git/smarthome/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/osgi/ServiceBinder.java:41: error: block element not allowed within inline element <code>: pre
[ERROR] * <b>Usage Example:</b> <code><pre>
[ERROR] ^
[ERROR] /Users/kai/Documents/dev/esh/git/smarthome/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/osgi/ServiceBinder.java:49: error: semicolon missing
[ERROR] *   &#64Bind
[ERROR] ^
[ERROR] /Users/kai/Documents/dev/esh/git/smarthome/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/osgi/ServiceBinder.java:50: error: semicolon missing
[ERROR] *   &#64Unbind
...
```

**Comment by kaikreuzer** [comment]
I found the solution: You will have to deactivate doclint, see http://stackoverflow.com/a/16743137

**Comment by VentsislavIliev** [comment]
A new profile is added which will be activated only if the JDK version is 1.8 or higher. 
The new profile sets one new project property with value '-Xdoclint:none'.
This property is needed by the maven-javadoc-plugin and its value will be passed by the maven-javadoc-plugin to the javadoc.exe in order to disable doclint.

**Comment by kaikreuzer** [comment]
Is it necessary to have the additional profile? Does Java 1.7 have problems, if there is the setting '-Xdoclint:none'?

**Comment by YordanDZhelev** [comment]
Java 1.7 will not recognize this argument and the build will fail.

**Comment by kaikreuzer** [comment]
ok, thanks!

**Pull request merged**
