### PR TITLE
[Sonos] Added support for Sonos Beam and Sonos Playbase

### PR DESCRIPTION
**Pull request by lolodomo**
…night mode and speech enhancement

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
Fixes issue #4156 

@pdcemulator : please try this version of the binding. Your Sonos Beam should now be correctly and automatically discovered (with the right thing type). Addtionnally, speech enhancement and night modes channels should be correctly updated when you change these modes from the Sonos app. You can even try to update these modes from the binding but there is only a little chance that it works because I tried to guess without the possibility to check what could be the action name, action parameter name and parameter value Sonos has defined for these 2 features.
[org.eclipse.smarthome.binding.sonos-0.11.0-SNAPSHOT.zip](https://github.com/eclipse/smarthome/files/2705871/org.eclipse.smarthome.binding.sonos-0.11.0-SNAPSHOT.zip)

**Comment by lolodomo** [comment]
@pdcemulator : you can also check that the channel `linein` is set correctly depending on whether you have connected the HDMI or not.
Of course, please check that the thing type is `Beam`.

Please try to send a notification to your Sonos Beam while you are listening the TV. I was told that with the playbar the TV sound is not restored after the notification. I have added additional logs I am interesting to check with you.

Regarding th econtrol of night mode and speech enhancement from the binding, if the action I use is wrong, you should probably get errors in the logs.

**Comment by pdcemulator** [comment]
Thank you so much. I will test this in the next days.

**Comment by lolodomo** [comment]
New version with updated documentation and translations.
[org.eclipse.smarthome.binding.sonos-0.11.0-SNAPSHOT.zip](https://github.com/eclipse/smarthome/files/2705921/org.eclipse.smarthome.binding.sonos-0.11.0-SNAPSHOT.zip)

**Comment by lolodomo** [comment]
New version with documentation updated and more probable accepted v
[org.eclipse.smarthome.binding.sonos-0.11.0-SNAPSHOT.zip](https://github.com/eclipse/smarthome/files/2705945/org.eclipse.smarthome.binding.sonos-0.11.0-SNAPSHOT.zip)
alues for the action parameter.

**Comment by lolodomo** [comment]
No feedback ?

**Comment by lolodomo** [comment]
New version with probable support of Sonos PLaybase in addition to Sonoas Beam
[org.eclipse.smarthome.binding.sonos-0.11.0-SNAPSHOT.zip](https://github.com/eclipse/smarthome/files/2716715/org.eclipse.smarthome.binding.sonos-0.11.0-SNAPSHOT.zip)

**Comment by lolodomo** [comment]
New version that should support the update of the speech enhancement and night mode features.
[org.eclipse.smarthome.binding.sonos-0.11.0-SNAPSHOT.zip](https://github.com/eclipse/smarthome/files/2718228/org.eclipse.smarthome.binding.sonos-0.11.0-SNAPSHOT.zip)

**Comment by lolodomo** [comment]
Please let me know more in details what is working well and what is not working well.
To be checked:
* auto detection of the Sonos Beam / Playbase with the correct thing type
* correct update of the new channels nightmode and speechenhancement when the mode is updated outside openHAB using the Sonos app
* correct update of the night mode and speech enhancement mode when updating the new channels in openHAB
* correct setting of the linein channel depending on whether your HDMI cable is connected or not (be careful it can be dangerous to connect/disconnect HDMI when the Sonos is powered)
* correct handling of a notification especially when you were listening the sound of the TV (sound of your HDMI input)

**Comment by pdcemulator** [comment]
Sorry, I misunterstood one of the many github notifications that you found information in forum and its done. Tested with fresh install of openHAB 2.5.0 Build #1484 on raspberry.

I have placed the yar file into addons folder. But bundle:list shows state as installed, but not as active and I cannot see the bundle in PaperUI.
openhab> bundle:list | grep Sonos
198 x Installed x  80 x 0.11.0.201812311100    x Eclipse SmartHome Sonos Binding

After installing Sonos Binding with paperUI, I have two versions installed.
openhab> bundle:list | grep Sonos
198 x Active   x  80 x 0.11.0.201812301624    x Eclipse SmartHome Sonos Binding
198 x Installed x  80 x 0.11.0.201812311100    x Eclipse SmartHome Sonos Binding

>     * auto detection of the Sonos Beam / Playbase with the correct thing type
Beam was discovered twice. One as Beam, another as Type Zoneplayer with same ID. Thing of Type Beam does not show 

Maybe I have a installation issue here. I have to use another system to test, maybe with latest 2.4 instead of 2.5 Shapshot. Please give me some days. Maybe already tomorrow.

**Comment by lolodomo** [comment]
And the jar for testing should work even in openHAB official release 2.4 because there were no breaking changes in ESH since 2.4 was released.

**Comment by pdcemulator** [comment]
Same issue with 2.4. There are unresolved dependencies and I do not know how to resolve this.

'openhab> bundle:start 20
Error executing command: Error executing command on bundles:
        Error starting bundle 20: Could not resolve module: org.eclipse.smarthome.binding.sonos [20]
  Unresolved requirement: Import-Package: org.eclipse.jdt.annotation; resolution:="optional"
  Unresolved requirement: Import-Package: org.eclipse.smarthome.config.discovery.upnp'

**Comment by lolodomo** [comment]
Just tested and it works perfectly for me !
Of course the file to put in the addons folder is the jar file, not the zip file itself. So first unzip the file in another place.
What you have to do:

1. Uninstall the Sonos binding using Paper UI and wait until uninstallation is finished
2. Unzip the file to get thje jar file
3. Put the jar file in the addons folder

**Comment by pdcemulator** [comment]
I did a fresh install on my windows pc. Latest 2.5 snapshot with your jar file.

Beam was discovered twice. One as Type Beam, another as Type Zoneplayer with same ID.
Beam Thing has no NightMode and no SpeechEnhancement channel listed in PaperUI.

**Comment by lolodomo** [comment]
Sorry but that is not possible. If you have only one Sonos binding installed, only one thing type should ne added in the box.
That means at a time, the old binding has run.
Delete your things from inbox. Check you have only one binding running and the good one. Fonally search Sonos devices.

**Comment by lolodomo** [comment]
If you added the right think type, the channels should be visible in Paper UI but take care they are advanced channels so click to show all channels.

**Comment by lolodomo** [comment]
@kaikreuzer : do you believe me if I tell you that I am very confident with this PR (even if @pdcemulator was not able to test it properly) ? ;)
If yes, please review and merge beginning of next week. The only point I am not so confident is the German translations :) so please take care about that in particular.
**This PR cannot break anything, it is just adding new features.**
When the change will be in the openHAB snapshot, this will be easier for any standard user to check.

**Comment by pdcemulator** [comment]
I have done another test with latest 2.5 snapshot

>    auto detection of the Sonos Beam / Playbase with the correct thing type

ok, discovered Beam

>    correct update of the new channels nightmode and speechenhancement when the mode is updated outside openHAB using the Sonos app

sometimes ok, maybe related to my environment? dou you need a special log output?
 
>   correct update of the night mode and speech enhancement mode when updating the new channels in openHAB

ok

>   correct setting of the linein channel depending on whether your HDMI cable is connected or not (be careful it can be dangerous to connect/disconnect HDMI when the Sonos is powered)

ok

>    correct handling of a notification especially when you were listening the sound of the TV (sound of your HDMI input)

will be tested later, I dont use notifications yet so I hafe to figure out how to use

**Comment by toxiroxi** [comment]
i would really love to that that new binding version. Any information somewhere on how to get to the new jar file ? Thanks a lot

**Pull request merged**
