### PR TITLE
Ignore Ntp tests

### PR DESCRIPTION
**Pull request by svilenvul**
See https://github.com/eclipse/smarthome/issues/3231#issuecomment-295646370

Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
@sjka WRT to #3231 do we need a workaround (ignore the tests) now because it is urgent or should we introduce a simple NTP server e.g. this one is available using the Apache License, Version 2.0: https://commons.apache.org/proper/commons-net//examples/ntp/SimpleNTPServer.java

**Comment by sjka** [comment]
No, we don't _really_ _NEED_ to. They are just annoying me in a somehow slow (wrt DNS resulution and/or realizing that there is nothing to connect to) CI server. With #3285 I would be happy enough to wait for you getting a CQ approved for the SimpleNTPServer 😉

**Comment by maggu2810** [comment]
> you getting a CQ approved for the SimpleNTPServer

... if I ever can access IPzilla again.

**Comment by sjka** [comment]
The tests are running stable with the prolonged timeouts (at least as stable they can get with their dependency to public ntp servers). And we have the open issue for tracking the effort to migrate them to using a mock. 
Therefore I suggest to abandon this PR. Luckily @svilenvul didn't have to put much effort into this!

**Pull request closed without merging**
