### PR TITLE
Added list of units and prefixes

### PR DESCRIPTION
**Pull request by vzorglub**
Added list of units and prefixes

### CODE REVIEW

**Comment by htreu** [comment]
Thanks @vzorglub for your contribution. In order for us to accept it you need to:

1. sign the Eclipse Contributor Agreement (ECA) here: https://www.eclipse.org/legal/ECA.php
1. sign off your commit with the same email address used for the ECA.

Please also read the [contribution guidelines for Eclipse SmartHome](https://www.eclipse.org/smarthome/documentation/community/contributing.html).

**Comment by hakan42** [comment]
We use markdown tables in the documentation, whereas you have direct HTML tables. Could you perhaps convert those?

**Comment by vzorglub** [comment]
I have signed the ECA and changed the html tables to markdown tables as advised.
I am sorry I had been notified of your comment
How do I sign my contributions?

**Comment by Confectrician** [comment]
Hey @vzorglub,

The `sign-off` has to be done on each commit message and not in the markdown file itself.
That means that you would have to change the commit messages for the first 2 commits and revert the last commit, since the sign-off is not correct in the markdown file.

I am not an expert in changing commit messages, so i can only point you to this article:
https://help.github.com/articles/changing-a-commit-message/

Maybe someone else has a better explanation to share.
I think i have read some really good instruction from @martinvw some time ago in a PR but i can't find them anymore.
Maybe he can help out here. 🙂

**Comment by htreu** [comment]
@vzorglub the same information about sign-off-by as in #5816 holds true here. Let me know if you need hep.

**Comment by vzorglub** [comment]
Yes I need help. I don't know what you mean at all.

**Comment by Confectrician** [comment]
Hey @vzorglub,

Lets start from scratch.
Which editor are you using, the one from the github website?
And have you worked with git before on your local system?
How much experience do you have in general with git?

It doesn't make sense to just throw some git commands in the discussion, 
if this confuses you even more maybe.

**Comment by vzorglub** [comment]
Hi Jerome,
I am using the online github editor.
I have never worked with git before on my local system.
I have zero experience with git.

How can I get to help? Please.
I have other units to add to the UoM extension.

Can you tell me how to start over.
If I have to use an editor I would use VSCode.

**Comment by Confectrician** [comment]
Ok then lets start. :)

The things we want to achieve here, are not possible with the GitHub Editor.
This is a nice tool for small edits, but if you want to contribute more often 
a local environment will be better on the long run anyways.

>If I have to use an editor I would use VSCode.

That's perfectly fine.
VSCode has built in git support.
You only have to install git on your system.
You can get it here: https://git-scm.com/download
That's already everything you have to setup for using git with vscode.

Next steps
1. Set up git for `sign-off`
2. Clone the (correct) repository
3. Check out the correct branch

### Set up git for sign-off

You could add that sign of line by hand for every commit message, but it is far easier to let git do that for you.

Open vscode with a new window and open the terminal.
For that press `ctrl` + `p` and type "view terminal" 

image

Now check if git was installed succesfully:

image

in my case the git command was recognized and i have installed version 2.16.2
(Which seems to be outdated by the way. 😄 )

Go on with setting up your name and email like this:

`git config --global user.name "Vincent Regaud"`
`git config --global user.email "vzorglub@gmail.com"` 

You can check if everything worked with the same commands just without the parameters,
like shown here:

image

Congrats. Sign-off is prepared now.
Lets start coding.

### Clone the correct repository

It is important to understand, that you have edited everything on **fork of the smarthome repository** so far.
By merging a Pull Request the smarthome theme, adds the changes from **your repo fork** to the **original smarthome repo**
When you use the github editor, github will generate a repository fork for you in background.

So if changes are always made in **your repo copy**, thats also the repo we want to use in vscode.

In this case it is: `https://github.com/vzorglub/smarthome.git`

You can find the url here:
image

So here is a pic of how to clone this repository:
clonesmarthomerepo

### Check out the wanted branch

Perfect. Now we have the repo available on the local environment.
Now you need to find the correct branch.
Branches are a concept of git.
Its like copying a current state of a folder to a new place, to not disturb others while doing changes.
(Sorry for the git pros who have to read this now. I know its a very rough explanation. 😄 )

While editing with the GitHub Editor, Github has created a fork and also added a new branch.
You can see here how its called:
image
For other pull requests this could be diffirent.
Just check the Pull Request to keep track of what changes have been made in which branch.

So the task to go on here, is to check out this specific branch in vscode.
checkoutpatchbranch


### Later more
I think this is already a long comment now.
I would say we take care about that commit rename stuff later.

Please leave some feedback if everything worked or if there were problems.
I will go on afterwards.

**Comment by vzorglub** [comment]
Brilliant!! Thank you
Got it all the way but when I click `master` it doesn't show the patch-2 branch :cry:

**Comment by Confectrician** [comment]
If you did not open it yet on your machine it coule be named `origin/patch-2`.
After opening it the first time it will be named patch-2 without the origin.

**Comment by vzorglub** [comment]
Ok done

**Comment by Confectrician** [comment]
Thanks for waiting. I am a bit busy these days.

Ok we have

- Set up git for vscode
- Cloned our repo fork/copy
- Choosen the correct branch

Now it is important to understand how git works in background.

Here is a simple picture i have created in 5 minutes for some visualization:
github_workflow

1. You make edits and improvements in vscode which will then be **only on your local machine**.
2. Everything you edit stays **local** until you decide to upload it.
3. When you think your edits/improvements are finished, you have to tell it to git.
4. This is done through a commit. (How that works in detail below)
5. If there are new commits on your **local** system you want to share, you sync them.
6. If there was already a Pull Request opened, 
GitHub recognizes this and updates the Pull Request Conversation (this page her in our case) accordingly and everyone is able to see and review the changes.
If there is no Pull Request yet, you have the ability to open one from your changed branch.

## How Commits with sign-off work

I have added a new branch for showing you this workflow.
We will do some stuff on the current branch of this pull request later,
but i didn't want to mix up stuff there. This is a bit out of our scope.

Again a gif picture which will be better than writing tons of text:
gitcommitwithsignoff

What i have done in short:

1. Created a test branch
2. Edited a file => git recognizes that here was a change bit did not work with it yet
3. Added all changed files with `git add .` => `.` adds all changed files. 
You could also type in `git add docs/documentation/units-of-measurement.md` in our case here.
4. Now the files that were added (in this case only 1) will be in the next commit we make.
5. Now i make the commit with `git commit -s -m "COMMIT MESSAGE"`. 
The `-s` adds the sign off statement automatically, due to our config we have set up. 
So you only need to write some short sentence about what was changed.
The `-m` Tells git that you want to add a message now. Dont forget the `"`.
6. After commiting i am doing a Log with `git log -n 1`. The `-n 1` limits the log only to the last commit.
We can see that the sign off was added to the commit message.

## OK but what now?!

Now we have a **local** change, which we want to upload and add it to the PR.
This would be done by pushing it to **your repo fork/copy** usually.
VSCode has a sync function which pulls (downloads from the remote to local)
and pushes (uploads local changes to the remote) automatically.

I will do the sync stuff in the next comment and also show you how you can rename your existing commit messages here and add a sign-off for them.

Again i will need some time, but i thought it would be better to show the whole concept first, befor digging into the pro stuff.
(At least for me it is already pro stuff, when it goes to changing existing commits.)

**Comment by vzorglub** [comment]
Thank you very clear explanation. 
Quick questions:

* Before typing any git command in the terminal I should be in the local repo directory, correct?
* and the `-m "MESSAGE"` is like the message we add in the online git commit?
* After a branch has been merged, I can delete it?
* How does the whole local repo keep in sync with the actual repo, automatically or do we have do something like `git sync`?

**Comment by Confectrician** [comment]
Ok now we will come to the "heavy stuff". 😄 
In my opinion this is far beyond a git beginners tutorial, but since we all want to get this pr merged, i will do the explanation.

Anyways.
I wanted to point out that this tutorial is a really quick and rough one, which was designed especially with a focus on vscode and giving you the tools the change your commits.
I am strongly encouraging you to take a dive in some of the git documentation out there.
Maybe one of the others here has a good beginners tutorial page in his bookmarks.

## To-Do

We want to change your commits in this pr, so that we have a clean history and all commits signed off.
For this we will first take a look on what you have commited so far and which commits are useful.
Afterwards we will do some git magic in vscode and you will end up with one clean commit that is signed off and we should then be nearer to a merge than before. 🙂 

## Existing commits in this PR

image

As you can see there are currently 4 commits in this pr.
The first 2 are useful. There is the initial one and the one where you changed everything to markdown tables.
The commit `added signature` is useless since the sign off was in the wrong place and the last one is more or less useless since it reverted the changes from commit 3 and is the only one with a sign-off statement included. 

## What we want to do now

We want to change the commits of this PR and remove the useless stuff.
There is a nice exiting technic for this, which is called *squashing*.
This means that we use a git tool to combine this 4 commits into one new commit.
We will then have
- all useful changes included
- all useless changes reverted/corrected
- the possibility to change the messae and add a manual sign off now

I will again use a gif and explain bellow what i did and where to pay attention to:
gitrebasewithsquash

1. This time we will use the `patch-2` branch, which is the real one of this Pull Request
2. We use `git log -n 4` to see if we are fine on our local machine.
As you can see, there are the 4 commits we want to combine
3. We then use `git rebase -i HEAD~4` to get into the *interactive rebase mode* for exact these 4 commits.
4. We will get into the rebase tool and can choose what to do for each of the commits.
(I am using vim editor in git, so the view could be different for you if you have iinstalled git different.)
5. We choose now `pick`for the first commit as a starting point,  `s` for `squash` for the second commit and `d` for `drop` for the useles ones.
(I have to press `I` in vim to get into INSERT mode and `ESC` + `:wq` to save everything.)
Don't worry about the error messages in the gif. They were from a test i made while writing this.
6. The rebase tool does its job and we are able to write the new commit message.
7. We can see now that there are 4 commits to download from your fork (the state it was before)
and one commit to upload (the one from our rebase and squash)
8. We now have to force git to upload our squashed commits with `git push  --force` after checking the git log once more

## Syncing the changes

So Git currently thinks that there is a problem, because the commit history in your `vzgorlub/smarthome` fork online at github and the vscode copy are different.
Technically thats correct, but we know that we made these history changes on purpose.
Usually i would recommend you to **not** use the force push, but in this case it is necessary.

So first we will check the commit history of your fork (**in the wanted branch**) online:
checkhistoryonline

Interesting for us is the last commit before you started editing stuff. It's 2e00585
We want to make sure that this is the last commit before our changes on the local branch too.

So we will check this and if only our 4 commits have been combined and locally 2e00585 is the commit before ours, we are good to go.
Let's go.

checklocalhistoryandforcepush

As you can see everything is alright.
Only the 4 commits we wanted to change are affected.
Now we can overwrite your GitHub fork with `git push --force`.
This doesn't work in the gif because i simply have no access to your fork.
In your case it should work and we should all be able to see the result, because this Pull Request will then be updated immediately.

**Comment by Confectrician** [comment]
Ok now to the questions:

> Before typing any git command in the terminal I should be in the local repo directory, correct?

Yes.

> and the -m "MESSAGE" is like the message we add in the online git commit?

Correct. It is the same just with a fancy formular online.

> After a branch has been merged, I can delete it?

Yes. You are good to go then.
You could keep it too, but i don't know any case where this would make sense here.

>How does the whole local repo keep in sync with the actual repo, automatically or do we have do something like git sync?

There are 2 answers, but anyways both have to be done manually always:

1. Everything is cool and there are no conflicts (mostly the usecase when you do sign off directly)
You can sync then with the vscode feature trough UI
image
It will take care of push and pull actions, which is really comfortable.

2. There are conflicts or a rebase
In this case the autimatic vscode sync will throw an error, since git doesn't want to push conflicted stuff.
So you have to do a push --force within the console.

Generally i would recommend you to get comfortable with the git console.
There are things that work better on console because git is designed for it.
All Git UI Abstractions are running console stuff in background and you have to deal with poor implementations maybe.

Personally i do the sync stuff with VSCode and commits within the console.
VSCode can't handle the `-s` parameter from the ui so it is useless for commits to openhab/smarthome which need a sign off.
I would have to type it by hand in the ui every time which is a no go for me.

But for viewing changes and files that have changed VSCode has a nice sidebar.
So i can live very well with having to commit in the console.
The rest is displayed nice and structured.

**Comment by Confectrician** [comment]
Maybe i can adda a git for beginners thread in openhab community. 
I have put some effort in the tutorial now and the gifs are created anyway.

Something for my todo list after master-degree. 😄

**Comment by vzorglub** [comment]
Sorry but:
```
home@home:~/Programs/smarthome-gitrepo/smarthome$ git rebase -i HEAD~4
Cannot rebase: You have unstaged changes.
Please commit or stash them.
```

**Comment by Confectrician** [comment]
image
is your friend.

Show me your source control area or better a complete screenshot with source control area opened. :)

image

**Comment by vzorglub** [comment]
## List of Units

List of the unit available with the UoM (Unit of Measurement) types


### Imperial:


| Type | Unit | Symbol |
| ---- | ---- | ------ |
|Pressure|Inch of Mercury|inHg|
|Temperature|Fahrenheit|°F|
|Speed|Miles per Hour|mph
|Length|Inch|in
|Length|Foot|ft
|Length|Yard|yd
|Length|Chain|ch
|Length|Furlong|fur
|Length|Mile|mi
|Length|League|lea


### SI:

|Type|Unit|Symbol|
|----|----|------|
|Acceleration|Metre per square Second|m/s2
|AmountOfSubstance|Mole|mol
|Angle|Radian|rad
|Angle|Degree|°
|Angle|Minute Angle|'
|Angle|Second Angle|''
|Area|Square Metre|m2
|ArealDensity|Dobson Unit|DU
|CatalyticActivity|Katal|kat
|Dimensionless|Percent|%
|Dimensionless|Parts per Million|ppm
|Dimensionless|Decibel|dB
|ElectricalPotential|Volt|V
|ElectricCapacitance|Farad|F
|ElectricCharge|Coulomb|C
|ElectricConductance|Siemens|S
|ElectricCurrent|Ampere|A
|ElectricInductance|Henry|H
|ElectricResistance|Ohm|Ω
|Energy|Joule|J
|Energy|Watt Second|Ws
|Energy|Watt Hour|Wh
|Energy|KiloWatt Hour|kWh
|Force|Newton|N
|Frequency|Hertz|Hz
|Illuminance|Lux|lx
|Intensity|Irradiance|W/m²
|Length|Metre|m
|Length|Kilometre|km
|LuminousFlux|Lumen|lm
|LuminousIntensity|Candela|cd
|Temperature|Kelvin|K
|Temperature|Celcius|°C
|MagneticFlux|Weber|Wb
|MagneticFluxDensity|Tesla|T
|Mass|Kilogram|kg
|Mass|Gram|g
|Power|Watt|W
|Pressure|Pascal|Pa
|Pressure|hectoPascal|hPa
|Pressure|Millimetre of Mercury|mmHg
|Radioactivity|Becquerel|Bq
|RadiationDoseAbsorbed|Gray|Gy
|RadiationDoseEffective|Sievert|Sv
|SolidAngle|Steradian|sr
|Speed|Metre per Second|m/s
|Speed|Kilometre per Hour|km/h
|Speed|Knot|kn
|Time|Second|s
|Time|Minute|min
|Time|Hour|h
|Time|Day|d
|Time|Week|week
|Time|Year|y
|Volume|Cubic Metre|m3

## Prefixes:

|Name|Symbol|Value|
|----|------|-----|
|Yotta|Y|10²⁴|
|Zetta|Z|10²¹|
|Exa|E|10¹⁸|
|Peta|P|10¹⁵|
|Tera|T|10¹²|
|Giga|G|10⁹|
|Mega|M|10⁶|
|Kilo|k|10³|
|Hecto|h|10²|
|Deca|da|10|
|Deci|d|10⁻¹|
|Centi|c|10⁻²|
|Milli|m|10⁻³|
|Micro|µ|10⁻⁶|
|Nano|n|10⁻⁹|
|Pico|p|10⁻¹²|
|Femto|f|10⁻¹⁵|
|Atto|a|10⁻¹⁸|
|Zepto|z|10⁻²¹|
|Yocto|y|10⁻²⁴|


To use the prefixes simply add the prefix to the unit symbol (Above).
Examples:
-milliAmpere - mA
-centiMetre - cm
kiloWatt - kW

**Comment by vzorglub** [comment]
I did it by command line
Started over with fresh repo

**Pull request closed without merging**
