### PR TITLE
Changed Item console command extensions to use DS service injection inst...

### PR DESCRIPTION
**Pull request by dnobel**
...ead of ServiceTracker.

Added Eclipse Console Command support bundle to runtime.target.

Signed-off-by: Dennis Nobel <d.nobel@external.telekom.de>

### CODE REVIEW

**Comment by dnobel** [comment]
@kaikreuzer The generic ServiceTracker did not work with older OSGi version (QIVICON).

**Comment by dnobel** [comment]
@maggu2810 Any concerns from your side regarding the usage of OSGi DS dependency injection?

**Comment by maggu2810** [comment]
No concerns from my side. The ServiceTracker was used before, so I kept that untouched. DS dependencies should be fine.

**Comment by kaikreuzer** [comment]
Yes, this change definitely makes sense. It wasn't possibly to do it this way before @maggu2810's refactoring.

**Pull request merged**
