### PR TITLE
Paper UI: apply the formatter to all js and html files

### PR DESCRIPTION
**Pull request by maggu2810**
The about.html has not been reformatted, as it is no part of the web
stuff.

Related to: https://github.com/eclipse/smarthome/pull/1161
Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
This doesn't look like the right formatter to me... It rather screws up the formatting of the files.
Note that I had applied formatting already on HTML files in https://github.com/eclipse/smarthome/pull/1160.

**Comment by maggu2810** [comment]
Have a look at:
https://github.com/eclipse/smarthome/pull/1180/files#diff-e9c74d23a3e318883f8e18e9ea2ed976L11

and the formatter changes here:
https://github.com/eclipse/smarthome/pull/1084/files#diff-6f1df7389de3bf45d12d92b2750cefa2R723
https://github.com/eclipse/smarthome/pull/1084/files#diff-6f1df7389de3bf45d12d92b2750cefa2R727

So we have:
inline element=...,i,...
lineWidth=999

I think that this changes here are correct:
```diff
-			<md-button ng-show="discoveryResult.flag === 'IGNORED'" ng-click="unignore(discoveryResult.thingUID)" aria-label="Unignore">
-			<i class="material-icons">visibility</i></md-button>
...
+			<md-button ng-show="discoveryResult.flag === 'IGNORED'" ng-click="unignore(discoveryResult.thingUID)" aria-label="Unignore"> <i class="material-icons">visibility</i></md-button>
```

As long as the setups.zip contains the old setup file, every IDE restart will reset the HTML formatter rules to the old ones.
So are you really sure, you have used the correct ones?
I am using a local setup file ATM that is equal to the current master one (and not equal to the december one).
If my format is doing now wrong stuff, I assume the formatter (as in the setup file) needs to be changed again.

**Comment by kaikreuzer** [comment]
I noticed the difference about the <i> element, so this might indeed be an error in the formatting that I commited.
But your PR also removes indentation on many lines, that looks pretty weird...?

**Comment by maggu2810** [comment]
> removes indentation on many lines

Many? The ones the indentation has been removed are the stuff inside the head tags of the index.html (see: https://github.com/eclipse/smarthome/pull/1161#issuecomment-195950040).
I do not see any other removed indentation except this ones.
The most notable changes are removed new lines.

So, what should we do now?
This PR applies the currently defined formatter to the Paper UI sources.
I do not know why the formatter does not indent childs of head and html (I found only this one ATM: https://bugs.eclipse.org/bugs/show_bug.cgi?id=122051).
I could remove the index.html from this PR but as soon as one character is changed in the index.html (and the setup points to the recent one) the current formatter will be applied and change it to the same I have done here.

**Comment by maggu2810** [comment]
https://www.eclipse.org/forums/index.php?t=msg&th=161636&goto=647071&#msg_647071

**Comment by kaikreuzer** [comment]
Ok, you are right, I actually missed the index.html and my formatter also removes the indentation there.

**Comment by maggu2810** [comment]
The formatter is really annoying:

If you write

```
<md-button><i>foo</i></md-button>
```

and apply the formatter once, it is replaced by

```
<md-button>
<i>foo</i></md-button>
```

after running the formatter again, it is replaced by

```
<md-button> <i>foo</i></md-button>
```

after running the formatter again, it stays equal.

**Pull request merged**
