### PR TITLE
WU: switch to the new system channels

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@cweitkamp : can you please help me. My translation of the forecast relative humidity does not work. As you explained, I overwrote the system channel description. It is working (English) except the translation in French.

**Comment by triller-telekom** [comment]
@lolodomo Have you seen the travis failure?

```
Results :

Failed tests: 
  SystemWideChannelTypesTest.systemChannelTypesShouldBeTranslatedProperly:227 expected null, but was:<Aktuelle Windrichtung ausgedrÃ¼ckt als Winkel.>

Tests run: 327, Failures: 1, Errors: 0, Skipped: 0
```

Can you please have a look?

**Comment by lolodomo** [comment]
I will have a look but I will fix it in my PR 6039.

**Comment by lolodomo** [comment]
@triller-telekom : I introduced the problem with tests in my PR #6035. Tests are now fixes in my PR #6039. So please consider a quick merge of #6039.
And please bypass this error in the current PR.

**Comment by lolodomo** [comment]
If really necessary, I can merge with the master branch to avoid the failing build. Let me know.

**Comment by triller-telekom** [comment]
I would like to see that the tests run fine. So can you please **rebase** and not merge onto the master? Thank you very much!

**Pull request merged**
