### PR TITLE
Ignore single hidden files as well

### PR DESCRIPTION
**Pull request by kaikreuzer**
related to #2854

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
The `AutomationWatchService` still uses `!path.getFileName().startsWith(".")`.
Shouldn't this be changed to use `isHidden()` method, too?
What is about e.g. a new directory entry for a hidden directory that contains non-hidden files?
If we ignore hidden files, I would expect we ignore a hidden directory, too.
WDYT?

**Comment by adimova** [comment]
I agree that isHidden() should be used instead of .startsWith(".")
If new directory entry for a hidden directory that contains non-hidden files - IMHO the directory and all files in it should be ignored

To achieve these, the fix should be changed:

public void importResources(File file) {
        if (file.exists() && !file.isHidden()) {
            File[] files = file.listFiles();
            if (files != null) {
                for (File f : files) {
                    importResources(f);
                }
            } else {
                try {
                    URL url = file.toURI().toURL();
                    String parserType = getParserType(url);
                    importFile(parserType, url);
                } catch (MalformedURLException e) {
                    // can't happen for the 'file' protocol handler with a correctly formatted URI
                    logger.debug("Can't create a URL", e);
                }
            }
        }
    }

Also, the .startsWith(".") check should be removed from org.eclipse.smarthome.automation.internal.provider.file.AutomationWatchService.WatchQueueReader.processWatchEvent

**Comment by adimova** [comment]
May I propose to fix this issue as part of the fix for #3129? This way we'll avoid the merging and conflict solving.

**Comment by kaikreuzer** [comment]
> May I propose to fix this issue as part of the fix for #3129?

Of course.

**Pull request closed without merging**
