### PR TITLE
reverted self-imported packages for model and ui bundles

### PR DESCRIPTION
**Pull request by BenediktNiehues**
Signed-off-by: Benedikt Niehues <b.niehues@external.telekom.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
Do we need to change the non-model bundles?
* org.eclipse.smarthome.ui
* org.eclipse.smarthome.ui.classic

**Comment by kaikreuzer** [comment]
> Do we need to change the non-model bundles?

I do not think so, since they don't have any issue with shared packages etc.

**Comment by maggu2810** [comment]
Oh, why you have merged it as long it changes ui and ui.classic?

**Comment by kaikreuzer** [comment]
Sorry - because I didn't see that they were also changes. I understood your question as if the PR should be extended to also cover these bundles.

**Pull request merged**
