### PR TITLE
[OWM] Store / cache icon files in a local folder and minor code improvements

### PR DESCRIPTION
**Pull request by cweitkamp**
- Store / cache image files in a local folder
- Reduced discovery timeout
- Minor code improvements

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hm, I assume the sunrise/sunset information is no "sensor" weather data at all, but purely calculated by OWM, right? If so, it completely duplicates the functionality of the Astro binding, which already provides all this (and much more). I would thus suggest to not duplicate such a feature here (especially with the all the configuration like offset/earliest/latest, which clearly targets shutter automation).
Or is there anything special about OWM why the values provided are better than the ones calculated by the Astro binding?

**Comment by cweitkamp** [comment]
> Or is there anything special about OWM why the values provided are better than the ones calculated by the Astro binding?

No, I do not think so. The OWM documentation does not tell anything about that. I assume the values are calculated. It is true that I copied a lot of functionality from the Astro binding. Adding the event handling here provides no general advantages. I am personally interested only in the sunrise/sunset triggers of the Astro binding thus - for my own sake - I can avoid using the Astro binding and would not loose any of the features.

**Comment by kaikreuzer** [comment]
> for my own sake - I can avoid using the Astro binding

That's a very weak argument for duplicating a lot of code - I'd definitely vote for removing it from this binding.

**Comment by cweitkamp** [comment]
Yes, I agree. I will remove it.

**Comment by cweitkamp** [comment]
I removed the event handling.

**Comment by kaikreuzer** [comment]
Hm, I was actually talking about the "the sunrise/sunset information", i.e. the channels themselves - there shouldn't be any good reason to use them instead of the Astro binding...

**Pull request merged**
