### PR TITLE
Paper UI: clean node_modules & npm cache during mvn clean

### PR DESCRIPTION
**Pull request by htreu**
Also: reformat o.e.s.ui.paper/pom.xml

Signed-off-by: Henning Treu <henning.treu@telekom.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
AFAIK we are using the "two space indentation" for all "pom.xml" files.
Why has this been changed for the Paper UI one now?

**Comment by htreu** [comment]
uh, sorry. I just ran the auto formatter and it looked okay. I will reformat in a separate PR.

**Comment by maggu2810** [comment]
No prob, let's run the maven plugin to fix all POMs. I will create a PR later.

**Comment by htreu** [comment]
alright then, thanks @maggu2810.

**Pull request merged**
