### PR TITLE
Add Classic Iconset

### PR DESCRIPTION
**Pull request by reitermarkus**

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Very cool! Could you please squash your commits into one? I will then create a CQ (i.e. have the Eclipse IP team approve the contribution).

**Comment by kaikreuzer** [comment]
Thanks! I have created CQ 10981 for it, waiting now for its approval.

**Comment by kaikreuzer** [comment]
FTR, in order to get PMC approval, I removed the scripts _iconconvert and _iconminify from the CQ.
So before merging, we need to remove these as well from the PR.

**Comment by reitermarkus** [comment]
Ok, I removed the two scripts and also added the changes from https://github.com/kaikreuzer/openhab-core/pull/27.

**Comment by kaikreuzer** [comment]
> Ok, I removed the two scripts 

Thanks.

> also added the changes from kaikreuzer/openhab-core#27.

Please revert this (or rather put it in a separate commit) - we must not change the content of a commit that is submitted as a CQ (only the script removal was required since that was requested before CQ was accepted for further processing).

**Comment by reitermarkus** [comment]
Ok, added them as a separate commit.

**Comment by kaikreuzer** [comment]
Perfect, thanks :+1:

**Comment by kaikreuzer** [comment]
CQ has been approved just now!

**Pull request merged**
