### PR TITLE
updated jue library in order to get the unique ids of lights

### PR DESCRIPTION
**Pull request by tomhoefer**
Signed-off-by: Thomas Höfer <t.hoefer@telekom.de>

### CODE REVIEW

**Comment by tomhoefer** [comment]
The jue libarary has been modified according to the last two commits of this branch https://github.com/qivicon/Jue/commits/get-new-lights-with-serial-number
Commit 1: changed range check for saturation and brightness
Commit 2: added unique id

**Comment by tomhoefer** [comment]
Squashed the commit for Jue Library https://github.com/qivicon/Jue/commits/get-new-lights-with-serial-number accordingly (without automatic code formatting):
Added unique id and changed range check for brightness and saturation [Commit a9549a7]

Added also new Jue Library extended by that single commit

**Comment by kaikreuzer** [comment]
Thanks, review is done and a CQ is submitted for approval for the update of the jue lib. Will merge once I receive the approval

**Comment by kaikreuzer** [comment]
CQ has been approved!

**Pull request merged**
