### PR TITLE
removed Yahoo Weather binding

### LINKED ISSUE #6491: [yahooweather] Yahoo had officially ended their free api
See https://community.openhab.org/t/yahoo-weather-binding-free-weather-api-services-canceled/56172 and https://developer.yahoo.com/weather/?guccounter=2.

The API is no longer free and the ending used by the binding had been closed down. The Yahoo Weather binding needs to be removed

### PR DESCRIPTION
**Pull request by kaikreuzer**
resolves #6491

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
> According to the [latest comments](https://community.openhab.org/t/yahoo-weather-binding-free-weather-api-services-canceled/56172/10?u=kai), this is not correct - the service is still working and we do not know a date when it will be closed down.

I am a little bit irritated.
Should it be removed now or not?
If it is still usable then we should perhaps wait until it is not available anymore.

WDYT?

**Comment by kaikreuzer** [comment]
I created the PR before I was told that it is still working.
So yeah, I am not sure about the best moment to merge either. Would be good to get some clearer information about the plans from Yahoo. If the retirement is by the end of this year, I think we should not roll it out with the 0.10.0 release anymore.

**Comment by kaikreuzer** [comment]
FTR: I e-mailed to yahoo-weather-ydn-api@oath.com last Friday and asked for the EOL date - I didn't yet get a response, though.

**Comment by kaikreuzer** [comment]
I'll close this PR again until there's a decision that we want to remove this binding.

**Comment by 9037568** [comment]
@kaikreuzer shouldn't we reopen and merge this now that the API has terminated?

**Pull request merged**
