### PR TITLE
Prevents the automation objects to become null during the provider's …

### PR DESCRIPTION
**Pull request by adimova**
…update

Signed-off-by: Ana Dimova <a.dimova@prosyst.bg> #1681
This fix is tested without the #1723 PR and prevents the NPE

### CODE REVIEW

**Comment by adimova** [comment]
#1681
This fix is tested without the #1723 PR and prevents the NPE

**Comment by marinmitev** [comment]
@kaikreuzer can we merge this PR?

**Comment by kaikreuzer** [comment]
I do not see a lgtm from anyone yet, so I would tend to say no. Did you review and test it?

**Comment by danchom** [comment]
I've tested and it works. LGTM

**Pull request merged**
