### PR TITLE
Corrected documentation for channelLinked method

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by puzzle-star** [comment]
Hi @kaikreuzer,

One question: as I understand the API doc, it says the method is only called if the thing is initialized, but it does not say anything (either positive or negative) on it being called, once initialized, for all channels that were already linked before the thing was initialized.

@cdjackson, does i.e. the ZigBee binding expect channelLinked to be called for channels that are already linked (so I understand already existing) before a thing is initialized? I recall something about polling only channels after being passed to channelLinked

**Comment by cdjackson** [comment]
> @cdjackson <https://github.com/cdjackson>, does i.e. the ZigBee binding expect channelLinked to be called for channels that are already linked (so I understand already existing) before a thing is initialized? I recall something about polling only channels after being passed to channelLinked
> 
Yes, the ZigBee binding only polls channels that are linked, but it is not required to call the channelLinked before the thing is initialised.

**Comment by puzzle-star** [comment]
Thanks @cdjackson, the question is whether the binding expects channelLinked to be called after the thing is initialized even if the channel was linked before

**Comment by cdjackson** [comment]
It doesn’t matter what order it is called, or if it is called multiple times.  Does that answer your concern or am I missing something? From the documentation change in this PR, I don’t see any issue, but I guess you think there is a problem?

**Comment by puzzle-star** [comment]
Hi @cdjackson, it came from a discussion from the M7 testing. No real issue probably, but needed to understand whether bindings expected channelLinked to be called for existing channels after thing initialization (as the doc said) even for channels that were linked before the thing being intialized.

@kaikreuzer, looking at the [code](https://github.com/eclipse/smarthome/blob/04cf8db5041774cc8c62819ef185c9e233701e7e/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/link/ThingLinkManager.java#L334) I would say the doc was OK and this is the expected behaviour, or maybe am I missing something?

```
@Override
    protected void receiveTypedEvent(ThingStatusInfoChangedEvent event) {
        // when a thing handler is successfully initialized (i.e. it goes from INITIALIZING to UNKNOWN, ONLINE or
        // OFFLINE), we need to make sure that channelLinked() is called for all existing links
        if (ThingStatus.INITIALIZING.equals(event.getOldStatusInfo().getStatus())) {
            if (ThingHandlerHelper.isHandlerInitialized(event.getStatusInfo().getStatus())) {
                Thing thing = thingRegistry.get(event.getThingUID());
                if (thing != null) {
                    for (Channel channel : thing.getChannels()) {
                        if (itemChannelLinkRegistry.getLinkedItemNames(channel.getUID()).size() > 0) {
                            informHandlerAboutLinkedChannel(thing, channel);
                        }
                    }
                }
            }
        }
    }
```

**Comment by puzzle-star** [comment]
Hi @kaikreuzer, as it happens the doc was OK, at least as it seems from the code, should the change in the doc be somehow undone?

The origin of the question comes from https://community.openhab.org/t/oh-2-4-0-m7-testing-results/58475/84 and it was related so some issue in a binding in M7 discussion.

The given answer was that bindings should not expect the method to be called if the channel was linked before initialization, and I remarked that according to the doc, it seemed they should.

So for the PR the assumption was that the doc was wrong, but it was not.

**Pull request merged**
