### PR TITLE
updated IDE setup instructions to using the Eclipse Installer

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer kai@openhab.org

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@maggu2810 May I ask you to also check if this setup process works for you?

**Comment by maggu2810** [comment]
Sure, will test it.

**Comment by maggu2810** [comment]
Have to switch to advanced mode to select Projects, too.

**Comment by maggu2810** [comment]
Looks fine.

Using this setup and the launch configuration I got some entries in the OSGi log.
Could you have a look at, if this is okay, or if something is missing.

<pre>!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:08.818
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.persistence.manager. The reference is: Reference[name = ModelRepository, interface = org.eclipse.smarthome.model.core.ModelRepository, policy = dynamic, cardinality = 0..1, target = null, bind = setModelRepository, unbind = unsetModelRepository]

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:08.819
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.persistence.manager. The reference is: Reference[name = PersistenceService, interface = org.eclipse.smarthome.core.persistence.PersistenceService, policy = dynamic, cardinality = 0..n, target = null, bind = addPersistenceService, unbind = removePersistenceService]

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:08.820
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.persistence.manager. The reference is: Reference[name = ItemRegistry, interface = org.eclipse.smarthome.core.items.ItemRegistry, policy = dynamic, cardinality = 0..1, target = null, bind = setItemRegistry, unbind = unsetItemRegistry]

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:08.824
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.model.persistence.extensions. The reference is: Reference[name = PersistenceService, interface = org.eclipse.smarthome.core.persistence.PersistenceService, policy = dynamic, cardinality = 0..n, target = null, bind = addPersistenceService, unbind = removePersistenceService]
 
!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:11.278
!MESSAGE Could not bind a reference of component ConfigDescriptionRegistry. The reference is: Reference[name = ConfigDescriptionProvider, interface = org.eclipse.smarthome.config.core.ConfigDescriptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigDescriptionProvider, unbind = removeConfigDescriptionProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:11.587
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.itemregistry. The reference is: Reference[name = ItemProvider, interface = org.eclipse.smarthome.core.items.ItemProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:11.605
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.itemregistry. The reference is: Reference[name = StateDescriptionProvider, interface = org.eclipse.smarthome.core.types.StateDescriptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addStateDescriptionProvider, unbind = removeStateDescriptionProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:11.613
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.binding.BindingInfoRegistry. The reference is: Reference[name = BindingInfoProvider, interface = org.eclipse.smarthome.core.binding.BindingInfoProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addBindingInfoProvider, unbind = removeBindingInfoProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:11.736
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.ThingRegistry. The reference is: Reference[name = ThingProvider, interface = org.eclipse.smarthome.core.thing.ThingProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:11.738
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.link.ItemChannelLinkRegistry. The reference is: Reference[name = ItemChannelLinkProvider, interface = org.eclipse.smarthome.core.thing.link.ItemChannelLinkProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:11.740
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.link.ItemThingLinkRegistry. The reference is: Reference[name = ItemThingLinkProvider, interface = org.eclipse.smarthome.core.thing.link.ItemThingLinkProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addProvider, unbind = removeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:11.744
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.core.thing.type.ThingTypeRegistry. The reference is: Reference[name = ThingTypeProvider, interface = org.eclipse.smarthome.core.thing.binding.ThingTypeProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addThingTypeProvider, unbind = removeThingTypeProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:11.885
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.io.rest.root. The reference is: Reference[name = RESTResource, interface = org.eclipse.smarthome.io.rest.RESTResource, policy = dynamic, cardinality = 0..n, target = null, bind = addRESTResource, unbind = removeRESTResource]

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:12.255
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.ui. The reference is: Reference[name = ItemUIProvider, interface = org.eclipse.smarthome.ui.items.ItemUIProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addItemUIProvider, unbind = removeItemUIProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:12.256
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.ui. The reference is: Reference[name = IconProvider, interface = org.eclipse.smarthome.ui.icon.IconProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addIconProvider, unbind = removeIconProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:12.256
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.io.rest.sitemap. The reference is: Reference[name = SitemapProvider, interface = org.eclipse.smarthome.model.sitemap.SitemapProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addSitemapProvider, unbind = removeSitemapProvider]

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:12.269
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.ui.chart. The reference is: Reference[name = ChartProvider, interface = org.eclipse.smarthome.ui.chart.ChartProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addChartProvider, unbind = removeChartProvider]
21:54:12.269 DEBUG o.e.s.u.i.chart.ChartServlet[:122] - Starting up chart servlet at /chart

!ENTRY org.eclipse.equinox.ds 1 0 2015-06-22 21:54:12.275
!MESSAGE Could not bind a reference of component org.eclipse.smarthome.ui.chart.defaultprovider. The reference is: Reference[name = PersistenceService, interface = org.eclipse.smarthome.core.persistence.PersistenceService, policy = dynamic, cardinality = 0..n, target = null, bind = addPersistenceService, unbind = removePersistenceService]</pre>

**Comment by kaikreuzer** [comment]
> Have to switch to advanced mode to select Projects, too.

Good catch, thanks! Once you have switched in advanced mode, it always stays there, that's why I didn't notice it.

**Comment by kaikreuzer** [comment]
> Could you have a look at, if this is okay, or if something is missing.

Yes, they are normal and can be ignored.

**Comment by kaikreuzer** [comment]
I've added a first step regarding switching to advanced mode.

**Pull request merged**
