### PR TITLE
added homematic binding to features

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
I retriggered the build

**Comment by kaikreuzer** [comment]
Me too, twice. But it seems we have some serious issues with the build infrastructure right now as https://ci.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/ is failing as well.

Not sure whether this is temporary due to load from Photon downloads or something we need to take action.

**Comment by maggu2810** [comment]
I assume we already comment about but I don't know what has been the latest conclusion:
Should we perhaps take the time (some time) and create our own p2 repository that contains all the stuff we need for a successful build (and is used in the ESH TP)?
We would be perhaps a little bit more relaxed if one our the used p2 repos is not available.
So, something similar we already have done for our 3rd party p2 repo.

**Comment by kaikreuzer** [comment]
I actually think that as an Eclipse project we should not copy and host releases of other Eclipse projects ourselves, but use them from the official Eclipse servers as we do.

Having failures like the current "Unknown host download.eclipse.org" is really nothing we should take precautions for - after all, our own deployments could break, if such fatal problems in the build/server infrastructure exist.

**Comment by kaikreuzer** [comment]
This issue is due to some outdated DNS entries at Eclipse, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=536435.

It sounds as if we only need to wait for the new records to be propagated.

**Comment by kaikreuzer** [comment]
Green again :-)

**Pull request merged**
