### PR TITLE
Implemented tests for org.eclipse.smarthome.binding.fsinternetradio

### PR DESCRIPTION
**Pull request by m-memova**
There are two test classes - one for the discovery and another for the handler. A mock HttpServlet is used.
I have run them on MacOs and Windows and everything seems fine to me.

Signed-off-by: Mihaela Memova <mihaela.memova@musala.com>

### CODE REVIEW

**Comment by m-memova** [comment]
OK, sorry about that. I found my mistake and I fixed it. I updated the PR but now it is failing for some other reason. I will try to figure it out.

**Comment by m-memova** [comment]
Done ;-)

**Comment by m-memova** [comment]
Thank you, @kaikreuzer !

**Comment by kaikreuzer** [comment]
CQ has been approved for check-in.

**Pull request merged**
