### PR TITLE
moved basic ui to extensions folder

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
LGTM, but there are conflicts.

**Comment by dnobel** [comment]
Merged manually

**Comment by maggu2810** [comment]
If the paper ui and the basic ui are extension, should we move the classic ui, too?

**Comment by kaikreuzer** [comment]
yes, absolutely. Just didn't yet find the time - if you want to do it, feel free :-)

**Comment by maggu2810** [comment]
PR created: #542

**Pull request merged**
