### PR TITLE
Update node and npm

### PR DESCRIPTION
**Pull request by GradyD**
This updates node and NPM to the latest version in the LTS release cycle. 

Signed-off-by: Grady Duncan <gradyduncan@gmail.com>

### CODE REVIEW

**Comment by hoegertn** [comment]
I tested the changes in #828 and it seems to work. 
Is there a special reason why you used npm2 instead of npm3?

**Comment by GradyD** [comment]
No specific reason expect it is the version that is bundled with node 4.x LTS, https://nodejs.org/en/download/releases/

We can easily move up to version 5.x but we will lose the LTS benefits. I'm not sure which version is preferred and personally I don't have a preference. My reasoning to choose LTS was because this project has a decent size user population and I felt it was safer to run the LTS version instead of managing the normally update path. This article is what I based my LTS decision off of, https://nodejs.org/en/blog/community/node-v5/

**Comment by hoegertn** [comment]
I think it doe snot matter which version we use. It worked with the old version and your new version and on another project I run the same stack on the latest node and npm versions. We can use node LTS but I think using npm 3 will be good to be future proof as there are breaking changes between npm2 and npm3.

**Comment by GradyD** [comment]
Sounds good to me. I update both node and npm to the latest version.

**Comment by hoegertn** [comment]
The latest version of npm is 3.5.3

**Comment by GradyD** [comment]
Do you think we should update to that or leave the version that comes bundled with the latest release of node?

**Comment by hoegertn** [comment]
I think it does not matter for our use case. ON my machine I always update everything to the latest version to get all possible bug fixes, but we can stick to the bundled version so be safe

**Comment by maggu2810** [comment]
@kaikreuzer Does this PR need some IP requests or could it be merged?

**Comment by kaikreuzer** [comment]
I think we actually need to declare all used tools at build time as a "build-only dependency".
Could you guys compile me a list of Maven plugins that we use (or plan to use) for the Paper UI?
Or does the frontend-maven-plugin cover already all we need?

**Comment by GradyD** [comment]
The only Maven plugin is the frontend-maven-plugin. Would you like a list of the nodeJS plugins/dependencies?

The short of what happens is Maven runs the frontend-maven-plugin which installs nodeJS and NPM. From there everything is ran inside of nodeJS and once complete returns back to running the Maven scripts.

**Comment by kaikreuzer** [comment]
I will request the approval for the Maven plugin only - let's see if this is enough. Thanks!

**Comment by kaikreuzer** [comment]
Requested it here: https://dev.eclipse.org/mhonarc/lists/iot-pmc/msg00924.html
Let's wait for the PMC response.

**Comment by GradyD** [comment]
Sounds good. 

On a side note, frontend-maven-plugin is already included in the repo. I just updated the version so we can use the latest version of node and npm, not sure if this makes a difference.

**Comment by kaikreuzer** [comment]
Well, you are right that it is already too late and the CQ should have done earlier already. So I agree, this PR does not make a difference to the situation as it only updates the version.
Just note that for the unlikely event that we do not get an approval, we would have to remove this plugin from our build again.

**Pull request merged**
