### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Rosi2143**
just correct a small typo

### CODE REVIEW

**Comment by maggu2810** [comment]
@kaikreuzer IIRC for such small typo fixes on non source files, we can accept changes without a `Signed-off-by` footer and perhaps also without an ECA. Is this correct?

@Rosi2143 Otherwise you have to add that stuff...

**Comment by kaikreuzer** [comment]
@maggu2810 Yes, but you have to add your own sign-off and mention @Rosi2143 as an also-by (without requiring an ECA). See https://www.eclipse.org/lists/iot-pmc/msg04795.html for reference.

**Comment by maggu2810** [comment]
@Rosi2143 Is your full name "Micha Schrott" (or perhaps "Michael")?

```text
Also-by: Micha Schrott <Micha Schrott.Micha@web.de>
Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>
```

**Comment by kaikreuzer** [comment]
Replaced by https://github.com/eclipse/smarthome/pull/6851.

**Pull request closed without merging**
