### PR TITLE
add unit mbar

### LINKED ISSUE #6411: [UoM] unit bar not working with prefix
```
@Test 
public void UnithPaTest() {
    QuantityType<Pressure> hPa = new QuantityType<>(20, MetricPrefix.HECTO(SIUnits.PASCAL));
    assertEquals("20 hPa", hPa.toString());

    QuantityType<Pressure> hPa2 = new QuantityType<>(hPa.toString());
    assertEquals(hPa, hPa2);
}
```

This works as expected.

```
@Test
public void UnitmbarTest() {
    QuantityType<Pressure> mbar = new QuantityType<>(20, MetricPrefix.MILLI(SmartHomeUnits.BAR));
    assertEquals("20 mbar", mbar.toString());
  
    QuantityType<Pressure> mbar2 = new QuantityType<>(mbar.toString());
    assertEquals(mbar, mbar2);
}
```

This fails with

```
java.lang.IllegalArgumentException: mbar not recognized (in 20 mbar at index 3)
	at org.eclipse.smarthome.binding.onewire.internal.UtilTest.UnitmbarTest(UtilTest.java:73)
```

### PR DESCRIPTION
**Pull request by J-N-K**
fixes #6411 

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by htreu** [comment]
mh, `DynamicThingUpdateOSGITest` succeeds locally on my machine. I restarted Travis for a 2nd round.

**Comment by J-N-K** [comment]
Shall I remove the test from QuantityTypeTest then?

**Comment by htreu** [comment]
I would rather leave it there as it tests the parsing of `mbar`. The SmartHomeUnitsTest was intended to test the conversion between related units to state the correctness of the conversion math.

**Comment by J-N-K** [comment]
retriggering build

**Pull request merged**
