### PR TITLE
Timer enhancements / Rules API changes to java.time.ZonedDateTime

### PR DESCRIPTION
**Pull request by evansj**
This is a follow-up to #6492. I've added a compatibility class which gets loaded into the rules engine so that most Joda-time syntax will still work. e.g. `ZonedDateTime#plusMillis(int)`.

Currently just seeking feedback on this approach!

Cheers

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hey @evansj, sorry for not having replied earlier! I very much like the approach and think we should go for it!
As https://github.com/eclipse/smarthome/pull/6646 has just been merged, you might maybe directly want to do some adaptions to remove the Quartz dependencies (as we had already discussed in https://github.com/eclipse/smarthome/pull/6492). Wdyt?

**Comment by kaikreuzer** [comment]
Hi @evansj! As we didn't manage to merge this in time, I hope you are still interested to work on this - getting rid off joda-time is definitely still highly desired!

It would be great if you could port this work over to https://github.com/openhab/openhab-core, where this code is now maintained for openHAB (while ESH is being discontinued). Thanks!

**Comment by evansj** [comment]
@blueK68 this code was not merged yet. You can tell that your running version is still using joda time rather than java time from the error message.

I think there is a bug in your rule.

```
delay1 = R_Delay.state as Number
```

the type of delay1 will be Number. the `plusMinutes()` method needs an `int`. Try something like this:

```
var delay1 = 0
var az = now

rule "Test"
when ...
then
    delay1 = (R_Delay.state as DecimalType).intValue
    az = new DateTime((Sunrise_Time.state as DateTimeType).zonedDateTime.toInstant.toEpochMilli).plusMinutes(delay1)
end
```
 or even

```
var az = now

rule "Test"
when ...
then
    val delay1 = (R_Delay.state as DecimalType).intValue
    az = new DateTime((Sunrise_Time.state as DateTimeType).zonedDateTime.toInstant.toEpochMilli).plusMinutes(delay1)
end
```

...if you're not changing the value of `delay1` after you set it, or using `delay1` in any other rules (same for `az`).

P.S. You would get better / faster answers on [the forum](https://community.openhab.org/).

**Comment by blueK68** [comment]
Jon,
thank you, that's it, and sorry for choosing this way to get the  
information. But for me it seems sure the timer enhancements were merged  
already, though I didn't found where and though I saw the joda.time part  
in error message.

And yes I use the var delay1 in other rules.

Again, thank you for your reply and your work in the project and keep  
healthy

@blueK68


Am 22.02.2019, 11:41 Uhr, schrieb Jon Evans <notifications@github.com>:

> @blueK68 this code was not merged yet. You can tell that your running  
> version is still using joda time rather than java time from the error  
> message.
>
> I think there is a bug in your rule.
>
> ```
> delay1 = R_Delay.state as Number
> ```
>
> the type of delay1 will be Number. the `plusMinutes()` method needs an  
> `int`. Try something like this:
>
> ```
> var delay1 = 0
> var az = now
>
> rule "Test"
> when ...
> then
>     delay1 = (R_Delay.state as DecimalType).intValue
>     az = new DateTime((Sunrise_Time.state as  
> DateTimeType).zonedDateTime.toInstant.toEpochMilli).plusMinutes(delay1)
> end
> ```
>  or even
>
> ```
> var az = now
>
> rule "Test"
> when ...
> then
>     val delay1 = (R_Delay.state as DecimalType).intValue
>     az = new DateTime((Sunrise_Time.state as  
> DateTimeType).zonedDateTime.toInstant.toEpochMilli).plusMinutes(delay1)
> end
> ```
>
> ...if you're not changing the value of `delay1` after you set it, or  
> using `delay1` in any other rules (same for `az`).
>
> P.S. You would get better / faster answers on [the  
> forum](https://community.openhab.org/).

**Pull request closed without merging**
