### PR TITLE
Fix https://github.com/eclipse/smarthome/issues/3132

### PR DESCRIPTION
**Pull request by kgoderis**
@maggu2810 Can you give this a go? The adjusted test is not yet in the repo, hence I could not do the automated test, but I have manually tested the expressions you reported as faulty and they yield the correct output over here

Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
Hi @kgoderis thank you for your changes, but this seems to break a currently existing test:

```
    @Test(expected = IllegalArgumentException.class)
    public void dayOfWeekAndMonth() throws ParseException {
        new CronExpression("* * * 1 * 1");
    }
```

I assume this test needs to be changed now.

**Comment by maggu2810** [comment]
The other test(s) I added succeeded now. Thank you! 
Can you change the one currently existing test, so it pass?

**Comment by kgoderis** [comment]
> I assume this test needs to be changed now.

or the code ;-) I will check this asap

**Comment by maggu2810** [comment]
Thank you for fixing it such promptly.

**Pull request merged**
