### PR TITLE
Fix label/description localization for channel definition

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
My previous PR was handling label/description localization for channel goup definition but we need a similar handling for channel definition too.

**Comment by lolodomo** [comment]
Please wait before merging...

**Comment by kaikreuzer** [comment]
Most certainly - at a quick glance, this was anyhow too much code change to be reviewed on a Saturday night ;-)

**Comment by lolodomo** [comment]
Thank you for all your reviews and merges on a Saturday night ;-)

**Comment by lolodomo** [comment]
Ok, change done. Ready again for review.

**Pull request merged**
