### PR TITLE
Fix "mixed content" warning on mapviews

### PR DESCRIPTION
**Pull request by hakan42**
Signed-off-by: Hakan Tandogan hakan@tandogan.com

### CODE REVIEW

**Comment by hakan42** [comment]
When using an SSL-enabled reverse proxy (and maybe even when using SSL support in jetty, did not test that version), you get a warning about mixed content while displaying the minimap from openstreetmap.

Removing the explicit scheme in the URL and allowing the browser to use whatever scheme the fixes this issue as openstreetmap.org is also available via https by now.

**Comment by hakan42** [comment]
@kaikreuzer , do you have any hint what might be wrong with my "Signed-off-by" comment on the issue?

**Comment by dnobel** [comment]
I don´t see a Signed-off-by line in the commit itself, only in the comment of the PR. The Signed-off-by has to be added to the Commit.

**Comment by hakan42** [comment]
ip-validation failed, opening new PR

**Pull request closed without merging**
