### PR TITLE
Fix config dispatch test

### PR DESCRIPTION
**Pull request by sjka**
Usually waitForAssert is the magic healing potion for tests.
But ocasionally less is more.

Signed-off-by: Simon Kaufmann <simon.kfm@googlemail.com>

### CODE REVIEW

**Comment by sjka** [comment]
Please wait for Travis to finish before merging it, as I need a vote from a slow CI server

**Comment by maggu2810** [comment]
CI failed

**Comment by sjka** [comment]
Thanks for the notice. In the meantime I think I found the root-cause: An embarrassing little mistake in unit conversion AND a nice little int overflow. Just running the tests locally, will update this PR in a few minutes.

**Comment by maggu2810** [comment]
> An embarrassing little mistake in unit conversion AND a nice little int overflow.

Ah, yes :wink: 

You should calculate the timeout (multiplication) only once at the beginning of the function.
Perhaps we should use:
```
final long timeoutNs = TimeUnit.MILLISECONDS.toNanos(timeout);
```

**Comment by sjka** [comment]
> Perhaps we should use [...]

Now I'm wondering on which planet I've been living for the last 13 years. Nice hint, thanks.

**Pull request merged**
