### PR TITLE
Digitalstrom: fix internal zone group name id handling

### PR DESCRIPTION
**Pull request by maggu2810**
Fixes: https://github.com/eclipse/smarthome/issues/4081

### CODE REVIEW

**Comment by kaikreuzer** [comment]
This fix will probably cause merge conflicts for https://github.com/eclipse/smarthome/pull/3182.
@MichaelOchel How would you prefer to proceed? Shall I merge this and you rebase your branch and resolve the conflicts? Or do you prefer to check these fixes and directly incorporate them in your branch (if it is at all still applicable there)?

**Comment by MichaelOchel** [comment]
@kaikreuzer 
At first it is applicable, the Object-Array is still existing in the second update.

I prefer to incorporate the fixes directly in my branch. I already checked it, but I think one object which contains all informations (zone name/id and the two maps) is enough.

Furthermore I saw, that we forgot to change the query execution to the new DsAPI method (DsAPI#query(String, String)). So I can corrected this by the incorporation of the fix, too.

I have already incorporated it locally and done a short test.

Best regards 

Michael

**Comment by kaikreuzer** [comment]
@maggu2810 Ok for you to close this PR as soon as @MichaelOchel has included the fixes in #3182?

**Comment by MichaelOchel** [comment]
@maggu2810 Can I commit it?

**Comment by maggu2810** [comment]
@MichaelOchel Sure, I will close this issue as soon as it has been fixed.

**Comment by MichaelOchel** [comment]
@maggu2810 That’s good. Because I fixed some more things with the commit, here the direct link to the affected class/fix: [fix internal zone group name id handling ](https://github.com/MichaelOchel/smarthome/commit/84609fb494ba0ddddc64844956bb8aa1ba1570df#diff-15ed87cab5c37f4262bc4152fa0ea898)

**Comment by maggu2810** [comment]
I have added two comment about your upper case usage and missing static keyword.


Your diff still shows this usage that has been removed by my changes:
```diff
		 +                if (((HashMap<Short, String>) zoneGroupIdNameMap.get(zoneID).GROUP_ID_NAMES).get(groupID) != null) {
 -                    return ((HashMap<Short, String>) this.zoneGroupIdNameMap.get(zoneID)[1]).get(groupID);		 +                    return ((HashMap<Short, String>) zoneGroupIdNameMap.get(zoneID).GROUP_ID_NAMES).get(groupID);
```

**Comment by MichaelOchel** [comment]
I have incorporated your comments and deleted the last no more needed class-casts.

**Comment by kaikreuzer** [comment]
@maggu2810 Can this PR be closed then?

**Comment by maggu2810** [comment]
For me #3182 seems to be a never ending story (starting at Mar 24th).
I personally prefer small fixes that could be merged into a feature / rework branch instead of waiting for month until such a big refactor is finished.

So, as you (@MichaelOchel and @kaikreuzer) think it will be integrated in #3182 and this PR will be finished some time (and we don't need this reminder anymore) we can close it.

**Comment by kaikreuzer** [comment]
> never ending story

Well, it is mainly sitting there and nobody yet took the time to review it - afaik, it is not under any active further development.

**Comment by maggu2810** [comment]
> Well, it is mainly sitting there and nobody yet took the time to review it

Then I misinterpret the message:

> We don’t really know what the state of the PR is. We wait for the review or other messages from e.g. @hmerk about the functional test.

My assumption has been that both the review from @hmerk and messages from @hmerk are necessary first.

**Comment by kaikreuzer** [comment]
No, it just means they are waiting for review comments and will happily incorporate them once comments are there. I have asked @triller-telekom to see if he finds the time to do a review of it in the next days, so I hope we can get things moving here again.

**Comment by triller-telekom** [comment]
I have just finished a review on https://github.com/eclipse/smarthome/pull/3182#pullrequestreview-65483264 But that PR will take some time until it is ready for merging. So if the fix in this PR is critical I think we should apply it first.

**Comment by triller-telekom** [comment]
An update from my side: PR #3182 has been improved quite a lot so far and we are now waiting for a test with real hardware next week, afterwards we can create a CQ and hopefully merge it soon.

**Comment by maggu2810** [comment]
Thank you for the update. I will close this issue as soon as the fix that is part of #3182 has been merged.
Let keep me this PR open as a reminder...

**Pull request closed without merging**
