### PR TITLE
Minor changes to Thing class

### PR DESCRIPTION
**Pull request by martinvw**
* Interface fields are always public static final, leave out the modifiers
* Corrected @return to @param in setLabel docblock
* Corrected fieldname in setBridgeUID docblock

### CODE REVIEW

**Comment by maggu2810** [comment]
Thanks, LGTM.
WRT to https://github.com/eclipse/smarthome/pull/4177#discussion_r138828738 would you like to remove the disliked new lines and empty lines, too (as you already fixed the JavaDoc)?

**Comment by martinvw** [comment]
> WRT to #4177 (comment) would you like to remove the disliked new lines and empty lines, too (as you already fixed the JavaDoc)?

Done

**Comment by maggu2810** [comment]
Again many thanks :wink: 
Can I ask you to remove the empty lines between `@...` tags, too?

**Comment by martinvw** [comment]
> Can I ask you to remove the empty lines between @... tags, too?

Nope 😛 

Have to really do the work where they pay me for now, than it will end of business day.

**Comment by martinvw** [comment]
:-D thanks

**Pull request merged**
