### PR TITLE
WU binding: fix timeout for icon download

### LINKED ISSUE #4476: WU: icon image sometimes in state UNDEF
It looks like sometimes the download of the condition icon is failing because the state of the image item is UNDEF.

### PR DESCRIPTION
**Pull request by lolodomo**
Default 5s timeout replaced by a 30s timeout.

Fixes #4476

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by maggu2810** [comment]
I am just wonder about the timeout and how we find an useful one. It seems to me currently chosen by a trial and error mechanism.
Wouldn't it be better to use a common approach about that timings?

* cloudy.gif: 1647 bytes
* fog.gif: 1847 bytes
* nt_cloudy.gif: 1647 bytes

So, the "biggest" icon has a size of 1847 bytes resp. 1.9 kb.
May I ask you about your internet connection (downlink)?

If we need more then 5 seconds to receive about 2 kb, I wonder the time the 5 seconds are spend.
I did not check the implementation, but does it not work, because the download has never been started because the job is canceled (e.g. because there is no internal resources free to start the worker) before. Or takes it more then five seconds after byte 1 is received until the other 1846 bytes are received?

**Comment by lolodomo** [comment]
My downlink is more than 20 Mbps.

I suppose that when it happens, the WU server is just not able to respond quicly.

**Comment by triller-telekom** [comment]
I am wondering if you get any of these logging lines where the state of the icon is set to `null`.

https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.net/src/main/java/org/eclipse/smarthome/io/net/http/HttpUtil.java#L496-L505

If you do NOT get any of these, I guess it is probably OK to increase the timeout as the server might be slow.

**Comment by lolodomo** [comment]
I can do this test in my production environment and let you know.
I will stop the test in case I have roo many things logged.

**Comment by lolodomo** [comment]
Here are additional logs with failures when using the default timeout:
```
2017-12-07 13:52:29.387 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - About to execute http://icons.wxug.com/i/c/k/rain.gif
2017-12-07 13:52:34.392 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - Media download failed (URL http://icons.wxug.com/i/c/k/rain.gif)
2017-12-07 13:52:34.397 [INFO ] [nd.handler.WeatherUndergroundHandler] - Failed to download the content of URL http://icons.wxug.com/i/c/k/rain.gif

2017-12-07 16:52:42.326 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - About to execute http://icons.wxug.com/i/c/k/nt_rain.gif
2017-12-07 16:52:47.330 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - Media download failed (URL http://icons.wxug.com/i/c/k/nt_rain.gif)
2017-12-07 16:52:47.333 [INFO ] [nd.handler.WeatherUndergroundHandler] - Failed to download the content of URL http://icons.wxug.com/i/c/k/nt_rain.gif

2017-12-07 17:52:50.615 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - About to execute http://icons.wxug.com/i/c/k/nt_rain.gif
2017-12-07 17:52:55.621 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - Media download failed (URL http://icons.wxug.com/i/c/k/nt_rain.gif)
2017-12-07 17:52:55.624 [INFO ] [nd.handler.WeatherUndergroundHandler] - Failed to download the content of URL http://icons.wxug.com/i/c/k/nt_rain.gif
```

**Comment by lolodomo** [comment]
As you can see the error message is logged 5s after the start.

**Comment by kaikreuzer** [comment]
@triller-telekom Why is this logging relevant? Do we only get there if there was some error other than a slow response? Does it mean that waiting longer won't help anyhow?

**Comment by lolodomo** [comment]
You can see that a second icon is downloaded with success just after the failure:
```
2017-12-07 13:52:29.387 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - About to execute http://icons.wxug.com/i/c/k/rain.gif
2017-12-07 13:52:34.392 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - Media download failed (URL http://icons.wxug.com/i/c/k/rain.gif)
2017-12-07 13:52:34.397 [INFO ] [nd.handler.WeatherUndergroundHandler] - Failed to download the content of URL http://icons.wxug.com/i/c/k/rain.gif
2017-12-07 13:52:34.452 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - About to execute http://icons.wxug.com/i/c/k/chancerain.gif
2017-12-07 13:52:34.485 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - Media download response: status 200 content length 1730 media type image/gif (URL http://icons.wxug.com/i/c/k/chancerain.gif)
2017-12-07 13:52:34.488 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - Media downloaded: size 1730 type image/gif (URL http://icons.wxug.com/i/c/k/chancerain.gif)
```

**Comment by kaikreuzer** [comment]
If the download is successful by increasing the timeout, I would be fine to merge this as the "slowness" indeed seems to be on the WU server side (and thus be the same for all) and not on the individual Internet connection.

**Comment by lolodomo** [comment]
With a timeout of 10 seconds, I got no failure but it run only 2 days with this patch I think.
With a timeout of 5s, I have around 3 failures every day (the data are requested evey half an hour).

**Comment by kaikreuzer** [comment]
@maggu2810 Are you fine with this change after these observations?

**Comment by triller-telekom** [comment]
@kaikreuzer I was curious about what is in the caught `IOException` but I just recognized that we do not log the exception :( I was hoping for a reason for the failure other than "timed out".

But since the logs from @lolodomo show that the download is successful right after a failure, I guess increasing the timeout should be OK.

**Comment by lolodomo** [comment]
New day and 3 new failures. It is just interesting because it is on different gif files:
```
2017-12-07 19:53:00.148 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - About to execute http://icons.wxug.com/i/c/k/nt_cloudy.gif
2017-12-07 19:53:05.152 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - Media download failed (URL http://icons.wxug.com/i/c/k/nt_cloudy.gif)
2017-12-07 19:53:05.155 [INFO ] [nd.handler.WeatherUndergroundHandler] - Failed to download the content of URL http://icons.wxug.com/i/c/k/nt_cloudy.gif

2017-12-07 22:53:12.023 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - About to execute http://icons.wxug.com/i/c/k/nt_partlycloudy.gif
2017-12-07 22:53:17.037 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - Media download failed (URL http://icons.wxug.com/i/c/k/nt_partlycloudy.gif)
2017-12-07 22:53:17.040 [INFO ] [nd.handler.WeatherUndergroundHandler] - Failed to download the content of URL http://icons.wxug.com/i/c/k/nt_partlycloudy.gif

2017-12-08 17:24:09.141 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - About to execute http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif
2017-12-08 17:24:14.147 [DEBUG] [lipse.smarthome.io.net.http.HttpUtil] - Media download failed (URL http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif)
2017-12-08 17:24:14.151 [INFO ] [nd.handler.WeatherUndergroundHandler] - Failed to download the content of URL http://icons.wxug.com/i/c/k/nt_mostlycloudy.gif
```

**Comment by kaikreuzer** [comment]
@maggu2810 Please let us know whether you are fine to merge.

**Comment by maggu2810** [comment]
I have been interested in two points:
* what is the root cause of the timeout
* which timeout value does make sense

I am fine with increasing the timeout as long as it is really the server that is such slow.

If it has just been caused by the server I am also happy to use an e.g. 30 seconds timeout, just to prevent another PR that fix a "10 seconds is not always enough".
That's the reason why I would like to find the value not only by "it works using 10 seconds" but by a commitment how much time should maximal be spend. Then we can state later "no, a value greater then 10 seconds does not make sense".

If 10 seconds is the maximum value that we would like to allow because a greater value is not acceptable we can merge this one.
If 30 seconds are also okay but just not necessary at the moment, I would increase the timeout. It should be the maximum that is allowed and not the maximum that is currently necessary.

**Comment by lolodomo** [comment]
We are already using a 30s timeout for the main request getting the data, so the same timeout for the icon download could make sense.
Let me know what value you finally want.

**Comment by maggu2810** [comment]
@lolodomo I did not know the WU code base, sorry about all the stupid questions. :wink: 

> We are already using a 30s timeout for the main request getting the data

Then let's use the same timeout for the icons as for the data. Would a constant WU_FETCH_TIMEOUT make sense?

**Comment by lolodomo** [comment]
Change done. I hope it is the final one :)

**Comment by wborn** [comment]
> If we need more then 5 seconds to receive about 2 kb, I wonder the time the 5 seconds are spend.

Perhaps the time could also be spent in:
* Java Garbage Collection
* Swapping memory from/to a slow SD card
* Log rotation

**Comment by maggu2810** [comment]
Normally, I would assume that all that tasks running in a different thread context and will not slow done the HTTP download. That's the reason I would like to know at which places the timeout measurement starts working.

**Comment by wborn** [comment]
Eventually the timeout is used by the Jetty HttpClient as an await(..) parameter of a CountDownLatch in [FutureResponseListener.get(..)](https://github.com/eclipse/jetty.project/blob/jetty-9.3.22.v20171030/jetty-client/src/main/java/org/eclipse/jetty/client/util/FutureResponseListener.java#L107). It is only started after the request has been sent.

Jetty 9.4.8 [has an improvement](https://github.com/eclipse/jetty.project/issues/1897) to properly spread load through load balancers in front of servers. So that might fix continuously sending requests to the same server that has become overloaded.

**Pull request merged**
