### PR TITLE
Added card layout to extensions page

### PR DESCRIPTION
**Pull request by aounhaider1**
fixes https://github.com/eclipse/smarthome/issues/2923
Signed-off-by: Aoun Bukhari <bukhari@itemis.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks. Some observations:

- I would prefer the list/card buttons to be positioned at the very top, next to the reload button. At the moment, the selection is individual per tab, i.e. when switching to another category, I again see the list view. Furthermore, moving the buttons would safe screen space (no additional white space under the search field) and also allow the inclusion of "card-only" views at other places in the UI in future.
- When pressing the install button, it disappears and the card shrinks in size. It should instead show the "waiting rotation" as in the list view.

**Comment by kaikreuzer** [comment]
Some more:
- If there is no documentation link, the button on the top right must not be shown
- Page switches back to list view upon a browser refresh
- Images must not be changes in their aspect ratio.
- As most logos are wider than high, I would suggest to reserve a 3:2 box for it, which usually fits quite well (see e.g. [here](http://www.openhab.org/technologies.html).
- There must not be a grey background, but if the image is transparent, it should be displayed transparently as well.
- If no logo is available, I would leave the space blank. The grey square with a letter inside looks rather ugly.

Just to show what I am talking about wrt the logo:
screen shot 2017-02-03 at 12 09 58

**Comment by aounhaider1** [comment]
Updated accordingly.

**Comment by kaikreuzer** [comment]
> - There must not be a grey background, but if the image is transparent, it should be displayed transparently as well.
> - If no logo is available, I would leave the space blank. The grey square with a letter inside looks rather ugly.

These two issues are still not solved (tested with Chrome and Safari). Does this work for you?

> - When pressing the install button, it disappears and the card shrinks in size. It should instead show the "waiting rotation" as in the list view.

The "waiting rotation" is shown on the left, while the button disappears on the right - not really what the user would expect. Is it different for you?

**Comment by kaikreuzer** [comment]
Thanks, better.

> Images must not be changes in their aspect ratio.

Is this already addressed?

**Comment by aounhaider1** [comment]
As you said, I reserved fixed space of 3:2 for logo. I can remove the fixed sizing but that means that images will take as much space as they want.

**Comment by kaikreuzer** [comment]
Well, what I asked for is to reserver a fixed 3:2 space and fit in the image without changing its aspect ration. Just the same way as on http://www.openhab.org/technologies.html. Distorting logos is not a good idea, I hope you agree.

**Comment by aounhaider1** [comment]
Should work now.

**Comment by kaikreuzer** [comment]
Yes, but it seems to be aligned top-left. Would it be possible to center it within the 3:2 box?

**Comment by aounhaider1** [comment]
Centered. :)

**Comment by kaikreuzer** [comment]
Indeed :-(

screen shot 2017-02-09 at 11 04 18

**Pull request merged**
