### PR TITLE
Xtext upgrade

### PR DESCRIPTION
**Pull request by sjka**
This contributes towards #3898 and #1402: It upgrades Xtext to the latest release version. This however entails some additional upgrades due to Xtext's minimal requirements:

* Xtext 2.12
* Eclipse 4.7 (Oxygen)
* Guava 15 (requires PB CQ)

Build, runtime and designer still seem to work well for me, so the upgrade was pretty smooth. However, as the equinox upgrade it already uncovered #4091 and #4092, I'm happy for feedback if there are any more surprises related to this...

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Could you check what needs to be done in https://github.com/eclipse/smarthome/blob/master/features/karaf/esh-tp/src/main/feature/feature.xml#L167-L205 (maybe with some help of @maggu2810, who had some libs repackaged for the current version)?

**Comment by kaikreuzer** [comment]
I successfully tested this and it all looks good to me.
I have added https://github.com/eclipse/smarthome/pull/4100/commits/79a486fbca45b308b41e3dfdb853e447848b0c37, which also updates the Karaf feature. I even built an openHAB distro with this and all looked good.

@maggu2810 Please also have a look, especially at my changes to the Karaf feature and let me know in case I did anything wrong there.

**Comment by sjka** [comment]
As smooth as it goes until now, I created CQ 14019 for Guava 15

**Comment by sjka** [comment]
FTR: The CQ got approved.

**Comment by kaikreuzer** [comment]
Cool, let's go for it and see what breaks ;-)

**Pull request merged**
