### PR TITLE
cleanup watch service rel. path

### PR DESCRIPTION
**Pull request by maggu2810**
It seems @kaikreuzer and me reviewed the PR #2432 parallel, as it has been merged as I added some comments.
This PR changes the commented stuff.

@svilenvul As my formatter does some additional cleanup (removing trailing whitespaces), I assume that your IDE is not set upped correctly.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
And it seems your review was much better ;-) Thanks.

Still, Travis fails since there are apparently code parts that need to be changed.
Is this an API breaking change? I didn't check that...

**Comment by svilenvul** [comment]
[AutomationWatchService](https://github.com/eclipse/smarthome/blob/34e844b5e6aa2817542849fe10c43d3051d54e02/bundles/automation/org.eclipse.smarthome.automation.provider.file/src/main/java/org/eclipse/smarthome/automation/internal/provider/file/AutomationWatchService.java) was merged in the meantime ...

**Comment by maggu2810** [comment]
@svilenvul Can you provide a fix for?

**Comment by svilenvul** [comment]
Yes.

**Comment by maggu2810** [comment]
The fix #2561 has been merged.
I rebased this PR, so we can wait for Travis CI.

**Comment by kaikreuzer** [comment]
Failing unit test: FolderObserverTest

**Comment by maggu2810** [comment]
> Failing unit test: FolderObserverTest

@svilenvul, @kaikreuzer  Do you agree that the changes of this PR are only cosmetic ones?

I don't think that changes of this PR are the source of a failed test and that this PR does not anything that will break anything (that is not already broken).

**Comment by kaikreuzer** [comment]
Which means that https://github.com/eclipse/smarthome/pull/2432 is likely to have broken it? Yes, I would agree. @svilenvul could you check?

**Comment by m-memova** [comment]
I ran the tests 100 times in Eclipse and 10 times in Maven and I cannot make it fail again :)

**Comment by kaikreuzer** [comment]
Thanks for testing, @m-memova!
This time, Travis didn't fail on these tests and Hudson seems happy with the current code as well.
So let's merge :-)

**Pull request merged**
