### PR TITLE
Replace synchronized() in favour us ConcurrentHashMaps in order to pr…

### PR DESCRIPTION
**Pull request by kgoderis**
…event lock race conditions with UpnpIOParticipants + Code Formatting

Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Your PR replaces spaces by tabs as it seems - could you try to change back the formatting changes, so that the PR only contains the code change?

**Comment by kgoderis** [comment]
hue? I applied the ESH code formatter... Since it is saved, etc, I dunno how to undo that

**Comment by kaikreuzer** [comment]
Are you really sure? The code formatter does replace tabs by spaces and your PR definitely contains tabs...

**Comment by kgoderis** [comment]
Grrr.. i had the openHAB code formatter active in Eclipse. Is there a way to keep the ESH and OH formatters equal? I looks better now

**Comment by kaikreuzer** [comment]
Much better, thanks!

> Is there a way to keep the ESH and OH formatters equal?
Yeah, I will soon provide IDE setups with identical formatters.

**Pull request merged**
