### PR TITLE
Add constructor to create HSB from RGB.

### PR DESCRIPTION
**Pull request by cdjackson**
Currently there are methods to return RGB from HSB, but no constructor/method to create HSB from RGB.

I've found myself needing this for ZWave and BLE lights recently, so it seems like it might be useful as a constructor rather than putting it into my bindings...

Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by watou** [comment]
Would you mind adding a test to HSBTypeTest.java in org.eclipse.smarthome.core.test?

**Comment by cdjackson** [comment]
Sure - I wanted to see if this was acceptable before adding tests?

**Comment by maggu2810** [comment]
Hm, there is already a constructor that is using three number arguments.
It could perhaps be a little confusing.
What do you think about a static function similar to this one.
```java
    public static HSBType valueOf(String value) {
        return new HSBType(value);
    }
```

```java
    public static HSBType fromRGB(int r, int g, int b) {
        float tmpHue, tmpSaturation, tmpBrightness;
        int max = (r > g) ? r : g;
        if (b > max) {
            max = b;
        }
        int min = (r < g) ? r : g;
        if (b < min) {
            min = b;
        }
        tmpBrightness = max / 2.55f;
        tmpSaturation = (max != 0 ? ((float) (max - min)) / ((float) max) : 0) * 100;
        if (tmpSaturation == 0) {
            tmpHue = 0;
        } else {
            float red = ((float) (max - r)) / ((float) (max - min));
            float green = ((float) (max - g)) / ((float) (max - min));
            float blue = ((float) (max - b)) / ((float) (max - min));
            if (r == max) {
                tmpHue = blue - green;
            } else if (g == max) {
                tmpHue = 2.0f + red - blue;
            } else {
                tmpHue = 4.0f + green - red;
            }
            tmpHue = tmpHue / 6.0f * 360;
            if (tmpHue < 0) {
                tmpHue = tmpHue + 360.0f;
            }
        }

        return new HSBType(new DecimalType(tmpHue), new PercentType((int) tmpSaturation),
                new PercentType((int) tmpBrightness));
    }
```

**Comment by cdjackson** [comment]
That's fine - I did originally have this and then thought it would be better as a constructor, but I don't mind... I'm also considering an RGBA version might be useful but I've not needed this right at the moment...

**Comment by kaikreuzer** [comment]
> I wanted to see if this was acceptable before adding tests?

I think we all agree it is acceptable :-)
But I would also prefer the static method version.

**Comment by cdjackson** [comment]
Ok, I'll update tonight.

**Comment by cdjackson** [comment]
Updated to the static method.

Just a note that due to rounding, the to/from RGB/HSB methods don't return the same value - they can be 1% out.

**Comment by kaikreuzer** [comment]
lgtm. @maggu2810 any comments? If not, feel free to merge.

**Pull request merged**
