### PR TITLE
Fixed PaperUI tests + added test task to dev and prod mode

### PR DESCRIPTION
**Pull request by aounhaider1**
Signed-off-by: Aoun Bukhari <bukhari@itemis.de>

### CODE REVIEW

**Comment by htreu** [comment]
And one more thing: The tests will produce a `PaperUI-tests.xml`. Please add this to `.gitignore`.

**Comment by aounhaider1** [comment]
Updated

**Comment by htreu** [comment]
Hi @aounhaider1, did you push your changes?

**Comment by htreu** [comment]
@aounhaider1 do you want to include the tests in the main build here? I would vote for that.

**Comment by aounhaider1** [comment]
I added the tests to gulp default task. I think that should be sufficient. Or am I missing something?

**Pull request merged**
