### PR TITLE
Script editor

### PR DESCRIPTION
**Pull request by aounhaider1**
Requires CQ for https://github.com/isagalaev/highlight.js/.
fixes https://github.com/eclipse/smarthome/issues/1560

### CODE REVIEW

**Comment by htreu** [comment]
please improve on the following topics:
- the script code is not stored in the rule anymore.
- text area should have the same look/feel like before. grey & white borders are very large and the input line is not easily visible.
- highlighting works only on focus lost. highlighting should occur while you type.

**Comment by aounhaider1** [comment]
```the script code is not stored in the rule anymore.````
Just checked, seems to be working.

```text area should have the same look/feel like before. grey & white borders are very large and the input line is not easily visible.```
Updated.

```highlighting works only on focus lost. highlighting should occur while you type.````
This is currently not achievable with highlight.js. Note that highlight.js is not a highlighting library for text areas or input fields. It is meant for divs etc. But I used it because of its light size. If we really need a complete text editor than we have to use some other highlighting library. The lightest one, that I know of, is around 200 KB (highlight.js is 12KB).

**Comment by htreu** [comment]
Thanks for the fixes.
However there are still major issues when using highlight.js here:
- highlight.js will paste the formatted script code back into the input DIV and does not escape HTML tags (e.g. `let myVar = '<p>my paragraph<p>'`). This will totally mess up the editor and may even allow for script injection when reading a template from file.

My suggestion would be to look out for an alternative JS code editor with acceptable footprint.

**Comment by htreu** [comment]
Maybe we can provide the xtended script editor as an option and load the specific JS editor from a cdn instead of providing it with the rule engine bundle. what do you think @aounhaider1?

**Comment by kaikreuzer** [comment]
Might indeed be an option to download it remotely only when using it (and have it as a works-with dependency).
But this will be a new PR, so I suggest to close this one as highlight.js does not seem to be appropriate for our needs.

**Comment by kaikreuzer** [comment]
Discussion should be continued on https://github.com/eclipse/smarthome/issues/1560.

**Pull request closed without merging**
