### PR TITLE
use rule DTO for rule events

### PR DESCRIPTION
**Pull request by maggu2810**
Fixes: https://github.com/eclipse/smarthome/issues/2137

This PR has not been tested by myself but I assume @aounhaider1 you can cherry-pick the PR and report it.

### CODE REVIEW

**Comment by maggu2810** [comment]
Does not fix your issue

**Comment by aounhaider1** [comment]
Yes, it does not fix the issue.

**Comment by maggu2810** [comment]
I will ping you...

**Comment by maggu2810** [comment]
ping

**Comment by aounhaider1** [comment]
Fixes the issue.

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
