### PR TITLE
notify handlers asynchronously so that longer running operations do not block us

### PR DESCRIPTION
**Pull request by kaikreuzer**
Currently, the ThingLinkManager might process events very slowly, which can be a cause for the issue described in #4591. Notifying the handlers asynchronously should solve this.

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
Doesn't this increase the potential change about a "not initialized anymore" call to the channel (un)linked method?

**Comment by kaikreuzer** [comment]
True. I've now moved the check into the runnable, so that it is checked immediately before the call - does that look better?

**Comment by maggu2810** [comment]
Yes, the change is so the same as before, but the other issue is resolved.
Looks good to me. Let's wait for Travis and then merge the PR.

**Comment by sjka** [comment]
> Yes, the change is so the same as before [...]

At least there is a pretty high probability that is is 😉  

Let's see how the chances are in reality of running into a race condition at this place - the consequences would not be of real harm though, so I'm fine with it!

**Pull request merged**
