### PR TITLE
Add synchronize(this) to onValueReceived()

### PR DESCRIPTION
**Pull request by kgoderis**
Code Formatting as a bonus.

Signed-off-by: Karel Goderis<karel.goderis@me.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
You are using the synchronized statement for the whole function.
So why do you not use the keyword on the function declaration as it is done for the other ones in that file:
* private synchronized void onSubscription()
* private synchronized void removeSubscription()
* private synchronized void onUpdate()
This will also reduce the indentation of the whole function implementation.

Do you see any difference?

**Comment by kaikreuzer** [comment]
@kgoderis Do you still have this PR on your radar?

**Comment by kaikreuzer** [comment]
@kgoderis Ping :-)

**Comment by kgoderis** [comment]
Damn. Missed this comment

**Comment by kgoderis** [comment]
@kaikreuzer @maggu2810 Ok sorry for the very late response. I seem to miss quite some github notifications to the bazillion number of emails I have to deal with

Fixed, squashed and ready to merge

**Comment by maggu2810** [comment]
LGTM, thanks.

**Pull request merged**
