### PR TITLE
add missing license header to homematic test files

### PR DESCRIPTION
**Pull request by maggu2810**
@FStolte If new files are added you need to ensure that the license header is present.
I  forget it myself from time to time, too. :wink:

### CODE REVIEW

**Comment by maggu2810** [comment]
@svilenvul Why has this not been detected by SAT?

**Comment by svilenvul** [comment]
Test files are not being processed - https://github.com/openhab/static-code-analysis/blob/master/sat-plugin/src/main/resources/configuration/checkstyle.properties#L3

**Comment by maggu2810** [comment]
@svilenvul Thanks for clarification. Do you know why?

**Comment by svilenvul** [comment]
Not exactly, I can only assume that main consideration was increased effort.

**Comment by kaikreuzer** [comment]
Afair, the tests were never fully covered wrt the coding guidelines, especially as we had a lot of Groovy involved in the past. To be discussed whether we want to tighten the requirements on them.

**Pull request merged**
