### PR TITLE
fix Paper UI build

### PR DESCRIPTION
**Pull request by maggu2810**
I cannot grant that this is a grant fix, but I ran into #2219 now multiple times.
I used a shell while loop to restart `mvn clean install` as long as it does not succeed.

The while loop never finished since hours.

After this fix I can do a clean build again.

I don't know which code of Maven or some of the plugins clean up my target while building but I think this commit makes the situation not more wore and for me it helps (at least today).

Fixes: #2219

### CODE REVIEW

**Comment by kaikreuzer** [comment]
I never had issue #2219 and I have no clue what this PR is actually doing. So I'll leave it to @aounhaider1 to comment and am fine with any outcome :-)

**Comment by maggu2810** [comment]
npm downloads the stuff it uses to a temporary directoy.
Normally it is the temporary directory.
Caused by [this issue](https://github.com/npm/npm/issues/6855) we changed that to the build directory.

IMHO: The import change for us has been to use a fixed directory all the time, so not multiple ones are created that are never cleaned up.

There is no need to download the stuff on every build again (the build directory is cleaned up on the `clean` phase) and as it seems there are corner cases the build directory is cleaned up while the frontend-maven-plugin is running...

I am happy to wait for some feedback of @aounhaider1.

**Comment by kaikreuzer** [comment]
@aounhaider1 Still waiting for your approval of this change.

**Comment by aounhaider1** [comment]
Yes, changing tmp directory path should not affect anything. I don't exactly understand why maven build would fail in case of no npm tmp directory but if this fixes the issue then its fine.

**Pull request merged**
