### PR TITLE
LIFX : Fix #1778 #1788

### LINKED ISSUE #1778: ColorTemperature not working on LIFX Color 1000
I did a demo with a LIFX Color 1000 yesterday and noticed that the color temperature channel wasn't working at all - when moving the slider in the Paper UI, it was going to a cold white, flickering a bit, but I was not able to change the temperature as expected.

@kgoderis Does it work for you?

### PR DESCRIPTION
**Pull request by kgoderis**
Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by kgoderis** [comment]
@kaikreuzer I was not sure what people woud prefer in terms of the interpretation of light. Very often, light of low Kelvin is considered to be "warm", and high kelvin like 9000K is considered to be "cold" light. So, in that perspective, I have mapped a temperature of 0 to 9000K and 100% to 2500K. The reverse can easily be implemented but I have the "consumer" point of view in the PR

**Comment by kaikreuzer** [comment]
>  I have mapped a temperature of 0 to 9000K and 100% to 2500K

Yes, that's perfect and how the Philips hue binding does it as well.
As the channel is about "temperature", it means "a lot of" temperature is warm, no temperature is cold.

Still, it does not work for me as expected.
When I send a percent value to the item, the bulb keeps its color and only slightly adapts it. But I would expect that it actually always switches to white tones (like in the app). Fiddling with it, it looks as expected if I manually set the saturation to 0. I would expect this to happen automatically when making use of the color temperature channel. Would you agree?

**Comment by kgoderis** [comment]
@kaikreuzer Yes, i would. When I tested it, it worked for me. What you say is quite strange I must admit, certainly with https://github.com/kgoderis/smarthome/blob/e1fd13804ce0c0205bb06b12c7c5c45c253d8f00/extensions/binding/org.eclipse.smarthome.binding.lifx/src/main/java/org/eclipse/smarthome/binding/lifx/handler/LifxLightHandler.java#L291 in mind. Changing the % does only change the temperature, and that is directly mapped in to the API call without changing the saturation field.

**Comment by kaikreuzer** [comment]
> Changing the % does only change the temperature, and that is directly mapped in to the API call without changing the saturation field

And this is exactly the problem. You should explicitly set the saturation to 0 here.
The LIFX API has the weird feature that they can "shift" any (colorful) color by changing the color temperature. But making a red light cold, imho does not really make much sense.

**Comment by watou** [comment]
> But making a red light cold, imho does not really make much sense.

It doesn't make *any* sense, because colour temperature actually means a color in a space (see example algorithm [here](http://www.tannerhelland.com/4435/convert-temperature-rgb-algorithm-code/)).  This is 1500K to 15000K:

temperature_to_rgb_1500_to_15000
 
Also, as I just learned:

* Red values below 6600 K are always 255
* Blue values below 2000 K are always 0
* Blue values above 6500 K are always 255

**Comment by kaikreuzer** [comment]
> It doesn't make any sense

Tell this the LIFX guys :-)

**Comment by watou** [comment]
> Tell this the LIFX guys :-)

It might be a fun thing to make a red light "cold," but setting the color temperature of a light source should really do the one thing it means!  :-)

**Comment by kgoderis** [comment]
Ok - So, how shall we proceed? (1) saturation to 0 or (2) implement the algorithm?

@kaikreuzer Can we in the meantime integrate the PR and put the above on the to-do list?

**Comment by kaikreuzer** [comment]
1!!!! That should be a single line of code, right?

**Comment by kgoderis** [comment]
@kaikreuzer done  & squashed

**Comment by kaikreuzer** [comment]
Perfect, this now works exactly as expected - many thanks!

**Pull request merged**
