### PR TITLE
Revert "Merge pull request #679 from chriskn/BUG_596"

### PR DESCRIPTION
**Pull request by maggu2810**
This reverts commit cf47248423b95e1180ce8ba5ae12b1e50d159658, reversing
changes made to a106b119ab6d58ff5fc2029fc55fe953089beead.

@kaikreuzer 
Should we do a revert by a PR or directly without PR?

As #679 has not been rebased cleanly, I would prefer to refert it and do it again.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Why do you think a revert is required? We would still have the commit + its reverse in the history.
Can't we simply fix the problem that was introduced through it with a new PR?

**Comment by maggu2810** [comment]
Reverting is a common practice in Git.
Sure, we could create an additional PR, but if you want to see the changes that has been necessary to implement #679 some time, you can't have a look at one commit but have a look at least to two separate commits.
I thought that was the reason you want all the commits squashed, that you get one commit for a PR / for a feature / bugfix (that is complete by itself).

**Comment by maggu2810** [comment]
If you prefer to create a bugfix PR, it is okay, too. But reverting is a base feature of Git (more standard as history rewriting).

**Comment by kaikreuzer** [comment]
I am not a git pro, so yes, if it is a common practice and it does not add "balast" to the repo, this is fine for me - but then probably indeed as a direct revert and not through a PR.

> I thought that was the reason you want all the commits squashed, that you get one commit for a PR / for a feature / bugfix (that is complete by itself).

The main reason for the squashing is to make sure than no code can be secretly added to the repository (into its history) as you would have to review every single commit and not just the changes of the PR.

**Comment by maggu2810** [comment]
I would assume that Mr. Torvalds does know what should be done with Git :wink: 
https://www.kernel.org/pub/software/scm/git/docs/howto/revert-a-faulty-merge.txt
And they introduced an explicit command for that "git-revert - Revert some existing commits".
So, we should do it (IMHO) the next time.
For this one, I will merge PR #765 with the fix.

Using a PR with a separate fix will it make difficult is someone read the history later.
If I see in the history, that there has been a PR, the PR has been reverted and then there is another one, I know that the last one should contain all changes for the PR.
So, what we have now is
* a corrupt blame, the changes I have done in the test are now done by another person.
* the commit of the first PR does change a file that should not be part of this PR (but as it is not reverted we do not see it a year later)
* ...

Perhaps we can think about it later, how we want to proceed such stuff (IMHO the stuff about the blame would be a pro for the revert).

**Comment by kaikreuzer** [comment]
> So, we should do it (IMHO) the next time.

Ok, fine with me!

**Pull request closed without merging**
