### PR TITLE
Implements RuleRegistry.runNow(ruleId) #689

### PR DESCRIPTION
**Pull request by danchom**
Also fix bug in rule normalization. Default values defined in ConfigDescritptionParameter was not normalized.
Signed-off-by: Yordan Mihaylov <j.mihailov@prosyst.bg>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks! How about adding this feature to the REST API as well, so that we can include a button in the Paper UI?

**Comment by danchom** [comment]
Yes I was forgot about it. I'll try to extend REST API tomorrow and update the PR.

**Comment by kaikreuzer** [comment]
@danchom Question: Wouldn't it actually make sense to allow the runNow to be executed, even if the rule is "disabled"? When developing/testing rules, I usually have them disabled, so that they are not triggering unexpectedly and I test them by doing a runNow - which is not possible in that case. Wdyt?

**Comment by maggu2810** [comment]
> Question: Wouldn't it actually make sense to allow the runNow to be executed, even if the rule is "disabled"? When developing/testing rules, I usually have them disabled, so that they are not triggering unexpectedly and I test them by doing a runNow

I think this should be allowed as it is IMHO a common use case.

**Pull request merged**
