### PR TITLE
Moved Astrobinding from openHAB to Eclipse SmartHome

### PR DESCRIPTION
**Pull request by triller-telekom**
I have refactored all package names, adjusted the manifest and about.html. See issue #3213

Also-by: Dimitar Ivanov <dstivanov@gmail.com>
Also-by: Martin van Wingerden <martinvw@mtin.nl>
Also-by: Petar Valchev <petar.valchev@musala.com>
Also-by: Gaël L'hopital <glhopital@gmail.com>
Also-by: Ingo Theiss<ingo.theiss@i-matrixx.de>
Also-by: John Cocula <john@cocula.com>
Also-by: Laurent Garnier <lg.hc@free.fr>
Also-by: Svilen Valkanov <svilen.valkanov@musala.com>
Also-by: Karel Goderis <karel.goderis@me.com>
Also-by: Kai Kreuzer <kai@openhab.org>
Also-by: Gerhard Riegler <gerhard.riegler@gmail.com>
Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by sjka** [comment]
For the poor committer having to create the CQ:

```
Gerhard Riegler gerhard.riegler@gmail.com (91%)
Gaël L'hopital glhopital@gmail.com (2%)
Kai Kreuzer kai@openhab.org (2%)
Dimitar Ivanov dstivanov@gmail.com (<1%)
Martin van Wingerden martinvw@mtin.nl (<1%)
Petar Valchev petar.valchev@musala.com (<1%)
Ingo Theissingo.theiss@i-matrixx.de (1%)
John Cocula john@cocula.com (<1%)
Laurent Garnier lg.hc@free.fr (<1%)
Svilen Valkanov svilen.valkanov@musala.com (1%)
Karel Goderis karel.goderis@me.com (<1%)
```

[org.eclipse.smarthome.binding.astro.patch.zip](https://github.com/eclipse/smarthome/files/916799/org.eclipse.smarthome.binding.astro.patch.zip)

**Comment by kaikreuzer** [comment]
Thanks, do you mean me? 
Did you already check if all of them have a valid ECA?

**Comment by sjka** [comment]
Now I did 😁 

According to the CLA Lookup Tool, the following email addresses have no valid CLA:

* gerhard.riegler@gmail.com
* kai@openhab.org (<-- ?!?)
* Theissingo.theiss@i-matrixx.de

The rest is okay. 

So @gerrieg, @itheiss and @kaikreuzer (still wondering about that one...), would you mind checking your [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca)? If you already signed one before it simply might have expired. If you have it signed it would certainly ease the process of getting the approval for moving the astro binding into Eclipse SmartHome.

**Comment by sjka** [comment]
PS:

> do you mean me?

Only by a third 😉 
I actually checked it, but I really cannot create CQs for a project where I'm not committer. Which somehow makes sense, I guess.

**Comment by itheiss** [comment]
Man you make it harder than neccesary. I just added only some lines to Readme.md 😀
I signed the Eclipse Contributor Agreement. Hope everything ist finde now ...

**Comment by kaikreuzer** [comment]
@itheiss See it as an investment done for all you future contributions to Eclipse!

@sjka I now also have a valid ECA 👼

**Comment by gerrieg** [comment]
My ECA seems to be expired, created a new one now.

**Comment by kaikreuzer** [comment]
I have created CQ 13273 for this PR. Please refrain from doing any changes to it from now on!

**Comment by kaikreuzer** [comment]
Good news, the CQ is approved!

**Pull request merged**
