### PR TITLE
Updated readme.md

### PR DESCRIPTION
**Pull request by KaaNee**
added info that the free api will be ended by end of 2018.

### CODE REVIEW

**Comment by htreu** [comment]
Thanks @KaaNee, can you provide a source for this information? Thanks you.

**Comment by KaaNee** [comment]
Sure, if you go directly to the URL (https://www.wunderground.com/weather/api/) you see the warning about the free api at the top Links to this subpage of wunderground:
https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api

**Comment by htreu** [comment]
thanks for the link. There is however also this passus:

```
For developers who use WU API data for non-commercial purposes, you will have access to a new plan for a personal use, low call volume API. Stay tuned for more details as we build this out.
```
So we should update the docs when there is further information available for the none-commercial use. wdyt?

**Comment by KaaNee** [comment]
Ok first, i didn't get the passus first time.
I'm with you - but an hour ago these comments were written by the official ibm representive Victoria Gardner:

"There will no longer be a WU "developer key". "
and
"If they are likely to want free access only, you're going to need to look for another platform."

see:
https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api?topic-reply-list[settings][filter_by]=all&topic-reply-list[settings][reply_id]=19857906#reply_19857906

They are all transfering to TWC (The Weather company), which have their own plans (paid) and api.
So i think we can add this to documentation as a hint - before other users build their weatherplan in hours and hours and can throw it away finally.

**Comment by htreu** [comment]
Thanks @KaaNee, that are some clear words. It even tells that existing PIA keys will only work for a little while until they switch to the new WU API.
WU will then be "paid only". What does this mean for our binding? It would have to be ported to the new paid API, so I guess its essentially dead then.

**Pull request merged**
