### PR TITLE
Swagger annotations added to REST resources

### PR DESCRIPTION
**Pull request by YordanDZhelev**
Signed-off-by: YordanDZhelev <zhelev.yordan@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks for this PR!
As discussed, I still find the result a bit difficult to browse and read.
I do not see any value in the sub-menu entries "Core", "Sitemap" and "SSE" - this appears to be a random split of the REST API and does not even tell the user that this is the technical doc of REST endpoints (I would rather expect an explanation about SSE when choosing this menu entry). I understand that it is a technical restriction and we cannot easily merge these 3 pages into a single on as we also cannot split the Core page into multiple ones for each main endpoint.

As the TOCs on top of the three pages are rather useless as well (they do not link to the according anchor), I would completely remove them. Instead, we should imho manually maintain a list of main (meaning /discovery, /inbox, etc.) endpoints at https://www.eclipse.org/smarthome/documentation/features/rest.html#rest-endpoints and link to the according anchor of the generated page, what do you think?

The generated pages (btw, all 3 pages have "REST Core API" as a title)
have a LOT of space everywhere - this does imho not really help for the readability (as you hardly have any content on the screen without scrolling). Maybe this could be easily improved by e.g. changing
```
/inbox/{thingUID}

DELETE
```
to
```
DELETE /inbox/{thingUID}
```
and condensing the line spacing in the CSS for these pages?

Two small remarks to conclude:
- the /id endpoint is missing in this PR
- It would be great to have some description on the /events endpoint, especially the "topics" parameter and the EventOutput model (maybe @kolkoo can provide input on these)

**Comment by dnobel** [comment]
> As the TOCs on top of the three pages are rather useless as well (they do not link to the according anchor), I would completely remove them

I still hope that we could get them working. Especially the Core Page is such long, that it´s hard to find something. But a static list of endpoint might also work.

Maybe this could be easily improved by e.g. changing

>/inbox/{thingUID}
>
>DELETE
>to
>
>DELETE /inbox/{thingUID}

I agree that the current layout is not optimal. I think the endpoint is h2 and the methods are h3. If we change that to always repeat the endpoint, there is no structural element for one endpoint. The endpoints and methods would be on the same level. Not sure if that increases the readability 

> the /id endpoint is missing in this PR

You are right. At the time where this branch was created, the ID bundle did not exist.

> It would be great to have some description on the /events endpoint, especially the "topics" parameter 

We already have a good description for SSE (https://www.eclipse.org/smarthome/documentation/features/rest.html#server-sent-events-sse). The generated page only is the technical endpoint generated by swagger, which provides a link to the SSE documentation. But we could also remove it, if you want.

**Comment by kaikreuzer** [comment]
> I still hope that we could get them working. Especially the Core Page is such long, that it´s hard to find something. But a static list of endpoint might also work.

Right, if the TOC would include links, we could keep it. Nonetheless, having a single manually maintained list of main endpoints makes imho sense in any case.

> The endpoints and methods would be on the same level. Not sure if that increases the readability

This is what I have seen on the example template and [it looked nice](https://github.com/kongchen/swagger-maven-plugin/wiki/Sample.markdown#131-createuserswithlistinput), but maybe you are right and this is an old example since [this one](http://htmlpreview.github.io/?https://raw.github.com/kongchen/swagger-maven-example/master/generated/document.html) does it the same way as in this PR. So ok for me to keep it as is as long as the line spacing (and font sizes?) gets optimized.

> The generated page only is the technical endpoint generated by swagger, which provides a link to the SSE documentation. But we could also remove it, if you want.

I do not ask for a very detailed description (since we have that on a separate page as you rightly point out), but having "topics" as a description of the topics parameter is a bit too brief. I would not remove it, since we will also need this documentation for the Swagger UI in future as well.

**Comment by kaikreuzer** [comment]
FTR: [CQ 9833] swagger-annotations Version: 1.5.0 has been approved for parallel IP.

**Comment by dnobel** [comment]
Closed this one, because of new PR #510 .

**Pull request closed without merging**
