### PR TITLE
Paper UI: binding component example

### PR DESCRIPTION
**Pull request by htreu**
This is based on the file restructuring #5102.
* Most of the `PaperUI.bindings` module is turned into directives. 
* The routing configuration moved to the module. 
* The top level title is set through the new title service.
* Everything is decoupled from the rest of the app.
* [Controller Activation Promise](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#controller-activation-promises) is used to speed up view switching.

### CODE REVIEW

**Comment by htreu** [comment]
Rebasing will be done after #5102 is merged.

**Comment by maggu2810** [comment]
@htreu #5102 has been merged (but I am pretty sure you know that already) :wink:

**Comment by htreu** [comment]
Thanks @maggu2810, I already did the rebase.

**Comment by maggu2810** [comment]
I would like to test this changes, but I cannot build it.

[maven-log.txt](https://github.com/eclipse/smarthome/files/1790317/maven-log.txt)
[2018-03-07T18_04_15_384Z-debug.log](https://github.com/eclipse/smarthome/files/1790320/2018-03-07T18_04_15_384Z-debug.log)

**Comment by kaikreuzer** [comment]
Travis is another reviewer, which wasn't happy yet. Just retriggered it...

**Comment by maggu2810** [comment]
My machine has also been a reviewer for the build process and it gives its go :wink:

**Comment by kaikreuzer** [comment]
Ok, so two machines and @maggu2810 are happy now - that should suffice ;-)

**Pull request merged**
