### PR TITLE
Show rules tab only if rules rest endpoint is available

### PR DESCRIPTION
**Pull request by aounhaider1**
Signed-off-by: Aoun Bukhari <bukhari@itemis.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
Great

**Comment by maggu2810** [comment]
Oh, I perhaps merged to early.
This commit removes the option to hide the entry by configuration if the rule REST endpoint is available.

@kaikreuzer Is it okay, to remove the option to hide fields if the technical base is available?

**Comment by kaikreuzer** [comment]
> @kaikreuzer Is it okay, to remove the option to hide fields if the technical base is available?

No, I would have actually expected that it is still possible to statically overrule this new feature by configuring that the rule menu should be hidden. Would you agree or are you working on some alternative in #1409?

**Comment by maggu2810** [comment]
I give it a try in #1409.
I would like to implement this way:
not available => not shown (regardless of the configuration)
available => shown if configuration has this set to true, not shown if configuration has this set to false

Will reopen #1409 if tested.

**Comment by kaikreuzer** [comment]
Ok, cool, this is exactly the logic I would expect - thanks!

**Pull request merged**
