### PR TITLE
Fix mixed console command descriptions

### PR DESCRIPTION
**Pull request by marcelrv**
Signed-off-by: Marcel Verpaalen <marcel@verpaalen.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
LGTM, but perhaps we should change the formatter settings, so a new line is added after the comma. WDYT?

**Comment by marcelrv** [comment]
Indeed the automatic formatter in this case seems to make the code less tidy.
I was fixing the formatting manually, but it seems that with the new Oomph setup the formatter is automatically applied with each save, hence it  

I did not see easy way to fix it outside of adding `@formatter:off` tags to this part to allow to manually fix the formatting. Don't know if that is the best way. What you think?

**Comment by maggu2810** [comment]
I would not assume that the formatter settings are all perfect and must not be changed. If we could improve the settings to generate more readable code, you should create a PR for the formatter.

**Comment by marcelrv** [comment]
okay, I think I was able to fix some settings in the formatter, now it looks better.
Do you know where the formatter file is stored, so I can make a PR (separate) for that one as well?

**Comment by maggu2810** [comment]
The settings are part of the Oomph setup file. You can use the Oomph recorder or settings import...

**Comment by maggu2810** [comment]
targetplatform/EclipseSmartHome.setup

**Pull request merged**
