### PR TITLE
Serialize degree celsius with °C, drop special char

### LINKED ISSUE #5669: RfC: Change QuantityType serialisation for degree celsius
I would like to suggest changing the string serialisation for degree celsius from the special character `℃` to `°C` (two separate characters).

When working with such units, I noticed that:
- many fonts either do not support `℃` at all or render it in some weird fashion
- Many Text-to-speech engines cannot cope with `℃`, while they correctly process `°C`.
- as `℃` is not on the keyboard, people won't use it themselves (in rules, sitemaps, etc.) and thus we will always have a mix which might result in issues (e.g. when trying to do string comparison).

TL;DR: I think our life would be easier if we avoid using the very uncommon char `℃`.

### PR DESCRIPTION
**Pull request by htreu**
Fixes #5669.

Note: During parsing the special character `℃` is still supported.

Signed-off-by: Henning Treu <henning.treu@telekom.de>

### CODE REVIEW

**Comment by sjka** [comment]
```
Failed tests: 
  QuantityTypeTest.toFullStringShouldParseToEqualState:193 
Expected: is "20 ℃"
     but: was "20 °C"
```

**Comment by kaikreuzer** [comment]
Sounds as if the failing test confirms the correctness of the change 😎 .

**Comment by htreu** [comment]
Test fixed, thanks guys.

**Comment by sjka** [comment]
Computer says: No. 🤣 

```
Failed tests: 
  ScriptEngineOSGiTest.testAssignQuantityType:117 expected:<20.0 [℃]> but was:<20.0 [°C]>
```

**Comment by sjka** [comment]
Ahhh, there we go. Thanks!

**Pull request merged**
