### PR TITLE
look for jsondb backup files if a .json file is missing

### PR DESCRIPTION
**Pull request by philomatic**
Signed-off-by: Patrick Gottschaemmer <mail@gottschaemmer.net>

### CODE REVIEW

**Comment by philomatic** [comment]
Hmm... thats odd, looking at the commit, I see my private (with eclipse account) address :

> Signed-off-by: Patrick Gottschaemmer <mail@gottschaemmer.net>

however, ip-validation tells me:

> The following users do not have valid ECAs. Please see this page for details, or to sign a ECA.
> pg@vs-sh.de

Which is my business email. How is that even possible? 🐙

**Comment by kaikreuzer** [comment]
Your git commits are always done with an email address that you have configured in your git client.
Check:
```
git config --get user.email
```
and it will most likely show you pg@vs-sh.de.

**Comment by philomatic** [comment]
Yes, I know. But I've thought the IP-check uses the signed-off address :)

I'll change the commit.

**Comment by kaikreuzer** [comment]
Sorry, but I do not understand the logic behind this and I think it is a buggy behavior now - see #3428. I created #3429 which reverts parts (all?) of this change.

**Comment by maggu2810** [comment]
I added the comment to your PR...

**Pull request merged**
