### PR TITLE
Sonos binding: sound notification without parsing the full queue (fix…

### PR DESCRIPTION
**Pull request by lolodomo**
… #2709)

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
I updated my PR to keep an insert at the end of the queue rather than at the the first entry of the queue.

**Comment by kaikreuzer** [comment]
@kgoderis & @R-Edelhoff Could you please review?

**Comment by kgoderis** [comment]
LGTM

**Comment by R-Edelhoff** [comment]
Seems to be OK from my side too

**Comment by kaikreuzer** [comment]
Thanks everyone!

**Pull request merged**
