### PR TITLE
add Orange and OSGi pointers in the readme.md

### PR DESCRIPTION
**Pull request by Nicolas-Lingois**
under Andre request, I added orange and OSGi pointers in the protocol/enocean readme.md

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Nicolas, I actually learnt that an Eclipse project can have multiple repos on Github.
As the EnOcean driver is not part of the normal build, but indeed really an independent sub-project, what would you (and André) think about having it moved to a repo of its own?

**Comment by kaikreuzer** [comment]
FTR, I have created https://bugs.eclipse.org/bugs/show_bug.cgi?id=498204 for this.

**Comment by maggu2810** [comment]
I assume you want to drop the "-r" and name it "osgi" instead of "osg-ri"

**Comment by kaikreuzer** [comment]
Err, no, I actually missed the "i" of osgi - the "ri" is intentional and means "reference implementation".

**Comment by kaikreuzer** [comment]
@Nicolas-Lingois Please note https://github.com/eclipse/smarthome/pull/1923 and the new repo at https://github.com/eclipse/smarthome.osgi-ri.enocean.

Feel free to create a PR there to enhance the [README.md](https://github.com/eclipse/smarthome.osgi-ri.enocean/blob/master/README.md) - thanks!

**Pull request closed without merging**
