### PR TITLE
changed back to jsonpath 2.0.0, added 3rd party sources and increased tp sequence no

### PR DESCRIPTION
**Pull request by kaikreuzer**
A follow-up on #3541. Let's see if Travis still has issues.

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
I will wait for Travis CI :wink:

**Comment by kaikreuzer** [comment]
Me too 😎

**Comment by maggu2810** [comment]
failed

**Comment by kaikreuzer** [comment]
Argh. jsonpath 2.1.0 [requires net.minidev:json-smart:2.2](https://github.com/json-path/JsonPath/blob/json-path-2.1.0/build.gradle#L15), but we only have 2.1.1 so far. Means we will first need yet another CQ 😢

**Comment by sjka** [comment]
...and for the completeness of the fun, [jsonpath 2.2.0](https://github.com/json-path/JsonPath/blob/2.2.0/build.gradle#L15) will require json-smart 2.2.1 😄

**Comment by kaikreuzer** [comment]
If Travis succeeds again (which I hope), please merge this by rebasing as the PR now includes two independent commits.

**Comment by maggu2810** [comment]
I will do so

**Pull request merged**
