### PR TITLE
reactivated UI tests

### PR DESCRIPTION
**Pull request by sjka**
* fixed mockito dependencies
* added launch config
* included the tests in the maven build
* fixed a test
* fixed the behaviour when an item could not be found

Signed-off-by: Simon Kaufmann <simon.kfm@googlemail.com>

### CODE REVIEW

**Comment by sjka** [comment]
Do not merge yet!
I want to have a Travis vote on this one, hence I will rebase it once #3337 got merged.

**Comment by maggu2810** [comment]
#3337 has been merged

**Comment by kaikreuzer** [comment]
Just retriggered Travis for this PR.

**Comment by sjka** [comment]
Thanks.
Travis looks good.
So: go! 😄

**Pull request merged**
