### PR TITLE
Feature/sass

### PR DESCRIPTION
**Pull request by GradyD**
This PR is a fork of #899. The only changes are converting the current CSS to SASS. With this I did make changes in some files where the same selector was used, I did not read through every file to this level of detail.

The benefit of using SASS in the long term is that we can use CSS variables. So for things like colors you just include a different value for the same variable and you can easily change the look without having to override or use `!important;` tags, this currently has not been created but as I touch the SASS files I will work on updating/cleaning the files.

In the short term it is very easy to see all of the CSS associated with a specific feature instead of digging through 3 different CSS files trying to find if a selector already exists for what is being styled. 

Another benefit of moving to SASS could help reduce the bootstrap css file size, if we decide to include the BS SASS files we can comment out the CSS items that are not being used.

### CODE REVIEW

**Comment by GradyD** [comment]
@aounhaider1 I believe I will need your opinion on this change.

**Comment by GradyD** [comment]
Pulling in what @kaikreuzer said in #918.

Since the plan is to avoid having gulp included in other solutions built on top of this I think the best plan is to leave theme.css as its own file and include it in `index.html` after ESH styles. This means theme.css would always be included even if it is not used.

**Comment by aounhaider1** [comment]
I am not much familiar with SASS. I read about it and it looks pretty cool but still, I am not in a state to decide whether we should use it or not. Maybe @sja can help us decide as he already talked about it here https://github.com/eclipse/smarthome/pull/800#issuecomment-170221083.

**Comment by kaikreuzer** [comment]
There doesn't seem to be much enthusiasm for SASS here... I have heard many people saying that it just brings another layer of complexity and I wonder if it is worth doing so?
We should try to make it simple enough to get started and not being an absolute JS expert to work on the Paper UI - see [requests like this](https://www.eclipse.org/forums/index.php/t/1074951/) from people wanting to start with it.
@GradyD Would it be ok for you to stay with "simple" CSS for now?

**Comment by cdjackson** [comment]
Not that I’m developing for PaperUI, so I probably don’t have a say, but… :)

I would recommend SASS or LESS simply to keep things consistent. The use of variables ensures that you can keep the them standard, and also change something simply, and have it filter across the whole style sheet…

Just my 2c…

(FYI in HABmin I use LESS).

**Comment by kaikreuzer** [comment]
As this PR is pretty outdated by now and @GradyD does not seem to be available anymore, I am closing it.
If anybody wants to revive this discussion, feel free to do so.

**Pull request closed without merging**
