### PR TITLE
drop lazy activation

### PR DESCRIPTION
**Pull request by maggu2810**

### CODE REVIEW

**Comment by maggu2810** [comment]
https://www.osgi.org/developer/design/lazy-start/

**Comment by maggu2810** [comment]
openHAB offline distribution using this PR: https://drive.google.com/open?id=0Bx99QXY8p6gvQkU5ZnRoWTF3Wm8

**Comment by kaikreuzer** [comment]
independent of the feedback on #1393, I would actually suggest to merge this as it seems that it solves many existing issues - or do you see any risk that something could break (and hence you keep the WIP prefix)?

**Comment by maggu2810** [comment]
After reading the design of the lazy start on osgi.org I think it could solve some trouble. The whole mechanism is very complicated (startup order of bundles, etc.) if lazy activation is used (if my reading is correct).
But this PR changes the activation logic of 18 bundles.
I don't know why the lazy one was used.

For me it works better then before, but I don't know if other stuff is broken.

The WIP is still set, because my intention was to wait for @shorty707.

If you feel fine with this changes, feel free to merge.

**Comment by kaikreuzer** [comment]
> I don't know why the lazy one was used.

I think the reason is that this is the default setting when you use the Eclipse project wizard for creating a new plug-in project.
But I fully agree with you that it is a rather risky setting and can lead (as we see) to unexpected lifecycle behavior.

**Comment by maggu2810** [comment]
> this is the default setting when you use the Eclipse project wizard for creating a new plug-in project

Ah okay, didn't know that.

**Pull request merged**
