### PR TITLE
Sinope binding

### PR DESCRIPTION
**Pull request by chaton78**
The sinope binding use the local API of the Sinope gateway. It doesn't require access to the sinope cloud (neviweb).

It supports for now, only the thermostats for baseboard.

For more information on the product:
http://www.sinopetech.com/en/

### CODE REVIEW

**Comment by chaton78** [comment]
Hum... I can't get the ip-validation to pass... with noreply@github.com

**Comment by hmerk** [comment]
It seems that you did not sign-off your commits using "git -s ..."

**Comment by chaton78** [comment]
Yes, I understand. I was hoping that signing the last commit would pass the validation. If not, I need to sign-off all my commits... Also, I see that it validates also for noreply@github.com.

**Comment by kaikreuzer** [comment]
> If not, I need to sign-off all my commits... 

No, you should make sure that there is only a single commit! (i.e. squash them)

**Comment by maggu2810** [comment]
Replaced by #2420

**Pull request closed without merging**
