### PR TITLE
[Tradfri] Use first IP address which is reachable

### PR DESCRIPTION
**Pull request by ivivanov-bg**
Get first IP address which is reachable in the network

Signed-off-by: Ivaylo Ivanov <ivivanov.bg@gmail.com>

### CODE REVIEW

**Comment by ivivanov-bg** [comment]
The simplest way to reproduce the issue is:
1. Reboot the bridge with the LAN cable un-plugged.
   -> Bridge assigns to itself a local link address (in the rangle169.254.0.1 to 169.254.255.254)
2. Plug the LAN cable 
  ->DHCP server assigns an IP

3. mDNS result contains the following addresses:
  -> /<local-link address>, /<LAN ip address>, /<IPv6 address>

And with the current version of the discovery participant the local link address is used (which is usually not accessible by other devices)


I suppose this is bug in the Tradfri Gateway firmware but I also think that the binding is the place where those bugs have to be workarounded (if possible) until they are fixed.
(The other option is to have binding which makes the device unusable)

**Comment by kaikreuzer** [comment]
I tried really hard, but I cannot reproduce this behavior.
Can you confirm that you are still seeing it with the latest firmware?

**Comment by ivivanov-bg** [comment]
I can't check now because I don't have gateway currently.
But it was very easy to reproduce: 
1. Power on the gateway with no LAN cable plugged.
2. After it boots (may be in 10 to 20 secs) plug the lan cable
3. Start discovery

**Comment by kaikreuzer** [comment]
I did exactly these steps and it worked smoothly 3 times in a row.
I'd suggest to close this for now, unless anyone is still able to reproduce this issue.

**Comment by ivivanov-bg** [comment]
OK - close it and will keep an eye on this

**Pull request closed without merging**
