### PR TITLE
changed HTML and JS formatter settings

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
If there is no more to say to spaces or tabs (https://github.com/eclipse/smarthome/pull/1015#issuecomment-187751734), I will merge...

**Comment by kaikreuzer** [comment]
So let's wait for @GradyD to explain why he preferred spaces over tabs here.

**Comment by kaikreuzer** [comment]
@GradyD Could you give us an indication on when you are available again for discussion? The formatting blocks a few PRs now, so it would be great if we could proceed soon.

**Comment by kaikreuzer** [comment]
@maggu2810, since we do not get any feedback from @GradyD: Shall I switch the formatter to tabs in HTML? We could then merge this and we can finally do the formatting of all HTML/JS code.

**Comment by maggu2810** [comment]
@kaikreuzer, for HTML and JS I think we can use tabs.
Have you tested the formatter settings, the result of the reformatted files? Do they look good?

**Comment by kaikreuzer** [comment]
For JS we agreed on spaces, since it anyhow runs through the minifier.

> Do they look good?

JS never looks good to me, so it doesn't make a difference ;-)
But yes, even to me, the formatted version looked better than with the default settings.

**Comment by maggu2810** [comment]
So, ok for me.

**Comment by kaikreuzer** [comment]
ok, updated PR as discussed.

**Pull request merged**
