### PR TITLE
don't serialize unit for unitless quantities

### PR DESCRIPTION
**Pull request by maggu2810**
Fixes: https://github.com/eclipse/smarthome/issues/5445

### CODE REVIEW

**Comment by sjka** [comment]
Makes sense. 

I reckon though it would be worth amending [QuantityTypeTest.testDimensionless()](https://github.com/eclipse/smarthome/blob/4157491527705cb281abeb8aa5c39affa39c988b/bundles/core/org.eclipse.smarthome.core.test/src/test/java/org/eclipse/smarthome/core/library/types/QuantityTypeTest.java#L49) accordingly.

**Comment by htreu** [comment]
I had the discussion with @kaikreuzer during implementation phase. Imho this is nit the bug. Please also see my comment here: https://github.com/eclipse/smarthome/issues/5445#issuecomment-383916890

**Comment by htreu** [comment]
It is to be discussed, if AbstractUnit.ONE should be the default unit for the dimension `Dimensionless`.  After all, NumberItems which are not linked to Channels providing QuantityType should not define a dimension.

**Comment by maggu2810** [comment]
> It is to be discussed, if AbstractUnit.ONE should be the default unit for the dimension `Dimensionless`.  

Hm, isn't that the intention of that public static member?
* the `DefaultQuantityFactory` is using this member for the `Dimensionless.class` in its `CLASS_TO_METRIC_UNIT` map
* `DefaultQuantityFormat` checks if the unit if equal to `AbstractUnit.ONE` in its format method
* `NumberSpaceQuantityFormat` checks if the unit if equal to `AbstractUnit.ONE` in its format method
* ...

**Comment by htreu** [comment]
Okay, to be more precise I was talking about the default defined in I18nProviderImpl in ESH:

https://github.com/eclipse/smarthome/blob/95830210a7f215823712f0fbca053e938e878950/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/internal/i18n/I18nProviderImpl.java#L370-L373

And imho its correctly defined as such.

That being said, the issue originates from the fact that we try to set a unit to dimensionized Number items also for DecimalType state updates. This is helpful when initialising the item from the REST API which may not yet be aware of the correct unit.
Forcing a "legacy" channel which does not support units yet is another reason to support this. When the user wants his DecimalType temperature value from a legacy binding expressed as QuantityType he may do so by defining the Temperature dimension and get the default unit for the current locale.

In the particular case of #5445 the problem seems to be 

> ...and still allow for numerical comparisons

which I found in the light of script support is a correct statement for SmartHomeUnits.ONE. In the script `NumberExtensions` we assumed that any QuantityType is not comparable to a simple scalar number. This holds true for all of them except SmartHomeUnits.ONE which should actually be comparable to a scalar (which it represents in the unit system).
I suggest to:
1. fix the NumberExtensions to allow for comparison between Number and SmartHomeUnit.ONE
2. evaluate what "numerical comparisons" was done. Switching the dimension to "Angle" should not fix the script problem but just "clean" the logs.

**Comment by htreu** [comment]
We had an offline discussion about this issue/PR and a good argument for this PR was, that it should be possible to add a dimension to any Number item (with whatever dimension fits the channel purpose, also Dimensionless) and work with it without interruption. Therefore it makes sense to cut off the " one" prefix.
Otherwise, w/o the prefix we wouldn't have had such an easy time examining the issue at hand. And imho the console log alone does not make for a good argument to drop it.
I would like to wait for further feedback on #5445.

**Pull request merged**
