### PR TITLE
Fix potential NPE in thing config description provider

### PR DESCRIPTION
**Pull request by cdjackson**
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
Can't we add that check for the caller?
Calling getConfigDescription with a null URI does not make sense at all. Does it?

**Comment by cdjackson** [comment]
No - I agree - it doesn’t make sense, but the point is if it occurs for some reason (and it did!) then it’s not good and it seems better to handle the error.  Sanity checks are there for when things don’t make sense :)

**Comment by maggu2810** [comment]
Sorry, I missed to reply here but (I know that this is just a personal opinion / preference) I am not a fan of validate arguments in the called functions and prefer the caller should check if he could pass an argument.

Sure, if we can protect the internal core to be broken by miss usage, we should do that (if one bundle adds something to a map that will break another one that is using the map content etc.).

But if only the caller gets an exception he can protect itself.

I have written C code for "very" embedded devices for years and there are big performance impacts if a function has to check its arguments every time. So I am perhaps a little bit paranoid here.

Perhaps I am missing the point at which time this error occurs (stack trace).
Perhaps this is handled in Java differently but I assume it is handled the same way (in some places) in the Java API. For example the HashMap (IIRC its the same for the most collections) constructor that gets another Map also raises a NPE if the given one is null. It relies to the caller to check if the argument is null and using the no-arg constructor or the copy constructor.

If I am wrong here, please tell me.
As someone who have to look at the framework I would like to know if that is the way we handle to get rid of NPE.

**Comment by kaikreuzer** [comment]
You should note that the interface contract of `ConfigDescriptionProvider.getConfigDescription` does not require the uri to be non-null. Therefore the fix is imho fully correct, since the implementation has to be able to deal with null values.

What can be discussed is whether the contract should be changed as null values do not make much sense in this case. But this discussion should be done separate from this PR. My pov is that I am very much looking forward to use null-check-annotations in Java 8; until then, I do not want to spend too much time on fixing JavaDoc and discussing every single parameters. Makes sense?

**Comment by maggu2810** [comment]
We do not need to discuss that stuff and we could change the code instead of the JavaDoc, but I don't think that will improve the performance of the framework.
It is okay for me if the decision if to add that fixes first and create another PR after that, but I assume this will add more work that necessary (first change code, then the JavaDoc and revert the code change).

**Comment by kaikreuzer** [comment]
My point is that relying on JavaDoc as a contract is pretty weak and you will still stumble over the problem that only 50% of the developers have read it and comply to it. With Java 8, we will have compile-time checks, so it is much easier to guarantee that you can rely that the callers respect the contract.

**Comment by maggu2810** [comment]
A change of the JavaDoc does not really have an impact of current usage because a null parameter already throws a NPE, so add a "must not null" to the JavaDoc should not change any runtime behaviour.

If we rely on the fact that framework users are not reading the doc and we have to add checks (using compile-time checks in Java 8, real runtime checks in Java 7), okay. As written above: It is okay for me if this decision is done. I will adapt my reviews to fit that decision. I just followed other requirements till now.

**Comment by maggu2810** [comment]
Perhaps my current understand of such rules has been to strict for ESH. Sorry about that.
There are other projects I am working for that are more strict. :wink:

**Comment by kaikreuzer** [comment]
>  It is okay for me if this decision is done.

I do not want to overrule anyone, so I am open to discuss any ill-decision that I might imply.

> I just followed other requirements till now.

Which would have meant which solution for the problem here?

**Comment by maggu2810** [comment]
I don't know how my messages are read, so let's state me first this one:
I feel unhappy with such changes, but I am not pissed off. I am happy to discuss it without further personal feelings.

I don't know if we could name it an ill decision. There are different ways to go for a framework.
E.g.:
* rely on the fact that it is used correctly by the caller and do not check every argument but add as much as documentation as possible
* rely on the fact that the caller does not read all the documentation and add the checks to the framework

As long as a framework does not know how frequently its public functions are used I prefer to add documentation and keeps the checks to the caller.
If there are multiple independent modules (bindings for ESH) it is okay, that the framework tries to protect one module from the other one.

So "my" solution for the problem has been to add a note to the JavaDoc and fix the occurrences of the NPEs.

**Comment by kaikreuzer** [comment]
Ok, but you would be retro-fitting the JavaDoc and thus changing the existing contract (no caller did anything wrong!)
So you are refactoring the framework and calls that were once correct, suddenly become invalid. You would have to figure out the situations when a null value might be passed, which could be a tricky thing to do.

**Comment by maggu2810** [comment]
But a null value does throw a NPE before. Doesn't it? So I assume every one that calls that function with a null argument already catches a NPE or fails till now.
After adding "must be non-null" no one can state "this has been worked previously and does not work now".

**Comment by maggu2810** [comment]
But, I am aware that we change the contracts of a public function if we add such a constraint. Just think that it does not be critical here.

**Comment by kaikreuzer** [comment]
Yes, but still the bug is in the implementation, not in the calling code.

**Comment by maggu2810** [comment]
Or the bug has been in the documentation :wink:

**Comment by kaikreuzer** [comment]
In the documentation AND the calling code - 2 bugs!

**Comment by maggu2810** [comment]
@cdjackson and the other reader about being off-topic here...
I started the discussion here, but perhaps I should move some to some other place.
But I think the most thing is already written, so perhaps I am allowed to add a few other questions:

If there is code of public functions that implementation does not fit the documentation we have first to correct the implementation to fit the documentation before we can change the documentation or some behaviour. Correct?

The ESH framework is still in development and uses "SNAPSHOT" but we should not change a function that could be used by a binding. Correct?

Is the REST API handled the same way as the functions a binding is using or does we need not to be as strict here (IIRC there are currently discussions about  changing / PR that changes return codes)?

I think I am missing the general survey here...
What is code that needs to stay to not break third party stuff and which one could be changed without knowing some closed source components that are using that code.

**Pull request merged**
