### PR TITLE
Sonos binding: don't download too big or unknown sized cover arts

### PR DESCRIPTION
**Pull request by lolodomo**
If the cover art size is unknown or bigger than 500000 bytes, it is not downloaded and the image channel is set to UNDEF.

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@kaikreuzer : I suddenly thought that your use case with an audio file provided as cover art URL may be normal when the covert art is encoded inside the audio file. I will try to test this case.
My PR will already handle this case. But I could add another test, checking that the MIME type starts with "image".

**Comment by kaikreuzer** [comment]
> when the covert art is encoded inside the audio file

That might indeed be the case - I don't have my setup available to check, if this was the case, so if you could try that out, it would be awesome!

**Comment by kaikreuzer** [comment]
@lolodomo Did you manage to do some further testing/analysis on this?

**Comment by lolodomo** [comment]
I have not found such files in my personal library. So I was not able to reproduce your problem.
My change is working, I tested it by setting a small threshold.

**Pull request merged**
