### PR TITLE
Initial prototype of the event/notification routing infrastructure

### PR DESCRIPTION
**Pull request by kgoderis**
For discussion purposes. I have added 3 external services for now : PushOver, email and simple logging.  Filters are a empty passthrough filter, and leaky bucket implementation to rate control 
No javadoc present yet

Signed-off-by: kcoKarel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by dnobel** [comment]
Thanks Karel. I think this can be used as an initial proposal for the discussion. I will comment it later.

**Comment by dnobel** [comment]
Hi Karel,

these are my first comments:

* **NotificationService:** The notification service is an interface, which pushes an event to somewhere else. As also written in the Bug I would see the NotificationService as one service, where everybody can send notifications. For that we need to define a Notification class. Services, which then pushes Notifications to somewhere else, I would call NotificiationPushService
* **NotificationManager:** This implementation class is highly dependent on the DSL. It receives the model from the DSL and calls the according NotificationServices. As with all other components we need to make the framework independent from DSLs, so that they are only one way of configuring the framework.

Tu summarize:

Your implementation "just" sends the existing events over different channels, which can be configured through a DSL. For the notification concept - that we had in mind - this is not sufficient.

Let´s start with the requirements:

* Notifications are high-level important messages for the user, that have a proper meaning (thus it can´t be Events). e.g:
   * A new device was discovered
   * An alarm was activated
   * A device has switched to offline
* The framework maintains a "persistent" list of unread notifications
* The list of unread notifications can be returned
* There is a service which can be used to create new notifications

I Would suggest to first model the Notification concept itself. Looking at http://developer.android.com/guide/topics/ui/notifiers/notifications.html we can first discuss the Notification class:

```java
public interface Notification {
   String getTitle();
   String getDescription();
   Severity getSeverity(); // or priority
   Category getCategory(); // an enum
}
```

Usage example:

The InboxService can for example automatically send notifications when a new thing has been added to the Inbox

```java
Notification notification = new NotificationCompat.Builder()
        .setContentTitle("New Thing discovered: " + inboxEntry.getLabel())
        .setContentText("Some text").build();

notificationService.notify(notification);
```

Some more complex topics are: how to deal with Icons, multiple languages etc.

Regards

Dennis

**Comment by maggu2810** [comment]
Should the producer of a notification be able to remove the notification (at a later time)?
Perhaps if a condition is not true anymore (battery level is low).

**Comment by kgoderis** [comment]
Hi - Cfr the thread on the Buglist, I am ok to see this as something separate from the Notification ESH infrastructure. Never mind the class naming; it could be something that rather integrates in to the Event structure if we want to. Yesterday I tinkered a bit around with the UML Eclipse plug-in from Obeo and start drafting things in line with what you also mention here above, so we are aligned.

Maggu, I also had this reflection and I added a revoke() method so that the NotificationManager can revoke Notifications if they are not relevant anymore (or expired!), or when the Notification was acknowledged by one instance (in case the same Notification was sent to multiple NotificationSubscribers)

**Comment by dnobel** [comment]
> Hi - Cfr the thread on the Buglist, I am ok to see this as something separate from the Notification ESH infrastructure. Never mind the class naming; it could be something that rather integrates in to the Event structure if we want to. 

The question is just, if we need two concepts. Maybe we should first discuss what is the benefit of having the possibility to post all kind of events to some output. Let´s assume we have a proper notification mechanism working, do you think it is still needed to also configure low-level events pushed as emails or to other channels?

> Yesterday I tinkered a bit around with the UML Eclipse plug-in from Obeo and start drafting things in line with what you also mention here above, so we are aligned.

I also commented in the bug, you can use whatever you want to visualize ideas.

> Maggu, I also had this reflection and I added a revoke() method so that the NotificationManager can revoke Notifications if they are not relevant anymore (or expired!), or when the Notification was acknowledged by one instance (in case the same Notification was sent to multiple NotificationSubscribers)

I would also see this as a feature of the Notification concept. That again shows me that the concepts are very similar and I´m not sure if we need both. Events are more low level without a proper meaning and especially they are transient. Notifications have a meaning and can be directly represented to the user.

**Comment by kgoderis** [comment]
Sorry for the confusion - I meant I was drawing schemes for the notification stuff apart from the remote event stuff in the PR

But I do agree that maybe there will be a bridge between events and notifications

K

**Comment by kaikreuzer** [comment]
I am closing this PR in favor of continuing the discussion on https://www.eclipse.org/forums/index.php/t/1070058/.

**Pull request closed without merging**
