### PR TITLE
WU README - avoid %unit% for persisted items

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
I do not think that this should be added here as it is not at all an information that is specific to this binding. Rather consider finding a good place in the central openHAB documentation for it.

**Comment by lolodomo** [comment]
I agree that it should be written elsewhere too but it is required here because the items in the items are with %unit%.

**Comment by lolodomo** [comment]
So a user reading the WU binding documentation should have a clear information before doing a simple copy&paste of the example.

**Comment by lolodomo** [comment]
Ok I close it but I think it is not fair to not inform the users they could have problems with the example.

**Comment by maggu2810** [comment]
As @htreu already pointed out, this is related to OH1 persistence services and not related to the ESH framework. So at least this repo is not the correct place.

**Pull request closed without merging**
