### PR TITLE
Add tests for Timer

### PR DESCRIPTION
**Pull request by evansj**
This adds unit tests for org.eclipse.smarthome.model.script.actions.ScriptExecutionTest and the Timer instances that it creates.

Signed-off-by: Jon Evans <jon.evans@pobox.com>

### CODE REVIEW

**Comment by htreu** [comment]
Hi @evansj, thanks for your contribution.

Unfortunately Travis is unhappy and reports:

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.09 sec <<< FAILURE! - in org.eclipse.smarthome.model.script.actions.ScriptExecutionTest
testRescheduleTimerDuringExecution(org.eclipse.smarthome.model.script.actions.ScriptExecutionTest)  Time elapsed: 0.09 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <false>
     but: was <true>
	at org.eclipse.smarthome.model.script.actions.ScriptExecutionTest.testRescheduleTimerDuringExecution(ScriptExecutionTest.java:56)
```

Please have a look.

**Comment by evansj** [comment]
I'm looking now... unfortunately it's really hard to test in a robust way because it uses the Quartz scheduler. It worked on my machine with a job set to run in 10ms and then using a Thread.sleep(30) to wait for it to run - this timing obviously doesn't work on the Travis server.

I might see if I can work out how to use a mock scheduler.

**Comment by htreu** [comment]
Yes, I would also prefer a mock scheduler. So the tests become reliable.

**Comment by evansj** [comment]
Note that the tests don't include testRescheduleTimerAfterExecution() because that would break the build - this is fixed in the other PR (#6480).

**Comment by kaikreuzer** [comment]
This is superseded by https://github.com/eclipse/smarthome/pull/6480.

**Pull request closed without merging**
