### PR TITLE
replaced CLASSI by QUALI parameter to make the script work as expected

### PR DESCRIPTION
**Pull request by kaikreuzer**
@maggu2810 Not sure if this script worked for you in the past, but I had to do a few adaptions for building a 0.9.0.b1 - if I am missing something, please let me know!

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
With these changes, the script works for me - as I need it right now, please allow me to merge it myself.

**Comment by maggu2810** [comment]
Why has this PR been merged without any feedback?
I assume it will break my ones now.

**Comment by kaikreuzer** [comment]
["as I need it right now, please allow me to merge it myself."](https://github.com/eclipse/smarthome/pull/2167#issuecomment-246991257) - I wasn't able to build 0.9.0.b1 without it.
If you need adaptions, please feel free to do further PRs with changes.

**Comment by kaikreuzer** [comment]
Btw, is there any documentation on how this script is to be used? The only one I found was [here](https://github.com/kaikreuzer/smarthome/commit/2387271a591610c5a10ea4b5734afd08fda31da7) and that didn't work as described...

**Comment by maggu2810** [comment]
I have build a lot of ref-tags and it has been working all the time.
The last one yesterday: https://github.com/maggu2810/smarthome/commit/9d8ecdec7738336b4540ad99fc74225bf1ed4acf

Perhaps I miss something that failed on your side.

I don't know about any documentation.

**Comment by kaikreuzer** [comment]
Which environment variables did you set before calling the script?

**Comment by maggu2810** [comment]
e.g. `REMOTE=eclipse VERSION_NEW_CLASSI=b1 tools/ref-tag/create.sh a8ba85a`

**Comment by maggu2810** [comment]
We can add an issue (a TODO) to create a documentation for the ref-tag tool.
I assume your changes broke the mechanism to use the ref-tag tool to bump from e.g. 0.x.0-SNAPSHOT to 0.y.0-SNAPSHOT.
Can you revert it after you have build the b1?
You can assign the docu todo to me.

**Comment by kaikreuzer** [comment]
This is pretty different to what you described in https://github.com/kaikreuzer/smarthome/commit/2387271a591610c5a10ea4b5734afd08fda31da7.

When specifying VERSION_NEW_CLASSI, the VERSION_NEW_QUALI was always set to "${VERSION_NEW_MMR}.qualifier".

I still believe the fix makes it better, because the script was buggy - so not really a need to revert it; only to further improve it, I would say.

**Pull request merged**
