### PR TITLE
updated TP to use recent versions of JAX-RS Connector and JUPnP

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
@kaikreuzer If there are new artifacts that should be used in shk, please ping me.

**Comment by kaikreuzer** [comment]
Jax-rs connector is already on 5.3 in SHK, so no action there.
We will need JUPnP in OH2 - is the only way updating it through SHK? At the moment, it is referencing a RC, which, if successful, will be replaced next week by a release.

**Comment by maggu2810** [comment]
> We will need JUPnP in OH2 - is the only way updating it through SHK?

It depends what you would like to do. You can also drop the shk usage and define such dependencies in OH2 directly.

**Comment by maggu2810** [comment]
IIRC I used requirements and capabilities for the target platform dependent features, already. So you should be able to fulfil this requirement yourself. E.g. adding the capability to openhab-transport-upnp and define the jupnp dependency here.
No prob doing so, but perhaps it would be better to move away from shk at all, it could be very in-transparent in feature which stuff is resolved which way.

**Comment by kaikreuzer** [comment]
Can this PR be merged then?

**Comment by kaikreuzer** [comment]
Thanks a lot - now YOU have to rebase #954 ;-)

**Comment by maggu2810** [comment]
Already done.

**Comment by kaikreuzer** [comment]
That was quick, but you missed the squashing!

**Pull request merged**
