### PR TITLE
BasicUI: properly destroy controls before navigation

### PR DESCRIPTION
**Pull request by resetnow**
* Fix memory leaks in BasicUI from ESH code. Without proper event listeners cleanup, DOM nodes were left hanging detached in heap. This should improve long-term UI stability.
* Pause any media elements before navigation

Signed-off-by: Vlad Ivanov <vlad@ivanov.email>

### CODE REVIEW

**Comment by lolodomo** [comment]
Here is the example I am using inside the demo sitemap:
`Video encoding="mjpeg" url="http://webcam.st-malo.com/axis-cgi/mjpg/video.cgi?resolution=640x480"
`
I tried your code and it does not help to stop video proxying by thez server, neither with Firefox nor with Chrome. It is only working in Edge. I did not test with Edge without your change so I cannot say that your change helped for Edge.
Note that proxying is immediately stopped if I trigger a refresh with F5 (in Firefox).

**Comment by resetnow** [comment]
For me it does stop after a while or after I trigger garbage collection manually, so it makes sense. I'll update to manually stop the translation.

**Comment by resetnow** [comment]
Updated with media support

**Comment by lolodomo** [comment]
Quickly tested with my MJPEG video example and now it works in Firefox, Chrome and Edge. Bravo.
Needs to be tested with a video tag (MP4 file for example) too.

**Comment by lolodomo** [comment]
For video like MP4 files, the handling seems to be different. Rather than having regular data transfer like for MJPEG, it looks like the browser is downloading and caching the data. So the data transfer is not regular. Browser caching leads to another problem, I will open a different issue.
By the way, it looks like you fixed the issue I noticed when using MJPEG video.

**Comment by resetnow** [comment]
For MP4 videos I just added `pause()` call. Browser prefetching may occur after the call for a while I guess.

**Comment by lolodomo** [comment]
I just tested the PR but did not review the code.

**Comment by lolodomo** [comment]
Yes I will.

**Comment by resetnow** [comment]
Any update on the PR?

**Comment by maggu2810** [comment]
I cannot really review that changes, but perhaps @htreu can have a look at the JavaScript changes.
If you tested it yourself and also @lolodomo I am fine with give it a go.
@htreu Okay for you?

**Comment by htreu** [comment]
All, sorry I'm so late. I have to admit that the Basic UI JavaScript code goes over my head. So I find it hard to ensure correctness here.

**Pull request merged**
