### PR TITLE
Revert "Fix #1211"

### LINKED ISSUE #1211: org.eclipse.smarthome.automation.core.util.ConnectionValidator throws exception when optional inputs are left unconnected
The validation of unconnected inputs must be allowed if they are not required. This will allow the definition of more general module types

### PR DESCRIPTION
**Pull request by adimova**
Reverts eclipse/smarthome#1212

Signed-off-by: Ana Dimova <a.dimova@prosyst.bg>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
The commit misses the signed-off footer.

**Comment by kaikreuzer** [comment]
@maggu2810 Merged even without the signed-off footer...?

**Comment by maggu2810** [comment]
Really?

**Comment by maggu2810** [comment]
Mom, I am a little bit irritated. I assumed you revert a commit because the commit (the one that is reverted) miss a signed-off footer.

**Comment by maggu2810** [comment]
Fast history rewriting before it is checked out by s.o.?

**Comment by kaikreuzer** [comment]
No, this PR reverts #1212, because it broke the tests and it is apparently not easy to fix.

**Comment by kaikreuzer** [comment]
> Fast history rewriting before it is checked out by s.o.?

Ok for me.

**Comment by danchom** [comment]
Ani has reverted and updated her PR

**Comment by maggu2810** [comment]
Master should be fixed now.

**Comment by kaikreuzer** [comment]
Thanks @maggu2810 

> Ani has reverted and updated her PR

Please create a new PR from that, since it does not have any effect on an already merged PR.

**Pull request merged**
