### PR TITLE
Change retrieving the firmware version to be async

### PR DESCRIPTION
**Pull request by ivivanov-bg**
The current timeout of 2 seconds is way to short on very first initialization of the CoapClient

According to https://tools.ietf.org/html/rfc7252#section-4.8.2 the initial timeout should be 93 seconds.

The proposal is to increase the timeout from 2 to 20 secs. This way it will be relatively small but still long enough for first initialization

Signed-off-by: Ivaylo Ivanov <ivivanov.bg@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
That's an interesting finding. The [JavaDoc](https://github.com/eclipse/californium/blob/245fac1e9dc1547cc6f42ffa984ee6cc6b660144/californium-core/src/main/java/org/eclipse/californium/core/CoapClient.java#L135-L137) indeed says:
> Under normal circumstances this property should be set to at least the <em>EXCHANGE_LIFETIME</em>

And `EXCHANGE_LIFETIME` is [defined as 247s](https://github.com/eclipse/californium/blob/76d023b97d7ada9b259e4d87432a9383b2574b3b/californium-core/src/main/java/org/eclipse/californium/core/network/config/NetworkConfigDefaults.java#L81). (note that this is NOT the same as the `MAX_TRANSMIT_WAIT`, which is 93s).

So I would actually claim that the correct fix is to completely remove the call to `setTimeout(TIMEOUT)` and rather go with the default.

BUT: This setting only specifies how long synchronous calls will block. Do we actually use any synchronous call? I am only aware of async communication, so I am not sure whether this fix will actually fix anything. Did you come across a bug where you identified this setting to be the root cause?

**Comment by ivivanov-bg** [comment]
Hi,

Yes - we do have a synchronous call - in updateGatewayInfoSynchronious() for retrieving the firmware version of the gateway

**Comment by kaikreuzer** [comment]
> Yes - we do have a synchronous call - in updateGatewayInfoSynchronious()

Hm, ok, this has only been recently introduced by yourself. I didn't notice when reviewing it that it is a blocking call. Any reason why this cannot be done asynchronous? It looks to me like a perfect candidate for it...

**Comment by ivivanov-bg** [comment]
Should it be done similar to: requestDeviceDetails ?

I thought it's dangerous because this runs in different thread and I don't see any synchronization on setURI

And also - the other option (to have another client) is way to heavy

**Comment by kaikreuzer** [comment]
>  I don't see any synchronization on setURI

Well, if this is a problem, we will have the same problem with requestDeviceDetails, so I do not see this as an argument :-)

**Comment by ivivanov-bg** [comment]
> we will have the same problem with requestDeviceDetails

We might have it - just not yet been hit :)

Ok - I'll change it in similar fashion

**Comment by kaikreuzer** [comment]
When implementing it that way I had a look at the Californium sources and am confident that there is no synchronization issue, since the URI is set in a newly created instance for every async call.

**Comment by ivivanov-bg** [comment]
>since the URI is set in a newly created instance for every async call

I also checked the code and I think there might be an issue as the changing of the URI is not synchronized.
So - when you do: deviceClient.setURI() you change the uri of the instance and later in the get there is: asynchronous(newGet().setURI(this.uri), handler);

But at this point someone else might have already changed the URI.


Anyway - I'll do the change and if there is an issue at some time in the future - then will think about a fix

**Comment by kaikreuzer** [comment]
> But at this point someone else might have already changed the URI.

Well, as the `deviceClient` is private to our handler, it can be only ourself. But yes, as a safeguard we could actually synchronize the `requestDeviceDetails` method.

**Comment by ivivanov-bg** [comment]
Did I missed something else ??

**Pull request merged**
