### PR TITLE
ItemChannelProvider now informs listeners about removed elements - fi…

### PR DESCRIPTION
**Pull request by kaikreuzer**
…xes failing test of #1518

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@maggu2810 Hope it is ok for you that I merge it myself, I'd just like to get the build green again asap!

**Comment by maggu2810** [comment]
No prob. But there is no another failure (perhaps unrelated)

**Comment by kaikreuzer** [comment]
Already on it...

**Comment by kaikreuzer** [comment]
Created https://github.com/eclipse/smarthome/pull/1522 - sorry for the trouble.

**Pull request merged**
