### PR TITLE
Initial contribution of the  bespoke scheduler infrastructure for ESH

### PR DESCRIPTION
**Pull request by kgoderis**
Signed-off-by: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks, I have created CQ 11136 for it - waiting now for its approval.

**Comment by kaikreuzer** [comment]
@kgoderis I had some discussion with the PMC and in the end they now ask to remove the JavaDoc sections that were copied from Quartz and rather replace them by a link to the original version (e.g. http://quartz-scheduler.org/api/2.2.0/org/quartz/CronExpression.html).

Although this isn't that nice for a developer, I think it is acceptable, so I'd suggest to go for this in order to get the CQ approved. May I ask you to do this change?

**Comment by kaikreuzer** [comment]
@kgoderis Did you see my comment above?

**Comment by kgoderis** [comment]
I just did... too many emails, missing too many of these important ones .. ok will do

**Comment by kgoderis** [comment]
Shall I squash after cq approval?

**Comment by kaikreuzer** [comment]
You can squash now if you like.
Just to be sure: Was the CronExpression the only class where you copied the JavaDoc?

**Comment by kgoderis** [comment]
Yep - the others are coming from the RFCs

**Comment by kaikreuzer** [comment]
Thanks a lot, I have updated the CQ accordingly.

**Comment by kaikreuzer** [comment]
@kgoderis Good news, the CQ has just been approved!

**Comment by kgoderis** [comment]
@kaikreuzer Cool - Time to dig up some old code. I was looking for it but could not find back where we talked about migrating org.eclipse.smarthome.model.rule and .script to use the Automation engine. I have code in place that does this migration "as is", but maybe you have ideas to overhaul the userspace rule/script pieces altogether?

**Comment by kaikreuzer** [comment]
FTR: https://www.eclipse.org/forums/index.php?t=msg&th=1073582&goto=1719275&#msg_1719275

> I have code in place that does this migration "as is", but maybe you have ideas to overhaul the userspace rule/script pieces altogether?

I think we might need both; supporting existing rules "as is" would be perfect for backward compatibility and a way that would allow us to really remove the old rule engine from the code and just use the new one.

Additionally, I would love to have a textual way to define rules for the new rule engine (since the JSON format is nice for web editors, but not nice to be written manually by users). But such a new syntax should not be specific to Xbase, but rather allow the usage of any ModuleType of the new rule engine.

**Pull request merged**
