### PR TITLE
Hide system services with no config-description

### PR DESCRIPTION
**Pull request by aounhaider1**
Fixes https://github.com/eclipse/smarthome/issues/2026
Signed-off-by: Aoun Bukhari <bukhari@itemis.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
I am not sure if this is the right solution for #2026 (I currently cannot test it), but I am merging it to have the blocking issue resolved.

#2026 wasn't asking to hide any service, but to display its config parameters correctly, even if they are not yet set. If there is something that needs to be adapted on the server side (are the config descriptions not available at all?) then please say so.

**Comment by aounhaider1** [comment]
Ok, this implements something entirely different. I thought 404 was because no config-description was found. I will have to change it for configurations instead.

**Comment by aounhaider1** [comment]
PaperUI seems to work fine if no configurations are set and the response from services/{serviceid}/config is '{}'. Also the error that you mentioned in https://github.com/eclipse/smarthome/issues/2026 says that config-description was not found. 
GET http://localhost:8080/rest/**config-descriptions**/system:persistence 404 (Not Found)
And I am not sure what should be displayed when there is no config description at all?

**Comment by kaikreuzer** [comment]
Ok, it is indeed no problem with the Paper UI but with the packaging - I created https://github.com/eclipse/smarthome/pull/2079 to fix it.

**Pull request merged**
