### PR TITLE
Add a description to the system weather channel types

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by htreu** [comment]
waiting for Travis...

**Comment by lolodomo** [comment]
Wait for a second, I will update the description for the windi direction to mention that it is an angle.

**Comment by lolodomo** [comment]
Done, I updated the windi direction description.

**Comment by htreu** [comment]
Thanks @lolodomo. This should not affect Travis, so going on merging.

**Comment by htreu** [comment]
@lolodomo please have a look at the latest Travis reports, the new description for wind direction causes test errors:

```
Failed tests: 
  SystemWideChannelTypesTest.systemChannelTypesShouldBeTranslatedProperly:227 expected null, but was:<Aktuelle Windrichtung ausgedrückt als Winkel.>
```

Please fix.

**Pull request merged**
