### PR TITLE
Creation of GeoHashType

### PR DESCRIPTION
**Pull request by clinique**
Some complementary testing in LocationItemTest
Added logic to LocationItem to handle both PointType and GeoHashType

Signed-off-by: Gaël L'hopital glhopital@gmail.com

### CODE REVIEW

**Comment by kaikreuzer** [comment]
You come up with interesting stuff - I had never heard of GeoHash before...
Can you elaborate, why you think it is a useful addition here? Which services use it and what's the benefit over the PointType?

In general, I am not really keen on including 3rd party jars in the smarthome.core bundle. As it is only 24KB, we can discuss it though.

I think in your implementation, you would also have to override `getStateAs()` and also add a method `send(GeoHashType)`.

**Comment by clinique** [comment]
Thanks for the comment. Yes I thought it was interesting enough to take a bit of time to make a PR.
I discovered this while digging in Owntracks documentation and see how they were using it (http://owntracks.org/booklet/features/msg/).

On top of that, while the algorithm is open-sourced, many libraries exists in many languages, it was worth giving a look at it.

I see some advantages over PointType, while being complementary of it : 
- GeoHashType with high precision is shorter and easier to handle than PointType, It helds both latitude, longitude in a single event.
- It also holds by himself an easy to check precision level that has the advantage to make him interesting both to define a positions and/or areas.
- This makes very easy to work with presence checking, while the zone can be described by a geoHash and tracked item by PointType. This removes the need to calculate distance, handle geofance. Many intermediary steps are completely removed, leading to clearer rules, less proxy items...

I had some clues of usage of geoHash by OpenStreeMap - and it seems intregrated in geographical handling algorithm of many bigdata related solutions (MongoDB, ElasticSearch...).
As the geoHash comes with the according bounding box, it will also be possible to show it in GMaps, OSM...
I plan to take a look at the according widget once/if the PR gets positive reactions :smile:

I was nearly sure you would point the external library, but for sure it's very lightweighted ...

**Comment by watou** [comment]
_Related:_ The GeoHash concept is the basis for several postal code systems around the world, including a [great system for Ireland](http://www.openpostcode.org/) which was unfortunately passed over by the government for the [very worst postal code system ever invented](http://www.eircode.ie/).

**Comment by kaikreuzer** [comment]
> both to define a positions and/or areas.

This is actually the feature that worries me most. Is a "Location" item now a point or an area? Aren't the potential use cases of both pretty different? Does a "distance" make sense between two overlapping areas? A question like "is A in B?" (like your presence example) is only valid if A is a point and B is an area. But if both are "Location" items, you cannot really do this in a type-safe way.
Also, if Location items are potentially areas, would we maybe want them to be sub-types of Group items, so that there can be a containment of other items?
Such questions probably closely related to https://github.com/eclipse/smarthome/issues/582 as well.

**Comment by watou** [comment]
As this and #582 are worked through, consider the arguable absence of an optional `radius` member in PointType, with the new string format `lat,lon[,alt[,radius]]`, where `radius` is expressed in meters and `alt` must be given if `radius` is given.  The meaning of `radius` is left to the user and could mean accuracy of the lat,lon or a geofence boundary.

This would allow `PointType.contains(PointType)` (and `LocationItem.contains(LocationItem)` through delegation).  And if there is someday a dynamic group membership feature, dynamically including and excluding Location items based on geospatial containment, you could give Location items Group item semantics, so Locations would dynamically contain other Locations.

> Is a "Location" item now a point or an area? Aren't the potential use cases of both pretty different?

A Location would still have a center point, and optionally a circular area.  You will always receive a meaningful answer to `thisLocation.contains(LocationItem thatLocation)`.

I think this concept is more readily useful that using GeoHashes for containment, but new methods `PointType.getGeoHash(Number characterPrecision)` and `PointType.fromGeoHash(String geoHash)` would still be useful.

**Comment by clinique** [comment]
I join @watou on the fact that we shall introduce a [radius] in PointType, either describing the level of precision of the reported measure either turning it in a definition of area.

Having this in mind, PointType and GeohashType covers the same concept and it's up to the user to define wether it is a concrete location or an area (roughly user defined may represent areas to handle presence purpose while updated one may represent reported location of a thing with a certain level of accuracy).

I really liked the idea of viewing locations as a kind of dynamic groups this would really rock ! But it also leads to the need maybe to define such a physical location by the combination more than one geohashes or pointtypes. (A house footprint maybe the sum of 2 or three geohashes at a given level of precision).

**Comment by kaikreuzer** [comment]
Disclaimer: I studied mathematics, so I might have a stronger opinion here than an average person ;-)

We are now talking about three different "interpretations" and thus meanings for a location:
- A point
- An area (or even volume?)
- A point specified by a probability field

Reading up a bit, I found that w3c tends to talk about [spatial things](https://www.eclipse.org/higgins/ontologies/2008/6/higgins-doc/geo_SpatialThing.html), of which [points are a sub-type](https://www.eclipse.org/higgins/ontologies/2008/6/higgins-doc/geo_Point.html).
I think this comes close to your idea here - a Location item represents spatial thing (e.g. a room, a person, etc.) which an be specified either as a Point (long/lat/alt) or through some other [spacial expressions](https://www.w3.org/wiki/GeoRDF#Lines_and_Polygons). So GeoHash would fit in here, but we might also introduce other types in the future (since most of my rooms are cubic and not spheres).

What I am not so sure of is how the probability fields fit in here. But maybe the can be interpreted as a kind of "fuzzy" spacial shape.

**Comment by clinique** [comment]
> GeoHash would fit in here, but we might also introduce other types in the future (since most of my rooms are cubic and not spheres)
Yes, and Geohash maybe quite convenient for this

> types in the future (since most of my rooms are cubic and not spheres)
Thinking of Postal adresses :+1:

**Comment by kaikreuzer** [comment]
Well then, I am fine with that PR.
@maggu2810 Any comments from your side?
If not, I would go ahead and create a CQ for the included lib - we will anyhow then have to wait for its approval.

**Comment by watou** [comment]
> So GeoHash would fit in here

Not entirely, because it is not possible to specify the vertices or shape of the polygon surrounding the point—the encoding of (lat,long,characterPrecision) loses detail.  It's also not possible to recover the center point accurately when going from point->geohash->point (as that's the not purpose of geohashes).

> What I am not so sure of is how the probability fields fit in here.

I am thinking of real-world applications like navigation via GPS (and the new Android client from Igor) where accuracy is expressed as a radius.  I think ESH needs to encapsulate the point and a radius, where radius is given meaning based on its usage.

**Comment by clinique** [comment]
> It's also not possible to recover the center point accurately when going from point->geohash->point (as that's the not purpose of geohashes).

Please, note that's is possible to get the center of the bounding box corresponding to the geoHash (but did not push it in GeoHashType as of now).

**Comment by watou** [comment]
> Please, note that's is possible to get the center of the bounding box corresponding to the geoHash (but did not push it in GeoHashType as of now).

Yes, but the center point is not the point with which the GeoHashType was created.  GeoHashes are great for representing some region (of stepped levels of precision) that contains a given point, but not the size or shape of the region itself.  

I would like to better understand concrete use cases in ESH for GeoHashes; I'm sure they exist, but they are not orthogonal with arbitrary points and polygons in 2D space, and do not address 3D space.  GeoHashes might be part of a very efficient algorithm for determining containment that avoids "Great Circle" computation or other expensive math.

**Comment by maggu2810** [comment]
> @maggu2810 Any comments from your side?

Another point on my "to read" list (spatial things, GeoHash, ...).

> I would like to better understand concrete use cases in ESH for GeoHashes

Me, too. I think it would be of interest if its will be used by different stuff soon or if it is only used in one corner case.

**Comment by kaikreuzer** [comment]
@clinique Any feedback for @watou and @maggu2810?

**Comment by clinique** [comment]
Well, apart from usage of GeoHash on Owntracks side, my idea is to use GeoHash to define fixed locations (home, work....) and stick with PointType for moving objects (cellphone, car).
Once the appropriate level of precision used for every location, it is very convenient to use this for geofencing.
Sure, it could also be done with PointType + Radius but with GeoHash it would be more straitforward.

**Comment by kgoderis** [comment]
@clinique @watou @kaikreuzer Any progress made on this?

**Comment by watou** [comment]
> Any progress made on this?

@kgoderis Do you have a use case in mind?

**Comment by kgoderis** [comment]
Yes and No, it is geofencing in general that I would like to deploy in a proper manner within ESH/OH2, e.g. with object that do define the geofence in a complete manner, thus not PointType+Radius. This does not have to be limited to GeoHashes as such, but could also be for example object that are more complex, such as 4 long/lat/alt points that could describe a cube. I am pretty much aligned with @kaikreuzer and @clinique on this, just wondering if the CQ is finished.

Reading the various threads somewhere it was stated that Things should not update their location, but refrain from doing so. The practical use case here is definitely my Tesla, which is updating its location every 200ms, and which I use to enable certain things around the house (opening gates, control charging station,...)

**Comment by watou** [comment]
A GeoHash isn't well suited to geofencing unless you aren't bothered by the fact the edges of GeoHash boundaries cannot be specified and are only two-dimensional.  Polytopes and point+radius are more precise but require more computation to determine whether a point is inside the region (while computing a GeoHash from GPS coordinates also requires computation, so there is a cost unless all of your data comes in as GeoHashes).  It might make sense to have GeoHash methods on the PointType class to return a GeoHash for the point (to some resolution), and for cases where the imprecision of GeoHash boundaries isn't important, use myPosition.startsWith(myRegion) to determine if you are in the "box."  

But speaking for myself, I would not use GeoHashes for geofencing since they can't be used to specify the regions I'm interested in.

**Comment by kgoderis** [comment]
@watou Ok I understand, then still, there is a need for a GeoFence base class that deals with the calculations and so forth, and from which for example a RadiusGeoFence ( {x,y} + radius) or CubeFence (4 {x,y,z}), or ... can be derived. And that consequently, cane be exposed to userland as a kind of Item and so forth.

**Comment by triller-telekom** [comment]
@watou @kgoderis @clinique Since this PR has been on hold for a year now and there so far is no specific use case where we really needed (geofence would be too imprecise), what shall we do with this PR? Can we close it?

Also since @kaikreuzer wrote in https://github.com/eclipse/smarthome/pull/1042#issuecomment-184802871

> In general, I am not really keen on including 3rd party jars in the smarthome.core bundle. As it is only 24KB, we can discuss it though.

that we do not want to have such a dependency inside our core bundles, I think it makes sense to close this PR. WDYT?

**Comment by clinique** [comment]
No problem on my side. GeoHashes does not seem to spread so much :)

**Comment by kgoderis** [comment]
@triller-telekom Ok for me to close this

**Pull request closed without merging**
