### PR TITLE
Implemented tests for the Wemo Binding.

### PR DESCRIPTION
**Pull request by svilenvul**
PR for #2101 

During the test implementation several problems were found and some tests are
ignored. Additional PR will be opened for them.

Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>

--------------

### CODE REVIEW

**Comment by maggu2810** [comment]
@svilenvul Which problems remain that needs the ignoring of some tests?
Also you need to solve a conflict in your PR now.

**Comment by svilenvul** [comment]
The tests with REFRESH command are now working. 

For each Handler I have test, that the channels are being updated when the thing is initialized. These tests are still unstable - I execute them hundred times, and  they fail sometimes. I have ignored them with "ItemChannnelLinks may not be created before the Item State is updated.".

**Comment by svilenvul** [comment]
@maggu2810 
No problems that need ignoring tests remain now.

**Comment by maggu2810** [comment]
As you are still using "import org.junit.Ignore" but don't use the import at all, I assume you could run the organize import again.

For me it is okay to merge these tests. If there is something broken in the test case it could be fixed later, too. Thanks @svilenvul

@kaikreuzer Any opinion or free to merge?

**Comment by kaikreuzer** [comment]
Looks like a huge piece of work, many thanks @svilenvul.

I am ok with merging, but as it has almost 2000 loc, I am afraid that we first have to create a CQ for it.

**Comment by kaikreuzer** [comment]
FTR, I have created CQ 12110.
@svilenvul Please refrain from doing any changes to this PR from now on, thanks!

**Comment by kaikreuzer** [comment]
CQ has been approved.

**Pull request merged**
