### PR TITLE
Remove RuleManager and ModuleHandlerCallback

### LINKED ISSUE #3474: RuleStatus "Running" not sufficient
As user I would assume that if the Rule is in status "RUNNING", that currently the actions are performed. But it is also "RUNNING" if the conditions are evaluated. 
Maybe there should be StatusDetails like "EvaluatingConditions" and "ExecutingActions" accordingly.
Furthermore we have to think about the ruleStatus handling for long running (asynchronous) actions..

### PR DESCRIPTION
**Pull request by adimova**
Closes #3474, Fixes javadoc and some unresolved issues of #4468

Signed-off-by: Ana Dimova <a.dimova@prosyst.bg>

The RuleManager and ModuleHandlerCallback interfaces are removed temporary until we decide what are their functions.

Now the Rule become RUNNING when its conditions are satisfied. The new picture of rule status transitions is 
image

### CODE REVIEW

**Comment by htreu** [comment]
Travis disagrees:
```
[ERROR] /home/travis/build/eclipse/smarthome/bundles/automation/org.eclipse.smarthome.automation.core/src/main/java/org/eclipse/smarthome/automation/core/internal/RuleRegistryImpl.java:[232] 
[ERROR] 	this.disabledRulesStorage = storageService.<Boolean> getStorage(RuleEngine.DISABLED_RULE_STORAGE,
[ERROR] 	                                                                           ^^^^^^^^^^^^^^^^^^^^^
[ERROR] The field RuleEngine.DISABLED_RULE_STORAGE is not visible
[ERROR] 1 problem (1 error)
```

**Comment by sjka** [comment]
To be honest I haven't had a deeper look yet, still,

> The RuleManager and ModuleHandlerCallback interfaces are removed temporary until we decide what are their functions.

makes we wonder a bit. That's exactly the opposite of what #4468 was about. I'd really like to see @kaikreuzer's view on this.

**Comment by adimova** [comment]
If you remember we need a mechanism for a `ModuleHandler` to inform the `RuleEngine` that it is operational. For example, an Item handler will not be operational if the required item is not available. In this case, the rule should not become `IDLE`, but should stay in `UNINITIALIZED` state. When the item becomes available, the `ModuleHandler` should notify the `RuleEngine` (through the `ModuleHandlerCallback`), and if all Module Handlers are operational, the rule can become IDLE. In the other direction, if a ModuleHandler for an IDLE rule becomes nonoperational, it should notify the RuleEngine and the rule's status must be changed to UNINITIALIZED. We can achieve this by adding some method in ModuleHandler, and some notification method in ModuleHandlerCallback.
That is my vision for this interface.

**Comment by adimova** [comment]
> I thought we have rather clearly defined their function and agreed on it in #4468 (comment):
> RuleManager - The service that actively instantiates and assigns handlers to entities and deals with their lifecycle.
> ModuleHandlerCallback - A callback API that gives handlers access to the framework features that they are generally allowed to use.

> Surely, they are meant to be extended in future, but I do not see any reason to remove them now - there does not seem to be any direct relation to the issue you are claiming to fix.

I agree that such functionality is maybe needed but at the moment these interfaces do not provide what is described above. Currently, they just duplicate the Rule public API. Such duplication is not acceptable. Once we have a callback specific functionality, we will integrate them back.

> Also, the title of this PR does not seem to reflect that it is about implementing #3474 - it would be good to keep those things separate.

As I said in https://github.com/eclipse/smarthome/pull/4468#issuecomment-400995571 there are still several API and implementation issues.
I thought that it would be nice to finish the API changes and fix the implementation as soon as possible. The title will become too big if all changes are described, so I described them in my comment. The title contains only the most significant change.

> Wrt "an Item handler will not be operational if the required item is not available. In this case, the rule should not become IDLE, but should stay in UNINITIALIZED state": I actually think we should learn from (and sync with) the Thing handler infrastructure here as well: For Things, we have distinct statuses for stuff that the framework takes care of (e.g. UNINITIALIZED, if something is missing to instantiate a handler) and stuff that is in the responsibility of the handler (e.g. setting OFFLINE-CONFIG_ERROR) - imho, we should therefore think about introducing a further (handler-operated) status for the situation that the handler decides that it isn't ready to rumble. Wdyt?

This is the current state and it seems quite well aligned. Can you please describe where do you see differences which need to be synchronized?
statuses

**Comment by adimova** [comment]
done with #5937

**Comment by kaikreuzer** [comment]
> Currently, they just duplicate the Rule public API.

I think with the changes of https://github.com/eclipse/smarthome/pull/5942, this is no longer the case.

> This is the current state and it seems quite well aligned. Can you please describe where do you see differences which need to be synchronized?

The main difference is that we have for Things the OFFLINE.CONFIGURATION_ERROR status - this is set in case the (fully initialised, i.e. all dependencies fullfilled) handler notices some issue with its configuration (e.g. an item is missing or only one of two available or whatever - at least something that the framework cannot decide, but where the handler needs to have the logic implemented).
We do not have anything equivalent for the rules yet. As explained above, UNINITIALIZED.CONFIGURATION_ERROR would imho be a bad choice, because this rather indicates that the framework cannot even initialise (meaning: bootstrap, create handler instances, etc) the rule.

**Comment by adimova** [comment]
`ONLINE` / `OFFLINE` does not make sense for the rules but maybe `UNINITIALIZED` with some new `RuleStatusDetail` - `HANDLER_PENDING`?

**Comment by adimova** [comment]
IMHO I don't think that we need a new status. The reasons/arguments you had for moving the `DISABLED` status to the status details (which is good, I admit) should be valid in this case too. What exactly a new rule status will bring as information to the user? Why the `UNINITIALIZED` with the appropriate details is not acceptable for you? If you don't like the `HANDLER_PENDING` detail, I would suggest `HANDLER_INCAPABLE` instead.

**Comment by kaikreuzer** [comment]
@adimova I just discussed this in detail with @sjka and as a conclusion, we agree with you that we won't need another status and we can go with `UNINITIALIZED.CONFIGURATION_ERROR`.

A few comments, just to capture the contents of the discussion:
- In contrast to the Thing infrastructure, we do not have any "handler managed statuses" for rules, so ALL status changes are done by the framework, never by the handlers.
- If there is a configuration problem (thus the status in `UNINITIALIZED.CONFIGURATION_ERROR`), no module handlers should be resolved/assigned, i.e. if an error is detected, the framework unresolves the modules, so that the situation is the same for all `UNINITIALIZED` statuses.
- We should introduce a `ModuleHandler.initialize()` method (in analogy to the `ModuleHandler.initialize()` method). Currently, handler implementation have to put far too much logic in their constructors and at that moment, they do not even have the moduleHandlerCallback available. The constructor should be called in the `UNINITIALIZED`->`INITIALIZING` transition, while `initialize()` should then be called in the `INITIALIZING->IDLE` transition.
- Once `initialize()` has been called, a handler should have at any time the possibility to report a configuration error. Our suggestion is to do so through a dedicated method on the callback, e.g. `moduleHandlerCallback.reportConfigurationError(@Nullable Collection<ConfigStatusMessage> messages)`. Using `ConfigStatusMessage` instances (which are also used by thing handlers) allows to have fine-grained information about which parameter has a problem etc. Once this method has been called, a module handler must expect to be disposed by the framework as the rule will transition to `UNINITIALIZED` state.
- The framework should keep track of the `ConfigStatusMessage`s for all rules that are in `UNINITIALIZED.CONFIGURATION_ERROR` status, so that the `ConfigStatusService` can provide the latest messages at any time to the UI.

Does this make sense to everyone?

**Comment by sjka** [comment]
Thanks for the summary - this is precisely my understanding of our discussion, so to me it makes sense 😄

**Comment by adimova** [comment]
I agree for most of the stuff described above but about this

> Once this method has been called, a module handler must expect to be disposed by the framework

I actually imagine this a little bit different - the framework does not dispose the handler and the handler gets the responsibility to care about its capability and when it's ready to report this to the framework

**Comment by kaikreuzer** [comment]
Can you elaborate what that would exactly mean?
Have a look at your state diagram above - reporting a configuration error means going to UNINITIALIZED status, which means that the rule is unresolved, i.e. no handlers are instantiated for modules anymore. I do not think this should be done any differently, because it would become very messy for the framework to correctly deal with handler lifecycles upon status transitions.

**Comment by adimova** [comment]
Handlers will be disposed only when the rule is removed or disabled,  the rule may become UNINITIALIZED without unresolving it.

**Comment by adimova** [comment]
image

**Comment by sjka** [comment]
> the rule may become UNINITIALIZED without unresolving it.

That's in fact surprising and unexpected. The key characteristic of the UNINITIALIZED state is that there are no handler modules existent. This is how it is for Things, and also it had been like that for Rules so far. If you drop this, then it's going to be very messy to implement the state/transition handling in the corresponding manager(s). The state machine should be kept as clean and consistent as possible.

**Comment by adimova** [comment]
how do you propose the Rule Engine to learn that a handler is ready to work?

**Comment by adimova** [comment]
The key characteristic of the UNINITIALIZED state is that the rule can't work for some reasons

**Comment by kaikreuzer** [comment]
If it isn't ready to work due to a configuration error, it will be automatically re-initialized upon an update of the configuration. This indeed assumes that the I cause of the unreadiness is due to a configuration, that needs to be changed (which is what CONFIGURATION_ERROR expresses).
We obviously cannot cover any random "I am currently not ready to work for whatever reason" situation with it, but I am not sure if we really would want this.

**Comment by adimova** [comment]
Imagine that some handler needs some service to work. Who knows that fact, except the concrete handler? In this case there is no user collaboration, the handler is the only one who can track the service and notify that is ready to work.

**Comment by kaikreuzer** [comment]
I think this is another case (not "configuration error", which we probably should discuss separately. For the start (and that's the status quo of the rule engine), I think it can suffice to have exceptions during execution, i.e. a module can simply interrupt the rule execution if there is some internal issue that prevents it from providing its service.

The discussion moved quite a bit away from this PR - is there actually still anything open here or shall we close this PR and create new ones for the configuration_error handling, etc.?

**Comment by adimova** [comment]
> is there actually still anything open here or shall we close this PR and create new ones for the configuration_error handling, etc.?

if this question is addressed to me, my answer is "yes, we can close this PR"

**Comment by kaikreuzer** [comment]
Ok, thanks. I have created https://github.com/eclipse/smarthome/issues/6083 as a follow-up. Please feel free to also enter another issue wrt dynamic signalling of a "capable status" during runtime, if this is a feature that you think should be added.

**Comment by adimova** [comment]
sorry maybe I did not understand you well, this PR should be merged and then closed

**Comment by kaikreuzer** [comment]
Sorry, but neither the title nor the discussion here seem to reflect any of the PRs content - for the sake of clarity, I'd suggest to keep this closed and you create a new PR (or maybe better multiple PRs?) with your commit, in which you describe the content and change that it does.

**Pull request closed without merging**
