### PR TITLE
Jetty HttpClient version downgraded in the TP

### PR DESCRIPTION
**Pull request by svilenvul**
This should fix one of the problems of the failing nightly build - #2003.

Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
A change to set file should also be combined with a increased sequence number (the first lines).

**Comment by svilenvul** [comment]
Thanks, I missed this one. It is fixed now.

**Comment by maggu2810** [comment]
Thanks, I will wait for the Travis CI build and merge then if all is fine.

**Comment by maggu2810** [comment]
@svilenvul The Eclipse SmartHome launch configuration seems to be incorrect again.
Can you please have a look at

**Comment by svilenvul** [comment]
@maggu2810 
OK, I will open a PR for that.
About the 8.1.14 bundles, I am not sure it will be easy.
org.eclipse.equinox.http.jetty_3.0.200.v20131021-1843.jar seems to depend on these bundles. I guess it is a part of [org.eclipse.equinox.sdk.feature.group](https://github.com/MusalaSoft/smarthome/blob/e2d2afc67393941c246bfde30f820e4cee3715c5/targetplatform/smarthome.target#L109).

**Pull request merged**
