### PR TITLE
ClassicUI migration to Material Design Lite — test and discussion

### PR DESCRIPTION
**Pull request by resetnow**
As I said [before](https://github.com/eclipse/smarthome/pull/380#issuecomment-122962206), I'm opening a pull request so maintainers can review changes and discuss some questions. It is not intended for merge.

As of current state, most widgets work and changes are synchronized between opened webpages and other clients. There are some problems, though.

## Icons

I'm not sure what to do with icons. Current implementation does not have them. I understand many people need icons for their stuff, however, I would prefer to keep icons disabled because current Smarthome/Openhab icons just don't look good when placed on Material Design page. Unfortunately, Material icon font does not provide anything smarthome-related. Can we have some kind of configurable option for icons, so icons are enabled by default but can be disabled?

## Testing

ClassicUI works in recent Chrome and Firefox versions, Android 5 (updates webview independently from the OS so it's basically latest Chromium), Chrome for Android. Android 4.3, 4.4 and IE >= 10 are expected to be supported later — some fallbacks for layout and EventSource probably can be implemented. It would be good if somebody can test it on some of the older iDevices (iPhone 4 probably?). iPhones 5 and 6 running recent iOS should be supported even now.

## Live update

Server-sent events provide a simple way to watch for item state changes. However, events only provide item state itself and thus value formatting is lost. I'm not sure what to do with it. I don't think formatting should be done on client — this would be too complex for ClassicUI. It would be great to have some kind of event channel containing sitemap-related changes — with formatted values and icons.

### CODE REVIEW

**Comment by resetnow** [comment]
Some screenshots:

screenshot from 2015-07-27 21 26 39
screenshot from 2015-07-27 21 27 44
screenshot from 2015-07-27 23 55 56

**Comment by kgoderis** [comment]
Vlad

I think the UI looks way cleaner without all the icons, I would not bother too much about it. (at least, I won’t ;-) ) did you already test it with Safari on Mac OS X? (if not, I can give that a try)

Karel

**Comment by kaikreuzer** [comment]
Thanks Vlad, you are making great progress!

Some thoughts:
Icons: I do not agree with @kgoderis - the icons are definitely a must (just look how much effort is put into creating new icons, you wouldn't want to tell people that soon no icons can be displayed anymore: https://github.com/openhab/openhab2/pull/291/files). Note that the icons also visually present the state and are thus not just eye candy. 
I agree that the current icon set is not a good match for Material Design. But I am working on a mechanism to easily support multiple alternative iconsets (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=423545). And the Paper UI is currently also lacking icons and is looking for a set that matches Material Design. The good news is: there is already a start for such an iconset (https://bugs.eclipse.org/bugs/show_bug.cgi?id=463518#c1).
If people do not want to have icons at all in the UI, I am also fine with a configuration option to disable them. But the default should imho be with icons.

Testing: The good thing about the current Classic UI (in contrast to the Paper UI) was that it was more or less plain HTML+CSS and thus worked on almost every browser. I hope that the new approach does not give this up too much and I will help testing with different devices. And I am aware that SSE for the server push mechanism causes most problems about incompatibility e.g. with IE.

Live Update: I think for the moment it is ok to not update the formatting, but only the state (i.e. listening for item events). With the new sitemap concept (https://www.eclipse.org/forums/index.php/t/1064113/), there will definitely be sitemap related events, so that all information about widgets (also visibility, coloring, etc.) can be transported this way.

**Comment by resetnow** [comment]
Karel,

I plan to test later on Yosemite VM. There shouldn't be any major problems in Safari (at least according to caniuse.com).

Vlad

**Comment by resetnow** [comment]
Kai,

> If people do not want to have icons at all in the UI, I am also fine with a configuration option to disable them. But the default should imho be with icons.

That's good! I haven't looked into it yet, but icons option can be added to TODO list then.

>The good thing about the current Classic UI (in contrast to the Paper UI) was that it was more or less plain HTML+CSS and thus worked on almost every browser

Well, before Firefox issues were fixed it was webkit-only. I agree it was quite undemanding on the Javascript part, though. Neither is new UI, I hope it will be possible to use polling as EventSource fallback.

**Comment by resetnow** [comment]
#411

**Pull request closed without merging**
