### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by krikk**
corrected namespace of homematic binding

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Not sure why you think that needs to be changed as it is fully correct. Homematic is a binding at ESH.

**Comment by krikk** [comment]
are you REALLY sure that this info is correct??? ...i tried this on my openhabian openhab 2.3 installation and the did NOT work! ...my corrected commands DID work, so can you please check this again...?

**Comment by kaikreuzer** [comment]
If you are using openHAB 2.3, please check the 2.3 version of the docs at https://www.openhab.org/v2.3/addons/bindings/homematic/#troubleshooting, which is correct. The latest code has the binding under the ESH namespace.

**Comment by krikk** [comment]
ok, thanks, sorry for this... but if i go on https://www.openhab.org/docs/ and search for homematic i find this page:

https://www.openhab.org/addons/bindings/homematic/#homematic-binding whis is a page with the outdated info and not the page you provided... why?

so the problem is that the search function does not return the 2.3 (aka latest) version of the documentation... not a really good behaviour.. :(

**Comment by kaikreuzer** [comment]
> so the problem is that the search function does not return the 2.3 (aka latest) version of the documentation... 

It actually retrieves the latest version (i.e. the one for 2.4-SNAPSHOT), but not the one that corresponds to the latest release (2.3) - yes, this is confusing and not ideal, but there wasn't a simple solution. Had been discussed on the docs website, but cannot find the discussion again right now...

**Comment by krikk** [comment]
thanks for the clarification

**Pull request closed without merging**
