### PR TITLE
null annotation code improvements

### PR DESCRIPTION
**Pull request by kaikreuzer**
For continuing the discussion from https://github.com/eclipse/smarthome/pull/6091#discussion_r211623646

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
> @maggu2810 Why did I change any semantic? The specification says that the parameter is a `java.util.Map`, it does not say that values are non-null (or did I overlook this information?).

The `NetUtil` class is marked as `@NonNullByDefault`.
If a member function of `NetUtil` uses e.g. `Map<K,V> arg` it is similar to `@NonNull Map<@NonNull K, @NonNull V> arg`.
So changing `@NonNull V` to `@Nullable V` change the semantic.
I don't say that the previous / new declaration has been correct, I also didn't say that that the previous / new declaration is incorrect.

The annotation should be chosen to state what is suspected.
So, if we want to allow a map with nullable values `@Nullable V` is correct, if we don't want nullable values it would not be correct.

I complain about your argumentation that you add nullable to get rid of a compiler warning because the warning itself is caused by a missing EEA. The get method can always return a nullable value regardless if the value type of the map is nullable or not.

I don't understand why you don't see a semantic change to state that a map's value if nullable or not nullable.

**Comment by maggu2810** [comment]
About the correctness of the change itself:

I am not completely sure if a value can be null.
The service properties are provided using a `Dictionary` (e.g. calling [registerService] manually).
A `Dictionary` states "Any non-null object can be used as a key and as a value." and on its put method "NullPointerException - if the key or value is null.".
So if the OSGi framework itself is using `Dictionary` the map schould not contain a value that is equal to null.

But I could be wrong.

[registerService]: https://osgi.org/javadoc/r4v43/core/org/osgi/framework/BundleContext.html#registerService(java.lang.Class,%20S,%20java.util.Dictionary)

**Comment by kaikreuzer** [comment]
> The annotation should be chosen to state what is suspected.

Yes, I agree that this is not a general solution and must not be added everywhere blindly.

> I don't understand why you don't see a semantic change to state that a map's value if nullable or not nullable.

I do see the semantic difference, but in this case I consider it a bug that the annotation was missing so far - so I actually fixed the declaration of the semantics here.

> The service properties are provided using a Dictionary

Yes, but we are talking about activate/modified methods here, where the spec says that it is a "Map" without stating any further details about the content of the map. So you must agree that the only valid (and more conservative) interpretation is to potentially expect null values in the map.

**Comment by maggu2810** [comment]
> Yes, but we are talking about activate/modified methods here, where the spec says that it is a "Map" without stating any further details about the content of the map. So you must agree that the only valid (and more conservative) interpretation is to potentially expect null values in the map.

If we would really use a very conservative interpretation we also have to mark the key as nullable because the map interface itself does not prevent a nullable key. It states there are maps that restrict the key but that is not a must. For example the `HashMap` allows a nullable key.

Isn't there a little bit more information reading the compendium spec 4.2 (chosen that one because that's the version we must support):

> Map – The component instance will be passed an unmodifiable Map containing the component properties.

The content of the map consists of the component properties.
The component properties are AFAIK a non null property with a non null value.

I would be really interested if a nullable key (I am pretty sure this will not be part of the map) or a nullable value (at the moment I don't this this will be the case) is a valid member of the map.

**Comment by kaikreuzer** [comment]
> If we would really use a very conservative interpretation we also have to mark the key as nullable 

You are right, I have added that.

> The content of the map consists of the component properties.
> The component properties are AFAIK a non null property with a non null value.

Yes, it could be interpreted that way. Nonetheless, I'd prefer the conservative approach as the spec is without annotations and no annotation must always be considered as potentially null.

**Comment by htreu** [comment]
I second @kaikreuzer's approach of being conservative about the key/value types. In our case it does not hurt much as the `activate` (read: lifecycle methods)  are anyhow only called by the OSGi runtime. Better safe then sorry.

**Comment by maggu2810** [comment]
> In our case it does not hurt much as the `activate` (read: lifecycle methods)  are anyhow only called by the OSGi runtime. Better safe then sorry.

With respect to the changes I don't see anything that is now more safe then before.


I assume I have bean clear that I don't think we need to mark the key and the value with a `@Nullable` annotation. I never seen that any of my activation methods has been called with a nullable key or value in the map and I don't think a DS implementation will start doing so some time just to break existing implementations. There is no explicit naming about "no nullable values" in the specification but as it points to the properties and AFAIK the properties cannot be null it is IMHO stated implicit.


But okay if you don't agree, it is my personal feeling.


To allow also nullable key / values does not "break" anything and sure, it makes the code more robust -- perhaps it is never needed -- but we need to add more runtime checks as before.

If you now iterate over the "entry set" of the map (so the entries that are known to exist) we need to check every key and value first if it is not null before we can use it in a safe manner.


If you decide that we don't trust the OSGi framework to call the `activate` and `modified` with non null map entries only but potential nullable ones, this should be
* added to the guidelines of correct nullable usage in ESH
* the other activation and modified methods should be corrected

It does not make any sense to state it only on that service implementation "to be more safe then sorry" but require non null members on other service implementations that are considered to be broken.

**Comment by htreu** [comment]
> properties cannot be null it is IMHO stated implicit

> that we don't trust the OSGi framework to call the activate and modified with non null map entries

Sorry, my first comment was written with a lack of the bigger picture in mind. When it comes to trust in the OSGi framework we are already on the "trust" side when keeping service references out of the null-check equation (with `NonNullByDefault({})` given).
So in general I do trust the framework to not call the lifecycle methods with null **keys**. And although the existing values in the map might considered to be none null, too, when using the map with any arbitrary key the result will be null for sure. There might be a configuration option which is unset so the configAdmin will not even know the specific key exists. So we have to guard the usage of any value from the config map with null checks. When we rely on the framework to behave nicely and state none-null on both keys and values the necessary null-check will be reported as dead code (and then be removed by accident later?).
Maybe we can go the same route as with the service references and exclude the lifecycle config maps from the null-checks completely.

**Comment by maggu2810** [comment]
> When we rely on the framework to behave nicely and state none-null on both keys and values the necessary null-check will be reported as dead code (and then be removed by accident later?).

As written above (I assume it is already known now) that is caused by missing EEAs, in that special cause because of a missing (external) annotation of the `Map`.
Adding annotations to state that something is allowed to be null just to work around that dead code warnings is wrong. The dead code warning should be removed by EEAs (and we can remove a lot of warnings then and concentrate on fixing the LOCs that are "really wrong").

**Comment by kaikreuzer** [comment]
> The dead code warning should be removed by EEAs

The dead code warnings actually derive from the fact that the class is marked with `@NonNullByDefault` - this makes the `parameters.get()` method to be evaluated as `@NonNull Object @NonNull java.util.Map.get(Object key)`. This is clearly wrong. If the `@NonNullByDefault` is removed on the class, the dead code warning disappears as the compiler does not make this false assumption anymore.

So should we actually rethink our NonNullByDefault-rule?

**Comment by maggu2810** [comment]
This is no offense, just an attempt to understand the situation now:

AFAIK this problem has been discussed from the beginning.
@trigger-telekom and me have come up with PRs that adds EEA.
The decision has been to change errors to warnings, remove warnings if possible, ...

We repeated comments about that problem multiple times.

So nothing has been changed the last months, why should we change the agreement about the null annotation usage now?

**Comment by kaikreuzer** [comment]
Sorry, maybe the reason is that I didn't follow the discussion and the effects of the decisions in all details at the time.
My understanding was that we had warnings due to the fact that we had NO annotations for 3rd party code and we configured the IDE to suppress such warnings.
I wasn't yet aware that we also accepted the fact that we see warnings due to WRONG annotations and that we did not / cannot suppress those warnings in the IDE. I do not think this is a good idea and I actually believe it is rather dangerous to have dead code warnings as they are an invitation to remove such code by accident.

But ok, it is my fault that I didn't involve myself in depth in those discussions at the time and I don't feel strong enough about it that I would want to reverse any decision that has been taken. Anyhow, this would be out of scope of this PR, so let's close it.

**Pull request closed without merging**
