### PR TITLE
Fix the handling of default elements from sitemap

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
Fix #3396 
Fix #3208 
Fix #2933 
Fix #2370 
Fix #2295

**Comment by lolodomo** [comment]
This is not yet ready for a merge, I have not yet done enough tests but after few tests, everything seems to work well now.

@resetnow : could you please take a look, especially the changes in the xlass ItemUIRegistryImpl (how I link thenew created widget with the original widget).

I have still one case with a name as widget id, so a bug remains.

**Comment by lolodomo** [comment]
I will integrate the code @sjka proposed for tje issue #3208, it's a cleaner solution.

**Comment by resetnow** [comment]
@lolodomo 

>could you please take a look

I can, of course, take a look but I'm not really familiar with server-side stuff. And, of course, API changes like the one in ItemUIRegisters should be approved by maintainers and not me :)

**Comment by lolodomo** [comment]
Fix #3476

**Comment by lolodomo** [comment]
My PR is now ready for review and merge.

I have done a lot of tests with default for switch, dimmer and player items, with default located:
* at top of a sitemap
* inside a frame at top of a sitemap
* inside a subpage without a frame around
* inside a subpage with a frame around

I also tested groups.

I tested with Basic UI, Classic UI and HABdroid.

I even improved the rendering in Classic UI in case there are not frame widgets at top level of a sitemap by adding a frame around. That is not a perfect rendering but already a big improvment compared to the previous rendering.

The 6 issues I referenced are fixed.

**Comment by lolodomo** [comment]
@kaikreuzer @sjka : please review this PR, I think I am fixing here a major issue in all UIs.

**Comment by kaikreuzer** [comment]
@triller-telekom Could you have a look, please?

**Comment by sjka** [comment]
Looks reasonable to me too.
Thanks a lot for both, implementation and testing!

**Comment by lolodomo** [comment]
Thanks for the quick review.
Is it normal that all the issues were not automatically closed ?

**Comment by triller-telekom** [comment]
The "Fixes #num" has to be in the first comment I think, otherwise I think it gets ignored by github...

**Pull request merged**
