### PR TITLE
Update a thing from the binding & Inform Handlers about linked and unlinked Channels

### PR DESCRIPTION
**Pull request by dnobel**
Added methods to update a thing from the binding.
Added methods to inform handlers about linked and unlinked channels.
Added documentation about ThingHandler implementation in general.
Removed ThingListener and used a callback for the handler instead.
Removed obsolete methods and added additional minor improvements.

Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=461874
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=456214
Signed-off-by: Dennis Nobel d.nobel@external.telekom.de

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
:white_check_mark: 
#### Eclipse validation results:
All committers passed Eclipse CLA and Signed-off-by validation.

**Comment by eclipsewebmaster** [comment]
:white_check_mark: 
#### Eclipse validation results:
All committers passed Eclipse CLA and Signed-off-by validation.

**Comment by eclipsewebmaster** [comment]
:white_check_mark: 
#### Eclipse validation results:
All committers passed Eclipse CLA and Signed-off-by validation.

**Comment by eclipsewebmaster** [comment]
:white_check_mark: 
#### Eclipse validation results:
All committers passed Eclipse CLA and Signed-off-by validation.

**Comment by dnobel** [comment]
I will update the PR, so that is merge-able and also considers the new properties.

**Comment by dnobel** [comment]
Done: Updated PR.

**Pull request merged**
