### PR TITLE
Convert IO Rest bundle to DS annotations

### PR DESCRIPTION
**Pull request by triller-telekom**
Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by sjka** [comment]
Looks good to me - let's wait for Travis

**Comment by maggu2810** [comment]
>> sjka commented 4 hours ago
> Looks good to me - let's wait for Travis

Still waiting for Travis CI...

**Comment by triller-telekom** [comment]
Damn Eclipse auto-complete feature, almost as nasty is this case as writing funny text messages on a smartphone... :(

**Comment by maggu2810** [comment]
Travis CI passed. @sjka will you approve it and agree that your requested changes are done?

**Comment by triller-telekom** [comment]
Hmm I just found this, where the configurationPid is also a `String[]`. Why does Travis not complain about it?

https://github.com/eclipse/smarthome/blob/ce45260ff4c45d42aa337b9ec3363ecb6e4d8f01/bundles/io/org.eclipse.smarthome.io.transport.mqtt/src/main/java/org/eclipse/smarthome/io/transport/mqtt/MqttService.java#L42-L43

**Comment by sjka** [comment]
Sure, thanks!

**Comment by maggu2810** [comment]
Another question about the usage of `configuration-pid`.
AFAIK it has been added in DS 1.2 and so OSGi compendium 4.3 but is missed in DS 1.1 OSGi compendium 4.2

As we still need to support 4.2 is it okay to change the configuration PID for >= 4.3 products only?
As I don't use such an old OSGi spec version it does not change anything for me, just wanted to have a look at the specifications if it changed from `String` to `String[]` some time.

**Comment by triller-telekom** [comment]
Uhoh that is indeed not nice :(

I have created a feature request for the maven-scr plugin: https://issues.apache.org/jira/browse/FELIX-5694

**Pull request merged**
