### PR TITLE
drop lazy activation of automation modules

### PR DESCRIPTION
**Pull request by maggu2810**
Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@danchom & @marinmitev I assume this is ok for you?

**Comment by maggu2810** [comment]
* <code>ping</code> @danchom
* <code>ping</code> @marinmitev

**Comment by maggu2810** [comment]
@kaikreuzer can we merge this as there are no comments?

**Comment by kaikreuzer** [comment]
Yes!

**Pull request merged**
