### PR TITLE
Update jUPnP to version 2.4

### PR DESCRIPTION
**Pull request by triller-telekom**
Needs the upcoming 2.4 release before this PR can be merged.

Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
The Karaf features needs to be changed, too.

**Comment by kaikreuzer** [comment]
There are 5 open PRs on JUPnP, which I still need to look at. I didn't plan a 2.4 release shortly, probably rather in 1-2 months.

**Comment by lolodomo** [comment]
My PR is submitted: https://github.com/jupnp/jupnp/pull/98

**Comment by lolodomo** [comment]
This will be really cool if you could build a new version with my fix in a shorter delay. It will allow users having a new cool feature with the Sonos binding.

**Comment by triller-telekom** [comment]
Closed, since the release isn't planned anytime soon.

**Pull request closed without merging**
