### PR TITLE
Removed groups from things

### PR DESCRIPTION
**Pull request by aounhaider1**
Groups are removed from things as described here https://github.com/eclipse/smarthome/issues/1014.

Signed-off-by: Aoun Bukhari <bukhari@itemis.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
I am using the Paper UI most of time to configure and control my things.
I also group my devices using the group feature of the Paper UI.
As a user point of view I don't care if this is a feature of the Paper UI only or a general concept.
I am fine to use this as a grouping for the Paper UI only.

So I do not get the point why we should remove this function from the Paper UI as long as there is no other grouping mechanism added.

**Comment by maggu2810** [comment]
As a developer point of view, I get the point that this will lead to a miss-understanding of the current internals.

**Comment by kaikreuzer** [comment]
Note that this issue is a preparation for https://github.com/eclipse/smarthome/issues/1013.
The /setup resource together with the ThingSetupManager class is something that we imho need to get rid off - it tightly couples Things/Links/Items, which definitely must not be the default behavior.

> As a user point of view I don't care if this is a feature of the Paper UI only or a general concept.

The Paper UI should only support the concepts of ESH. If the solution that you as a user are using has additional features, it is up to the solution to deal with them.

For organizing UI content, ESH has the concept of sitemaps (for which a [more modern version is under discussion](https://www.eclipse.org/forums/index.php/t/1072530/). The "control" section of the Paper UI should make use of this instead of inventing its own mechanisms (by introducing custom tags for items).

We can think of a new optional service that allows auto-creation of items for things. We can also think about having introducing a "physical location" for Things (maybe in line with https://github.com/eclipse/smarthome/issues/582), but the current item groups are functional locations and thus it is conceptionally something different that should not be mixed.

**Comment by kaikreuzer** [comment]
@maggu2810 Are you ok with merging this? It will increase the pressure to work on #1083 and others :-)

**Comment by maggu2810** [comment]
> It will increase the pressure to work on #1083 and others

Only if some of the web guys does need this and will implement the UI part.

> Are you ok with merging this?

Progress can not be stopped.

**Comment by kaikreuzer** [comment]
Thanks for rebasing!

**Comment by maggu2810** [comment]
Just to be sure:
Now I cannot use the Paper UI to add things and to control them by the control view anymore.
I can add e.g. discovered things, but in the control view I see only items of groups.
Is it correct that the only way to get items visible in the Paper UI control view using ESH bundles only is to send the REST calls myself?
Or am I missing something?

**Comment by maggu2810** [comment]
So, I don't talk about location groups or something similar.

IMHO the Paper UI miss a item configuration page where you can add new items (e.g. group items), edit the group membership of items etc.

**Comment by maggu2810** [comment]
What about the app.js entry:
```java
    }).when('/configuration/groups', {
        templateUrl : 'partials/configuration.html',
        controller : 'ConfigurationPageController',
        title : 'Configuration'
```

I think this could be removed, too.

**Comment by aounhaider1** [comment]
Yes, this route should also be removed.

**Comment by kaikreuzer** [comment]
> Yes, this route should also be removed.

So will you remove it, @aounhaider1?

**Comment by maggu2810** [comment]
I can remove it, too. It's just about removing four lines.
But I wait for a reply on the formatter question / investigation of myself before adding new PRs about the Paper UI.

**Comment by kaikreuzer** [comment]
> Is it correct that the only way to get items visible in the Paper UI control view using ESH bundles only is to send the REST calls myself?

Correct for this temporary situation, indeed.
I would hope that we soon see https://github.com/eclipse/smarthome/issues/1083 being implemented, which would be the replacement for the "groups" here.

Together with https://github.com/eclipse/smarthome/issues/1039, I would think that we can have a "simple mode", which allows you to show Things in the control ui in some default (and not individually adjustable) way (e.g. only using labels as defined on the channels, etc.).

**Comment by kaikreuzer** [comment]
> Now I cannot use the Paper UI to add things and to control them by the control view anymore.

This is now addressed by https://github.com/eclipse/smarthome/pull/1246 - so although you cannot group them (this will be possible again with https://github.com/eclipse/smarthome/issues/1083), you can again use the control ui to quickly test your Things.

**Comment by maggu2810** [comment]
Haven't tested it, but this sounds great :wink:

**Comment by kaikreuzer** [comment]
It is ;-)

**Pull request merged**
