### PR TITLE
Improved UPnP implementation to find service from correct namespace

### PR DESCRIPTION
**Pull request by paulianttila**
Signed-off-by: Pauli Anttila <pauli.anttila@gmail.com> (github: paulianttila)

### CODE REVIEW

**Comment by paulianttila** [comment]
I have a correct eclipse account, but still verification fails?

**Comment by kaikreuzer** [comment]
> I have a correct eclipse account, but still verification fails?

Did you also sign the CLA in your account? I just checked and the database claims that you have not. But maybe this is a temporary hick-up on the database, that happens sometimes...

**Comment by paulianttila** [comment]
I accidentally invalidate my CLA, but now it should be OK. Can you re-validate PR or should I make new PR ones again?

**Comment by kaikreuzer** [comment]
I have manually checked your CLA and can confirm that it is there now - so I merge this PR, thanks!

**Pull request merged**
