### PR TITLE
PaperUI cleanup and maven build

### PR DESCRIPTION
**Pull request by GradyD**
Part of cleaning up the PaperUI. It also builds the minified/concatenated files when using maven, #676.

Signed-off-by: Grady Duncan gradyduncan@gmail.com

### CODE REVIEW

**Comment by GradyD** [comment]
@sja or @aounhaider1 can you please review this? I'm still having some environment issues that make me not fully trust everything. I get a successful maven build and can tell that the gulp task is ran and when looking at the index.html I don't get any unexpected errors.

**Comment by hoegertn** [comment]
I really like the approach. Do you mind having a look at the following links for further ideas?

https://github.com/Swiip/generator-gulp-angular - Template for AngularJS projects with gulp
https://github.com/johnpapa/angular-styleguide - Styleguide for AngularJS

Regarding these pages I would recommend some changes:
- one file per controller or service
- using injection to add bower and js files to index.html during build
- use ngAnnotate before uglify step
- use "gulp serve" during development to avoid building and deploying for every change

If you are interested in some of these changes I am happy to assist. If not I still like the improvements to the build workflow.

**Comment by kaikreuzer** [comment]
@GradyD The PR shows again many additions and deletions and not many moved files. I assume that might be due to small changes in the file, which make git consider it a new one.
I wonder if (for the purpose of reviewing and history keeping) it might be better to have 2 commits in this PR - one, which only moves files and the second one which edits them. What do you think?

**Comment by GradyD** [comment]
@hoegertn thanks for the feedback. I will look into adding ngAnnotate, wasn't aware it was available.

I look into injection and I think the best method is to still pull the resources out of their bower module and into the dist folder. This allows for a much smaller and precise final package that long term we can look into shoving into jetty cache instead of having misc packages and specific files for the static.

I have not tried gulp serve and I'm not sure what would happen if you ran the frontend outside of jetty. I'm sure it would be doable to make edits and point the local test server to the jetty server but I've never done this so I'm not sure what it would take. I would love to get to the point where each module has its own JS and associatedSCSS file, this would allow for very easy targeted changes. I'm just getting started with this project and haven't actually looked at any of the JS code in detail but if you would like to start working on this I would touch base with @sja as I believe he is leading the UI. I'm not following what you were talking about with yo and scaffolding out the project.

@kaikreuzer I'm fine with doing that. I'm currently out of town so it will have to wait until this coming weekend. If I remember correctly most of the additions and deletions are with the CSS to SASS conversion. Since I deleted two CSS files I converted to SASS and created multiple SASS files for the CSS that is a good chuck of of the file changes. The CSS files had multiple 'components' in them and I broke each SCSS file into what I considered a component. So if I need to update all buttons I would look in the buttons.scss file.

I mainly want to get this change pushed it so how ever you would like, and is easiest for tracking and pushing in, I will do my best to accomplish. They are all pretty easy changes on my end especially since I've already wrote the needed code.

**Comment by hoegertn** [comment]
@GradyD 
1) I think the advantage of injection is mainly for the own JS files as the number of files will grow rapidly when using one file per controller/service/... and they should be concatenated in the build process. Injection will then switch between single files in dev and one large file in dist
2) When using injection instead of pulling the desired files from bower_components you can concatenate and minify the bower files too. So you have one app.js for your own files and one vendor.js for all deps
3) Starting the AngularJS frontend without Jetty should do no harm as it is client only. The request to the server can be proxied to avoid CORS and routing problems
4) The thing with yo was just to have starting point of a project that contains all my mentioned things. It can be build manually too

@sja what is your comment on this?

**Comment by sja** [comment]
Sorry, very busy atm. I'll review tomorrow afternoon.

**Comment by GradyD** [comment]
@Hoegertn

**Comment by GradyD** [comment]
Hey,

I agree with 1-3 but I think 4 will be more work then it will be worth. Only because we would have to do it in such a way that the current file history is tracked. I think we can keep improving the current file structure, slowly, and still keep the history.

1-3 I feel are very helpful changes. Due to the change in the build process I think 1 and 2 should be combined and 3 a separate PR. Looking at injection this AM I think it will be easy enough to add. The server proxy I think is doable and I found a few good examples but I still lack the hands on experience. If you have experience with any of this you can gladly work on any part. Let me know if you have any questions and I will be glad to assist, setting up the build environment can be tricky.

**Comment by hoegertn** [comment]
I will fork your branch and see if I get it running. Then I will start and try 1 and 2. If I run into any problems I will contact you. 3 can be done afterwards as you proposed.

Do you have any special advice for setting up the build env?

**Comment by GradyD** [comment]
Here is a link that will get you mostly setup, https://www.eclipse.org/forums/index.php/t/1073385/. It has links to install guides as well as some issues I ran into and their fixes.

The only part I have not figured out is how to build the UI changes when starting openhab2. I believe I have figured it out but am not 100% sure as I did not get a chance to try my theory before leaving town.

**Comment by kaikreuzer** [comment]
> If I remember correctly most of the additions and deletions are with the CSS to SASS conversion

Ah, ok, this explains it of course, I didn't pay attention to that.
So I leave it up to you whether it is possible / makes sense to split the PR into 2 commits to make the history better traceable. If it isn't easy, don't spend too much time on it, though.

**Comment by hoegertn** [comment]
@GradyD I implemented the steps 1 and 2 on my fork under https://github.com/hoegertn/smarthome/tree/PaperUI

If you are fine with it you can merge it into your branch and update this PR.

Step 3 will be implemented separately to keep the PRs smaller

**Comment by GradyD** [comment]
@kaikreuzer I can split them up into two but I think having them combined will be fine. Especially since I consider this more of getting the foundation created so that we can make incremental changes and easily track the history in good detail moving forward.

@hoegertn I think they should be separate PRs. Especially since you did the work. Once you open your PR just comment that this PR is a requirement before yours can be merged.

**Comment by GradyD** [comment]
I have found a bug in this PR so I'm going to close this and will create a new PR once I resolve the issue. The short of the bug is that when I concat the controllers*.js files into 1 file it appears to break the routes. 

@hoegertn just a heads up as this will probably impact your changes. When you build are you having the same error? (note I only see the errors in the console after the build is complete)

**Comment by hoegertn** [comment]
@GradyD can you check this bug on my PR. I completely reworked the file concat so 1) this bug should not be there anymore 2) your fix will be dropped by my PR anyway

**Comment by GradyD** [comment]
@hoegertn I will build against your PR tomorrow/this weekend. At first glance it appears to be fine but until I get a completed maven build I won't know 100%. 

I will say that having gulp server will be amazing as it takes 5-10 minutes per maven build right now :-1:

**Comment by hoegertn** [comment]
I will start working on gulp serve this weekend. Currently working on the UI is really painful imho.

**Comment by sja** [comment]
Ok, some words from me.

Disclaimer: I like preprocessors. So don't think that I'm a *retro-web-developer* if I say, that some of them are not good at this project.

 - **ngAnnotate**: Yes, should be definitely part of the build process, because it is backwards compatible, so you can write components with and without array syntax. And in the past it never destroyed things of mine.
 - **one file per controller/service/...** Definitely!
 - **gulp serve** Maybe. We have correct CORS headers in jetty since some month, it just has to be enabled in a cfg file. In one of my projects, I have webpack serve my content to enable stuff like Live Reload and all requests to `/rest/*` are proxied to openHAB. That works quite well, but we should keep this only as an option, because it increases the tech stack which should be kept small. The default way should be, that we disable the openHAB/jetty Cache and send headers to not cache anything in the browser and let openHAB deliver either the `web-src` or the `dist` folder. The `web-src` can only be used for dev reasons, because we'll easily reach more than 32 CSS or JS file, which is the limit for older IEs. The dist folder should contain all stuff needed, which includes the files from Bower.
 - **bower** Bower is getting more and more deprecated. Many popular Frontend-Libs are moving to npm which we should use, too. That would reduce the build time, because bower (correct me if I'm wron) most of the time clones a github repo every time you run a *bower install*. In npm >4 you have better caching mechanisms and just some files (you really need) are downloaded.
 - **SASS** I like sass, but what's the benefit here? Contributors have to learn that. If you can write SASS, you always able to write CSS. So SASS should be optional, too. Luckily gulp-sass is using libsass, so we're not in need of ruby, but it's one more build step which can produce it's own error messages and so on. So we have to think about: Pros of SASS: More DRY, shorter code and modules and the Cons: One more Build-Step, complex settings (paths, minification rules, dependencies ...), heavier for beginners.
 - **SASS vs Components** In the future, we should modularize the frontend widgets to have one folder per component like 'ColorWidget' or whatever. With that you can enhance/augment the UI with other widgets with fragment bundles. Whats the benefit of SASS then? On small and medium web projects you have one CSS context. libsass is loading all your sass files, generates one output. Here we want independent widgets. Each widget should be able to come with it's own CSS and it's own module css namespace. [See SMACKS for example](https://smacss.com/book/type-module).

Ok, that are some of my thoughts, not a review, sorry. I hope I get another time slot today to read through the code changes.

**Comment by hoegertn** [comment]
gulp serve: see #828 

bower: I agree but there any some dependencies that are not yet available via npm in the current version. I think there should be a version upgrade of node, npm and so on and then we can check which dependencies have newer versions and if they are available via npm

sass: it currently takes 150 ms to process the files and the settings should be a one time configuration which is already done. The pro of using variables and style reuse it worth the change imho

**Pull request closed without merging**
