### PR TITLE
Classic UI slider

### PR DESCRIPTION
**Pull request by sja**
Port of [PR 2792](https://github.com/openhab/openhab/pull/2792) to ESH.

This is just a quick shot, tested with demo sitemap. I saw many JS Console errors, not related to this PR, so ClassicUI needs some more sync from OH1.
But this PR should sync the slider feature from OH1 to ESH.

For the reviewer: Yes, the Logic.js is not minified. But I think it's ok here, because that should be another PR to automate this. At the moment, an ETag is used so caching should prevent performance lack.

Signed-off-by: Sebastian Janzen <sebastian@janzen.it>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Is the modification of Logic.js required? This was so far an unmodified 3rd party file (under a different license) and we only have an CQ for that, so modifiying it will mean additional efforts regarding IP clearance...

**Comment by sja** [comment]
Oh, havent seen this question. Yes, we started modifying this file because the project is not active anymore. It's maybe possible to overwrite parts of it in the browser afterwards, but that could produce many regressions.

In this PR there are only some additions for the slider, that may be able to externalize to another js file, but in the next PR there are patches for WebApp.net itself.

**Comment by kaikreuzer** [comment]
At the Classic UI is at its EOL soon and the Basic UI takes over with a more modern framework, do you think it is still worth to enhance the WebApp.Net files?

**Comment by sja** [comment]
From my technical point of view it's good to let it die. But I don't know how many people will still use ClassicUI because they like it.

By the way: Why do I merge the enhancements of OH1' classicui if it will die soon?

**Comment by kaikreuzer** [comment]
> Why do I merge the enhancements of OH1' classicui if it will die soon?

I order to not have any regression. People should be allowed to continue using the Classic UI. While they should not expect major enhancements, they should also not be confronted with features disappearing again.

**Comment by kaikreuzer** [comment]
If you are talking about pure non-functional refactorings that do not have any impact on the UX at all, there is indeed not really a need to port them. But having lots of js errors in the console is not necessarily something that I would consider "no impact".

**Comment by kaikreuzer** [comment]
> In this PR there are only some additions for the slider, that may be able to externalize to another js file

Could you do this? I think it is the easiest way to move forward as I really do not want to go into modifying 3rd party code...

**Comment by sja** [comment]
Today i started on this. Will finish tomorrow. 

Von meinem Telefon gesendet

**Comment by kaikreuzer** [comment]
Cool, thanks a lot!

**Comment by sja** [comment]
@kaikreuzer  Sorry, worked on that, but didn't found a way to get the internal Re-Render event from my external code. Have to think about that. As a result the sliders get uninitialized (dead) after page got refresh due to a longpoll event.

**Pull request closed without merging**
