### PR TITLE
added previousState method to PersistenceExtensions including tests.

### PR DESCRIPTION
**Pull request by mdbergmann**
Re-added previousState from OH1 and added some tests.

Signed-off-by: Manfred Bergmann <mb@software-by-mabe.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
There are a lot of tabs in this PR.
Have you used the ESH formatter?

**Comment by mdbergmann** [comment]
Nope. I have used a text editor, not Eclipse.
I'll convert those to spaces.

**Comment by mdbergmann** [comment]
OK, done.
How can you get the latest commit from my repo?

**Comment by maggu2810** [comment]
The PR tracks your branch, so it is already part of this PR.
For a PR it is IMHO necessary to consist of one commit only (if it will get merged).
So you have to do a squash (+rebase if necessary), before we can merge it.
But this is the last part after someone says, "do it and it will be merged" :)

**Comment by kaikreuzer** [comment]
lgtm. So unless @maggu2810 has further comments, feel free to squash and we can merge.

**Comment by maggu2810** [comment]
All fine

**Comment by mdbergmann** [comment]
Thanks

**Comment by kaikreuzer** [comment]
@mdbergmann Now you have messed up something - you should never merge the master into your branch; always only do a rebase and a force push for updating the PR. Can you try to squash the commits (or locally re-create your branch and torce push it)?

**Comment by mdbergmann** [comment]
Sorry. I'm not yet too familiar with git.
Good now?

**Comment by kaikreuzer** [comment]
Yep, thanks!

**Pull request merged**
