### PR TITLE
BasicUI: build frontend files as a part of Maven build process

### PR DESCRIPTION
**Pull request by resetnow**
Signed-off-by: Vlad Ivanov <vlad@ivanov.email>

### CODE REVIEW

**Comment by resetnow** [comment]
It's WIP because I want to see how it goes on Travis.

**Comment by resetnow** [comment]
Okay, travis fails because download.itemis.com is down and some repo is hosted there. Anyway, the build is working for me locally.

**Comment by kaikreuzer** [comment]
I can retrigger Travis.

**Comment by resetnow** [comment]
But the mentioned repo is still down, and other PRs fail too with the same error: https://travis-ci.org/eclipse/smarthome/builds/263839542

**Comment by maggu2810** [comment]
Would it make sense to move antlr-generator-3.2.0-patch.jar to our github repo similar to the third party repo?

**Comment by kaikreuzer** [comment]
I would have to dig for details, but I am sure that there was some reason, why Xtext/MWE didn't simply include this bundle in their project to host it at Eclipse, but rather prompt the user if he agrees to download it and then fetches it from externally...

**Comment by resetnow** [comment]
Forgive my ignorance but how is antrl related to BasicUI?

**Comment by kaikreuzer** [comment]
Not at all, it was just the artifact that caused the build to be red because its repo was down - but it is only required for other parts of the build, not for the Basic UI.

**Comment by resetnow** [comment]
Both of these packages are somewhere deep into the dependency chain. Updating packages listed in `package.json` to newer versions may solve the problem, but it will require new opening new CQs.

**Comment by triller-telekom** [comment]
I feared that this is the case but wanted to ask anyway ;)

One more thing I just noticed while switching branches: You should define a ".gitignore" for the auto-generated files:

```
node/
npm_cache/
web/smarthome.css
web/smarthome.js
```

**Comment by resetnow** [comment]
Updated.

**Pull request merged**
