### PR TITLE
added ConfigStatusBridgeHandler

### PR DESCRIPTION
**Pull request by tomhoefer**
Signed-off-by: Thomas Höfer <t.hoefer@telekom.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
lgtm, although it duplicates the code from the ConfigStatusThingHandler - but I wouldn't now how to elegantly avoid this.

@maggu2810 ok for you to merge?

**Comment by tomhoefer** [comment]
As long as there are no additional operations to be overwritten I think the duplication is easier than to introduce something like an additional callback impl..

**Comment by maggu2810** [comment]
If there is some time another optional interface, do we then need a ThingHandler, ConfigStatusThingHander, FooThingHandler, FooConfigStatusThingHandler, ... (same for bridge handler)?

The config.core bundle is no more optional, so wouldn't it be an option that every thing handler is a config status provider (with a dfl impl. that does nothing)?

If that is no option and you think it is better to handle it this way, then it is okay for me to merge.

**Comment by kaikreuzer** [comment]
I would hope to that the next such feature comes up once we are on Java8 and then we can have default implementations on the interface - which would make this all much easier as we would not need to create any additional abstract classes. With this in mind, I would keep the architecture as is and not introduce all dependencies in the BaseThingHandler.

**Pull request merged**
