### PR TITLE
Fixed javascript that was breaking the colorpicker.

### PR DESCRIPTION
**Pull request by 9037568**
Added to esh per request from @teichsta. See PR https://github.com/openhab/openhab/pull/4021.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@9037568 Please note that you need a CLA and to sign-off your commits, see https://github.com/eclipse/smarthome/blob/master/CONTRIBUTING.md for details.

**Comment by 9037568** [comment]
Could someone please make it harder to submit a one-line code change?
That'd be great.

I submitted a CLA. Do I need to do anything else to finish this out?


This email has been sent from a virus-free computer protected by Avast.
www.avast.com <https://www.avast.com/sig-email>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by kaikreuzer** [comment]
> Could someone please make it harder to submit a one-line code change?

My hope would be that you will do further contributions in future and this is a one time effort only.
The other option is to ask somebody else to do the code change.

> Do I need to do anything else to finish this out?

Yes, you need to [sign off your commit](https://github.com/eclipse/smarthome/blob/master/CONTRIBUTING.md#technical-considerations).

**Comment by 9037568** [comment]
Ok, I think I've got the sign-off done. Let me know if this is incorrect?

**Comment by kaikreuzer** [comment]
Well, done! Thank you for going through the formalities - the next contribution will be easier :-)

**Pull request merged**
