### PR TITLE
Refactored thing create and update mechanism through the REST API

### PR DESCRIPTION
**Pull request by kaikreuzer**
With this PR, it is now possible to update any part (incl. channels and their config) of a Thing through an HTTP PUT to `/rest/things/<uid>`. There is no need to pass the complete Thing content - fields can be left null, which will keep the existing content. Only non-null fields will replace the previous content of the Thing.

This supersedes #1087.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Note: I am not sure if all tests are passing correctly as I have some local issue (which seem not to be related though).
In any case, I'd like @cdjackson to pick this up and test it in combination with HABmin.

**Comment by cdjackson** [comment]
Fundamentally it seems to work ok. I've not given it an exhaustive test, but I can update the basic thing properties, and channel configuration ok from HABmin.

**Comment by kaikreuzer** [comment]
Thanks - I have meanwhile also fixed the tests, so all should be good now.

**Comment by kaikreuzer** [comment]
I have now also refactored the create method, so that it solves #1087 as well.
@sjka, would be good if you could also do a review.
@maggu2810 It would be great to have this merged soon as it is critical to the Z-Wave binding.

**Comment by sjka** [comment]
logically lgtm
However, placing the createThingOfType method into the registry somehow feels wrong wrt separation of concerns....

**Comment by kaikreuzer** [comment]
> However, placing the createThingOfType method into the registry somehow feels wrong wrt separation of concerns....

I agree, but please note that i only moved it from ManagedThingProvider to ThingRegistry as I felt that the ManagedThingProvider was even worse a place to have it. I thought about adding it to the ThingHelper instead, but since it needs to be a proper OSGi service, I felt that it is more pragmatic to have it in the ThingRegistry. If you think that it should be removed there completely, I would suggest to handle this in a separate PR, since the problem is not introduced by this PR either.

**Comment by sjka** [comment]
> If you think that it should be removed there completely, I would suggest to handle this in a separate PR, since the problem is not introduced by this PR either.

agreed

**Comment by maggu2810** [comment]
I assume this breaks at least the Hue binding tests (#1309).

**Comment by kaikreuzer** [comment]
Yes, it does. I will try to fix them asap.

**Pull request merged**
