### PR TITLE
Correction of Issue #1107 : Scale and Map transformation services sha…

### PR DESCRIPTION
**Pull request by clinique**
…ll return empty string when searched value not found

Signed-off-by: Gaël L'hopital <glhopital@gmail.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
Hi @clinique, there are a lot of changes caused by the formatter. That's fine, but could you point me to the "real" code change? I did not found it :wink:

**Comment by maggu2810** [comment]
Ah, found it ;)
https://github.com/eclipse/smarthome/pull/1114/files#diff-764ef6ae91ad3d60e96de380ffb51973R93

**Comment by maggu2810** [comment]
LGTM

**Comment by clinique** [comment]
You're too quick !

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
