### PR TITLE
esh should work on cp2 with portablebase64

### PR DESCRIPTION
**Pull request by Mixajlo**

### CODE REVIEW

**Comment by maggu2810** [comment]
I don't like the usage of Class.forName and optional Import-Packages.
Now the OSGi requirements for org.eclipse.smarthome.core are satisfied if I use Java 7 and no one provides the package javax.xml.bind.
I will run in CNF exceptions at runtime.

If we start to use such wrapper that handle internally the dependency that depend on the Java version, why not using two different bundles one for Java 7 and one for Java 8.
The bundle itself could use the requirement / capability OSGi methods to require a special Java version. So every bundle could provide a PortableBase64 implementation. The Java 7 bundle has a package import of javax.xml.bind and delegates the calls to this implementation and the Java 8 bundle has no special import and delegates the calls to the java.util.Base64 implementation.
This approach could be used to handle other stuff, too.
If we drop the Java 7 support some time, the change would be much simpler, as we could migrate the classes that are using the Java 8 bundle to use functions directly.

**Comment by JochenHiller** [comment]
Thanks for feedback and new PR.

> Now the OSGi requirements for org.eclipse.smarthome.core are satisfied if I use Java 7 and no one provides the package javax.xml.bind. I will run in CNF exceptions at runtime.

Thats true: assumption is that JavaSE 7 (or older) always contains javax.xml.bind package.
At least it will be reported by log messages. I thought about adding s simple Base64 implementation as fallback, not yet done, as such an implementation will look like many others in Internet, so has to be done careful to not violate IPR.

> If we start to use such wrapper that handle internally the dependency that depend on the Java version, why not using two different bundles one for Java 7 and one for Java 8.

We originally thought about that. That would make the build and distribution more complex (compiling some parts using Java 8, or compiling the whole framework with Java 8 against JavaSE 7 runtime).

> The bundle itself could use the requirement / capability OSGi methods to require a special Java version. So every bundle could provide a PortableBase64 implementation. The Java 7 bundle has a package import of javax.xml.bind and delegates the calls to this implementation and the Java 8 bundle has no special import and delegates the calls to the java.util.Base64 implementation.

That is a perfect idea. But cap/req model requires OSGi R5 at minimum which is not yet the case for all users of ESH. Minimum OSGi requirement is still at 4.2.
And: we would also need to consider to provide a fallback implementation in case of Java 7 does NOT include javax.xml.bind.

> This approach could be used to handle other stuff, too. If we drop the Java 7 support some time, the change would be much simpler, as we could migrate the classes that are using the Java 8 bundle to use functions directly.

Thats a very valid argument.

Overall I think it is a tradeoff between build/deployment complexity and runtime penalty.

@kaikreuzer any thoughts on that?

**Comment by maggu2810** [comment]
> And: we would also need to consider to provide a fallback implementation in case of Java 7 does NOT include javax.xml.bind.

Okay, if we implement that fallback, we could use it for every Java version and does not need to check for Java 8 at runtime at all.

> I thought about adding s simple Base64 implementation as fallback, not yet done, as such an implementation will look like many others in Internet, so has to be done careful to not violate IPR.

Why not using something that is already part of an Eclipse product e.g. http://download.eclipse.org/rt/ecf/3.9.1/javadoc/org/eclipse/ecf/core/util/Base64.html

**Comment by maggu2810** [comment]
> Overall I think it is a tradeoff between build/deployment complexity and runtime penalty.

That is corrrect, but a build configuration needs to be setup once. All stuff decided on runtime must be executed more frequently :wink:

**Comment by JochenHiller** [comment]
> Why not using something that is already part of an Eclipse product e.g. http://download.eclipse.org/rt/ecf/3.9.1/javadoc/org/eclipse/ecf/core/util/Base64.html

Good idea, thanks for the link. I am not an IPR expert: can we take that code and put it into ESH? I would avoid to have any build time dependencies to ECF just for that tiny class. 

@kaikreuzer If this is possible I think this would be most simple solution.

>> Overall I think it is a tradeoff between build/deployment complexity and runtime penalty.
> That is corrrect, but a build configuration needs to be setup once. All stuff decided on runtime must be executed more frequently

Yep, thats why I called it "runtime penalty". My assumption was that this call will just be used for ImageItems which is not a core use case. Even there are some test cases which did not indicate any significant performance penalty.

**Comment by kaikreuzer** [comment]
From my perspective, this PR is fine - I very much prefer to be able to keep the build as is and not having to setup an even more complex infrastructure just for this very small (and not really important) use case.

Considering that we will likely switch to Java8 in the course of this year anyhow, I consider this PR a temporary solution only.

**Comment by kaikreuzer** [comment]
@maggu2810 ok for you?

**Comment by maggu2810** [comment]
How can we track such stuff to clean it up, if we switch to Java 8 CP2 some time?
Is there a nice Github feature or can we add a NOTES.md or something similar to the source tree?

**Comment by kaikreuzer** [comment]
I am not aware of any good features in place.
The best would probably to track such things on a wiki page.
I do not like the Eclipse Wiki much, but we could consider activating the Github Wiki for ESH for such things.

**Comment by maggu2810** [comment]
> @maggu2810 ok for you?

Ok, feel free to merge.

> but we could consider activating the Github Wiki for ESH for such things.

If you activate the Wiki, I will add a page for "Java 8 CP2 cleanup".

**Comment by maggu2810** [comment]
merged myself

**Comment by kaikreuzer** [comment]
> If you activate the Wiki, I will add a page for "Java 8 CP2 cleanup".

FTR: https://bugs.eclipse.org/bugs/show_bug.cgi?id=491014

**Comment by maggu2810** [comment]
Thank you Kai

**Comment by maggu2810** [comment]
https://github.com/eclipse/smarthome/wiki/Java-8-CP2-cleanup

**Comment by kaikreuzer** [comment]
Thanks!

**Comment by Mixajlo** [comment]
Thank you all

**Pull request merged**
