### PR TITLE
Update polling example according to Coding Guidelines (scheduleAtFixe…

### PR DESCRIPTION
**Pull request by triller-telekom**
…dDelay)

Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by sjka** [comment]
Shouldn't we also adapt the existing bindings?

**Comment by triller-telekom** [comment]
`smarthome/extensions/binding [master]$ grep -rn "scheduleWithFixedRate" *` -> empty
`smarthome/extensions/binding [master]$grep -rn "scheduleWithFixedDelay" *` -> 12 matches

So at least in ESH we do not have such bindings.

**Comment by sjka** [comment]
Try `scheduleAtFixedRate` 😉

**Comment by triller-telekom** [comment]
OMG, I knew there were quite some bindings using `scheduleAtFixedRate` and I was wondering why I did not find them today. But this explains why ;-) I have adjusted the bindings in my last commit.

**Comment by triller-telekom** [comment]
close/reopen due to problems with downloading stuff from maven central

**Comment by triller-telekom** [comment]
close/reopen due to problems with downloading stuff from p2 eclipse

**Pull request merged**
