### PR TITLE
BaseThingHandler initialize() now abstract, does not set Thing to ONLINE anymore

### PR DESCRIPTION
**Pull request by triller-telekom**
The background for this PR is that a lot of new binding developers do the super call and "accidentally" set their thing to online.

Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by lolodomo** [comment]
Please don't merge this PR, **it reverts one of my recent bug fix in the Sonos binding** (bug making TTS not working). Please first rebase your code on current code source.

And does this change not break existing bindings that call `super.initialize()` ?

**Comment by lolodomo** [comment]
Replacing `super.initialize()` by `updateStatus(ThingStatus.ONLINE)` is I think not what is expected. It is at least not for the Sonos binding.

**Comment by lolodomo** [comment]
For the Sonos binding, just suppressing the call to `super.initialize()` should be correct.

**Comment by triller-telekom** [comment]
> Please don't merge this PR, it reverts one of my recent bug fix in the Sonos binding (bug making TTS not working). Please first rebase your code on current code source.

Sorry I did a rebase but messed up the merge :( I have created a new commit fixing this merge.

Regarding the change from `super.initialize()` to `updateStatus(ThingStatus.ONLINE)` is in ALL cases right because that is what `super` was doing ;) The only question is if the `ONLINE` state makes sense, i.e. some bindings set it to `OFFLINE` immediately afterwards. I am adjusting the bindings as well.

The background for this PR is that a lot of new binding developers do the `super` call and "accidentally" set their thing to online.

**Comment by lolodomo** [comment]
For Sonos, don't set to ONLINE. It is set either to ONLINE or OFFLINE.just after when trying to contact the device.

**Comment by lolodomo** [comment]
In fact, just before and not just after, by the thread created by the call to onUpdate.

I was one of the developer who has no idea that super.initialize() was setting the state to ONLINE !

Don't forget to check that this call is not inside the binding archetype.

**Comment by lolodomo** [comment]
By the way, setting status to ONLINE in replacement to super.initialize() is a secure option that will avoid regression with binding remaining in INITIALIZING state.
It is just unnecessary for the Sonos binding because I am sure about that ;)

**Comment by triller-telekom** [comment]
Thank you for your input, I have changed the Sonos Binding as you said.

Regarding the archtype, this is already OK, see [here](https://github.com/eclipse/smarthome/blob/master/tools/archetype/binding/src/main/resources/archetype-resources/src/main/java/handler/__bindingIdCamelCase__Handler.java#L53)

**Comment by maggu2810** [comment]
> The background for this PR is that a lot of new binding developers do the super call and "accidentally" set their thing to online.

Hm, this should be added to the initial comment.

The base class implementation is already abstract, so not every interface method must be implemented. Why not removing the implementation at all? It should not be necessary to mark the method abstract as a non-abstract class needs to implement all the not-yet-implemented interface methods.

I assume this will break a lot of the openHAB bindings as well. @kaikreuzer WDYT about that change?

**Comment by martinvw** [comment]
@maggu2810 a PR to fix the bindings already merged has been created and looks fine, https://github.com/openhab/openhab2-addons/pull/2506#issuecomment-319116951 . However I share your concerns even more for bindings developed outside of openHAB or pending as PR at our side, we have 72 new bindings pending.

**Comment by mjagdis** [comment]
Is the only justification, "a lot of new binding developers do the super call and "accidentally" set their thing to online."? Seriously?

The archetype's comments are ok. The original comments in the base class are ok. Your "fixes" to bindings simply replace the super call with a direct updateStatus so it's just inlining and fixes nothing that you aren't breaking yourself. Abstracting or removing the base implementation is just an API change that breaks in development and out-of-tree bindings.

If bindings *do* get it wrong raise PRs to fix *them* properly.

And be thankful that Linus doesn't do ESH/openHAB...

**Comment by triller-telekom** [comment]
I did some tests regarding the binary compatibility of this PR, turns out that unfortunately it isn't. :( Even bindings which override `initialize()` and do NOT call `super.initialize()` would be broken. I was not aware of this problem. So thank you for pointing this out.
```
10:29:24.011 DEBUG o.e.s.b.w.h.WeatherUndergroundHandler[:79] - Initializing WeatherUnderground handler.
10:29:24.011 INFO  s.e.ThingStatusInfoChangedEvent[:43] - 'weatherunderground:weather:stefansWeather2' changed from UNINITIALIZED to INITIALIZING
10:29:24.012 INFO  s.event.ThingStatusInfoEvent[:43] - 'weatherunderground:weather:stefansWeather2' updated: UNINITIALIZED (HANDLER_INITIALIZING_ERROR): org.eclipse.smarthome.core.thing.binding.BaseThingHandler.initialize()V
10:29:24.013 INFO  s.e.ThingStatusInfoChangedEvent[:43] - 'weatherunderground:weather:stefansWeather2' changed from INITIALIZING to UNINITIALIZED (HANDLER_INITIALIZING_ERROR): org.eclipse.smarthome.core.thing.binding.BaseThingHandler.initialize()V
10:29:24.038 ERROR o.e.s.c.t.i.ThingManager[:743] - Exception occurred while initializing handler of thing 'weatherunderground:weather:stefansWeather2': java.lang.AbstractMethodError: org.eclipse.smarthome.core.thing.binding.BaseThingHandler.initialize()V
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: org.eclipse.smarthome.core.thing.binding.BaseThingHandler.initialize()V
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.callAsynchronous(SafeMethodCaller.java:194)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:83)
	at org.eclipse.smarthome.core.common.SafeMethodCaller.call(SafeMethodCaller.java:67)
	at org.eclipse.smarthome.core.thing.internal.ThingManager.doInitializeHandler(ThingManager.java:728)
```

I will now change the PR in a way that I fix the bindings and change the `BaseThinghandler.initialize()` to print a warning that it should not be called. If we get reports/issues that people see this warning we can then fix the binding and eventually in the future, if we have another binary incompatible change, chnage it to be an abstract method.

**Comment by triller-telekom** [comment]
I have made this change non API breaking by marking the method as `@Deprecated` and logging a warning. Are you fine with this change now?

@maggu2810 @lolodomo @mjagdis

**Pull request merged**
