### PR TITLE
Add Photon repository to resolve xtend 2.14.0 when installing Eclipse…

### LINKED ISSUE #6249: Eclipse IDE: 2018-09
The Eclipse IDE 2018-09 has been released.
Should we consider an update (as soon as all that annoying Xtext bump related stuff is solved)?

### PR DESCRIPTION
**Pull request by htreu**
… 2018-09

Addresse #6249.

Signed-off-by: Henning Treu <henning.treu@telekom.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
I assume you should not use "Fixes" but "Related".
It does not fix the whole issue and should not auto close that issue.

**Comment by htreu** [comment]
@maggu2810 you are right. I did the PR due to my own observations that 2018-09 didn't install.

**Comment by maggu2810** [comment]
I assume you already tested that there are no conflicts if the Photon and the 2018-09 repositories are used on feature resolution.

**Comment by htreu** [comment]
I ran the full IDE install procedure w/o any problems. All projects where imported and compiled just fine after the manual tasks (maven build) finished.

**Pull request merged**
