### PR TITLE
Test framework initial contribution

### PR DESCRIPTION
**Pull request by aounhaider1**

### CODE REVIEW

**Comment by kaikreuzer** [comment]
As I have no clue about testing Javascript, this lgtm.
I'd suggest we create a request to the PMC about build+test-only dependencies.

@maggu2810 Any comments from your side?

**Comment by maggu2810** [comment]
> As I have no clue about testing Javascript, this lgtm.

Me, too.
No clue, but happy to see such a contribution.

**Comment by kaikreuzer** [comment]
I have created CQ 11708 for it.

**Comment by kaikreuzer** [comment]
CQ is approved!

**Pull request merged**
