### PR TITLE
Basic UI: fix refresh interval for image and chart

### LINKED ISSUE #3308: BasicUI: Images and Charts not updating according to Configuration
There's been a discussion in the community about images and charts not updating as expected:
https://community.openhab.org/t/basic-ui-image-refresh-rate-in-seconds-instead-miliseconds/27152

Some tests suggest that the refresh parameter is interpreted differently:
* ClassicUI: milli sec
* BasicUI: sec

**Fix**: Use same time base for all UIs

Also, in my own setup the update works only on images not on charts.
The chart initially loads in BasicUI but then instead of updating it shows a broken image symbol.

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #3308

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@resetnow : can you review please ?

**Comment by kaikreuzer** [comment]
Sorry, you'll have to rebase this one after I merged the other PR.

**Comment by lolodomo** [comment]
It was expected ;)
Merge done.

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
