### PR TITLE
automation: rule engine should be independent of the specific rule implementation

### PR DESCRIPTION
**Pull request by maggu2810**
This changes makes the rule engine independent of the specific rule implementations.

The current implementation requires:
* `RuleImpl` for `Rule`
* `ActionImpl` for `Action`
* `ConditionImpl` for `Condition`
* `TriggerImpl` for `Trigger`

After that changes the `RuleEngineImpl` uses `ManagedRule` (I don't rely on that name, just did not find a better one) instances that wrap the rule instances.
It also creates specific implementation for the used module interfaces of the rule.

### CODE REVIEW

**Comment by maggu2810** [comment]
With that changes to `RuleEngine` is independent of the specific `Rule` and `Module` (`Action`, `Condition` and `Trigger`) implementation.
The private implementations used by the public builders does not add any magic setters anymore. At least it does not make sense, as the rule engine needs to support any other implementation anyway.
The "magic" information a rule engine needs to hold for `Rule` and `Module` (`Action`, `Condition` and `Trigger`) is split of and hold by the respective `Managed...` class.
So, no need to create e.g. a new rule that holds the same information as the given rule on the time it is added to the engine. We just need to create an object that holds the additional information and holds a reference to the specific interface implementation.

**Comment by maggu2810** [comment]
ready for review

**Comment by maggu2810** [comment]
I thought about the conflict with managed providers but as it is not public API and also in the package for the rule engine only it has been okay for me (managed by the ruleengine -- the package postfix).

It is okay for me to change the name (I just did not found a better one).
`Runtime...` (for rule, module, action, condition, trigger) is okay for me,
also `Wrapped...` is okay for me.

Choose one and I will change the class names.

I don't see any option to keep the status method for the rule in the interface if it is free to be implemented. I also don't see any reason (with my current knowledge about the code base) to keep it for the rule, if it is an information that is managed by the `RuleManager`. So, simple ask the rule manager about the status.
It is not in sync with our current `Thing` infra, but ... :wink:

**Comment by kaikreuzer** [comment]
@adimova Any preference for the name? I am pretty indifferent here.

**Comment by adimova** [comment]
We should try to make the API more simple and logical instead of being driven by how it can be implemented.

- getStatus is more appropriate to be part of the Rule
- adding Managed, Wrapped, etc. just increases the complexity
- what happen with the idea - Action, Condition and Trigger to become classes again - immutable ones?
this will help us to solve #5939

**Comment by maggu2810** [comment]
Hm, as reading the code base the last weeks I would really prefer to use separate wrapper objects for the information the rule engine needs to add. We should not add information to the Rule and specific Modules just because some RuleManager implementation needs them. The current implementation is very irritating which information is written by which participant etc. We should separate information.

At least this classes are necessary as soon as interfaces or immutable base classes are used.
The connections and the inputs are changed by the rule engine so also with your third point we need to use that wrappers.

If getStatus is part of the rule, how should this be implemented?
Then a setStatus used by the rule engine must also be part of the interface / base class

**Comment by adimova** [comment]
> The connections and the inputs are changed by the rule engine

- the inputs are changed by the RuleEngine because of the auto-mapping function - this is a great example of what services the RuleManager should provide
- the connections are implementation detail and are used by RuleEngine only, so they can be moved to the RuleImpl and the Actions, Conditions and Triggers to remain untouched

> If getStatus is part of the rule, how should this be implemented?
please see how it is done in #5870

**Comment by maggu2810** [comment]
> the inputs are changed by the RuleEngine because of the auto-mapping function - this is a great example of what services the RuleManager should provide

It is a feature of the specific `RuleEngine` that is still present in this PR but does not require that a module must provide and handle changed inputs at runtime.

> the connections are implementation detail and are used by RuleEngine only, so they can be moved to the RuleImpl and the Actions, Conditions and Triggers to remain untouched

Already separated by this PR.

I assume we already agreed that the rule engine should work with every Rule implementations.
And WHY should we create a new `RuleImpl` for every provided rule if we could separate the additional information.

**Comment by maggu2810** [comment]
@kaikreuzer For me there is one remaining point: The DTO of the rule that is used to store the rule does not contain the flag that signals if a rule is disabled or enabled. If this will be added how should a rule be disabled or enabled? Should a new one be generated using the rule builder and the updated method of the managed provider (using the registry) be called?

**Comment by maggu2810** [comment]
Changed naming from "Managed..." to "Wrapped..."

**Comment by maggu2810** [comment]
Information that is managed (so changed or set) by the rule engine and only of their interest (and because it needs to be set for every implementation we cannot rely on some special base class):

* action
** module handler
** inputs
** connections

* condition
** module handler
** inputs
** connections

* trigger
** module handler

We could all that information holding to the WrappedRule but IMHO object orientated programming told us to split that information into separate classes, as small as possible and to hold that information that is necessary for their purpose.

Why do you prefer one big class?

**Comment by adimova** [comment]
Actually i do not prefer one big class but try to prevent duplicate information. Also updating the Inputs to the Wrapped module is not the desired thing but updating the inputs to the real modules in the real rule, that is added to the registry. Rule Engine uses the connections, not inputs, the inputs are needed as information to the user.

**Comment by maggu2810** [comment]
> Also updating the Inputs to the Wrapped module is not the desired thing but updating the inputs to the real modules in the real rule, that is added to the registry.

Do you want that the inputs of the modules' rule are changed and the modified rule should be persisted?
If the rule is provided by a non-managed provider, how should this rule be updated?
If the rule is added by the scriptengine, where do you want to store the modified rule?

I don't see duplicate information here. But perhaps my understanding of the inputs is wrong.
There are inputs provided by the rule's modules in a read-only manner (do we still discuss if "should work with every implementation" should be changed again?), so we need to store the modifications temporary.

**Comment by adimova** [comment]
> Do you want that the inputs of the modules' rule are changed and the modified rule should be persisted?
 
yes

> If the rule is provided by a non-managed provider, how should this rule be updated?
If the rule is added by the scriptengine, where do you want to store the modified rule?

in the registry - run-time only. As I said the RuleEngine uses the connections and does not need to store the modifications temporary.

**Comment by maggu2810** [comment]
> in the registry - run-time only

Is the Rule registry implemented different then the other registries?

AFAIK add and update of a registry requires a managed provider.
The managed provider is optional and does not need to be present.

The managed rule provider stores the rules to the storage.

How do you think the run-time only modification using the rule registry should work?

**Comment by adimova** [comment]
Thank you for the training, maybe you think I've implemented the automation module without knowing how the registers work.
And yes, the RuleRegistry works different from the other registers, otherwise it would be with the default implementation.

**Comment by maggu2810** [comment]
@adimova I used the question mark in my comments above because I would like to know your intention in more details and to learn more about your ideas.
I asked because I would like to get an explanation.

Isn't it allowed to question the automation architecture?

My understanding has been that we would like to move the whole architecture to fit the the one that is used on other places. So, if we would like a registry that acts different then I missed that point.

**Comment by adimova** [comment]
> we would like to move the whole architecture to fit the the one that is used on other places.

This can be achieved and these functions can be supported by other components, but still should be persisted or stored temporary in the registry

**Comment by maggu2810** [comment]
So, the only difference between (the current state of) the PR and your POV is that the result of the auto-mapping is not supplied to the rule registry?
Can you point me to the line of code the rule's registry takes the updated rule and checks if it could be persisted or needs to be stored temporary?
What's the real difference at runtime between my and your approach? For me the only difference is that the auto-mapping will be done on every startup and only if the rule is provided by a managed provider...

**Comment by adimova** [comment]
> Can you point me to the line of code the rule's registry takes the updated rule and checks if it could be persisted or needs to be stored temporary?

currently this mechanism is broken

> For me the only difference is that the auto-mapping will be done on every startup

this is true but the auto-mapping will change something only if there is a required input that is not connected. If the user wants to change the connection done by the auto-mapping it will need the info about it

**Comment by adimova** [comment]
in #5870 my approach is that the RuleEngine will receive and modify the same rule that is folded in the elements map of the RuleRegistry

**Comment by maggu2810** [comment]
>> Can you point me to the line of code the rule's registry takes the updated rule and checks if it could be persisted or needs to be stored temporary?

> currently this mechanism is broken

Perhaps that the reason I cannot identify such a behavior looking at the current code base. :wink:

>> For me the only difference is that the auto-mapping will be done on every startup

> this is true but the auto-mapping will change something only if there is a required input that is not connected. If the user wants to change the connection done by the auto-mapping it will need the info about it

Okay, I assume I got it, but:
If the user connects all the inputs, no auto-mapping is necessary.
If the user does not connect all the inputs, auto-mapping will be applied.
So, if the user wants to change the connection of a auto-mapped one, he can always do it, because the auto-mapping is just optional.
If I get you correctly, then you want that the user can "see" how the inputs looks like after the auto-mapping has been applied. Correct?
Is it necessary? As long as the user wants a specific connection, he can set the inputs, if he don't care, he does not need to do it.

If the current behavior of the rule registry is broken and needs to be fixed, can't this one be used at the moment and moving the logic back to the registry to be discussed in s separate issue?

**Comment by adimova** [comment]
> If I get you correctly, then you want that the user can "see" how the inputs looks like after the auto-mapping has been applied. Correct?

Correct

> Is it necessary? As long as the user wants a specific connection, he can set the inputs, if he don't care, he does not need to do it.

It is necessary because the user may want to be lazy and to connect only this input that is left unconnected or connected wrongly or maybe its assumption about auto-mapping is wrong.

> If the current behavior of the rule registry is broken and needs to be fixed, can't this one be used at the moment and moving the logic back to the registry to be discussed in s separate issue?

Ok this can be done in a separate issue. Also about duplicate information.

**Comment by maggu2810** [comment]
Still anything missing here?

**Comment by adimova** [comment]
I already agreed to merge this PR, anyone disagreed?

**Comment by kaikreuzer** [comment]
I didn't follow your discussions yesterday, so give me a moment to catch up and have a final look at the PR as well.
@maggu2810 Is [this question](https://github.com/eclipse/smarthome/pull/5942#issuecomment-407066672) still open?

**Comment by adimova** [comment]
>  Is this question still open?

yes it is but we decided to be done in a separate issue.

**Pull request merged**
