### PR TITLE
Adapted Inbox and Discovery REST resource paths to be compliant to the o...

### PR DESCRIPTION
**Pull request by dnobel**
...ther resources.

Signed-off-by: Dennis Nobel <d.nobel@external.telekom.de>

### CODE REVIEW

**Comment by dnobel** [comment]
@cdjackson Please be aware, that you need to change your REST calls after merge of this PR.

**Comment by cdjackson** [comment]
Got it - thanks.

**Comment by kaikreuzer** [comment]
thanks!

**Comment by cdjackson** [comment]
> 
> @cdjackson <https://github.com/cdjackson> Please be aware, that you need to change your REST calls after merge of this PR.
> 
For my planning purposes, when do you think this will be merged into OH2? I assume that this will be before the alpha2 (or whatever it’s called) release in late May?

**Comment by kaikreuzer** [comment]
You tell me when it will suit you best - I can do a new ESH stable release anytime!

**Comment by cdjackson** [comment]
Ah - ok. Great - maybe toward the end of this week then?

**Comment by kaikreuzer** [comment]
ok, give me a ping if I forget it.

**Comment by cdjackson** [comment]
Great - thanks Kai.

**Comment by kaikreuzer** [comment]
@cdjackson I have just published a new stable build, so it is time to adapt your REST calls!

**Comment by cdjackson** [comment]
Thanks - updated it last night so will push the changes now :)

Cheers
Chris

**Pull request merged**
