### PR TITLE
Sonos audio sink: check thing status first

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by maggu2810** [comment]
Hm, IIRC @kaikreuzer stated that a thing status is always outdated and a thing could be marked offline but gets online if some interaction is done. So with that background I don't think we should skip the play mechanism.
If I found the resp. comment, I will linkt it.

**Comment by maggu2810** [comment]
https://github.com/eclipse/smarthome/issues/2127

**Comment by lolodomo** [comment]
@maggu2810 @kaikreuzer  : The current code is checking the thing status for MP3 audio format and not for WAV audio format.
My fix consists in applying this same check whatever the audio format.
Checking the thing status or not is another question; we could decide to suppress this check.

**Comment by maggu2810** [comment]
@lolodomo You are right. It is not consistent. Missed it.
The question is, if we should introduce the check for WAV or remove it for MP3.

**Comment by lolodomo** [comment]
I let you two decide and then I will adjust my PR if the decision is to remove the check.

**Comment by kaikreuzer** [comment]
Afair, I added the check to make sure that the handler is initialized (because it otherwise might not expect calls to `playNotificationSoundURI()`.
So the correct check would actually be `handler.getThing().getStatus() == ThingStatus.ONLINE || handler.getThing().getStatus() == ThingStatus.OFFLINE`.

**Comment by lolodomo** [comment]
Test updated.

**Comment by maggu2810** [comment]
@kaikreuzer Perhaps I should update #2022 so it could be used here...

**Comment by kaikreuzer** [comment]
@maggu2810 Yes, this would be helpful!

**Comment by kaikreuzer** [comment]
@lolodomo https://github.com/eclipse/smarthome/pull/2022 is merged, so you could change your code to use the isInitialized() method now to make it slightly simpler.

**Comment by lolodomo** [comment]
I can use ThingHandlerHelper.isHandlerInitialized(handler) but I cannot use handler.isInitialized() because isInitialized() is protected.
Is it ok if I use ThingHandlerHelper.isHandlerInitialized(handler)  ?

**Comment by kaikreuzer** [comment]
Right, I forgot that we are not within a handler - yes, your solution is perfect this way, thanks!

**Pull request merged**
