### PR TITLE
Issue #698  get AutomationIntegrationTest more stable

### PR DESCRIPTION
**Pull request by BenediktNiehues**
fixes issue #698 
Signed-off-by: Benedikt Niehues <b.niehues@external.telekom.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@maggu2810 Can you test and merge, if ok?

**Comment by maggu2810** [comment]
I have build d4e124e18f263a917c2199389a82525bd7a6731b and this one succeeded.
So, don't know if this has been by accident or if #700 is invented here.

Will merge this one locally and test again.

**Comment by maggu2810** [comment]
The build succeeded on my local machine, so I will merge it.

**Comment by maggu2810** [comment]
I have realized that this PR added trailing whitespaces:
https://github.com/eclipse/smarthome/pull/701/files#diff-fc89bf30f79ed3734231b41da92fb726R407

@BenediktNiehues Could you check if your formatter is working?

**Comment by kaikreuzer** [comment]
That is a groovy file where the formatter is afaik not applied.

**Pull request merged**
