### PR TITLE
Changed ItemStateTriggerHandler to properly filter relevant topics

### LINKED ISSUE #6317: [Automation] ItemStateChangeTrigger misfires
I rely on nested groups with functions for much of my automation, and had essentially changed all my triggers over to GenericEventTriggers due to this issue, but I was wanting to use some item state change events. I've been chasing my tail on this for months, but I think I've gotten close to finding the cause.

With this item/group structure, the ItemStateChangeTrigger will fire 3 times when the item state changes... once for the item and once for each group. ItemStateUpdateTrigger does not have this issue. The group function seems to be related to the issue, and this is the simplest way I've found to reproduce the problem. I'm still looking into this, but thought I'd post it in case this is a known issue, or if one of the devs can spot something quicker than I can (very likely).

https://github.com/eclipse/smarthome/blob/master/bundles/automation/org.eclipse.smarthome.automation.module.core/src/main/java/org/eclipse/smarthome/automation/module/core/handler/ItemStateTriggerHandler.java
```
Group:Switch:OR(ON,OFF)         gTest_Parent                "Test Parent Group [%s]"             <none>   (gTest)
    Group:Switch:OR(ON,OFF)         gChild_1                "Test Child Group 1 [%s]"             <none>    (gTest_Parent)
        Switch                          Test_Switch_1        "Test Switch 1 [%s]"               <switch>    (gChild_1,gTest_Parent)
```
```
'use strict';
var log	= Java.type("org.slf4j.LoggerFactory").getLogger("org.eclipse.smarthome.model.script.Rules");

scriptExtension.importPreset("RuleSupport");
scriptExtension.importPreset("RuleSimple");

var testRule1 = new SimpleRule() {
    execute: function( module, input) {
        log.debug("JSR223: JS: Test Rule 1: [" + input['event'].itemName + "]: [" + input['event'].itemState + "]");
    }
};

testRule1.setTriggers([
    TriggerBuilder.create()
        .withId("TestTrigger1")
        .withTypeUID("core.ItemStateChangeTrigger")
        .withConfiguration(
            new Configuration({
                "itemName": "Test_Switch_1"
            })).build()
    ]);

automationManager.addRule(testRule1);
```
**Log result:**
```
2018-10-05 06:45:46.755 [DEBUG] [org.eclipse.smarthome.model.script.Rules] - JSR223: JS: Test Rule 1: [Test_Switch_1]: [OFF]
2018-10-05 06:45:46.760 [DEBUG] [org.eclipse.smarthome.model.script.Rules] - JSR223: JS: Test Rule 1: [gChild_1]: [OFF]
2018-10-05 06:45:46.780 [DEBUG] [org.eclipse.smarthome.model.script.Rules] - JSR223: JS: Test Rule 1: [gTest_Parent]: [OFF]
```
**Event.log:**
```
2018-10-05 06:45:46.740 [INFO ] [smarthome.event.ItemCommandEvent] - Item 'Test_Switch_1' received command OFF
2018-10-05 06:45:46.744 [INFO ] [smarthome.event.ItemStateEvent] - Test_Switch_1 updated to OFF
2018-10-05 06:45:46.746 [INFO ] [smarthome.event.ItemStateChangedEvent] - Test_Switch_1 changed from ON to OFF
2018-10-05 06:45:46.757 [INFO ] [smarthome.event.GroupItemStateChangedEvent] - gChild_1 changed from ON to OFF through Test_Switch_1
2018-10-05 06:45:46.771 [INFO ] [smarthome.event.GroupItemStateChangedEvent] - gTest_Parent changed from ON to OFF through Test_Switch_1
```
**Relevant lines from org.eclipse.smarthome.automation:**
```
2018-10-05 06:45:46.752 [TRACE] [org.eclipse.smarthome.automation.module.core.handler.ItemStateTriggerHandler] - ->FILTER: smarthome/items/Test_Switch_1/statechanged:Test_Switch_1
2018-10-05 06:45:46.752 [TRACE] [org.eclipse.smarthome.automation.module.core.handler.ItemStateTriggerHandler] - Received Event: Source: null Topic: smarthome/items/Test_Switch_1/statechanged Type: ItemStateChangedEvent  Payload: {"type":"OnOff","value":"OFF","oldType":"OnOff","oldValue":"ON"}
2018-10-05 06:45:46.753 [DEBUG] [org.eclipse.smarthome.automation.core.internal.RuleEngineImpl] - The trigger 'TestTrigger1' of rule '56a33ba0-0304-4232-b420-36f64302be3a' is triggered.
2018-10-05 06:45:46.755 [DEBUG] [org.eclipse.smarthome.automation.core.internal.RuleEngineImpl] - The rule '56a33ba0-0304-4232-b420-36f64302be3a' is executed.

2018-10-05 06:45:46.760 [TRACE] [org.eclipse.smarthome.automation.module.core.handler.ItemStateTriggerHandler] - ->FILTER: smarthome/items/gChild_1/Test_Switch_1/statechanged:Test_Switch_1
2018-10-05 06:45:46.760 [TRACE] [org.eclipse.smarthome.automation.module.core.handler.ItemStateTriggerHandler] - Received Event: Source: null Topic: smarthome/items/gChild_1/Test_Switch_1/statechanged Type: GroupItemStateChangedEvent  Payload: {"type":"OnOff","value":"OFF","oldType":"OnOff","oldValue":"ON"}
2018-10-05 06:45:46.760 [DEBUG] [org.eclipse.smarthome.automation.core.internal.RuleEngineImpl] - The trigger 'TestTrigger1' of rule '56a33ba0-0304-4232-b420-36f64302be3a' is triggered.
2018-10-05 06:45:46.761 [DEBUG] [org.eclipse.smarthome.automation.core.internal.RuleEngineImpl] - The rule '56a33ba0-0304-4232-b420-36f64302be3a' is executed.

2018-10-05 06:45:46.779 [TRACE] [org.eclipse.smarthome.automation.module.core.handler.ItemStateTriggerHandler] - ->FILTER: smarthome/items/gTest_Parent/Test_Switch_1/statechanged:Test_Switch_1
2018-10-05 06:45:46.779 [TRACE] [org.eclipse.smarthome.automation.module.core.handler.ItemStateTriggerHandler] - Received Event: Source: null Topic: smarthome/items/gTest_Parent/Test_Switch_1/statechanged Type: GroupItemStateChangedEvent  Payload: {"type":"OnOff","value":"OFF","oldType":"OnOff","oldValue":"ON"}
2018-10-05 06:45:46.779 [DEBUG] [org.eclipse.smarthome.automation.core.internal.RuleEngineImpl] - The trigger 'TestTrigger1' of rule '56a33ba0-0304-4232-b420-36f64302be3a' is triggered.
2018-10-05 06:45:46.780 [DEBUG] [org.eclipse.smarthome.automation.core.internal.RuleEngineImpl] - The rule '56a33ba0-0304-4232-b420-36f64302be3a' is executed.
```

### PR DESCRIPTION
**Pull request by openhab-5iver**
Resolves #6317 

Signed-off-by: Scott Rushworth openhab@5iver.com (github: openhab-5iver)

### CODE REVIEW

**Comment by htreu** [comment]
Hi @openhab-5iver, thanks for this PR.
Please notice that you need to also sign your commit with the `Signed-off-by` footer.
Additionally, in order to accept your contribution to this Eclipse project may I ask you to create an [eclipse.org](https://www.eclipse.org/) account and sign the Eclipse Contributor Agreement (ECA) [here](https://www.eclipse.org/legal/ECA.php). See [the developer docs](https://www.eclipse.org/smarthome/documentation/community/contributing.html#conventions-for-pull-requests) for detailed information.

**Comment by openhab-5iver** [comment]
First commit to ESH... should be all set now!

**Comment by htreu** [comment]
Hi Scott, thanks for signing the ECA.
As for the commit, leaving a comment on github is not sufficient. Please do the following when on your branch `patch-1`:

`git commit -s --amend` which will bring up your default editor with the previous commit message but appended you should also see the sign-off. Just save and quit the editor to rewrite the commit with the sign-off included.
Now do a `git push --force` to allow git to overwrite the remote branch (which is the base for this PR). Then also the ip-validation should be convinced.

Thanks for taking the time!

**Comment by openhab-5iver** [comment]
I had made the change right on GH, but I didn't see a way to actually sign-off on the commit. But I have a clone of the repo now. I'm sure I would have mangled something without your instruction... thank you!

**Comment by openhab-5iver** [comment]
I had set my GH email address as private, which appears to have confused the ECA verification. I've changed this, but I have doubts that it will retroactively correct anything... we'll see. I can always close this and recommit the change.

**Comment by htreu** [comment]
It's fine this way. I checked the ECA singing manually. Thanks @openhab-5iver, more contributions welcome.

**Pull request merged**
