### PR TITLE
Enhancement of Profiles with two new profile types

### PR DESCRIPTION
**Pull request by kgoderis**
“PassiveProfile" is a profile with only communication from the ThingHandler to the Item enabled, and “CommandProfile” is a profile whereby only Commands can flow between ThingHandlers and Items (but States are filtered out)

Signed-Off-By: Karel Goderis <karel.goderis@me.com>

### CODE REVIEW

**Comment by kgoderis** [comment]
@sjka huh? what happened with the Eclipse Validation? my Contributor Agreement is not expiring before 2020.

**Comment by maggu2810** [comment]
For me the profile itself are okay. If there is need for, why not adding it.
I am not sure about the chossen name, let's see about a comment of @sjka as I assume he knows most about the whole profile stuff.

**Comment by maggu2810** [comment]
> @sjka @kaikreuzer huh? what happened with the Eclipse Validation? my Contributor Agreement is not expiring before 2020.

A manual check state that there is a valid ECA for your address. So all fine.

**Comment by kgoderis** [comment]
@maggu2810 Tx. I was not sur myself about the preferred nomenklatura. The current Profiles do not exhibit a verb for example.

That being said, they are necessary for the KNX binding (in its current state), but general enough to make them System Profiles I think.

**Comment by sjka** [comment]
Generally I agree with you - the suggested profiles are "generic" enough to be put as system profiles. Still, I'm lacking a little the other use-cases apart from the generic/advanced KNX binding right now. In any case, they won't hurt having and sometimes the use-cases pop up with the availability of stuff.

Nevertheless, I don't like the name of the "passive" profile in particular, as it suggests it wouldn't be doing anything - which clearly is not the case here. Obviously, this depends on how you are looking at it. But is is confusing as it is right now. 

Problem is: I don't have a better suggestion immediately. Something like "read-only" crossed my mind (an the other one would be a "write-only" counterpart, but I'm not fully convinced either (because it still entails a point of view). Do you (or anybody else) maybe have a better idea?

**Comment by kgoderis** [comment]
@sjka what about system:inform instead of passive and system:execute instead of command ?

**Comment by kgoderis** [comment]
@sjka @maggu2810 can we push a bit ahead with this small mod? I need it rather urgently because my operational environment is in limbo because of the change in default Profile behaviour

**Comment by sjka** [comment]
Sure...

In a very rare moment of pure ingenuity (thanks for pushing this 😉 ) `system:inbound` just crossed my mind. IMHO this would match best what we want to express: It allows the communication flow only from the device/binding-side to flow into the system (and we could complement it with a `system:outbound` profile if ever needed at a later point in time). How about that?

The `system:command` profile is fine as it is, as it only allows commands and no updates in both directions. I'd leave it as it is.

**Comment by kgoderis** [comment]
@sjka ok let's do that. I will update the PR accordingly

**Comment by kaikreuzer** [comment]
Sorry to come late to the party, but I am actually a bit puzzled about the discussion here.
We mainly introduced profiles for trigger channels and having the default ones for state channels was mainly a side effect. I never thought that there should be a need to add additional ones, especially as this could lead to unexpected behavior for the bindings.

So IF there is really a need for them, I would love to learn about the use case behind it as we should make sure that we do not add features (and thus complexity) to the core framework, which simply duplicates something that can already be done with it.

So @kgoderis, with reference to the discussion in https://github.com/eclipse/smarthome/issues/4669 and #4525, why do you think those profiles are required?

**Comment by kgoderis** [comment]
@kaikreuzer Since the direct link between Bindings and Items evaporated with the introduction of Channels by the ESH framework the KNX binding can not be ported to ESH. Period.

As raised on various occasions, and discussed, for example https://github.com/eclipse/smarthome/pull/2881, https://github.com/openhab/openhab2-addons/pull/1438 and https://github.com/openhab/openhab2-addons/pull/2323, the KNX binding  due to the nature of its architecture needs to "guess" how the GA's are linked  together  in order to prevent "circular" Telegrams on the KNX bus. Since the GA's are defined at the level of Channels, and Channels are linked to Items, you *have* to know and control how Commands and States "flow" from one Channel to another (over the Items), in order to avoid the problem. As you can read from the discussions, the problem can not be solved at the level of the Binding, and even reversing the regression (https://github.com/eclipse/smarthome/issues/4669) will make  https://github.com/openhab/openhab2-addons/pull/2323 fail. Moreover, it was  https://github.com/openhab/openhab2-addons/pull/2323 that led to the creation of the system:follow (then called system:slave) Profile in the first place.  

You know, I have now developed and refactored the KNX 2.0 binding at least 3-4 times over the last 2 years. I have experimented with different solutions to overcome this problem. None of them work well. 

I seem to be ONLY person running a native ESH KNX binding in an operational environment, and I fear that unless other try to do the same, I will remain the only person shouting in the desert that the KNX binding needs a solution at the level of the framework. Either by supplying it with more information (e.g, source of Commands and States) so that I can figure out what to do by itself, or either go the way of Profiles or alike. *sigh* this has been the reason why I clearly indicated that I would cease to develop the KNX binding all together. No problem I guess, I will add some Binding specific Profiles to my edition of the KNX binding and run that until someone finally acknowledges there is an issue to solve and comes up with a solution......

**Comment by lewie** [comment]
@kgoderis 

No, you are not alone in the desert!!

Without knowing the origin, it is definitely not possible to recognize self-initiated events coming from the openHAB event bus. Only if the origin is known, the KNX binding can prevent (filter) such openHAB events from repeatedly being sent back to the KNX bus as a KNX telegram.

This realization cost me many weeks of work and testing when I wanted to make the KNX1 binding fit for openHAB2. Gave up KNX1 - It is not possible!

We all know, it is a hard stony way to a native KNX2 binding.

**Comment by tkuehne71** [comment]
Let me add a chip to the pile as well. While I am not familiar with the internal workings of the KNX binding and the Framework, let me reiterate from a User's Point of view, that the KNX binding today can run into a state where it makes the KNX bus unusable, since it Spams the bus with circular updates. Not only does this create issues with the Level of traffic, it also means that the UI will not handle setpoints for the affected items correctly (they simply get switched back to their previous state by the circular updates). As you can see from the discussion in https://github.com/openhab/openhab1-addons/issues/4547 a lot of users are running into similar Problems and are voicing their Frustration with OH2 over this.

Best,

Thomas

**Comment by sjka** [comment]
As you can see in openhab/openhab2-addons#2323, the KNX binding actually doesn't even need these profiles but can live with the system profiles perfectly well. 

The question whether events should have an origin or not is unrelated to this PR (don't get me wrong, I absolutely agree that something needs to be done in order to get the KNX 1 binding working as well). But I don't see how _this_ PR is able to solve that issue.

**Comment by kaikreuzer** [comment]
Thanks @sjka.
@kgoderis I would suggest that we have a closer look at the suggested implementation in https://github.com/openhab/openhab2-addons/pull/2323. If we all agree that this is a suitable way to model the channels and that this does not require any additional profiles, I think we could close this PR here, do you agree?

**Comment by kgoderis** [comment]
@kaikreuzer Yes, let's do that.

**Comment by kaikreuzer** [comment]
Imho, openhab/openhab2-addons#2323 works pretty well, so I would not see a need for those new profile types here right now - I'd therefore close this PR. If a new requirement comes up, we can at any time re-open it again.

**Pull request closed without merging**
