### PR TITLE
Add spotbugs to target platform

### PR DESCRIPTION
**Pull request by svilenvul**
The plugin exports annotations for FindBugs(SpotBugs).

See https://github.com/eclipse/smarthome/pull/4016#discussion_r132476289
See #3995

Signed-off-by: Svilen Valkanov <svilen.valkanov@musala.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Sorry, we cannot add this without a CQ approval.

So before creating a CQ, we need an agreement that we definitely need that. Do I get you right that those annotations are our only chance to define finegrained exceptions to our rules?

**Comment by svilenvul** [comment]
No, finegrained exceptions can be added in a filter file as well (it can filter methods in a class), but it will be a lot more difficult to maintain.

Should we discuss if we need annotations for Checkstyle and PMD as well ? Should we bring that back to https://github.com/eclipse/smarthome/issues/2437?

**Comment by svilenvul** [comment]
Actually Checkstyle and PMD support adding exceptions with comments, so annotations there should not be needed.

**Comment by kaikreuzer** [comment]
Sounds like my preferred option then 👍

**Comment by svilenvul** [comment]
OK, If  I got it right than I am going back to the filter file.

**Comment by kaikreuzer** [comment]
I was referring to "support adding exceptions with comments" as my preferred option :-)
But anything that does not introduce a new dependency for the target platform is a good solution...

**Pull request closed without merging**
