### PR TITLE
Add support for parameter groups to binding xml

### PR DESCRIPTION
**Pull request by cdjackson**
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by cdjackson** [comment]
@kaikreuzer I see there's a test failure following this merge - I don't think it's associated with this PR (??). The tests work here - although this test does seem to fail if I run it in the IDE, but it's unclear why and I don't see anything related to binding xml (it also fails in the IDE if I revert this change!)...

**Comment by maggu2810** [comment]
This one?

```text
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.automation.module.script.ScriptRuleTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.438 sec <<< FAILURE! - in org.eclipse.smarthome.automation.module.script.ScriptRuleTest
testPredefinedRule(org.eclipse.smarthome.automation.module.script.ScriptRuleTest)  Time elapsed: 1.89 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: not null
     but: was null
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:865)
        at org.junit.Assert.assertThat(Assert.java:832)
        at org.junit.Assert$assertThat.callStatic(Unknown Source)
        at org.eclipse.smarthome.automation.module.script.ScriptRuleTest$_testPredefinedRule_closure12.doCall(ScriptRuleTest.groovy:130)
        at org.eclipse.smarthome.automation.module.script.ScriptRuleTest$_testPredefinedRule_closure12.doCall(ScriptRuleTest.groovy)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:39)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
        at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy:181)
        at org.eclipse.smarthome.test.OSGiTest.waitForAssert(OSGiTest.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
        at org.eclipse.smarthome.automation.module.script.ScriptRuleTest.testPredefinedRule(ScriptRuleTest.groovy:129)


Results :

Failed tests: 
  ScriptRuleTest.testPredefinedRule:129->OSGiTest.waitForAssert:-1->OSGiTest.waitForAssert:181 
Expected: not null
     but: was null

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by maggu2810** [comment]
> I don't think it's associated with this PR 

I don't think so, too.

**Comment by kaikreuzer** [comment]
No, this is unrelated - at least this build was just green: https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/

**Pull request merged**
