### PR TITLE
BasicUI: disable value capitalization by default, add condensed layout

### PR DESCRIPTION
**Pull request by resetnow**
This is a combination of 2 commits:

* BasicUI: disable capitalization by default, fixes openhab/openhab2-addons#653 
    
    It's now optional, disabled by default and can be enabled back with: 
    `org.eclipse.smarthome.basicui:capitalizeValues=true`
* BasicUI: add condensed layout option
    
    Some users wanted to be able to fit more elements on the screen, this should help
    `org.eclipse.smarthome.basicui:condensedLayout=true`

Signed-off-by: Vlad Ivanov <vlad-mbx@ya.ru>

### CODE REVIEW

**Comment by maggu2810** [comment]
If not tested the UI themselves (e.g. visibility changes if condencedLayout css is included) but the code changes themselves looks good to me.

**Comment by kaikreuzer** [comment]
Thanks, looks nice, I especially like the new condensed layout :-)

Two remarks: 
- Could you please also add the new config parameters to https://github.com/resetnow/smarthome/blob/basicui-css-classes/extensions/ui/org.eclipse.smarthome.ui.basic/ESH-INF/config/config.xml?
- There is a problem with the positioning of the Map widget in the condensed layout, see here:
bildschirmfoto 2016-02-09 um 14 10 10

**Comment by resetnow** [comment]
Done.

**Comment by kaikreuzer** [comment]
Hm, now the map is not rendered at all anymore. In the Javascript console, I am getting:
```
Uncaught URIError: URI malformed
embed-7a3b74a89a41b03456c00b95dfc81dc2cb837513b16722e0ca90bbff4f955add.js:5
```
Any idea?

**Comment by resetnow** [comment]
I'll look into it later today, but this script belongs to the map service.

**Comment by resetnow** [comment]
I don't have this problem: 
screenshot from 2016-02-13 18-44-55

**Comment by kaikreuzer** [comment]
Ok, sorry, it was my mistake - for some reason, I didn't have the DemoLocation set and hence it didn't render a map. 
All is fine, thanks!

**Pull request merged**
