### PR TITLE
made DMX thing handler tests independent of the framework

### PR DESCRIPTION
**Pull request by sjka**
[This](https://travis-ci.org/eclipse/smarthome/builds/348722721?utm_source=github_status&utm_medium=notification) Travis failure made me finally have a closer look at the thing handler tests of the DMX binding. And that inspired me to turn them from framework integration tests into plain unit tests, focusing on the handler code itself. This should make them less timing sensitive and make them run quicker.

The bridge handler tests were out-of-scope in this PR. 

Signed-off-by: Simon Kaufmann <simon.kfm@googlemail.com>

### CODE REVIEW

**Comment by J-N-K** [comment]
Please also see my last commit in #5150. I‘ll have a closer look at your implementation tomorrow.

**Comment by sjka** [comment]
Argh, thanks for pointing this out - I indeed wasn't aware of it and haven't expected this from the title. Good that the overlap is small. I'm happy for feedback, improvements and further suggestions. And if you want to take it over that would be fine by me too. I have no strong feelings about this at all 😄

**Comment by sjka** [comment]
Just for the record: here is another failed build: https://ci.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/2552/testReport/junit/org.eclipse.smarthome.binding.dmx/DimmerThingHandlerTest/testPercentTypeCommand/

**Comment by J-N-K** [comment]
LGTM. After this is merged, I'll rebase my PR and adapt some more tests.

**Comment by kaikreuzer** [comment]
Merged!

**Pull request merged**
