### PR TITLE
Fix #2321: LIFX resend on packet loss, configurable power on brightness and code refactoring

### LINKED ISSUE #2321: LIFX commands sometimes not executed due to UDP packet loss
In the current LIFX implementation commands may not be succesfully executed due to UDP packet loss. As a result bulbs do not turn on/off or change to the correct color. In my setup it occurs quite often since I have a lot of bulbs that are motion activated. Sometimes I end up in a completely unilluminated room which is quite annoying.

I think the binding should:
- keep track of the most recently sent state change that was made with a `SetLightPowerRequest` or `SetColorRequest`
- resend the most recent state change when no `StatePowerResponse` / `StateResponse` for a state change request is received within a certain interval

Futhermore:
- the number of such retries should be limited
- the retries should disregard the online/offline state of bulbs
- it should still be possible to change the state of bulbs using other applications such as the LIFX app

Do you have any thoughts on this @kgoderis? I might also put in my own PR for this.

### PR DESCRIPTION
**Pull request by wborn**
This PR addresses the issue/functionality discussed in #2321 by:
- resending packets that change light power/color when they are not acknowledged after 250ms (max 3 retries)
- adding a channel configuration option to customize the power on brightness level

The binding code has been refactored by decomposing the `LifxLightHandler` into several objects:
- communication related logic has been extracted into the `LifxLightCommunicationHandler`
- a `LifxLightState` object has been introduced for keeping track of the current and pending light state
- the reoccuring task to update the current light state has been extracted into `LifxLightCurrentStateUpdater`
- the reoccuring task to determine the online/offline state has been extracted into `LifxLightOnlineStateUpdater`
- the logic for sending/resending packets to change the light state has been extracted into `LifxLightStateChanger`

The refactoring also includes:
- addition of the `LifxResponsePacketListener` interface, which allows implementors to listen to response packets received by the `LifxLightCommunicationHandler`
- addition of the `LifxLightStateListener` interface, which allows implementors to listen to changes of the current and pending light state
- addition of a thread pool

Other notable improvements include:
- fix of another deadlock scenario by always following the same locking strategy, this is the reason why the locks required for sending a packet have all been moved to `LifxLightCommunicationHandler.sendPacket(Packet packet, InetSocketAddress address, SelectionKey selectedKey)`
- packets are now send/resend using the thread pool, this makes it already possible to concurrently send commands to lights without the implemenation of #2221 (i.e. #2082 can also probably be closed)
- warnings are no longer logged in case of every packet loss (only when the 3 retries fail)
- lights are also powered on when changes are made on the temperature channel
- when there is a pending light state change, updating channels is only done when packets are received that match the pending light state
- due to the introduction of the pending light state, sending multiple commands in quick succession (HSB followed by temperature change) will now correctly update the light state

@kgoderis do you want to review my changes? @kaikreuzer could perhaps have a look at the new `powerOnBrightness` channel configuration? I've also made some remarks in a [#2321 comment](https://github.com/eclipse/smarthome/issues/2321#issuecomment-256198907) about this new option.

### CODE REVIEW

**Comment by kgoderis** [comment]
@wborn Wouter, this looks very GTM. That a lot! I tested the code on 3 bulbs only and it works pretty smooth from a functional point of view. ESH and the LIFX app are nicely in sync, and indeed the switch-on delay between bulbs is gone.

I have not yet looked at the code in detail, the only thing that is maybe of concern is that it requires Java 1.8 whereas we come from 1.7. AFAIK, ESH should stick to 1.7. Your only dependency on 1.8 lies in java.util.function.IntUnaryOperator, maybe you have an alternative for that class?

**Comment by wborn** [comment]
@kgoderis thanks for already having a quick look! I'll find a fix for that. :-)

**Comment by kaikreuzer** [comment]
Err, this isn't just some refactoring, this rather looks like a fully new binding :-)
The `powerOnBrightness` looks good to me, thanks.
As it is more than 1000 lines, I actually have to create a CQ for it and have it approved by the IP team.
@wborn let me know once you are ok to freeze this PR, since after creating the CQ there must not be any changes here anymore.

**Comment by wborn** [comment]
Yes I've completed working on this PR @kaikreuzer so you can freeze it. The first comment and further commits should explain what has changed and why. Extracting existing logic away from the `LifxLightHandler` will certainly have added up a lot to those line counts. The `LifxLightCommunicationHandler` logic already makes up for 530 lines alone.

**Comment by kgoderis** [comment]
@kaikreuzer The real changes are indeed rather limited, and it LGTM. Hopefully we can get this PR approved rapidly.

**Comment by kaikreuzer** [comment]
Ok, thanks - I have created CQ 12202 and waiting for its approval now.

**Comment by kaikreuzer** [comment]
Good news, we have check-in approval for this PR!

**Pull request merged**
