### PR TITLE
Fixes startup and reload behaviour of DSL rules

### PR DESCRIPTION
**Pull request by kaikreuzer**
- Make sure that only loaded rule resources are used.
- When items are changed, notify the rule engine that all rules are reloaded.

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Fixes #2117, which was introduced by the Xtext upgrade a while ago.

**Comment by maggu2810** [comment]
Without learning Xtext I assume I cannot understand the real impact of using e.g. eResource method instead of the eIsProxy method.
As this PR does not break anything but the DSL rule behaviour itself if it is not working and I assume you have tested the changes, should we wait for further comments or merge ASAP?

**Comment by kaikreuzer** [comment]
You cannot even understand it after learning Xtext/EMF, trust me ;-)
I would tend to say that it at least makes stuff better and not worse and therefore it should be merged.

**Comment by igorrobertifoc** [comment]
Hello,
I updated with the nightly build on
https://openhab.ci.cloudbees.com/job/openHAB-Distribution/ws/distributions/openhab-offline/target/apt-repo/

but it give me the same error. Is the patch updated?

Thank you

**Comment by kaikreuzer** [comment]
Better try the zipped distro to make sure there is nothing left from an earlier install.

**Pull request merged**
