### PR TITLE
Java 8

### PR DESCRIPTION
**Pull request by maggu2810**
Related to: #2926

### CODE REVIEW

**Comment by maggu2810** [comment]
@kaikreuzer The HIPP provides only
* jdk1.7.0-latest
* jdk1.6.0-latest
* jdk1.5.0-latest

Can you request support for `jdk1.8.0-latest`, too?

IMHO the PR itself is ready.

**Comment by maggu2810** [comment]
IMHO the PR itself is ready.
We can switch to Java 8 on Hudson in front of this merge.

Wait for your ack.

**Comment by maggu2810** [comment]
Hm, I don't think that we need to keep the separate commits.
If you squash the commits, perhaps you could edit the message to contain a summary of the stuff that has been done, like this one:

```
Java 8 (#3049)

* set tycho version to latest release
* update execution environment
* set Java version for Maven
* update Eclipse classpath to use Java 8
* update documentation for Java 8
* bump maven compiler plugin
* bump maven plugin for groovy eclipse
* add Xtext and Tycho source (target) version
* remove inherited stuff
* update Eclipse JDT preferences for Java 8
* fix groovy compiler level
* change setup for Java 8

Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>
```

So we don't loose the "logical" changes that has been done.

**Comment by kaikreuzer** [comment]
Hm, it seems the Wemo tests have a problem with Java 8 - since this PR has been merged, they are failing constantly. I am just wondering, why it had passed on Travis?

**Comment by maggu2810** [comment]
I can't believe that the Wemo tests have a problem with Java 8.
I assume that the Wemo tests are perhaps a little bit unstable or timing dependent and the switch to Java 8 and the build time behaviour of the Hudson caused the error. 😉 

I will give it a try in the Eclipse IDE on my machine as well, but perhaps the author of the tests could have a look at, too.

**Comment by kaikreuzer** [comment]
I tried it on Hudson 3 times in a row and all failed. I even had the same issue when running the build locally...

**Comment by kaikreuzer** [comment]
> perhaps the author of the tests could have a look at, too.

@svilenvul Could you have a look at https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/lastCompletedBuild/testReport/? Maybe you have an idea what causes the issue.

**Comment by maggu2810** [comment]
I run the Wemo tests on my machine now:
* Eclipse IDE and Java 8: passed
* Maven and Java 8: passed

**Comment by maggu2810** [comment]
I did reset hard to eclipse/master and a git clean (-x -d -f).
After that I started a full build.

```text
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:22 min
[INFO] Finished at: 2017-02-24T14:45:37+01:00
[INFO] Final Memory: 610M/1355M
[INFO] ------------------------------------------------------------------------
```

It seems that there is something wrong, but at least not completely broken.
Hm, ...

**Comment by maggu2810** [comment]
Continues here: #3070

**Pull request merged**
