### PR TITLE
fix resource leak

### PR DESCRIPTION
**Pull request by maggu2810**
The datagram socket must be closed.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Err, this class is actually dead code and should be removed. The hue binding uses an UPnPDiscoveryParticipant for discovery and not this class (which came in from the formerly external library).

Are you ok to remove it or do you actually use it?

**Comment by maggu2810** [comment]
I don't use it. I just realized that there is a resource leak. If we could remove the whole class without loosing functionality this is okay for me to.

**Comment by maggu2810** [comment]
done

**Comment by kaikreuzer** [comment]
Much better - this change is definitely free of bugs ;-)

**Pull request merged**
