### PR TITLE
Fixed fragment properties overwriting.

### PR DESCRIPTION
**Pull request by jwausle**
Signed-off-by: winter <winter@itemis.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
It seems the formatter has not been applied (at least on the java files).
There are mixed spaces and tabs, we are using braces also for one liners (after if) etc.

**Comment by kaikreuzer** [comment]
@jwausle Please do not use any prefixes like [QSDK-5365] in PRs and commits on ESH.
Please comment as soon as you have addressed the remark about the formatting above. Rest looks good to me (but I didn't test it myself).

**Comment by sjka** [comment]
@jwausle ping

**Comment by jwausle** [comment]
Replaced this pull-request with https://github.com/eclipse/smarthome/pull/2068.
-   same change 
-   with updated commit-message and java-file format.

**Pull request closed without merging**
