### PR TITLE
mqtt transport: fix reconnect and improve producer handling

### PR DESCRIPTION
**Pull request by maggu2810**
I started playing around with the mqtt transport.
I kept the commits separate, so you could check them separately.

style only:
* The first one applies the ESH clean up (remove trailing whitespaces).
* The second cleans up manual line breaks in the javadoc. The formatter does not remove manual line breaks, but I cleaned it manually and started the clean up again - so all fine.

feature:
* The third commit adds a method to the interfaces (consumer / producer) that informs the implemented clcass about the current state of the connection.
After a broker connection is established it is a common case to transmit the current state of all items, to inform subscribers about the current state (and guarantees that not a state change keeps not transmitted). 

bugfix:
* The fourth commit fix a connection problem. If a connection is established and lost later, a reconnect will be done automatically. If the connection could not be established in the handling of the update method of the MqttService, the connection will never established again. So let's call the normal retry mechanism so it will be retried later.

### CODE REVIEW

**Comment by maggu2810** [comment]
A comment to the added feature (callback to inform about connection state changes):
- we could create an enum with different connection states (connected, not connected) and change the function name to setConnectionState
- we could keep the interfaces unchanged and add a new one e.g. MqttConnectionObserver that contains a method setConnectionState (and add a add/removeConnectionObserver to the MqttService).
IMHO the connection state information is a requirement for a consumer / producer, but perhaps it would be better to keep it as it is and create a new one.

**Comment by maggu2810** [comment]
* Do you need some more information?
* Should I split the bug and the feature?
* Should I create a bug report in the eclipse bugzilla first?

**Comment by maggu2810** [comment]
Other PRs are opened and merged in the meantime, this one gets no comment at all.
Could you please give a comment if the priority of mqtt is to low to be reviewed at the moment or something similar. If there is no interest I could fork the bundle and send a pull request if you need it.
But then I could stop to wait for some comments at all.

**Comment by kaikreuzer** [comment]
Sorry @maggu2810 for not having responded yet - I am doing what I can, but I have many PRs in the queue, not only here, but also at openHAB 2. This is no excuse of course.

MQTT is code that I personally do not know yet, so it means for me some more effort to get into it to assess your suggested changes. As it was written by @dvanherbergen, maybe he is interested to have a look as well?

In general, I think it is a good idea to rather submit smaller PRs, i.e. not mixing features and fixes in a single one (but I do not ask you to do it for this one now). And yes, the Eclipse workflow suggests that there should also be a bugzilla issue for each PR. If any PR is urgent for you, please also mention this directly in a comment, otherwise processing time of a few weeks might occur (please note that this is the absolutely normal case for all PRs with > 1000 lines as you will notice with the console refactoring).

**Comment by dvanherbergen** [comment]
Hi Markus,
Just a minor remark: when looping over the list of consumers/producers to set the state, it might be better to put a try/catch block around each set. This way, if an error occurs setting the state in one of the producers/consumers, it won't block others from getting their status update.

**Comment by kaikreuzer** [comment]
Looks all good to me - as you have cleanly separated commits, there is not even a need to squash them.
Let me know if you want to implement Davys suggestion, afterwards we can merge.

**Comment by maggu2810** [comment]
I kept this all in one branch as all affected the mqtt transport and I need all of that changes.
As you already stated, I tried to keep the commits separated for their functionality.
I confirm that different branches would be better to merge.
Thanks also to Daavy, you are right, exceptions in the producers / consumers code should be caught, so the does not influence other code.
I will implement this little changes next week.
Best regards, happy Easter.

**Comment by maggu2810** [comment]
I changed the commit that introduced the "setConnected" callback.
I kept the MQTT message consumer and producer interface at it was before this PR.
I added a new interface (connection observer) that contains the setConnected callback function definition.
The caller of the setConnected callback uses now a try/catch block so the exception is logged (trace only) and does not influence some other logic.

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
