### PR TITLE
[1352] Eclipse SmartHome RaspBee binding

### PR DESCRIPTION
**Pull request by fatihboy**
Binding to support RaspBee shield which brings ZigBee connectivity to
Raspberry Pi added. RaspBee binding is a fork of Hue binding with
modifications to work with RaspBee.

Bug: https://github.com/eclipse/smarthome/issues/1352
Signed-off-by: fatihboy fatih@enterprisecoding.com

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=1352

**Comment by kaikreuzer** [comment]
That's cool, many thanks!
This is now for the first time a situation, where the same "Thing" is available through two different bridges and thus require different handler implementations.
Have you tried to think about a possibility on how we could avoid duplicating a lot of code, but rather share it between the hue and the RaspBee binding? I am a bit concerned that we might have a lot of effort to keep the implementations in sync (see e.g. https://github.com/eclipse/smarthome/pull/673).

@sjka, @afuechsel, @tomhoefer Any good idea from you guys how this could be dealt with?

**Comment by tomhoefer** [comment]
I don´t have any good idea. But of course we should not duplicate the code...

Some ideas:
- Introduce hue common bundle for main classes like state converters, base bridge handlers, light handlers etc
- copy thing type defintion from common bundle to hue and rasbee bundle and change the binding id

**Comment by kaikreuzer** [comment]
I remember that I had a similar discussion for the AVM binding. The problem is really that if you have different bridges, you potentially also have completely different functionality exposed.
So I could imagine that the RaspBee binding could provide much more information about Philips hue devices than the hue bridge itself, since more details are available if being accessed directly via Zigbee.

So although the physical device is identical, from a software perspective it can potentially look very different. Hence it might be indeed best to treat it as a separate binding, especially if we expect that the functionality might diverge in future.

@fatihboy I didn't look in detail into the code yet - but if it is not only the thing type XMLs, but also a lot of Java code that you have copied, we should nonetheless look having the hue binding exposing the required classes and your binding using them whereever possible.

**Comment by tomhoefer** [comment]
does the raspbee bridge replace the hue bridge?

**Comment by kaikreuzer** [comment]
Yes, it is a board that directly speaks Zigbee with the bulbs, so no need for an IP-bridge.

**Comment by tomhoefer** [comment]
ok... 

> we should nonetheless look having the hue binding exposing the required classes and your binding using them whereever possible

Of course, this would work. But do you think this is a good idea? Even the HueBridgeHandler and the RaspBeeBridgeHandler or the HueLightHandler and RaspBeeLightHandler are almost the same. So at the end we would have to modify all handlers if there are any changes.

**Comment by fatihboy** [comment]
I'm totally agree with @kaikreuzer 

Classes and things mostly shared; but at the end they are two different bridges from two different manufacturer. Somehow they may decided to change the way it works, expose different API's i.e.

Also Hue bridge 2.0 doesn't support 3rd party devices any more, at least that's what I know. So RaspBee would have additional things that Hue wouldn't. Actually, they already have;

- https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/fls-a-lp/?L=1
- https://www.dresden-elektronik.de/funktechnik/solutions/wireless-light-control/wireless-ballasts/?L=1

think about any 3rd party ZLL compatible bulb also.

On the other hand, as @tomhoefer stated; currently, RaspBee mostly mimics a recent Hue API. That's why it's easy to port. We could, also, use shared classes (base classes i.e.) and go on till one of the manufacturer publishes an incompatible API. 

Since I'm also the developer of jRaspBee library used by RaspBee binding, I will try to expose compatible API'si like Jue.

**Comment by kaikreuzer** [comment]
> Even the HueBridgeHandler and the RaspBeeBridgeHandler or the HueLightHandler and RaspBeeLightHandler are almost the same.

So maybe an abstract parent class can be extracted, but I think it would be pragmatic to put it in the hue binding and not create a new shared bundle for it.

> Also Hue bridge 2.0 doesn't support 3rd party devices any more, at least that's what I know.

No, Philips very quickly [reverted that decision](http://www.techhive.com/article/3015992/connected-home/philips-hue-bridges-wont-block-third-party-lightbulbs-after-all-after-fierce-backlash.html).

**Comment by tomhoefer** [comment]
> So maybe an abstract parent class can be extracted, but I think it would be pragmatic to put it in the hue binding and not create a new shared bundle for it

ok for me although there would be a dependency from one binding to another .... but we can start with this pragmatic idea...

**Comment by kaikreuzer** [comment]
> although there would be a dependency from one binding to another

Hm, right, I didn't think of that (that if you only want RaspBee that you also automatically have support for hue)... So also fine for me to create a shared bundle.

**Comment by tomhoefer** [comment]
I think this will result in a clean solution

**Comment by maggu2810** [comment]
What category (it is not a UI, not really a transport, not a binding itself, only shared code) should be used for such a shared bundle?

**Comment by maggu2810** [comment]
IMHO a separate bundle that contains the shared code is the correct approach.

**Comment by kaikreuzer** [comment]
It should imho also be in extensions/bindings next to the bindings that use it (and there is no use case for anyone else).

**Comment by kaikreuzer** [comment]
@fatihboy What do you prefer how to proceed? I am also fine with keeping the code duplicated for a start and to see how things evolve - it just means that the RaspBee binding won't directly benefit from any evolution of the hue binding and that it needs to be maintained independently.

**Comment by fatihboy** [comment]
@kaikreuzer shared library would be better way to go, I'm ok with it also. But there are a couple of points that needs to be separate only; things definitions i.e. (supported things could be different). I'm ready to modify raspbee binding; as soon as shared libs are ready.

**Comment by kaikreuzer** [comment]
>  as soon as shared libs are ready.

The problem here is that nobody is working on such "shared libs" and there are other refactorings of the hue binding on the way (like https://github.com/eclipse/smarthome/pull/673), which would likely get into conflicts.

Therefore I think it might be after all the best idea to keep the RaspBee binding like this for now and refactor later on...

**Comment by fatihboy** [comment]
@kaikreuzer I'm ready to maintain Raspbee binding independently; I'm fine with it.

**Comment by kaikreuzer** [comment]
ok, thanks - I'll then try to have a closer look soon then and I will need to create CQs to have the Eclipse IP team approve it as well.

**Comment by fatihboy** [comment]
With the latest Raspbee firmware installed, Raspbee mimics Hue Api through port 80 (which is default port for Hue). Also latest bits of hue binding have better described thing types (grouped by light properties exposed, instead of brands etc...). So, with default raspbee settings, you could use Raspbee with Hue binding shipped with OpenHab 2 b4.

With the latest hue binding bits, its seems that, there is no reason to have a seperate binding for Raspbee.

**Comment by kaikreuzer** [comment]
Hi @fatihboy, sorry for not coming back to this PR any time earlier. Indeed, I was first waiting for the refactoring of the hue binding to be finished, which is by now the case.

I would think that the RaspBee binding should be changed in the same way (supporting generic types instead of individual models), which would make maintenance much easier.

I leave it up to you whether you want to close this PR and go with the "hue bridge emulation" integration instead; this would obviously be less work for you, but from an integration perspective, it is less optimal and might add constraints on us and the users. E.g. there is no decent way to support motion detectors and switches yet through the hue binding/bridge, since all that can be done is to poll, which imho does not make much sense for such devices. Having a native RaspBee integration that immediately forwards the Zigbee events to ESH would clearly be much better. I also wonder about HA (i.e. non-ZLL) devices, which cannot be used through the bridge emulation.
Is this something you have in scope as well?

Another thought: Maybe it would be worth to think about a "low-level" integration in the [ZigBee binding efforts](https://github.com/openhab/openhab2-addons/pull/779) of @cdjackson and have the RaspBee board be one of the supported hardwares?

**Comment by kaikreuzer** [comment]
@fatihboy Any opinion on how to proceed?

**Comment by sjka** [comment]
@fatihboy Looks like you decided to abandon this here, right? Then I'd suggest to close this PR.

**Comment by kaikreuzer** [comment]
Agree, it can be re-opened anytime :-)

**Pull request closed without merging**
