### PR TITLE
[MQTT] Updated Readme

### PR DESCRIPTION
**Pull request by JueBag**
Corrected Item syntax and added a note about the difference syntax when creating the things via PaperUI or files.

Signed-off-by: Juergen Baginski opus42@gmx.de

### CODE REVIEW

**Comment by JueBag** [comment]
I have no idea how that "ip-validation" check could be passed. The user "noreply@github.com" is mentioned in the details?????

**Comment by JueBag** [comment]
Changed it, but that doesn't seem to trigger the check again.

**Comment by davidgraeff** [comment]
You didn't change the actual commit, only the description here on github. You need to `git --amend -s` and `git push -f` (force change push).

**Comment by JueBag** [comment]
Once again "git magic",  since I did this change on the browser I have to did a bit deeper for that.

**Comment by davidgraeff** [comment]
I have done successfully validated commits on the webeditor, too. It's possible. But you need to add this `Signed-off-by: Juergen Baginski <opus42@gmx.de>` line at the end of the commit message. Would be so nice if Github had a checkbox to tick.

**Comment by JueBag** [comment]
All that just because I did remember to SignOff, my mistake was to use the signature that worked back in 2016 (while creating the Tankerkönig binding). 
I did have much trouble with git back then also!
It looks to me now that I changed the actual commit using Source Tree, however looking from the browser it doesn't show. I'm (again) out off ideas, if it would be easy to drop/delete all those and make a new I would do it!

Sorry for all that, THANKS for all the help and a big THANK YOU for the new mqtt binding !

**Comment by davidgraeff** [comment]
I'm not using source tree. You need to look for a push (with force) option in that GUI.

**Pull request closed without merging**
