### PR TITLE
[core] Removed access to ConfigDescriptionValidator from BaseThingHandler

### PR DESCRIPTION
**Pull request by cweitkamp**
- Moved `ConfigDescriptionValidator` from `BaseThingHandler` to `ThingHandlerCallback`
- Removed `ThingTypeRegistry` from `BaseThingHandler`

I crawled ESH / OH2 bindings for usage of the `configDescriptionValidator` and `thingTypeRegistry` but none of them uses the services in other ways.

In the light of #5182.

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by htreu** [comment]
Thanks @cweitkamp for continuing on this topic!
Unfortunately the ZigBee and zWave bindings currently depend on the `thingTypeRegistry` from the BaseThingHandler. See this comment https://github.com/openhab/org.openhab.binding.zigbee/pull/169#issuecomment-397444985 and discussion. Until there is an alternative found I guess it has to stay there.

/cc @cdjackson & @kaikreuzer

**Comment by kaikreuzer** [comment]
@htreu For Zigbee, I already clearly said that we must get rid off that dependency.
ZWave would be left as the only bad citizen and in order to avoid a massive code change on that binding, we could nonetheless simply slightly change it to get the `thingTypeRegistry` in the ThingFactory and pass it to the handler via the constructor. This way, we can merge this PR, keep the framework clean and avoid others to accidentally use it.

**Comment by cdjackson** [comment]
It’s really not so nice to remove this sort of thing with no alternative. I think it would be worth updating documentation somewhere to make it clear that it is NOW not allowed to use this. There are other threads on the forum where this IS the recommended approach and that is why both ZWave and ZigBee were implemented like this maybe 3 years ago!

**Comment by htreu** [comment]
@cdjackson would you agree that from a coding pov the intermediate solution @kaikreuzer suggested would be feasible? Let the thingTypeRegistry be injected to the HandlerFactory and pass it on via constructor.
We will in addition document, that bindings must not use it, so we are clear on this side as well. wdyt?

**Comment by kaikreuzer** [comment]
> There are other threads on the forum where this IS the recommended approach

Sorry, that is a misunderstanding see https://github.com/openhab/org.openhab.binding.zigbee/pull/169#issuecomment-401066950.

**Comment by cdjackson** [comment]
Ok, but we discussed adding binding specific information to the thing XML files for this purpose here-:

https://www.eclipse.org/forums/index.php/m/1690582/#msg_1690582 <https://www.eclipse.org/forums/index.php/m/1690582/#msg_1690582>

If that wasn’t meant to be read through the registry, then the whole discussion was a bit pointless as there’s no other way to get it?

**Comment by kaikreuzer** [comment]
No, see again https://github.com/openhab/org.openhab.binding.zigbee/pull/169#issuecomment-401066950:

>  What was discussed is to have information stored in the Thing XMLs that is required by the handlers - and they get this information through the Thing instance, without the need to access the Thing registry.

**Comment by cdjackson** [comment]
I don’t believe that this is inline with the discussion we had was about discovery at the time (there were many ongoing discussions). Anyway, I will remove this, but as said I think there should be an alternative provided sooner rather than later.

**Comment by maggu2810** [comment]
In some proprietary code that mix binding and other logic I already need to use some of the stuff that is not intended to be used by bindings...
Injection that stuff into the thing handlers using the thing handler factory is a very easy approach and an one time effort.
So I would prefer to keep the framework clean and use that WAR in the respective bindings as long as another perhaps cleaner by the framework supported solution is available.
I don't think that one or two bindings (with full respect to your work @cdjackson, don't get me wrong) should prevent the framework from cleanups.
@cdjackson Regardless if this has been wrongly discussed three years ago, can't you add the WAR @kaikreuzer pointed out above? If you use a custom class for stuff the thing handler factory injects into the thing handler it is also very simple to add or remove stuff without touching all the handler implementations in your binding again...

**Comment by cweitkamp** [comment]
Thank you all.

I offer my help too. Give me a hint if I shall give you a hand.

**Pull request merged**
