### PR TITLE
Implement hashCode and equals in PointType

### PR DESCRIPTION
**Pull request by watou**
Bug: https://github.com/eclipse/smarthome/issues/663
Signed-off-by: John Cocula <john@cocula.com>

### CODE REVIEW

**Comment by watou** [comment]
(I did in fact sign the Eclipse CLA last month.)

**Comment by kaikreuzer** [comment]
Did you possibly sign the CLA with a different email address than john@cocula.com?

**Comment by hakan42** [comment]
If I read the hashCode() method correctly, you seem to assume latitude can be only two digits and then altitude gets mixed in. The same for longitude. 

Could you add some unit tests that prove / make certain that fractional degrees are handled properly? For example, a location that is at 48.1234 North, 11.5678 East should have a different hashCode to 48N11E

**Comment by watou** [comment]
@kaikreuzer I signed with john@cocula.com and I just checked to verify that it reports as on file under that email address.  "The CLA we have on record for you will expire on 2018-11-19". I did however just add my (optional) github ID to my account settings.  Perhaps that was needed?

@hakan42 the `hashCode` method is using the `BigDecimal` hash codes, not their decimal values, so it should be OK.

**Comment by kaikreuzer** [comment]
@watou, you can check yourself at https://projects.eclipse.org/user/cla/validate.
The CLA is independent from your github id in the account, so that does not make a difference. Maybe try to withdraw the CLA and re-sign it?

**Comment by watou** [comment]
Well that was strange, in that my account showed a valid CLA and yet the lookup tool didn't find it.  I have withdrawn and re-signed the CLA, and now the lookup tool finds me.

**Comment by kaikreuzer** [comment]
That's IT - shutdown and restart and it works ;-)

**Comment by watou** [comment]
Thank you, Kai. ;-)

**Comment by maggu2810** [comment]
Didn't we want to use blocks also for one-liner?

**Comment by maggu2810** [comment]
I have created #667 and will try to create a PR.

**Pull request merged**
