### PR TITLE
#2485 Sonos notification sound: restore the same volume …

### PR DESCRIPTION
**Pull request by ivivanov-bg**
… for all group members

When saving the current volume - retrieve the data from current player handler and not from the coordinator

Signed-off-by: Ivaylo Ivanov <ivivanov.bg@gmail.com>

### CODE REVIEW

**Comment by lolodomo** [comment]
Make sense...
I will test it and give a feedback soon.

PS: what is an adhoc group ? Is it a standard group of several Sonos devices ?

**Comment by lolodomo** [comment]
LGTM

Tested and working well.
I cannot test with Sonos pairs but it is working well with standalone Sonos and group of Sonos.

**Comment by ivivanov-bg** [comment]
'adhoc' group is a normal group of sonos devices, which is not a Stereo Pair or 5.1 (the latter ones are 'bonded' group)

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
