### PR TITLE
Fixed bug 474990: adding console commands to clear and remove items

### PR DESCRIPTION
**Pull request by sjka**
I have added commands to clear and remove items.

Bug: 474990
Signed-off-by: Simon Kaufmann <simon.kfm@googlemail.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=474990

**Comment by maggu2810** [comment]
Couldn't we brake the backward compatibility?
It would be stricter to do so.

**Comment by sjka** [comment]
I guess we actually can - just didn't want to upset anybody.
Objections anybody?

**Comment by kaikreuzer** [comment]
No objection from me, since I do not consider the console commands to be part of any real API that would be broken.

**Comment by sjka** [comment]
okay, I removed the compatibility part

**Comment by dnobel** [comment]
Thanks!

**Pull request merged**
