### PR TITLE
[core / expiring-cache] Add Nullable annotations & add new constructor

### PR DESCRIPTION
**Pull request by martinvw**
Add Nullable annotations & add new constructor

The current semi annotated implementation gives problems when combining with completely annotated classes, this solves the problem and makes sure work arounds are not needed. 

It seems that it does not break backwards compatibility but please let me know when it does,.

CC: @cweitkamp @maggu2810 @triller-telekom 

See also: 

https://github.com/openhab/openhab2-addons/pull/4182#discussion_r230594545
https://github.com/Hilbrand/openhab2-addons/pull/1

### CODE REVIEW

**Comment by cweitkamp** [comment]
@martinvw We had the very same idea (see #6482). And both failed with the unit tests.

**Comment by martinvw** [comment]
> @martinvw We had the very same idea (see #6482). And both failed with the unit tests.

hehe, it felt like reading my own PR except for the constructor ;-)

**Comment by cweitkamp** [comment]
> hehe, it felt like reading my own PR except for the constructor ;-)

I will fix the test and you add the constructor?

**Comment by martinvw** [comment]
> > hehe, it felt like reading my own PR except for the constructor ;-)
> 
> I will fix the test and you add the constructor?

In your branch, or shall I just create a new PR if yours is merged?

**Comment by cweitkamp** [comment]
> In your branch, or shall I just create a new PR if yours is merged?

What ever you prefer.

**Comment by martinvw** [comment]
I should be home and ready in half hour so I will create a PR against your
branch 👍

Op do 8 nov. 2018 om 20:12 schreef Christoph Weitkamp <
notifications@github.com>

**Comment by martinvw** [comment]
Closing in favor of https://github.com/eclipse/smarthome/pull/6482

**Pull request closed without merging**
