### PR TITLE
improve testing

### PR DESCRIPTION
**Pull request by maggu2810**
* remove Require-Bundle in favour of Import-Package
* bump Tycho
* use new dependency resolution for Tycho
* for Tycho bump there are two things that are improved / solved for
  testing:
  * https://wiki.eclipse.org/Tycho/Release_Notes/0.21
    (INCOMPATIBLE CHANGE) In case you have used test-runtime only
    dependencies in the tycho-surefire-plugin configuration, you may need
    to replace them with
    target-platform-configuration/dependency-resolution/extraRequirements
    instead. See bug 436617 comment 11 for details.
  * https://wiki.eclipse.org/Tycho/Release_Notes/0.22
    Tycho Surefire was updated to use Maven Surefire version 2.17. This
    enabled us to consume the fix for long-standing bug 369266

https://bugs.eclipse.org/bugs/show_bug.cgi?id=476024
Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
I tested the build using a clean environment, so I hope there are no failures.

<pre>
git clean -x -d -f
git reset --hard HEAD
rm -rf /home/maggu2810/tmp/delete
mvn -Dmaven.repo.local=/home/maggu2810/tmp/delete install
</pre>

All went fine, ...

**Comment by maggu2810** [comment]
I read this one: https://github.com/eclipse/smarthome/pull/379/files
Have we to add a version range to all imports?

**Comment by maggu2810** [comment]
Will test build at home, too. Please wait for merge until I know it runs successfully.

**Comment by maggu2810** [comment]
Hm, it is working using "mvn clean install", but it is not working, if I do a "mvn install" without a clean.
Could someone help?

**Comment by dnobel** [comment]
I can also test it later today. 

One question: Why did you remove all the static imports for assert?

**Comment by maggu2810** [comment]
Summary:
* <code>mvn clean install</code> works all the time
* <code>mvn install</code> on the root git directory: some test fails

The intention was not to remove the static imports, the changes (that results in removing static import, caused by auto import feature of Eclipse ID) have been done to remove junit.framework.Assert.

* junit.framework package is the legacy namespace used with Junit v3 and older versions
* org.junit is the new namespace used by JUnit v4

**Comment by dnobel** [comment]
> mvn install on the root git directory: some test fails

On the current master mvn install works on my machine. Usually we execute mvn clean install. But I just want to understand, if it is a problem of your fix. Can you build the current master with mvn install and check if the tests also fail?

> The intention was not to remove the static imports, the changes (that results in removing static import, caused by auto import feature of Eclipse ID) have been done to remove junit.framework.Assert.

Can we change it back to static import to "org.junit.Assert" then? Because I think it is more readable.

> Have we to add a version range to all imports

The problem was that in some other targetplatforms there also was JUnit 3.x. Then it resolved against this version and it didn´t work. Do the tests also run in Eclipse with your changes?

**Comment by maggu2810** [comment]
> But I just want to understand, if it is a problem of your fix.

I want to understand this, too.
Thank you for testing!

> Can you build the current master with mvn install and check if the tests also fail?

Will test that.
* <code>mvn clean install</code> works
* <code>mvn install</code> works

> Can we change it back to static import to "org.junit.Assert" then? Because I think it is more readable.

Whatever you want. ;-)
I Will change it after the "install without clean" problem is identified.
Will do it then for every Assert in all tests.

> The problem was that in some other targetplatforms there also was JUnit 3.x.

Ok! Also, if we know, that it will not work with JUnit 3.x and we need at least JUnit 4.x the version range is (IMHO) a must. Have to do it without such questions. Sorry ;-)


I have a new idea.

To be able to bump Tycho (we will perhaps to do it some time) we have to change the test POMs, caused by the incompatible changes for the surefire plugin (I linked it in my commit message).

I will first (for testing) split my changes in two parts, kept the Manifest as it is and just change the POMs. So we can identify it the failure was triggered by the changed Manifest (version constrait, require bundle, ...) or it the POMs are wrong.

Will post my results.

**Comment by maggu2810** [comment]
I changed only the POMs => failure.

The Tycho bump and the test POM changes are wrong or raise a bug:
https://github.com/maggu2810/smarthome/commit/b18f1d36b10897f1e6a558c2c568877e5bcf789d

Will have further inspection, if you see something, show it to me. ;-)

* clean install works
* install withotu clean raised for example this error

<pre>
$ cat /home/rathgeb/bin/pkgs/eclipse/smarthome-master-2/git/smarthome/bundles/config/org.eclipse.smarthome.config.core.test/target/work/configuration/1441268881152.log
!SESSION 2015-09-03 10:28:00.979 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_80
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -application org.eclipse.tycho.surefire.osgibooter.headlesstest -testproperties /home/rathgeb/bin/pkgs/eclipse/smarthome-master-2/git/smarthome/bundles/config/org.eclipse.smarthome.config.core.test/target/surefire.properties
Command-line arguments:  -data /home/rathgeb/bin/pkgs/eclipse/smarthome-master-2/git/smarthome/bundles/config/org.eclipse.smarthome.config.core.test/target/work/data -application org.eclipse.tycho.surefire.osgibooter.headlesstest -testproperties /home/rathgeb/bin/pkgs/eclipse/smarthome-master-2/git/smarthome/bundles/config/org.eclipse.smarthome.config.core.test/target/surefire.properties

!ENTRY org.eclipse.equinox.ds 1 0 2015-09-03 10:28:02.259
!MESSAGE Could not bind a reference of component ConfigDescriptionRegistry. The reference is: Reference[name = ConfigDescriptionProvider, interface = org.eclipse.smarthome.config.core.ConfigDescriptionProvider, policy = dynamic, cardinality = 0..n, target = null, bind = addConfigDescriptionProvider, unbind = removeConfigDescriptionProvider]

!ENTRY org.eclipse.swt.win32.win32.x86_64 2 0 2015-09-03 10:28:02.430
!MESSAGE Could not resolve module: org.eclipse.swt.win32.win32.x86_64 [100]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.ws=win32) (osgi.os=win32) (osgi.arch=x86_64))"


!ENTRY org.eclipse.swt.gtk.linux.x86 2 0 2015-09-03 10:28:02.431
!MESSAGE Could not resolve module: org.eclipse.swt.gtk.linux.x86 [97]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.ws=gtk) (osgi.os=linux) (osgi.arch=x86))"


!ENTRY org.eclipse.swt.win32.win32.x86 2 0 2015-09-03 10:28:02.431
!MESSAGE Could not resolve module: org.eclipse.swt.win32.win32.x86 [99]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.ws=win32) (osgi.os=win32) (osgi.arch=x86))"


!ENTRY org.eclipse.swt.cocoa.macosx.x86_64 2 0 2015-09-03 10:28:02.431
!MESSAGE Could not resolve module: org.eclipse.swt.cocoa.macosx.x86_64 [101]
  Unresolved requirement: Require-Capability: eclipse.platform; filter:="(& (osgi.ws=cocoa) (osgi.os=macosx) (osgi.arch=x86_64) )"


!ENTRY org.eclipse.osgi 4 0 2015-09-03 10:28:02.431
!MESSAGE Application error
!STACK 1
org.eclipse.core.runtime.CoreException: Plug-in org.eclipse.tycho.surefire.junit4 was unable to load class org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:176)
        at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
        at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
        at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:191)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: java.lang.ClassNotFoundException: Can not load a class from a fragment bundle: org.eclipse.tycho.surefire.junit4_0.23.1 [103]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:561)
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
        ... 16 more
</pre>

**Comment by maggu2810** [comment]
I compared the config.ini for the OSGi Framework running the tests (using "clean install" and "install"). The OSGi bundles used for running the test differs.

I could use this approach to further define the extraRequirements for the special test cases.

https://eclipse.org/tycho/sitedocs/tycho-surefire/tycho-surefire-plugin/plugin-info.html
The goal launches an OSGi runtime and executes the project's tests in that runtime. The "test runtime" consists of the bundle built in this project and its transitive dependencies, plus some Equinox and test harness bundles. The bundles are resolved from the target platform of the project. Note that the test runtime does typically not contain the entire target platform. If there are implicitly required bundles (e.g. org.eclipse.equinox.ds to make declarative services work), they need to be added manually through an extraRequirements configuration on the target-platform-configuration plugin.

https://wiki.eclipse.org/Tycho/Packaging_Types#eclipse-test-plugin
Tests typically fail if implicit dependencies are missing, e.g. if your bundle or a referenced bundle makes use of declarative services, but there is no explicit reference to the bundle org.eclipse.equinox.ds. The same problem can occur when your users install your bundles with p2. Therefore it is a good idea to make the implicit dependencies of your bundles explicit through the feature used to ship your bundles, e.g. by adding a dependency to org.eclipse.equinox.ds in the feature. Configuring this feature in the tycho-surefire-plugin configuration should then also make the test runtime complete.

Last but not least, I still prefer to do this change. Sometime we will have to bump Tycho for other reasons and then the test configuration is already working.

**Comment by maggu2810** [comment]
Will create a new one, if it is solved.

**Comment by maggu2810** [comment]
Reference to the new PR: #439

**Pull request closed without merging**
