### PR TITLE
Activates NamesAreUniqueValidator for Rules and Sitemaps

### PR DESCRIPTION
**Pull request by planger**
Bug: 423511
Change-Id: I9facb48060d403acd97530bc4ff5ffa2266ab75b
Signed-off-by: Philip Langer <planger@eclipsesource.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Two questions while testing this:

- On any rule file I know get two entries of 
```
Duplicate JvmIdentifiableElement '<unnamed>'	demo.rules	/config/config/rules	line: 0 
Duplicate JvmIdentifiableElement '<unnamed>'	demo.rules	/config/config/rules	line: 0 
```
- Creating two sitemaps demo1.sitemap and demo2.sitemap with "sitemap demo label="Main Menu""
as a first line does not give me any validation errors. I would have supposed that this PR means that I should get an error?

Thanks,
Kai

**Comment by planger** [comment]
Hi Kai,

I'll come back to this in the end of the week again in detail. Until then my quick answers would be:
  * I didn't get these entries, but I'll recheck that. Thanks for pointing that out.
  * The NamesAreUniqueValidator only checks for uniqueness of names within the configured scope. If I'm not mistaken, the scope currently used is always a single file. So only duplicates within the same file are annotated with an error marker at this point. If we want to check for duplicates among all .items files within the items folder, I can look into that again and make the adaptations.

Thanks and best wishes,
Philip

**Comment by kaikreuzer** [comment]
Hi Philip,

Thanks for the feedback. If the unique validator only works within a file, the change for the sitemap does not make any sense (or at least does not have any effect), does it?

**Comment by kaikreuzer** [comment]
@planger Any news on this?

**Comment by planger** [comment]
Hi Kai,

I'm very sorry for the delay. I was on vacation and -- as always -- the time before and after the vacation is a bit crazy and I wasn't able to work on this project... I'll try to come back to this asap. Hopefully end of next week.

**Comment by kaikreuzer** [comment]
> Hopefully end of next week.

Which next week exactly? ;-)

**Comment by kaikreuzer** [comment]
@planger Any news?

**Comment by planger** [comment]
I'm very sorry for the delay! Didn't find time to pursue on this topic. I'm not sure if I get back to it before Christmas, but I'll try to address this right after the holidays. Sorry again!

**Comment by kaikreuzer** [comment]
> but I'll try to address this right after the holidays

I'd love to have as long holidays as you @planger!

**Comment by kaikreuzer** [comment]
Closing due to inactivity.

**Pull request closed without merging**
