### PR TITLE
Handle item add/update/remove events

### PR DESCRIPTION
**Pull request by aounhaider1**
fixes https://github.com/eclipse/smarthome/issues/2871
Signed-off-by: Aoun Bukhari <bukhari@itemis.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@sjka For you to review as you entered the bug :-)

**Comment by sjka** [comment]
Hmmm, I see some really strange behavior. At first, I thought it's not working at alle, but then I noticed it is somehow always "one behind". I.e. if I change the item label from test1 to test2, nothing happens. If I change it from test2 to test3, the UI shows "test2". Can you please check what's going on?

**Comment by aounhaider1** [comment]
I could not reproduce this issue. There is obviously a delay of 2-4 seconds until the event arrives but paperUI is updating the item immediately after that. I've put the item update to next digest cycle, that should fix any weird issue regarding scope update.

**Comment by triller-telekom** [comment]
I have tested it with Firefox, Chromium and Opera, all browsers automatically show an added or removed item immediately.

**Comment by sjka** [comment]
indeed, must have been an issue with my project setup.
lgtm

**Pull request merged**
