### PR TITLE
increase xtext version range for IDE setup

### PR DESCRIPTION
**Pull request by R-Edelhoff**

### CODE REVIEW

**Comment by maggu2810** [comment]
Signed-off-by line is missing

**Comment by maggu2810** [comment]
Does this one solve the IDE update failure?
```text
Executing startup tasks
Product org.eclipse.products.epp.package.java.latest.released
Project org.eclipse.smarthome.core.master
Bundle org.eclipse.oomph.setup 1.3.0.v20151107-1225, build=1923, branch=8359c49a92734051d767cf7c2d0b8c8d16961b51, commit=8359c49a92734051d767cf7c2d0b8c8d16961b51
Bundle org.eclipse.oomph.setup.core 1.3.0.v20151017-0515, build=1923, branch=8359c49a92734051d767cf7c2d0b8c8d16961b51, commit=8359c49a92734051d767cf7c2d0b8c8d16961b51
Bundle org.eclipse.oomph.setup.git 1.3.0.v20151017-1318, build=1923, branch=8359c49a92734051d767cf7c2d0b8c8d16961b51, commit=8359c49a92734051d767cf7c2d0b8c8d16961b51
Bundle org.eclipse.oomph.setup.jdt 1.3.0.v20150923-0945, build=1923, branch=8359c49a92734051d767cf7c2d0b8c8d16961b51, commit=8359c49a92734051d767cf7c2d0b8c8d16961b51
Bundle org.eclipse.oomph.setup.launching 1.3.0.v20150923-0945, build=1923, branch=8359c49a92734051d767cf7c2d0b8c8d16961b51, commit=8359c49a92734051d767cf7c2d0b8c8d16961b51
Bundle org.eclipse.oomph.setup.p2 1.3.0.v20151016-1206, build=1923, branch=8359c49a92734051d767cf7c2d0b8c8d16961b51, commit=8359c49a92734051d767cf7c2d0b8c8d16961b51
Bundle org.eclipse.oomph.setup.pde 1.3.0.v20150923-1022, build=1923, branch=8359c49a92734051d767cf7c2d0b8c8d16961b51, commit=8359c49a92734051d767cf7c2d0b8c8d16961b51
Bundle org.eclipse.oomph.setup.projects 1.3.0.v20150923-0945, build=1923, branch=8359c49a92734051d767cf7c2d0b8c8d16961b51, commit=8359c49a92734051d767cf7c2d0b8c8d16961b51
Bundle org.eclipse.oomph.setup.targlets 1.3.0.v20151030-0735, build=1923, branch=8359c49a92734051d767cf7c2d0b8c8d16961b51, commit=8359c49a92734051d767cf7c2d0b8c8d16961b51
Bundle org.eclipse.oomph.setup.workingsets 1.3.0.v20150923-0945, build=1923, branch=8359c49a92734051d767cf7c2d0b8c8d16961b51, commit=8359c49a92734051d767cf7c2d0b8c8d16961b51
Performing P2 Director (Eclipse IDE for Java Developers (Mars))
Offline = false
Mirrors = true
Resolving 33 requirements from 8 repositories to /home/maggu2810/bin/pkgs/eclipse/smarthome-master/eclipse
Requirement org.eclipse.wst.xml_ui.feature.feature.group
Requirement org.eclipse.m2e.feature.feature.group
Requirement org.eclipse.m2e.logback.feature.feature.group
Requirement org.eclipse.xtend.sdk.feature.group [2.8.4,2.8.4]
Requirement org.eclipse.xtext.sdk.feature.group [2.8.4,2.8.4]
Requirement org.eclipse.emf.mwe2.language.sdk.feature.group [2.8.0,2.9.0]
Requirement org.eclipse.emf.mwe2.runtime.sdk.feature.group [2.8.0,2.9.0]
Requirement org.eclipse.emf.mwe.core.feature.group [1.3.2,1.3.3]
Requirement org.eclipse.emf.mwe.sdk.feature.group [1.3.2,1.3.3]
Requirement org.codehaus.groovy.eclipse.feature.feature.group
Requirement org.sonatype.tycho.m2e.feature.feature.group
Requirement org.eclipse.emf.sdk.feature.group
Requirement org.eclipse.mylyn.java_feature.feature.group
Requirement org.eclipse.mylyn.bugzilla_feature.feature.group
Requirement org.eclipse.mylyn.hudson.feature.group
Requirement org.eclipse.mylyn.git.feature.group
Requirement org.eclipse.pde.feature.group
Requirement org.eclipse.wst.jsdt.feature.feature.group
Requirement org.eclipse.wst.web_ui.feature.feature.group
Requirement epp.package.java [4.5.0,4.6.0)
Requirement org.eclipse.platform.feature.group [4.5.0,4.6.0)
Requirement org.eclipse.rcp.feature.group [4.5.0,4.6.0)
Requirement org.eclipse.jdt.feature.group [3.11.0,3.12.0)
Requirement org.eclipse.oomph.setup.feature.group
Requirement org.eclipse.oomph.targlets.feature.group
Requirement org.eclipse.oomph.setup.targlets.feature.group
Requirement org.eclipse.oomph.setup.jdt.feature.group
Requirement org.eclipse.oomph.setup.git.feature.group
Requirement org.eclipse.egit.feature.group
Requirement org.eclipse.oomph.setup.workingsets.feature.group
Requirement org.eclipse.oomph.setup.projects.feature.group
Requirement org.eclipse.oomph.setup.pde.feature.group
Requirement org.eclipse.oomph.setup.launching.feature.group
Repository http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-tycho/0.7.0/N/0.7.0.201309291400/
Repository http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/
Repository http://download.eclipse.org/modeling/emf/emf/updates/milestones/
Repository http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/
Repository http://download.eclipse.org/technology/epp/packages/mars
Repository http://download.eclipse.org/releases/mars/201510021000
Repository http://download.eclipse.org/oomph/updates/milestone/latest
Repository http://download.eclipse.org/egit/updates
Adding repository http://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-tycho/0.7.0/N/0.7.0.201309291400/
Adding repository http://download.eclipse.org/modeling/emf/emf/updates/milestones/
Adding repository http://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/
Adding repository http://dist.springsource.org/snapshot/GRECLIPSE/e4.5/
Adding repository http://download.eclipse.org/technology/epp/packages/mars
Adding repository http://download.eclipse.org/egit/updates
Adding repository http://download.eclipse.org/releases/mars/201510021000
Adding repository http://download.eclipse.org/oomph/updates/milestone/latest
Calculating requirements and dependencies.
Cannot complete the request.  Generating details.
ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:413)
  at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:325)
  at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:710)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3025)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:2969)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4149)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4143)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4141)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2960)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2935)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2829)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:552)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:671)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1449777384424
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: artificial_root 1.0.0.v1449777384424 requires 'org.eclipse.xtend.sdk.feature.group [2.8.4]' but it could not be found

Took 31 seconds.
There are failed tasks.
Press Back to choose different settings or Cancel to abort.
```

**Comment by kaikreuzer** [comment]
Yes, exactly. Unfortunately, the CLA check seems to be broken - I do not get clearance for this. So I guess the quickest solution is to close it and I create one myself. Give me a sec...

**Comment by kaikreuzer** [comment]
Replaced by https://github.com/eclipse/smarthome/pull/719

**Pull request closed without merging**
