### PR TITLE
[WIP] add bluetooth transport and BLE binding

### PR DESCRIPTION
**Pull request by maggu2810**
This changes are based on a PR based by Chris Jackson.

Related to: https://github.com/eclipse/smarthome/pull/551

### CODE REVIEW

**Comment by maggu2810** [comment]
WRT to the discussion to use the same license header on all files, I don't know why this files are using this line:
```text
Copyright (c) 1997, ${year} by Huawei Technologies Co., Ltd. and others.
```

**Comment by cdjackson** [comment]
This header was added well before the discussion on single headers.

What is the difference between this and my previous PR?

**Comment by maggu2810** [comment]
No logic in the code has been changed.

* merge conflicts has been solved
* the Eclipse SmartHome clean up rules has been applied (so also the formatter, etc)
* the XML formatter has been applied
* the pom files has been cleaned up
* the versions has been fixed
* the bluetooth.bluez - dbus references has been set upped correctly
* trailing whitespaces has been removed

**Comment by cdjackson** [comment]
Ok, thanks - I’ll try and see if I can resolve the changes some time over the coming days if I can get time.

**Comment by cdjackson** [comment]
@maggu2810 do you mind if we close this and reopen the original PR please - it would be easier for me at least and if you've not changed anything it seems better to me.

**Comment by maggu2810** [comment]
Sure, done.
It just seems you have no time and I tried to do it for you.

**Comment by cdjackson** [comment]
Thanks - the issue is I have updated this already as I changed this to be a single (example) binding based on a single device (the Yeelight) and it seems better to start with that than the older branch.

I'll try and push an update over the coming days - worst case I'll just push the last version I did.

**Comment by maggu2810** [comment]
@cdjackson Are there API changes compared to the current version of your old PR?
I would like to create a binding that uses Bluetooth. Can I start with the current code base or should I wait for your update?

**Comment by cdjackson** [comment]
I’ll push my latest changes later today - it’s probably best to work from that although I don’t think there’s API changes - more tidying up.

Note that you need to be using a recent BlueZ - depending on your Linux, you will likely need to update (standard Debian/Ubuntu will not work).

**Comment by maggu2810** [comment]
@cdjackson Thanks, will wait for your push.

> Note that you need to be using a recent BlueZ

Thanks for pointing that out.
I am already using the most recent release (5.43) on my Linux machine.
Is the stuff we need available in that release (29th October 2016) or should I use a snapshot of bluez?

**Comment by cdjackson** [comment]
I think 5.43 should be fine.

The update I’ll push removes a bunch of stuff from the main BLE binding. When I first wrote this, I assumed (!! stupidly !!) that there would be some sort of standard within BLE. I therefore assumed I could create a single binding that would work with many devices. The update removes the devices from the BLE binding and creates a separate binding for a single device (Yeelight Blue LED light).

Will push soon…  It probably needs merge conflicts removed after the DBus merge...

**Comment by hakan42** [comment]
> I would like to create a binding that uses Bluetooth.

@maggu2810 , what binding are you planning? I am setting up a project for the Xioami Mi Flora ( http://xiaomi-mi.com/smart-home/xiaomi-huahuacacao-flower-care-smart-monitor/ ), but if you wish to write something for that, I would find another thing to work on...

**Comment by cdjackson** [comment]
Just FYI, in the branch (maybe the previous commits) you should find a handler that handles the Parrot flower monitor. I don’t know if it’s the same as this or not, but I thought I’d mention it…

**Comment by maggu2810** [comment]
@hakan42 I will have a look at www.playbulb.com/en/playbulb-candle-bluetooth-smart-led-flameless-candle.html (https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Daps&field-keywords=playbulb+candle)

**Comment by maggu2810** [comment]
@cdjackson Already pushed?

**Comment by maggu2810** [comment]
@cdjackson Just another ping.

**Comment by cdjackson** [comment]
Sorry - I thought I'd pushed the branch before I went to India. Not sure why it didn't update, but done now.

**Comment by maggu2810** [comment]
Still missing the license update (https://github.com/eclipse/smarthome/pull/551#issuecomment-277661422):
Needs changes for new files in the three projects:
* `pom.xml`
* `src/etc/header.txt`

**Comment by kubawolanin** [comment]
Can't wait to see this merged! Lots of goodness here.

FYI: There's also ongoing effort on [OH2 Yeelight binding](https://github.com/openhab/openhab2-addons/pull/1514) which focuses on WiFi-enabled lightbulbs. 
Do you consider combining them together?

**Comment by kaikreuzer** [comment]
> Do you consider combining them together?

I think they are usually either BLE or Wifi, right? So combining probably does not make much sense, but we might consider to change the names to yeelightwifi and yeelightble or something like that...

**Comment by cdjackson** [comment]
My original PR includes the Yeelight Blue handler but I’m not sure how this could be combined with a wifi version...

**Comment by mrquincle** [comment]
How is the process of integration going on? Can I help somehow, maybe with reviewing?

**Comment by maggu2810** [comment]
> How is the process of integration going on?

Still waiting for the clarification of the license stuff...

**Comment by kaikreuzer** [comment]
Why did you close this?

**Comment by maggu2810** [comment]
I moved my branch to another repo, to start to work with.

I used the "current" bluez transport code to control my Playbulb Candle in a test.

As I have no real documentation, I read the code and found "printStackTraces" calls, ignored errors (exceptions are catch and proceeded as the calls does not fail)...

The "WriteValue" D-Bus method of Bluez's BLE is different on my system (two arguments, instead of one).

I need to change the Gatt Service and Characteristic handling because the current code base does not add any characteristics (but d-feed shows them). After the modification it works.

**Comment by kaikreuzer** [comment]
Ok, would be cool if you could create a new PR with your latest changes - the license has been clarified today, you can change the header to match the project guidelines, so there is nothing blocking us from merging the code anymore.

**Comment by kaikreuzer** [comment]
> The "WriteValue" D-Bus method of Bluez's BLE is different on my system (two arguments, instead of one).

Any idea why? Are you using a different BlueZ version? (fyi @cdjackson)

**Comment by maggu2810** [comment]
AFAIK It has been changed between 5.39 and 5.40.

**Comment by kaikreuzer** [comment]
That's really nasty that BlueZ is such a moving target...
I guess we should precise the info on the README ("A recent version of the BlueZ bluetooth layer is required - a minimum requirement of version 5") to give a specific version that this is code is known to work with.

**Comment by cdjackson** [comment]
In BlueZ 5, all the BLE features were considered experimental and had to be enabled through a specific ‘experimental’ command line option. A few months back they made an effort to ‘freeze’ the interface and I think at that time they also removed the experimental nature - I guess they also changed the API at the same time.

My original comment about using a “recent” version wasn’t related to this - it was related to the fact that earlier versions of 5.x had lots of problems and lacked features - I think things started to work around 5.29.

It’s a bit painful as some OSs still use BlueZ 4.x - e.g. Ubuntu and Debian stable is also quite old now (at least it was last time I looked).  Given the ‘mainstream’ nature of BLE it’s not so nice...

**Comment by maggu2810** [comment]
Just a short summary about my usage of the Bluetooth, Bluez, D-Bus stuff the last days:

* First I realized that I need the library unix-java and that it is not part of the io.transport.dbus OSGi bundle (using Bundle-NativeCode directive)
* I also realized that io.transport.dbus does not contain code itself but only bundles the two JARs libdbus-java and unix that are no OSGi bundles
* I migrated the libdbus-java and unix to real OSGi bundles itself and added the Bundle-NativeCode part to unix (also converted to Maven build system instead of Makefile)
* I realized that libmatthey's unix has a debendency to libmatthey's debug and libmatthey's debug has a dependency to libmatthey's hexdump, also libdbus-java has a dependency to libmatthey's debug and libmatthey's hexdump itself (haven't had a look at why it is working without that libraries)
* I migrated libdbus-java (https://github.com/maggu2810/dbus-java/commit/6c06ca60b7342c719c325ef5b221ab64a476a4cd) to use slf4j for logging instead of that custom debug library and removed the one line of logging by debug in the unix code base (https://github.com/maggu2810/libmatthew-java/commit/f1fb7d76e8191b1f15157559baa44417ef3fb045#diff-b15a6efa5256ef7b1a14e3c17b4b9d4aL143)
* I realized that there are some potential resource leaks in dbus-java (see e.g. https://github.com/maggu2810/dbus-java/commit/ab3967b8f81e6308a143414c3a613c842915a982). Don't know if the one in DBusConnection is code that is used by our code base).
* I fixed all the "generic types should be parameterized" warnings in dbus-java (the only change that has currently some impacts on bluetooth.bluez as it needs to use parameters instead of a raw type)
* And of course some other cleanup of unix, hexdump and dbus-java to remove all warnings etc.

If this is of interest for ESH itself is up to you.
But with the correct usage of the generic types the bluez transport bundle does not fit to the current dbus-java library. As the upstream development of libmatthey's unix and dbus-java seems to be stalled (no changes the last years), I assume that we need a solution if we need some modifiaction.

**Comment by maggu2810** [comment]
> A recent version of the BlueZ bluetooth layer is required - a minimum requirement of version 5

I agree that we need to state the version we support.

With respect to the release dates, I don't think we need to support a pre 5.40 version at all.

```text
Release of BlueZ 5.25: 9th November 2014, 10:11 pm by Johan Hedberg
Release of BlueZ 5.26: 12th December 2014, 04:48 pm by Johan Hedberg
Release of BlueZ 5.27: 26th December 2014, 10:20 pm by Johan Hedberg
Release of BlueZ 5.28: 2nd February 2015, 10:16 am by Johan Hedberg
Release of BlueZ 5.29: 11th March 2015, 06:56 pm by Johan Hedberg
Release of BlueZ 5.30: 1st April 2015, 08:31 am by Johan Hedberg
Release of BlueZ 5.31: 15th June 2015, 04:31 pm by Johan Hedberg
Release of BlueZ 5.32: 7th July 2015, 07:57 pm by Johan Hedberg
Release of BlueZ 5.33: 30th July 2015, 10:35 pm by Johan Hedberg
Release of BlueZ 5.34: 4th September 2015, 07:49 am by Johan Hedberg
Release of BlueZ 5.35: 28th September 2015, 06:26 pm by Johan Hedberg
Release of BlueZ 5.36: 30th October 2015, 07:36 am by Johan Hedberg
Release of BlueZ 5.37: 28th December 2015, 09:15 am by Johan Hedberg
Release of BlueZ 5.38: 18th March 2016, 08:55 am by Johan Hedberg
Release of BlueZ 5.39: 5th April 2016, 07:17 am by Johan Hedberg
Release of BlueZ 5.40: 27th May 2016, 07:55 am by Johan Hedberg
Release of BlueZ 5.41: 19th July 2016, 08:01 am by Johan Hedberg
Release of BlueZ 5.42: 26th September 2016, 06:33 pm by Johan Hedberg
Release of BlueZ 5.43: 29th October 2016, 09:44 am by Johan Hedberg
Release of BlueZ 5.44: 25th February 2017, 06:33 pm by Johan Hedberg
```

**Comment by kaikreuzer** [comment]
Thanks @maggu2810, that sounds as if you made an awesome progress!

I guess @cdjackson is the best to comment on https://github.com/eclipse/smarthome/pull/2670#issuecomment-289378352 - I don't remember all the details, but let me nonetheless give some comments (happy to stand corrected by Chris):

> First I realized that I need the library unix-java and that it is not part of the io.transport.dbus OSGi bundle (using Bundle-NativeCode directive)

Afair, no native code is needed when accessing DBUS over TCP - that was the whole deal here to NOT draw any (L)GPL code in. The native parts were supposed to be added by a different bundle/fragment that would come under (L)GPL (and thus not be part of ESH).

> I realized that libmatthey's unix has a debendency to libmatthey's debug and libmatthey's debug has a dependency to libmatthey's hexdump, also libdbus-java has a dependency to libmatthey's debug and libmatthey's hexdump itself (haven't had a look at why it is working without that libraries)

I thought to remember that Chris dealt with that - and I have heard users successfully using the DBUS bundle already, so even if there is this dependency, it does not seem to be required at runtime.

> If this is of interest for ESH itself is up to you.

Bug fixes are imho definitely of interest and it would be also fine for me to use the bundles standalone (not in ESH namespace). We would have to do a diff-CQ though, if we wanted to include a modified version of the library.

> But with the correct usage of the generic types the bluez transport bundle does not fit to the current dbus-java library.

What exactly do you mean by "does not fit"?

**Comment by maggu2810** [comment]
> Afair, no native code is needed when accessing DBUS over TCP - that was the whole deal here to NOT draw any (L)GPL code in. The native parts were supposed to be added by a different bundle/fragment that would come under (L)GPL (and thus not be part of ESH).

As written above I used the unmodified (the last version of this PR) code to start playing with it.
I don't change any configuration and hit the "missing library" error.
So, if I need to change something so D-Bus is using TCP and not unix sockets, I missed that notice.
(see e.g. first lines of the project website: http://www.matthew.ath.cx/projects/java/)

dbus-java is dual licensed using the AFL-2.1 and the LGPL-2.

libmatthew-java 0.8 (the unix and libunix-java and others are part of) is using the Expat (MIT) license.
I don't see a notice that this does not apply for the libunix-java.

>> But with the correct usage of the generic types the bluez transport bundle does not fit to the current dbus-java library.
> What exactly do you mean by "does not fit"?

Using the raw type `void foo(GenericType test)` differs from using parameterized `void foo(GenericType<?> test)` generic classes.

So, if dbus-java uses now generics "correctly", there is a small API change (the caller needs to use type parameters, too).

**Comment by maggu2810** [comment]
See #3531

**Pull request closed without merging**
