### PR TITLE
Support installation of Voice extensions from the IoT Marketplace.

### PR DESCRIPTION
**Pull request by jsichi**
This PR is for the discussion in 

https://community.openhab.org/t/moving-beyond-bindings-in-the-iot-addon-marketplace/42194

I tried to make the code a bit more data-driven (via enum PackageType) to make it easier to keep adding more extension types.  For the moment, I only added Voice and UI, but I can add the others (actions, persistence, transformations) if desired.

I renamed BindingExtensionHandler to BundleExtensionHandler for generality.  I also arranged for migration of the old installedBindingsMap.csv to the new installedBundlesMap.csv.  This might be unnecessary since I think this file gets discarded during an upgrade anyway, but it seems like the safest thing to do.

I tested by enabling plugin org.eclipse.smarthome.extensionservice.marketplace in my Eclipse workspace configuration.  For UI, I was able to test https://marketplace.eclipse.org/content/gauge-widget-habpanel.  With this change, it now shows up in the UI tab under extensions in the Paper UI, and I was able to successfully install+uninstall it.

For Voice, I am not able to do full testing since the Marketplace server does not currently allow for this package type when publishing an addon.  So I'll need someone's help to make that happen.

Bug: https://github.com/eclipse/smarthome/issues/3320

Signed-off-by: John Sichi <jsichi@gmail.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
I really like to add support for other types, too.


Just to link another comment from https://github.com/eclipse/smarthome/pull/4112#issuecomment-355006491

>> Shouldn't we enhance that bundle to support a transport type, too?

> There isn't such a thing as a "transport add-on/extension". Transport bundles are internal bundles that are technical dependencies, which get automatically installed (e.g. through Karaf if they are declared in a Karaf feature). For the marketplace, we do not have a dependency mechanism in place. What is prepared is to have other packaging formats than "bundle" in future, thus as "kar" - this would allow packaging multiple bundles that are required for a single add-on. But this is yet something to implement for the marketplace support.
> Until then, we only have "binding" and "rule templates" as valid categories.

I assume that UI and Voice are not "technical dependencies" only, but extensions that an user wants to add explicitly. Do you agree @kaikreuzer

**Comment by jsichi** [comment]
Sure, just let me know exactly which types make sense.  For voice, I think it's clear that these are extensions a user wants to add; we already have two which should be recategorized (they are currently listed as bindings):

https://marketplace.eclipse.org/content/pollytts-voice-service
https://marketplace.eclipse.org/content/shlurd-human-language-interpreter

For UI, I noticed that there was some discussion regarding the need to distinguish complete interfaces (such as HabPanel) from widgets (such as the gauge widget at https://marketplace.eclipse.org/content/gauge-widget-habpanel).  So maybe we should have a corresponding ui-widget package type?

I'll wait to hear from @kaikreuzer and then update this PR accordingly.

**Comment by jsichi** [comment]
Ping?

**Comment by jsichi** [comment]
Resolved merge conflicts.  @maggu2810 could you tell me the best way to get a code review started for this?

**Comment by maggu2810** [comment]
@jsichi I am waiting for some comment of the other committers (that they agree it is a good idea). Then the review itself shouldn't be the problem.

**Comment by htreu** [comment]
Hi @jsichi, please take another look at the merge you did. We avoid merging branches but do rebases instead. 
Please remove the merge commit and do a `git rebase master` and `git push --force` to update this PR.

**Comment by kaikreuzer** [comment]
@jsichi Sorry for my late reply and thanks for picking up that issue.

Wrt "voice": As you have correctly noticed, it currently is not possible to publish bundles with that category - I will have to ask Eclipse admins to add that in the marketplace first. But yes, I agree that this category makes sense.

Wrt "ui": We currently do not have any UIs in the marketplace, so I do not see a need for this right now. HABPanel widgets actually do not belong in the marketplace at all - all add-ons are meant to be fully ESH-compatible and not openHAB-specific; and as long as HABPanel itself is a proprietary openHAB UI, its extensions simply do not belong in the Eclipse Marketplace.

**Comment by jsichi** [comment]
@htreu got it, will do.

@kaikreuzer OK, I will remove the ui addon support.

**Comment by jsichi** [comment]
I've rebased the pull request and removed the UI support.

**Comment by kaikreuzer** [comment]
I've created a request for "Voice" type in the Marketplace: https://bugs.eclipse.org/bugs/show_bug.cgi?id=534469

**Comment by jsichi** [comment]
A month later, I don't see any response to the request you created...how often do those get processed?

**Comment by kaikreuzer** [comment]
Don't ask me - better leave a comment on that request yourself and ask there - maybe this helps to get someones attention...

**Comment by jsichi** [comment]
OK, the marketplace request has been carried out, and I've successfully tested it with my branch + extension.  Extensions which use the new Voice type will only be installable from ESH instances running a version which includes this PR (after it gets merged).  For older versions, such an extension won't be visible at all.

**Pull request merged**
