### PR TITLE
Overwrite getQueue on Scheduler

### LINKED ISSUE #3602: Return Queue of Runnables in ExpressionThreadPoolExecutor

### PR DESCRIPTION
**Pull request by triller-telekom**
Fixes #3602

Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@kgoderis Could you briefly review?

**Comment by triller-telekom** [comment]
Some background on this change:
Inside the [AstroBinding using the new scheduler](https://github.com/eclipse/smarthome/pull/3503/files#diff-637f70cb0a947f264138d125132a0a99R253) we came across the problem that we want to check the content of the schedulers queue to cancel jobs only matching a certain `thing uuid`.

Without this change the `getQueue()` method will be the one from `ScheduledThreadPoolExecutor` and return objects of type `ScheduledFuture`.

There is no way to retrieve a `Runnable` which was scheduled in the scheduler from these `ScheduledFuture` objects.

**Comment by amitjoy** [comment]
> There is no way to retrieve a Runnable which was scheduled in the scheduler from these ScheduledFuture objects.

Just in continuation. This is because the member map instance is neither exposed nor passed down to the `ScheduledThreadExecutor` of Java so that the scheduled `Runnable`s could have been extracted as is. That's why this change is integral for any scheduling operation and do some further operations on the scheduled `Runnable`s

**Comment by kgoderis** [comment]
@amitjoy @triller-telekom The queue and map with runnables are not exposed on purpose. Rather than directly manipulating these members, you have to keep track of the Expression you schedule, and call ExpressionThreadPoolExecutor.remove(Expression expression) instead.

**Comment by kgoderis** [comment]
> I guess the background of @kgoderis's veto is that if they get exposed, it becomes way too easy to accidentally tamper with other things'/handlers' jobs. I second that.

Right indeed, and beyond that, it is all about Expressions that get scheduled for execution, so, even as we would enhance the API, it should evolve around the Expressions themselves primarily.

**Comment by triller-telekom** [comment]
Alright, I agree that having direct access to the queue which would also reveal access to other tasks that I didn't schedule isn't a good thing. So I discard this PR and users of the scheduler like the astro binding have to store all tasks they schedule.

**Pull request closed without merging**
