### PR TITLE
Add support for AUNA Connect 150 Radio

### PR DESCRIPTION
**Pull request by garthy**
Signed-off-by: garthy <garth@garthy.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Could you add this info to https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/README.md#supported-things as well?

**Comment by kaikreuzer** [comment]
Could you please rebase this PR (necessary after I have merged the other one)?

**Comment by kaikreuzer** [comment]
@garthy Did you see my comment?

**Comment by kaikreuzer** [comment]
@garthy Ping :-)

**Comment by garthy** [comment]
Sorry I've used the github UI again to edit the commit as i'm still waiting on QNAP support to fix some issues with my NAS after a fairly disasterous upgrade.

**Comment by kaikreuzer** [comment]
Ok, no worries. I have created an according PR myself: https://github.com/eclipse/smarthome/pull/3421

**Pull request closed without merging**
