### PR TITLE
Sat plugin new version

### PR DESCRIPTION
**Pull request by svilenvul**

### CODE REVIEW

**Comment by maggu2810** [comment]
Would it make sense to fix all errors reported by the plugin and wait for a successful build of ESH in front of the CQ creation?

```text
[ERROR] /home/travis/build/eclipse/smarthome/bundles/test/org.eclipse.smarthome.magic/META-INF/MANIFEST.MF:[0]
The package org.eclipse.smarthome.magic.service should be marked as "internal" if it is not exported.
```

As long as ESH does not build completely successful we don't know, if we could detect an error in the plugin. If there is an error in the plugin, it needs to be fixed and another CQ has to be requested.
To reduce the work of the Eclipse IP team, I would prefer to fix all ESH violations the SAT found before.

WDYT?

**Comment by svilenvul** [comment]
> Would it make sense to fix all errors reported by the plugin and wait for a successful build of ESH in front of the CQ creation?

Yes, of course. I opened the PR just to make it visible.

**Comment by kaikreuzer** [comment]
@maggu2810 The SAT tool is an approved build-time only dependency, we do not require a new CQs when updating its version.

**Comment by svilenvul** [comment]
Hmm, strange , the last build fails with:
```
[ERROR] Failed to execute goal org.apache.karaf.tooling:karaf-maven-plugin:4.0.3:verify (verify-esh) on project verify: Verification failures -> [Help 1]
```

Do you have any clue if it is related ?

**Comment by kaikreuzer** [comment]
I doubt that it can be related - just retriggered Travis to check...

**Comment by svilenvul** [comment]
From the logs, I see that some ESH Karaf features depend on `mvn:org.openhab/nrjavaserial/3.12.0.OH`

This seems to be in JCenter - https://jcenter.bintray.com/org/openhab/nrjavaserial/, so I guess this is the cause of the failure. 

How should we proceed in this case ? Should I bring back the JCenter repository ?

**Comment by kaikreuzer** [comment]
Yes, you are right! I forgot that this was in JCenter as well.
So yes, please add the repo again.

**Pull request merged**
