### PR TITLE
Readded and adapted SatisfiableResourceFilter

### PR DESCRIPTION
**Pull request by triller-telekom**
Repairs problems created by PRs #3436 #3452

Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
The tests failed

**Comment by triller-telekom** [comment]
Yes, Ivan and me are looking for a fix, the launch config for eclipse is broken for these tests which is why they only work for Ivan at the moment. Once we figured out a fix, I will create a new commit.

**Comment by triller-telekom** [comment]
Thanks to Ivan for correcting the groovy tests, hopefully Travis likes them ;)

**Comment by triller-telekom** [comment]
Travis has some hickups again?
```java.io.IOException: Error downloading mvn:de.maggu2810.p2redist/com.google.guava/10.0.1.v201203051515```

**Pull request merged**
