### PR TITLE
fixes #1062

### LINKED ISSUE #1062: ThingType.hasConfigDescriptionURI() could be removed
This method does not bring any additional value as long as we say that `getConfigDescriptionURI()` returns null, if no such description exists.

See https://github.com/eclipse/smarthome/pull/1060#discussion_r53432145.

@sbussweiler, @sjka Any opinion on that?

### PR DESCRIPTION
**Pull request by tomhoefer**
Signed-off-by: Thomas Höfer <t.hoefer@telekom.de>

### CODE REVIEW

**Comment by tomhoefer** [comment]
Just saw that the ChannelType has also an operation hasConfigDescriptionURI... Do you want we to remove this operation as well?

**Comment by maggu2810** [comment]
If the function does use the same logic, I assume the same argument fits here.

**Comment by tomhoefer** [comment]
removed all occurrences of hasConfigDescriptionURI in several classes

**Comment by maggu2810** [comment]
thanks

**Pull request merged**
