### PR TITLE
[OneWire] Minor Updates and fixes

### PR DESCRIPTION
**Pull request by J-N-K**
- After a thing has been edited in PaperUI initialization could not finish if the thing was ok OFFLINE status before
- Documentation has been made more clear regarding the channel naming (esp. for digital channels)
- Minor internal code changes that removes proprietary code in favor of standard classes
- If the exact DS2438 multisensor type could not be determined the sensor was dropped. This has been fixed.

For easier review I have left the individual commits in place.

### CODE REVIEW

**Comment by J-N-K** [comment]
@kaikreuzer After thinking about my first changes: Is the root cause a framework issue? It seems that after updating the thing configuration the framework disposes the handler, calls `initialize()` again but keeps the thing status. I would expect it to go back to `INITIALIZING`.

**Comment by kaikreuzer** [comment]
No, changing the configuration does not necessarily dispose the handler. This is only done in the default implementation in [BaseThingHandler](https://github.com/eclipse/smarthome/blob/7176f8961a4caba501fe38bab52a44c8705011c3/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java#L196-L198), but this effectively means that it is the handler that calls dispose and not the framework.

**Comment by J-N-K** [comment]
Ok, but the question remains: would you expect the thing to have `INITIALIZING` state when `initialize()` is called? Then the BaseThingHandler should update the state when disposing or initializing.

**Comment by kaikreuzer** [comment]
INITIALIZING is set by the framework. If the framework is not involved (as explained above) I do not expect this status when the handler itself calls initialize. Note that the handler MUST NOT set the status to INITIALIZING, this is only allowed for the framework.

**Comment by J-N-K** [comment]
Ok. Thank you.

**Pull request merged**
