### PR TITLE
fix resolution errors in PDE

### PR DESCRIPTION
**Pull request by kaikreuzer**
https://github.com/eclipse/smarthome/pull/481 causes resolution errors within the IDE. Removing these imports fixes the problem. This might be due to split packages, so in this case it is not a good idea to re-import the own exports.

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@maggu2810 Can you confirm and are ok to merge?

**Comment by maggu2810** [comment]
Will have a look at.
First I need to understand why the re-import is not working (have to read about the re-import again).

**Comment by maggu2810** [comment]
IMHO we should merge this ASAP, so we get a working IDE.
I will try to find the cause of the problem and add a new PR if necessary.

**Comment by maggu2810** [comment]
If I use a clean working copy using the commit id bbec7d77ad84b539650f3ed5fefd7670b965aeb2 a ```sh
mvn clean install
```
fails with this error message
```sh
[ERROR] Failed to execute goal
org.eclipse.tycho:tycho-compiler-plugin:0.23.1:compile
(default-compile) on project org.eclipse.smarthome.model.script:
Compilation failure: Compilation failure:
[ERROR] /home/rathgeb/bin/pkgs/eclipse/smarthome-master/git/smarthome/bundles/model/org.eclipse.smarthome.model.script/src-gen/org/eclipse/smarthome/model/script/ScriptStandaloneSetupGenerated.java:[28]
[ERROR] return Guice.createInjector(new
org.eclipse.smarthome.model.script.ScriptRuntimeModule());
[ERROR] ^^^^^^^^^^^^^^
[ERROR] The method createInjector(Module...) in the type Guice is not
applicable for the arguments (ScriptRuntimeModule)
[ERROR] 1 problem (1 error)
[ERROR] -> [Help 1]
```

If I use a clean working copy using the commit id b810391a3abacfeb4ca1a0590722aa2577f95775 a ```sh
mvn clean install
```
fails with this error message
```sh
[ERROR] Failed to execute goal
org.eclipse.tycho:tycho-compiler-plugin:0.23.1:compile
(default-compile) on project org.eclipse.smarthome.model.persistence:
Compilation failure: Compilation failure:
[ERROR] /home/rathgeb/bin/pkgs/eclipse/smarthome-master/git/smarthome/bundles/model/org.eclipse.smarthome.model.persistence/src-gen/org/eclipse/smarthome/model/persistence/PersistenceStandaloneSetupGenerated.java:[28]
[ERROR] return Guice.createInjector(new
org.eclipse.smarthome.model.persistence.PersistenceRuntimeModule());
[ERROR] ^^^^^^^^^^^^^^
[ERROR] The method createInjector(Module...) in the type Guice is not
applicable for the arguments (PersistenceRuntimeModule)
[ERROR] 1 problem (1 error)
[ERROR] -> [Help 1]
```

So I think the re-import has broken all the model stuff.



Further info about the access restriction:

Using the Eclipse IDE with the sources before the re-import:
* org.eclipse.smarthome.model.sitemap.runtime
* Properties
* Java Build Path
* Libraries
* Plug-in Dependencies
* org.eclipse.smarthome.model.sitemap
* Access rules
*:There are 13 ones; 12 accessible and 1 forbidden (remaining)

If we now add the re-import to the package org.eclipse.smarthome.model.sitemap and do the same as above for org.eclipse.smarthome.model.sitemap.runtime, there are only 3 (instead of 12) accessible.

**Comment by kaikreuzer** [comment]
Interestingly, Hudson does not have any problem: https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution/584/

But I would be fine with reverting the change for the model bundles.
@BenediktNiehues, what do you think?

**Comment by maggu2810** [comment]
Does your hudson job a clean up of the working copy (not a mvn clean only) before the build?

**Comment by kaikreuzer** [comment]
It didn't, now it does. Let's see how this goes: https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution/585/

**Comment by maggu2810** [comment]
Seems that the models could be build. I will try to reproduce the error on another PC.

**Comment by maggu2810** [comment]
* did a clean checkout of the repo
* used commit id bbec7d77ad84b539650f3ed5fefd7670b965aeb2
* used an empty local maven repo
* start mvn clean install

All went fine.
Sorry for my report above.

But I think I have to do further testing tomorrow on the other PC. The git command states I have had a clean working copy, too.

**Comment by maggu2810** [comment]
Started a rebuild on the system that failures yesterday.
IMHO I Did the same, but now I also empty the local maven repo.
The build of bbec7d77ad84b539650f3ed5fefd7670b965aeb2 using mvn clean install succeeded.

**Comment by BenediktNiehues** [comment]
I also retested it with a clean checkout an empty local maven repo and I was facing the same compilation errors. Then I reverted the re-imported packages for the model bundles and it did not compile, either.
After that I did the following:
* checked out commit id db421ac (fully without reimported packages), 
* git clean -fdx
* deleted local .m2/repository/eclipse/smarthome
* mvn clean install

And this resulted in the same error.

'''
 /.../smarthome/bundles/model/org.eclipse.smarthome.model.sitemap/src-gen/org/eclipse/smarthome/model/SitemapStandaloneSetupGenerated.java:[28]
[ERROR] return Guice.createInjector(new org.eclipse.smarthome.model.SitemapRuntimeModule());
[ERROR] ^^^^^^^^^^^^^^
[ERROR] The method createInjector(Module...) in the type Guice is not applicable for the arguments (SitemapRuntimeModule)
[ERROR] 1 problem (1 error)
[ERROR] -> [Help 1]
'''

**Comment by maggu2810** [comment]
This is really strange.
Could you try to move your .m2 (so you could restore it later) completely and build it again (using a clean working copy)?

**Comment by BenediktNiehues** [comment]
I moved the .m2 repository completely and the build was successful on commit db421ac. Going to try the same for commit bbec7d7 now.

**Comment by BenediktNiehues** [comment]
build of bbec7d7 works as well with a clean checkout and clean .m2 repository

**Comment by BenediktNiehues** [comment]
With the clean .m2 repo the build also for the current master finishes successfully.
The question is now if we still have to do something or can we leave it as it is now?

**Comment by kaikreuzer** [comment]
> The question is now if we still have to do something or can we leave it as it is now?

When I tested the Xtext-upgrade-PR last night, I had error messages in the model pojects all over - not related to the upgrade, but again with resolution problems,
Furthermore, I have noticed that the Designer completely broke with the current code (test yourself by downloading the one currently on Hudson).

So, imho, we definitely need to further look into this.

**Comment by BenediktNiehues** [comment]
I've got the reverted reimported packages for the model and ui bundles in place and created PR#486 for it. But please test it on your machines before merging it. On my machine both is working maven build and  IDE. But I did not try out the designer.

**Comment by maggu2810** [comment]
> I moved the .m2 repository completely and the build was successful on commit db421ac. Going to try the same for commit bbec7d7 now.
build of bbec7d7 works as well with a clean checkout and clean .m2 repository
With the clean .m2 repo the build also for the current master finishes successfully.

So, this is all a little bit confusing.
I can only guess, are there multiple repositories (remote) containing different snapshots of an artifact and the one chosen to fetch it for building is non deterministic? Or is the problem so easy, that I don't see it...
Yesterday it failed. Today I moved the .m2, started the build and it succeed. After that I restored my old .m2 and a clean build still succeed (so, normally the same code and artifacts as yesterday).

**Comment by maggu2810** [comment]
I think the build problems depend on the Guice libraries in the local repository, too.
Have a look at:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=480300

**Pull request merged**
