### PR TITLE
Add location while creating thing

### PR DESCRIPTION
**Pull request by aounhaider1**
Related issue is: https://github.com/eclipse/smarthome/issues/1083
Signed-off-by: Aoun Bukhari <bukhari@itemis.de>

### CODE REVIEW

**Comment by afuechsel** [comment]
This already merged PR broke several tests, that relied on that API, Since you have changed the API, the tests need to be adapted as well. Apart from the 3 failed tests in Hudson, also the tests of the hue binding would be affected.

**Comment by maggu2810** [comment]
@kaikreuzer Is it allowed to use the Travis merge request builder for an Eclipse Project?

**Comment by kaikreuzer** [comment]
@maggu2810 It seems to be possible by opening a Bugzilla issue for the Eclipse webmaster, see https://github.com/eclipse/omr/issues/21.

**Comment by kaikreuzer** [comment]
@afuechsel: @aounhaider1 will fix this asap.

**Comment by kaikreuzer** [comment]
Reverted and fixed by https://github.com/eclipse/smarthome/pull/1776

**Pull request merged**
