### PR TITLE
Fix - Creation of a rule from template fails #831

### PR DESCRIPTION
**Pull request by adimova**
Signed-off-by: Ana Dimova <a.dimova@prosyst.bg>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
This PR does not solve the issue for me.
The created rule still looks the same. Please note that my expectation is that the rule does NOT refer the template anymore, but is "exploded", i.e. a rule that has the modules that are defined in the template.

**Comment by danchom** [comment]
I think the Ani's fix make sense, but you are right it does not fix this problem. At the moment when a template is appeared a runtimeRule is created with data of template, but the public rule object is not changed (It just contains reference to the remplate, not template data). I'll fix this. The reference will be removed and template's data will be filled into a new rule object.

**Comment by kaikreuzer** [comment]
@danchom Any news about this fix?

**Comment by danchom** [comment]
this PR is closed due to PR #879

**Pull request closed without merging**
