### PR TITLE
Thing location

### PR DESCRIPTION
**Pull request by sjka**
Added a location field to Things according to #1083

Signed-off-by: Simon Kaufmann <simon.kfm@googlemail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
No documentation updates necessary?

**Comment by kaikreuzer** [comment]
Thanks!

**Comment by maggu2810** [comment]
Didn't we miss the changes for the ThingDTO class?

**Comment by sjka** [comment]
Indeed - somehow it felt like I didn't touch enough classes just for adding this one string property... 
Will create another PR for it.

**Pull request merged**
