### PR TITLE
RollerShutter items are Sitemap-Switches but need PercentType state

### LINKED ISSUE #3445: Rollershutter Items with wrong image state
I updated my openhab2 installation to the latest snapshot. Now my Rollershutters are displayed wrong. They do not have a numeric state within the UI but `ON` / `OFF`.

I did some small check and I think the following lines could be the source of my problem.
https://github.com/eclipse/smarthome/commit/8ba0e7cdd141595e5d7fbe8a3d7716ce63cba799#diff-5d3a30bfebd36343f1f1d61e9f589de1R491

My understanding: It seems that the my Rollershutter is an instance of `Switch` and so it is converted to `ON` or `OFF`. So one should probably check the Item, too.

Perhaps @triller-telekom can have a look at this, as he committed the mentioned code parts?

best regards
Matthias

### PR DESCRIPTION
**Pull request by triller-telekom**
Fixes #3445

Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by lolodomo** [comment]
LFTM

**Comment by kaikreuzer** [comment]
> LFTM

Is that a mix of LGTM and RTFM?

**Comment by lolodomo** [comment]
:) Just a typo

**Comment by maggu2810** [comment]
>> LFTM
> Is that a mix of LGTM and RTFM?

Looks Fine To Me :wink:

**Pull request merged**
