### PR TITLE
remove bundled libs of transform.jsonpath

### PR DESCRIPTION
**Pull request by maggu2810**
Related to #1445

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks! Before merging this, I would like to also prepare https://github.com/openhab/openhab-deps-repo first, otherwise OH will break on the next stable ESH build...
It might make sense to change the openhab-deps-repo to the p2-maven-plugin as well.

**Comment by maggu2810** [comment]
Perhaps we could use this some time to generate one aggregator repo that contains all ESH dependencies (or at least the most).
ATM the repos at download.eclipse.org seems to be very slow or not available.

**Comment by kaikreuzer** [comment]
@maggu2810 Somehow Hudson cannot access the 3rd party p2 repo: https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/1028/console

Any idea what we can do?

**Comment by kaikreuzer** [comment]
Maybe it is due to https? Shall we have a try with http instead?

**Comment by maggu2810** [comment]
We should try that. IIRC that has been also necessary for npm.

**Pull request merged**
