### PR TITLE
optionally limit fields in /rest/item result

### PR DESCRIPTION
**Pull request by sjka**
While we have #4302 for _filtering_ REST APIs, [this forum post](https://www.eclipse.org/forums/index.php?t=rview&goto=1775927) made me experiment a little how we could (generically) introduce a mechanism to _map_ the resultset to something smaller. IMHO it would work nicely like this:

I'd suggest introducing an optional query parameter where it is possible to specify the field names which should only be included in the result, i.e.

```
/rest/items?fields=name,type
```

would give only 

```json
[
  {
    "type": "Dimmer",
    "name": "sonos_PLAY1_RINCON_949F3E140B2E01400_volume"
  },
  {
    "type": "String",
    "name": "sonos_PLAY1_RINCON_949F3E140B2E01400_zonename"
  },
  {
    "type": "Player",
    "name": "sonos_PLAY1_RINCON_949F3E85A92801400_control"
  },
  {
    "type": "String",
    "name": "sonos_PLAY1_RINCON_949F3E140B2E01400_tuneinstationid"
  },
```

What do you think? The very same mechanism obviously could be used for other resources/entities too, of course, if viable.

Signed-off-by: Simon Kaufmann <simon.kfm@googlemail.com>

### CODE REVIEW

**Comment by htreu** [comment]
Looks good! How about extracting the function into a DTOMapper and passing this into the Resource via OSGi DS? It will be plain simple to incorporate it into other Resources then.

**Comment by sjka** [comment]
Yepp, that's pretty much what I had in mind. I was just waiting for some word of encouragement before touching one - and thereby migrating all the services in the o.e.sh.io.rest.core bundle to DS Annotations.

**Comment by htreu** [comment]
ha, I knew it. A W E S O M E!!eins11

**Comment by maggu2810** [comment]
If the filter contains `id` and `properties` a result could look like this one:

```text
[
  {
    "id": "1",
    "properties": {
      "id": "2"
    }
  }
]
```

Correct?

Do we need to be able to filter also one of the both IDs? Or is it okay to keep every ID field if `id` is used?

**Comment by htreu** [comment]
From what I understand form the code it will only filter top level fields. So in your example the full "properties" object is passed but not filtered at all.

**Comment by sjka** [comment]
Yes, it's only filtering attributes on top level. They will be either in or out completely. 
For the sake of simplicity I though this might be sufficient. Otherwise the mapping instructions might end up much bigger than the actual content and we would need to invent yet another mapping language which can be squeezed into URLs. Certainly possible - but really needed?

**Comment by htreu** [comment]
For nested level filtering it could be something like `fields=id,properties.id,properties.value`. But I see this as an improvement when really needed and not in this PR.
wdyt?

**Pull request merged**
