### PR TITLE
Fixed #459628 by starting thing tracker in activate method and added tes...

### PR DESCRIPTION
**Pull request by dnobel**
...t for the bug.

Signed-off-by: Dennis Nobel d.nobel@external.telekom.de

### CODE REVIEW

**Comment by maggu2810** [comment]
Could this be triggered by your commit?
The test succeeded before and failed after your commit.

<pre>-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.core.thing.setup.ThingSetupManagerOSGiTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.852 sec
Running org.eclipse.smarthome.core.thing.internal.ThingLinkManagerOSGiTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.096 sec
Running org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.215 sec <<< FAILURE!
Running org.eclipse.smarthome.core.thing.internal.ChannelStateDescriptionProviderOSGiTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.052 sec
Running org.eclipse.smarthome.core.thing.link.ItemChannelLinkOSGiTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.08 sec
Running org.eclipse.smarthome.core.thing.binding.BindingBaseClassesOSGiTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.076 sec
Running org.eclipse.smarthome.core.thing.binding.ThingFactoryTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.051 sec
Running org.eclipse.smarthome.core.thing.factory.ManagedThingProviderOSGiTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.061 sec
Running org.eclipse.smarthome.core.thing.util.ThingHelperTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec
Running org.eclipse.smarthome.core.thing.UIDTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec

Results :

Tests in error: 
  ThingManager handles updates correctly(org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest)

Tests run: 44, Failures: 0, Errors: 1, Skipped: 0

[ERROR] There are test failures.</pre>

<pre>Regression

org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest.ThingManager handles updates correctly

Schlägt fehl seit 1 Build (Seit Instabil#7 )
Dauer: 25 ms.
Beschreibung hinzufügen
Stacktrace

java.lang.NullPointerException
	at org.eclipse.smarthome.core.thing.internal.ThingManager$1.channelUpdated(ThingManager.java:117)
	at org.eclipse.smarthome.core.thing.internal.ThingImpl.channelUpdated(ThingImpl.java:99)
	at org.eclipse.smarthome.core.thing.Thing$channelUpdated$3.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at org.eclipse.smarthome.core.thing.internal.ThingManagerOSGiTest.ThingManager handles updates correctly(ThingManagerOSGiTest.groovy:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:123)
	at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:86)
	at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:382)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:236)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)</pre>

**Comment by dnobel** [comment]
Yes, can confirm it. The test does not properly clean up, so it depends on the execution order, if the next test fails or not. I assume that because of this it runs on the Hudson ESH build. Will fix it soon.

**Comment by dnobel** [comment]
Fixed with https://github.com/eclipse/smarthome/commit/91a846f62b37555ca9fe469dce2363d23c8db783. Thanks for reporting it.

**Comment by maggu2810** [comment]
Thanks for fixing it ;-)

**Pull request merged**
