### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aurelio1**
Added until now undocumented possibility to give a name to bulbs and sensors which are then used in PaperUI.

### CODE REVIEW

**Comment by hakan42** [comment]
You can also put them into locations:

```
    0210 11 "Hue color lamp Office 1" @ "Office" [ lightId="11" ]
```

might be worth adding it to the examples...

**Comment by aurelio1** [comment]
> You can also put them into locations:
> 
> ```
>     0210 11 "Hue color lamp Office 1" @ "Office" [ lightId="11" ]
> ```
> might be worth adding it to the examples...

Thank you for your suggestion, just added location too.

**Comment by htreu** [comment]
Thanks @aurelio1 for extending the docs.
Since this is not a trivial contribution you need to sign the Eclipse Contributor Agreement (ECA) so we can accept your changes for the project. Please see this topic in the developer documentation about signing the ECA: https://www.eclipse.org/smarthome/documentation/community/contributing.html#conventions-for-pull-requests

**Comment by kaikreuzer** [comment]
Migrated to https://github.com/openhab/openhab2-addons/pull/4768.

**Pull request closed without merging**
