### PR TITLE
UI: "[]" at end of label to disable the display of value

### PR DESCRIPTION
**Pull request by lolodomo**
Implements #3367

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
I think I tested all combinations, label on sitemap element or only on item, format not set, format set and format empty.
I have not changed the order of priority but just added the empty format "[]".
The highest priority is the format in the label of the sitemap element; then it is the format in the item element and finally it is the format on the channel state description.

**Comment by sjka** [comment]
Looks like it would do what we think it should, on a first glance. 

However, we have this wonderful [ItemUIRegistryImplTest](https://github.com/eclipse/smarthome/blob/8ba0e7cdd141595e5d7fbe8a3d7716ce63cba799/bundles/ui/org.eclipse.smarthome.ui.test/src/test/java/org/eclipse/smarthome/ui/internal/items/ItemUIRegistryImplTest.java) in the corresponding test project. I'd love to see your assumptions (similar like [here](https://github.com/eclipse/smarthome/issues/3367#issuecomment-299148973), just now the other way round) being manifested there as test case(s). Just to be sure it really does what we think and to prevent somebody breaking it in future accidentally...

**Comment by lolodomo** [comment]
Independently of my change, there are missing test cases. I will add 2 new tests.

**Comment by lolodomo** [comment]
Done.

**Comment by sjka** [comment]
That looks good, thanks!

However, isn't the test-case for the purpose of this change missing? (i.e. pattern in state description, overriding it with `[]` to nothing)

**Comment by lolodomo** [comment]
In fact, the code ignores the state description in this case. So don't matter.  But I agree it makes sense for the test to define a state description with pattern to show that it is ignored. I will update my test case and squash everything.

**Comment by lolodomo** [comment]
@sjka : test updated and everything squashed.

**Comment by sjka** [comment]
Thanks!

> [...] to show that it is ignored

From my point of view the primary goal of such tests are making sure nobody breaks it again accidentally. So it's about regressions. The more adoption this project gets, the more we should try to not break stuff all the time.

**Comment by lolodomo** [comment]
Thank you for the merge.

Remains to update the documentation to explain the new option.

**Pull request merged**
