### PR TITLE
NTP binding: fix issue #3962 and add French translation

### PR DESCRIPTION
**Pull request by lolodomo**
Also add the unit to a configuration setting

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@kaikreuzer @cweitkamp : for good practice in binding internationalization, is `updateStatus` the only method in which you can use `"@text/xxx"` ?
Example in the Yahoo Weather binding: https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.yahooweather/src/main/java/org/eclipse/smarthome/binding/yahooweather/handler/YahooWeatherHandler.java#L188

If not, which are the other methods supporting that feature ?

**Comment by cweitkamp** [comment]
This looks like an easy peasy way to translate `updateStatus` messages. I will update the internationalization documentation shortly and add this one to the [using custom keys](http://www.eclipse.org/smarthome/documentation/features/internationalization.html#using-custom-keys) section.

The other way I am aware of is the `LocaleProvider` / `TranslationProvider` approach you are using in this PR. Later one looks much more complex than the custom key solution.

**Comment by lolodomo** [comment]
@kaikreuzer @maggu2810 @sjka : I would appreciate a review of this PR to be sure my approach with binding internationalization is good, before applying them to other bindings.

**Comment by kaikreuzer** [comment]
Sorry to be late to comment, I feel slightly flooded by the number of PRs this week...

I think this idea of yours in this PR leads a bit too far. The i18n support within ESH is made in a way that the same system can answer stuff in different languages (mainly for the REST API). It is NOT meant for fully translating all aspects of the system to another language (such as log files etc.).
So the default language for all stuff that is a "technical" artifact (such as log entries, events, etc.) is english.
Regarding the localisation of thing status messages, you might be interested in https://github.com/eclipse/smarthome/issues/3093.

**Comment by lolodomo** [comment]
Ok, I will reduce the scope of this PR and forgive all tranlations of log messages.
I will consider the translation of the thing status message (for NTP binding and other bindings I started to translate in French).
I think the tranlation of the automatic discovered thing name is important too as it is directly seen by the user in Paper UI.

**Comment by kaikreuzer** [comment]
> I think the tranlation of the automatic discovered thing name is important too as it is directly seen by the user in Paper UI.

Our approach here was so far to use official product names, which are in 90% of the cases international and do not require any translation...

**Comment by lolodomo** [comment]
For the discovered thing name, I think we should think of something similar to what is doable with ConfigStatus/ThigStatus so that it can be used easily by any binding. That means the thing name has to be localized. I will study this enhancement.

**Comment by lolodomo** [comment]
@kaikreuzer : I am talking about the label of the thing. For NTP, it is hardcoded as "Local Time". It is this label that I would like to make localized.
I think we have already something very similar for config status so it should not be very difficult to add this feature to the creation of thing result. I will take a look.

**Comment by lolodomo** [comment]
Ready for new review, I finally only include the "basics".
I will include other stuff in another PR later.

**Pull request merged**
