### PR TITLE
[WIP] [Hue] Fix to support bridge ports other than 80 and others 

### PR DESCRIPTION
**Pull request by davidgraeff**
This started as a PR to fix the wrong handling with hue bridge ports other than 80.

I got carried away and this is now a refactor / simplify PR targeted at ESH > 0.10.
It is consistent in itself, but not rebased to include the sensor support yet.

It removes about 2000 lines of code while improving the tests (HueLightsThingHandler tests are no OSGI tests anymore for example and a full integration OSGI test with http servlet for hue bridge emulation is added).

### All changes

* The discovery was correctly discovering bridges on non standard ports,
  but was not propagating that information to the configuration.
* Rename "IP" to "hostAndPort" in HueBridge to make it obvious that a port
  could be part of the host string.
* Show the port in the discovery label. One host can serve multiple hue
  bridge softwares, if for example the deCONZ hue emulation as well as
  the openHAB emulation are running.
* Adjust bridge.xml to not only talk of an IP. It might as well be a port
  part of the configuration.
* Adjust the test in HueBridgeDiscoveryParticipantOSGITest to check
  if a non standard port is correctly recognised.

Fix incorrect isReachable method:
* Instead of checking the REST API with an "invalid" user, the more neutral
  /api/config URL is checked.
* If authentication with a username fails, it is obviously not in the bridges
  whitelist. Reset the username.

Refactorings:
* Rename relativeURL to absoluteURL, because that is what it is.
* Don't log the obvious. If the Thing status changes, don't output a log with
  the same content.
* Move all REST API classes into dto package, remove getter/setters from DTO classes
* HueBridgeHandler Test -> plain Java test
* Add OSGI blackbox implementation test for entire binding with http rest api test servlet

### CODE REVIEW

**Comment by cweitkamp** [comment]
Sounds great so far. Some very nice improvements inside.

One additional feature I like to have is the support of HTTPS connections to a bridge. e.g. an optional configuration. The support for it has been introduced with Firmware 1806051111 for v2 bridges. Do you think you are able to consider it while you are already doing such a big rework?

**Comment by davidgraeff** [comment]
Sure. After the rebase I replace the fixed "http://" string.

**Comment by kaikreuzer** [comment]
@davidgraeff Is this still on your todo list?

**Comment by davidgraeff** [comment]
Yup. But at a lower priority. I have coap and paper UI on my list right now. 

And the Deconz binding users are thinking of adding light support. (Deconz is a hue API with a websocket connection in top for real time communication. Something that Philips should do as well by the way). 

If they really go ahead with adding light support, Deconz will be actually the more powerful binding than the hue one. But I'm not really into that discussion.

**Comment by kaikreuzer** [comment]
May I ask you to move this to https://github.com/openhab/openhab2-addons?

**Pull request closed without merging**
