### PR TITLE
use pure Java for some Hue tests

### PR DESCRIPTION
**Pull request by maggu2810**
This change migrated some Groovy OSGi tests to pure Java ones.
In addition it tries to eliminate some usage of private members etc.

Fixes: https://github.com/eclipse/smarthome/issues/3115

### CODE REVIEW

**Comment by maggu2810** [comment]
IMHO #3123 should be merged in front of this!

**Comment by kaikreuzer** [comment]
I guess you have to rebase now...

**Comment by maggu2810** [comment]
Done, let's wait for Travis CI

**Comment by kaikreuzer** [comment]
This PR includes changes to the code under test. Is this to make it testable or just improvements that you came across when working on the tests?

**Comment by maggu2810** [comment]
The current test access private members. As Groovy is using reflection for all that stuff it worked before but is a very bad test design (IMHO).
So, I changed the scope of some stuff to package or protected or added a getter / setter (with package or protected scope) if needed.
Do you see any other changes in the code under test that are not related to "visibility"?

**Comment by kaikreuzer** [comment]
> but is a very bad test design (IMHO).

For me it is in contrast not really nice to change visibility of productive code just for testability... 
Changes like [this one](https://github.com/eclipse/smarthome/pull/3122/files#diff-c35c0ced4b8dc5fbe154c4ce75c85c5fR23) simply leave a bad feeling for me as there are many classes in this package which can all of a sudden access this field, although they are not supposed to do so.

> Do you see any other changes in the code under test that are not related to "visibility"?

No, I think all is about visibility.

**Comment by maggu2810** [comment]
Really?
We should use reflection to access stuff in tests instead of using the common Java visibility keywords?
You complan about the changed visibility of internal(!) bundle stuff, that is already used for testing?
So, if you prefer to use reflection this is easy to change.

If you don't want to use reflection and you don't want to change visibility (also to internal stuff), then could you give me a hint what is your prefered solution?

**Comment by kaikreuzer** [comment]
No, I don't prefer reflection.
I think you are right that it is mainly bad test design; actually, tests should use the visible parts of classes and not access their internals (nor should it be necessary to expose their internals JUST for the tests).
As you only refactored the tests to Java and that made these changes necessary, I am fine to merge it.

**Comment by maggu2810** [comment]
I assume we agree both in the argumentation of each other.
I don't want to rewrite the tests itself only port it to pure Java to solve the error in the Eclipse IDE.
Perhaps we could improve the whole Groovy and test situation some time.

**Pull request merged**
