### PR TITLE
console: add implementation for Karaf

### PR DESCRIPTION
**Pull request by maggu2810**
This PR add support for the Karaf console.

The target platform need access to one package that exports org.apache.karaf.shell.api.console.

> The manifest must not have any version constraint on package imports, unless this is thoughtfully added.

I kept the minimum version constraint for the import-package of org.apache.karaf.shell.api.console because we need at least that version (tested with the next milestone, but there have no used API changed).
So, this was done "thoughtfully".

### CODE REVIEW

**Comment by kaikreuzer** [comment]
> The target platform need access to one package that exports org.apache.karaf.shell.api.console.

Unfortunately I am having serious problems with this step. The p2 repo that I prepared (https://dl.bintray.com/kaikreuzer/esh-deps-p2/) only contains the bundle, but no feature. For adding it to a TP, we would need a feature though. Trying to create a feature, I notice that I also have to provide all the dependencies of the karaf shell bundle - which I do not want to go into.
Then I tried to configure the project to use m2e and load this single dependency from Maven Central, but I also did not succeed in this (never did it before, maybe I'm trying it a stupid way...)?
Any suggestions or help would be appreciated! If nothing else helps, I would add the jar to the repo and add it to the build path...

Besides this, we need to create new features for the io.console.x bundles, so that we can include them in the delivery (which is the p2 repository). I'd suggest to have a separate feature for each console implementation, so that solutions can pick the one they need. Could you do this or don't you exactly know where this needs to be added and so I should do it?

**Comment by kaikreuzer** [comment]
Besides this problem, the code looks good and I would merge it!

**Comment by maggu2810** [comment]
I created a p2 repo that contains the bundle org.apache.karaf.shell.api.console and one that contains some karaf dependencies (more than just the ones for the console bundle, no time for clean up and not relevant at the moment).
Every p2 repo contains one feature that contains all bundles of the repo.
After that I added that two features (and so the two p2 repositories) to the target platform.
I could build it using Eclipse IDE and using Maven + Tycho.

So, the bundle should be build and working if the target platform contains the necessary stuff.

> Besides this, we need to create new features for the io.console.x bundles, so that we can include them in the delivery (which is the p2 repository). I'd suggest to have a separate feature for each console implementation, so that solutions can pick the one they need. Could you do this or don't you exactly know where this needs to be added and so I should do it?

I could learn it. This is more time consuming, but perhaps we could save the time then the next time.

**Comment by kaikreuzer** [comment]
> I created a p2 repo

Could you maybe just provide this somewhere to me so I can make it available on Bintray? Would save me quite some time, I guess.

> I could learn it. This is more time consuming, but perhaps we could save the time then the next time.

As learning by example is always easiest, I have done this job for the equinox and rfc147 console plugins, see https://github.com/eclipse/smarthome/pull/255. Just do it the same way for Karaf in this PR.

**Comment by maggu2810** [comment]
> Could you maybe just provide this somewhere to me so I can make it available on Bintray?

Is this (https://drive.google.com/file/d/0Bx99QXY8p6gvOFprbU9uOS1lMXc/view?usp=sharing) helpful?
I am using no category for the feature, so you have to show features without categories.
I used the Eclipse p2 mirror bundle, hope this works.

**Comment by kaikreuzer** [comment]
Which one? "karaf" or "karaf-dep-mod"?

**Comment by maggu2810** [comment]
* "karaf" contains Karaf bundles only.
* "karaf-dep-mod" contains some Karaf dependencies (fetched with maven for all Karaf bundles, so this contains at the moment Karaf bundles, too).
The repos have been generated more or less automatically to check if the new console karaf bundle for ESH is working.

**Comment by kaikreuzer** [comment]
So which of the two is enough to add to the TP in order to make the console.karaf bundle compile?

**Comment by maggu2810** [comment]
> After that I added that two features (and so the two p2 repositories) to the target platform. I could build it using Eclipse IDE and using Maven + Tycho.

As stated before, I used both. You asked me to provide that one.

I used this separation to get one repository that contains all deployed Karaf bundles with no other dependencies and one, that contains the dependencies of the Karaf bundles.

If you do not want such a separation, then we could not use that one and we have to create one that suffers you / our needs.

**Comment by kaikreuzer** [comment]
Ok, sorry, I did not read carefully enough. So if we require both, I am not sure if we should really go this way. It adds 60MB to the target platform and actually brings many bundles that are already there (like javax.*, apache commons, slf4j etc.), which could easily lead to problems.
As all we need is this single jar, I think the easiest way for now would be to add it to the repo and put it on the build path of the bundle. What do you think?

**Comment by maggu2810** [comment]
If size does matter, we could
* remove all bundles that are already available through another repository
* remove all bundles that are not necessary for the org.apache.karaf.shell.console bundle

If we inspect the the number of the bundles that are currently part of the target platform (1004 selected) then we should clean this up, too.

I would prefer to go this way (it is okay, I this have do be done by me) before modify the build path.

All hard coded / bundled dependencies should be be avoided as well as possible (in my opinion).

**Comment by kaikreuzer** [comment]
> remove all bundles that are already available through another repository
> remove all bundles that are not necessary for the org.apache.karaf.shell.console bundle

Do you have any clue, how much would roughly be left?
If it is < 10 I would go for it. Otherwise, I think the m2e option might be a better choice, if we get it working.

> If we inspect the the number of the bundles that are currently part of the target platform (1004 selected) then we should clean this up, too.

Agreed. But this will be a big effort, I am afraid. A general problem is that there is only one TP for all different parts. I would actually like to split off all dependencies that are only required by the designer from the rest. Same for test and build dependencies. But this should be discussed somewhere else.

**Comment by maggu2810** [comment]
> Do you have any clue, how much would roughly be left?

No, have to do it and then count the number of bundles.

If we would clean up the other repositories or the TP (at which time ever), it makes no sense to create a repository for Karaf that contains the respective bundles and the dependencies that are currently not available in the TP. My first approach was to create a repo, that contains all the karaf dependencies, but this is also not good.

If we modify the build path and that works for Eclipse IDE and Maven + Tycho, could we create a directory, that will contain all that "work with ... without a repo" bundles. I would prefer one directory that could be handled as a local repo instead of adding such jar to the resp. bundles.
If two bundles depend on the same jar, we could avoid duplicates... and the jar is not part of the bundle it is just a dependency.

**Comment by kaikreuzer** [comment]
The m2e solution would only mean that the jar is logically added as a Maven dependency to the project. Physically, it would be located in the local Maven repo and thus exist only once. So no need to create any directory at all.
For Tycho, this should work through ```<pomDependencies>consider</pomDependencies>
``` (see https://wiki.eclipse.org/Tycho/How_Tos/Dependency_on_pom-first_artifacts)

**Comment by maggu2810** [comment]
Ah, now I understand what you are talking about. ;-)
I know, that a dependency, that was added to the pom file, is recognized if pomDependencies is set to considered (if we are using Maven + Tycho). But that does not work using Eclipse IDE.
I do not know, you to configure Eclipse to add the maven dependency without using the pom file.

Is it correct, that we have to add the dependency on two different places? The pom.xml for Maven + Tycho and another file for Eclipse IDE?

If you feel this as the best (cost-benefit ratio) way to do this, ok. I think we all would prefer the p2 repo solution, but if this is to complicated, then we should do the one with the appropriate effort.

**Comment by kaikreuzer** [comment]
> Is it correct, that we have to add the dependency on two different places? The pom.xml for Maven + Tycho and another file for Eclipse IDE?

I do not exactly know. This was my comment about m2e - my hope was that the m2e plugin would take the dependency declared in the pom (just as tycho does it) and add this as a Maven deps classpath container to the project, so that it is also available in the IDE. I didn't spend much time on investigation yet, whether this is feasible. For me it would be also ok for the moment to have it only working for the Maven build and to have compilation errors in the IDE on this project. I am currently working on a new IDE setup, which anyhow might change the situation again.

**Comment by maggu2810** [comment]
> I am currently working on a new IDE setup, which anyhow might change the situation again.

Should we wait for the new setup?

**Comment by kaikreuzer** [comment]
No, if you can live with this project being red in the workspace for the moment, let's wrap this up.

**Comment by maggu2810** [comment]
We could build "org.eclipse.smarthome.io.console.karaf" if we add the dependendy to "org.apache.karaf.shell.core" to the pom.xml (so Tycho could resolve it and no changes to the TP are necessary).

But this does not solve the problem at all.

The feature will not build because this is using the bundle (reading the Manifest, not the pom) and complains about the missing dependency, too. 
So I have to add the dependency to the feature pom.xml, too.

This have all be done, now.
But this is not a clean solution.

**Comment by kaikreuzer** [comment]
So does a "mvn clean install" work for you with this change? I still get a
```
Caused by: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from org.eclipse.smarthome.io.console.karaf 0.8.0.qualifier to package org.apache.karaf.shell.api.console 4.0.0.M2.; No solution found because the problem is unsatisfiable.]
```
(even after changing the MANIFEST.MF to 4.0.0.M2, which is currently still 4.0.0.M1)

**Comment by maggu2810** [comment]
```bash
pushd bundles/io/org.eclipse.smarthome.io.console.karaf && mvn clean install && popd
```
is working (if the pom dependency is declared in "org.eclipse.smarthome.io.console.karaf").

To get the feature working
```bash
pushd features/org.eclipse.smarthome.feature.runtime.console.karaf && mvn clean install && popd
```
I have to add the dependency also to the pom of the respective feature.

So, to get something working that is using that feature (e.g. a product), I think we have also to add that dependency to that pom.xml.

I believe that every "stuff" that is using that bundle needs this entry in the pom as long as it is not available in the TP.

**Comment by kaikreuzer** [comment]
Maybe I am stupid, but I cannot get it to build successfully. Could you please try yourself with a clean checkout of the master repo and a pull of this PR? My criteria is that it should build with a "mvn clean install" on the repo root folder.

**Comment by maggu2810** [comment]
> I believe that every "stuff" that is using that bundle needs this entry in the pom as long as it is not available in the TP.

Let's try to explain this again.

* The bundle "org.eclipse.smarthome.io.console.karaf" needs the package "org.apache.karaf.shell.api.console".
* There is no package in the target platform that exports "org.apache.karaf.shell.api.console".
* To build "org.eclipse.smarthome.io.console.karaf" using Tycho we could add "org.apache.karaf.shell.core" in the pom of that bundle. This is working caused by considering pom dependencies.
* If we want to build something that contains the bundle "org.eclipse.smarthome.io.console.karaf" Tycho tries to find a package export for "org.apache.karaf.shell.api.console" again.
* Building "org.eclipse.smarthome.feature.runtime.console.karaf" fails because there is no such bundle in the target platform.
* To build "org.eclipse.smarthome.feature.runtime.console.karaf" using Tycho we could add "org.apache.karaf.shell.core" in the pom of that bundle. So also the feature could resolve that import.
* If we want to build "org.eclipse.smarthome.repo" that contains the feature "org.eclipse.smarthome.feature.runtime.console.karaf" that contains the bundle "org.eclipse.smarthome.io.console.karaf" Tycho is still looking for a package that exports "org.apache.karaf.shell.api.console".
* To be able to build "org.eclipse.smarthome.repo" using Tycho we need to add the dependency in that pom, too.

So, to build "something" that contains the bundle "org.eclipse.smarthome.io.console.karaf" we need to add the dependency in the pom of that "something" or using a target platform that contains the dependency.

So, we could using the following patch and we could start the build at the top level, but I believe this is nothing we want to do.
```diff
diff --git a/products/org.eclipse.smarthome.repo/pom.xml b/products/org.eclipse.smarthome.repo/pom.xml
index 3209703..63373d9 100644
--- a/products/org.eclipse.smarthome.repo/pom.xml
+++ b/products/org.eclipse.smarthome.repo/pom.xml
@@ -15,4 +15,13 @@
 
   <packaging>eclipse-repository</packaging>
 
+  <!-- This dependency is added as long as the bundles are not available in a p2 repo of the target platform. -->
+  <dependencies>
+    <dependency>
+      <groupId>org.apache.karaf.shell</groupId>
+      <artifactId>org.apache.karaf.shell.core</artifactId>
+      <version>4.0.0.M2</version>
+    </dependency>
+  </dependencies>
+
 </project>
```

**Comment by kaikreuzer** [comment]
Thanks @maggu2810, now even I have understood the problem ;-)
I'd have a fairly straight-forward suggestions: As Karaf distributions anyhow do not know what to do with Eclipse features and p2 repositories, we could simply remove the org.eclipse.smarthome.io.console.karaf feature. As all bundles are deployed to the Eclipse Maven Repo (https://repo.eclipse.org/), the Karaf bundle is available there, which is anyhow the right place to be picked up by Karaf solutions. Would you agree?

**Comment by maggu2810** [comment]
I agree that we do not need to add a feature for Karaf console support.

**Comment by maggu2810** [comment]
So, I remove the last three commits but keep the dependency in the pom of the karaf console bundle (caused by missing it in the target platform)?

**Comment by kaikreuzer** [comment]
Yes, please! And you should squash the remaining commits into one.

**Comment by maggu2810** [comment]
> And you should squash the remaining commits into one

Sure ;-)

Done.

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
