### PR TITLE
Removes slider from number item on control page

### PR DESCRIPTION
**Pull request by aounhaider1**
as discussed here https://github.com/eclipse/smarthome/issues/1700#issuecomment-289928566
Signed-off-by: Aoun Bukhari <bukhari@itemis.de>

### CODE REVIEW

**Comment by htreu** [comment]
Looks good, works as described. @aounhaider1 do you mind adding `min` and `max` attributes to the input field? This way at least the stepper buttons will not allow input of values outside the given range.

**Comment by aounhaider1** [comment]
Updated

**Comment by htreu** [comment]
Its awesome to have the validation build right in with the `ng-min` and `ng-max` attributes. Nice! But the steppers will allow the input of values beyond the valid range. With additional `min` & `max` attributes this can be avoided.
Another thing: When angular reports the value as invalid its still possible to "commit" the value which will result in a `400 - Bad Request` response. Is it possible to deactivate the commit button on invalid data? See here:

screen shot 2017-05-15 at 13 56 29

The valid range is [-80;12]. The value 100 is clearly reported as being invalid, see attribute `aria-invalid="true"`

**Comment by aounhaider1** [comment]
I've added min, max validation to number and rollershutter widget. But I think we should have decent editing option on control page as well (with proper error message and so on). However, we have a limited space for items so maybe we can introduce an expandable area and show the input field in that area. Wdyt?

**Comment by htreu** [comment]
Imho the current editing function is fine. I´m just talking about the submit button when ng-min or gn-max detected an invalid value:

image

can't we disable the button then?

**Comment by aounhaider1** [comment]
It should be working with the last commit. :)

**Comment by htreu** [comment]
ready to get merged.

**Comment by sjka** [comment]
Thanks!

**Pull request merged**
