### PR TITLE
Added Stream access to elements of registries.

### PR DESCRIPTION
**Pull request by ViToni**
This change enables usage of Predicates for filtering.

Signed-off-by: Victor Toni <victor.toni@gmail.com>

### CODE REVIEW

**Comment by sjka** [comment]
looks good IMHO. However, I'd love to give @maggu2810 also a chance to comment either here or in #3281.

**Comment by tomhoefer** [comment]
shouldnt the automation stuff be java-1.5 compatible?

**Comment by sjka** [comment]
nah, some days ago you would have been right, but you missed some really good news: #3317

**Comment by tomhoefer** [comment]
nice :)

**Pull request merged**
