### PR TITLE
Sonos binding: handle Google Play Music radio

### LINKED ISSUE #3937: Radio stations titles / current album not showing in Sonos
As per https://community.openhab.org/t/google-play-music-titles-current-album-not-showing-in-sonos/29444 there is an issue with the current sonos binding where both Google Play Music radio and Apple iMusic stations do not correctly report the current track information.

# Testing

## Test setup
Test setup on a Sonos Play 5 (using line in to clear the values out in between tests). Unfortuantely I don't have spotify to test if this has any similar effects

### Song info
Track: Yellow
Album: Parachutes
Artist: Coldplay

### Sources
App | Source | Function
------|-----------|-----------
Sonos App | Google Play Music | Play Song
Sonos App | Google Play Music | Play Radio
Google Play Music App | Direct Cast | Play Song
Google Play Music App | Direct Cast | Play Radio
Sonos App | Apple Music | Play Song
Sonos App | Apple Music | Play Radio

### Test procedure
Select Line input (using line in to clear the values out inbetween tests)
Select source
items list Office_Sonos*Current* (returns all track titles and uris)

### Source: Sonos App, GPM, Play track coldplay/parachutes/yellow
Status: Works as expected
```
openhab> items list Office_Sonos*Current*
Office_Sonos_CurrentAlbum (Type=StringItem, State=Parachutes, Label=Album, Category=sonos_album, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentArtist (Type=StringItem, State=Coldplay, Label=Artist, Category=sonos_artist, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentTitle (Type=StringItem, State=Yellow, Label=Title, Category=sonos_title, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentTrack (Type=StringItem, State=Coldplay - Parachutes - Yellow, Label=Track, Category=sonos_track, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentAVtransportURI (Type=StringItem, State=x-rincon-queue:RINCON_5CAAFDF2950C01400#0, Label=AV transport URI, Category=sonos_uri, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrenttrackURI (Type=StringItem, State=x-sonos-http:A0DvPDnowsLmdMYfMSfGy6FDzGMzjnm1poiGjx8aBQ5VcRvDNEQNKg.mp3?sid=151&flags=32&sn=1, Label=track URI, Category=sonos_uri, Groups=[gSonosOffice, gAllItems])
```

### Source: Sonos App, GPM, Play radio coldplay/parachutes/yellow
Status: no track updates reported
```
openhab> items list Office_Sonos*Current*
Office_Sonos_CurrentAlbum (Type=StringItem, State=, Label=Album, Category=sonos_album, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentArtist (Type=StringItem, State=, Label=Artist, Category=sonos_artist, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentTitle (Type=StringItem, State=PC, Label=Title, Category=sonos_title, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentTrack (Type=StringItem, State=PC, Label=Track, Category=sonos_track, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentAVtransportURI (Type=StringItem, State=x-sonosapi-radio:krhZLW6MiXPmdMYfMSfGy6FDzGMzjnm1poiGjx8aBQ49QG27SV-XXw?sid=151&flags=0&sn=1, Label=AV transport URI, Category=sonos_uri, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrenttrackURI (Type=StringItem, State=x-sonosprog-http:A0DvPDnowsLmdMYfMSfGy6FDzGMzjnm1poiGjx8aBQ5VcRvDNEQNKg.mp3?sid=151&flags=32&sn=1, Label=track URI, Category=sonos_uri, Groups=[gSonosOffice, gAllItems])
```

### Source: Google Play Music App, Play track coldplay/parachutes/yellow (cast to speaker)
Status: Works as intended
```
openhab> items list Office_Sonos*Current*
Office_Sonos_CurrentAlbum (Type=StringItem, State=Parachutes, Label=Album, Category=sonos_album, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentArtist (Type=StringItem, State=Coldplay, Label=Artist, Category=sonos_artist, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentTitle (Type=StringItem, State=Yellow, Label=Title, Category=sonos_title, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentTrack (Type=StringItem, State=Coldplay - Parachutes - Yellow, Label=Track, Category=sonos_track, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentAVtransportURI (Type=StringItem, State=x-rincon-queue:RINCON_5CAAFDF2950C01400#2, Label=AV transport URI, Category=sonos_uri, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrenttrackURI (Type=StringItem, State=https://mclients.googleapis.com/music/mplay?mjck=Tts2wa7qolm45thek4yd6wh64za&pt=a&dv=1&slt=1501592441499&sig=FxfvkHTWXs1cBvFBh8Dn0NFE6OI, Label=track URI, Category=sonos_uri, Groups=[g
SonosOffice, gAllItems])
```

### Source: Google Play Music App, play radio coldplay/parachutes/yellow
Status: Working as intended
```
openhab> items list Office_Sonos*Current*
Office_Sonos_CurrentAlbum (Type=StringItem, State=Parachutes, Label=Album, Category=sonos_album, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentArtist (Type=StringItem, State=Coldplay, Label=Artist, Category=sonos_artist, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentTitle (Type=StringItem, State=Yellow, Label=Title, Category=sonos_title, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentTrack (Type=StringItem, State=Coldplay - Parachutes - Yellow, Label=Track, Category=sonos_track, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentAVtransportURI (Type=StringItem, State=x-rincon-queue:RINCON_5CAAFDF2950C01400#6, Label=AV transport URI, Category=sonos_uri, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrenttrackURI (Type=StringItem, State=https://mclients.googleapis.com/music/mplay?mjck=Tts2wa7qolm45thek4yd6wh64za&pt=a&dv=1&slt=1501592521120&sig=8EijmtKkc_V4jiyhXrA2Bah-2x0, Label=track URI, Category=sonos_uri, Groups=[g
SonosOffice, gAllItems])
```

### Source: Sonos App, Apple Music, play track coldplay/parachutes/yellow
Status: Works as expected
```
openhab> items list Office_Sonos*Current*
Office_Sonos_CurrentAlbum (Type=StringItem, State=Parachutes, Label=Album, Category=sonos_album, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentArtist (Type=StringItem, State=Coldplay, Label=Artist, Category=sonos_artist, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentTitle (Type=StringItem, State=Yellow, Label=Title, Category=sonos_title, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentTrack (Type=StringItem, State=Coldplay - Parachutes - Yellow, Label=Track, Category=sonos_track, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentAVtransportURI (Type=StringItem, State=x-rincon-queue:RINCON_5CAAFDF2950C01400#0, Label=AV transport URI, Category=sonos_uri, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrenttrackURI (Type=StringItem, State=x-sonos-http:song%3a1122782283.mp4?sid=204&flags=8224&sn=2, Label=track URI, Category=sonos_uri, Groups=[gSonosOffice, gAllItems])
```

### Source: Sonos App, Apple Music, play radio coldplay/parachutes/yellow
Status: no track updates reported
```
openhab> items list Office_Sonos*Current*
Office_Sonos_CurrentAlbum (Type=StringItem, State=, Label=Album, Category=sonos_album, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentArtist (Type=StringItem, State=, Label=Artist, Category=sonos_artist, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentTitle (Type=StringItem, State=PC, Label=Title, Category=sonos_title, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentTrack (Type=StringItem, State=PC, Label=Track, Category=sonos_track, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrentAVtransportURI (Type=StringItem, State=x-sonosapi-radio:radio%3ara.1122782283?sid=204&flags=0&sn=2, Label=AV transport URI, Category=sonos_uri, Groups=[gSonosOffice, gAllItems])
Office_Sonos_CurrenttrackURI (Type=StringItem, State=x-sonosprog-http:song%3a1122782283.mp4?sid=204&flags=8224&sn=2, Label=track URI, Category=sonos_uri, Groups=[gSonosOffice, gAllItems])
```

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #3937

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
Please wait, I think I made an unnecessary (wrong) distinction between tunein radio and GPM radio when handling sound notification s.

**Comment by lolodomo** [comment]
Change done; ready for review and merge.

**Comment by lolodomo** [comment]
Travis is failing in Eclipse SmartHome Core Binding XML Tests on something that cannot have a link with my current change.

In my local environment, the Maven build is failing earlier in Eclipse SmartHome Core Tests with something else without any link with my change? I will open an issue for that.

**Comment by lolodomo** [comment]
@kgoderis : any chance that you review this little change ?

**Comment by maggu2810** [comment]
> @kgoderis : any chance that you review this little change ?

I don't think so. See here: https://github.com/eclipse/smarthome/issues/3912#issuecomment-320511933

**Comment by lolodomo** [comment]
Thank you

**Pull request merged**
