### PR TITLE
Custom Extensions in the Synthetic Bundle Installer

### PR DESCRIPTION
**Pull request by dstivanov**
Added an option in the Synthetic Bundle installer to add only defined set of extensions. Otherwise the default extensions will be used.

Signed-off-by: Dimitar Ivanov dstivanov@gmail.com

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@dstivanov Did you check the Travis logs? They end with:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.eclipse.smarthome.config.xml.test.ConfigDescriptionsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.096 sec - in org.eclipse.smarthome.config.xml.test.ConfigDescriptionsTest
assert that ConfigDescriptions of fragment host were loaded properly(org.eclipse.smarthome.config.xml.test.ConfigDescriptionsTest)  Time elapsed: 0.546 sec
assert that ConfigDescriptions were loaded properly(org.eclipse.smarthome.config.xml.test.ConfigDescriptionsTest)  Time elapsed: 0.209 sec
Running org.eclipse.smarthome.config.xml.test.AbstractAsyncBundleProcessorTest

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

Can this stalling be related to your PR? Or would you say it is safe to merge?

**Comment by maggu2810** [comment]
I have retriggered the Travis CI build, let's see how it finishes.

**Comment by kaikreuzer** [comment]
@maggu2810 What is your trick to retrigger it?

**Comment by maggu2810** [comment]
No "trick": Open the Travis CI site and call retrigger
I will add a screenshot soon...

**Comment by maggu2810** [comment]
trigger

**Comment by kaikreuzer** [comment]
Merci beaucoup!

**Comment by kaikreuzer** [comment]
And the tests have passed this time, so I guess we can merge.

**Pull request merged**
