### PR TITLE
clean pom.xml (indentation, trailing whitespace, line break)

### PR DESCRIPTION
**Pull request by maggu2810**
Bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=464281

### CODE REVIEW

**Comment by dnobel** [comment]
You really like uniformity, right? :). I agree, that it is good clean up all files and have a common format for pom files.

@kaikreuzer Do we need a CQ for formatting, as this is a major contribution with over 2000 lines of changes?

**Comment by maggu2810** [comment]
Sure, I prefer a common format. ;-)

I am using the "ignore-whitespace" switch of git diff command to check that there are only changes of the format and no other ones.

<pre>
git diff 6a45d40ead2afe7644faaaa598f3470e7869d2bb..69b79c823f5c3ad04646ea0e3197dd616b15fee0
</pre>
<pre>git diff -w 6a45d40ead2afe7644faaaa598f3470e7869d2bb..69b79c823f5c3ad04646ea0e3197dd616b15fee0</pre>

**Comment by teichsta** [comment]
regarding "Tabs vs. Whitespaces"

As far as i remember the Yoxos IDE makes use of the Standard Eclipse Formatter which uses Tabs in favour of Whitespaces. How should we deal with that?

**Comment by maggu2810** [comment]
The formatter is used for java files, not for XML.

**Comment by maggu2810** [comment]
But the difference would be 2 spaces for pom.xml and 4 spaces for java indentation (not spaces vs. tabulators).

**Comment by kaikreuzer** [comment]
> Do we need a CQ for formatting, as this is a major contribution with over 2000 lines of changes?

As the PR does not change a single character, but really only tabs and spaces, I think we can ommit creating a CQ for it as there is really no IP involved here.

**Pull request merged**
