### PR TITLE
added import required on Linux for charts

### PR DESCRIPTION
**Pull request by kaikreuzer**
fixes https://github.com/openhab/openhab-distro/issues/118

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
What is necessary to reproduce this error?

If I enter the chart url the log shows:
```text
2016-02-04 09:58:56,574 | WARN  | tp1402830325-154 | ChartServlet                     | 194 - org.eclipse.smarthome.ui - 0.8.0.b3 | Illegal argument in chart: No Persistence service found.
```
and the page shown is empty.

After that I installed "mvn:org.openhab.persistence/org.openhab.persistence.rrd4j/1.9.0-SNAPSHOT".
If I enter the chart url, I see an empty chart.

Can I use a certain openhab2-distro (which setup?) to reproduce it on my machine?

**Comment by kaikreuzer** [comment]
> Can I use a certain openhab2-distro (which setup?) to reproduce it on my machine?

Just use the default demo setup and click on "Outside Temperature" of the Classic UI.
And make sure that you are using an X11-based system :-)
@xsnrg, Can you provide details on what hardware/OS this happens for you?

**Comment by maggu2810** [comment]
Will check that.

**Comment by maggu2810** [comment]
> Just use the default demo setup and click on "Outside Temperature" of the Classic UI.

1. I downloaded the "openhab-offline-2.0.0.b2.zip" from bintray
2. I started openHAB
3. I went to the Classic UI
4. I clicked on "Outside Temperature"
5. I see an empty graph

I repeated steps 3. and 4. (after a few minutes) and see now a blue line.

Ah and to be sure:
* I am using a X11-based system

I would like to delay further inspection (reading the code) until @xsnrg could give me some steps to reproduce it on my Linux system.

**Comment by kaikreuzer** [comment]
Maybe this setting could resolve the issue as well: http://stackoverflow.com/a/8094703

**Comment by kaikreuzer** [comment]
I would assume that it should help, see http://stackoverflow.com/a/1688269:
The class used changes from `sun.awt.X11GraphicsEnvironment` to `sun.java2d.HeadlessGraphicsEnvironment`.

I'll therefore close this PR for now and we can discuss on the openhab-distro.

**Pull request closed without merging**
