### PR TITLE
Injecting the I18nProvider into the ConfigStatusProvider by the Confi…

### PR DESCRIPTION
**Pull request by tomhoefer**
…gStatusService to make it more convenient to provide a internationalized ConfigStatusMessage

Signed-off-by: Thomas Höfer <t.hoefer@telekom.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
lgtm in general.
We should note that this is a backward compatibility breaking chance. Is it correct that this interface is not used anywhere in the existing ESH code?
Btw, do we already have this functionality covered in the documentation? I couldn't find any reference there...

**Comment by tomhoefer** [comment]
In theory this is a breaking change.... However in ESH this feature isn´t used and in our project we are going to implement the first bindings that provide the config status... For this reason in our project there are ony some tests to be adopted....

Furthermore, I had documented the feature [here](http://www.eclipse.org/smarthome/documentation/development/bindings/xml-reference.html) and [here](http://www.eclipse.org/smarthome/documentation/development/bindings/thing-handler.html)

**Comment by kaikreuzer** [comment]
Ok, thanks.
As there is nowhere any code implementing this interface, it would imho be nice to have at least a short example in the documentation, showing how to use the I18nProvider and what to return exactly, what do you think?

**Comment by tomhoefer** [comment]
Fine for me.. I suggest to add the example to the XML reference page because the concept of the config status provider is independent on the thing entity... ok for @kaikreuzer?

**Comment by kaikreuzer** [comment]
Yes, it makes sense not to put it in the binding docu for this reason. Nonetheless, it has nothing to do with XML either, has it? I think we might need to move all the "config description" stuff to a separate section in https://github.com/eclipse/smarthome/tree/master/docs/documentation/concepts. This is of course not related to this PR, but maybe still a good opportunity to do so, if you have a little spare time...?

**Comment by tomhoefer** [comment]
No, you are right... It hasn´t anything to do with XML... Could we agree that you merge this PR and I will create a separate PR for the documentation stuff (containing also an exmaple how to use ConfigStatusProvider) until end of this week?

**Comment by kaikreuzer** [comment]
Fine with me. I leave the merging to @maggu2810, though :-)

**Comment by maggu2810** [comment]
Why do we need a mandatory dependency and not an optional one?
If there is no i18n interface injected, we could skip the translation at all.

The current XmlThingTypeProvider implementation of the function to get localized thing types can also handle a non existing i18n provider.

I added the locale parameter to some REST interfaces some time ago.
I do not remember that any function that handle the translation uses a supplied i18n manager, they all injected it themselves.
But as the most functions that handles the translation already exists, I could be wrong.

Why do we now start adding the i18n provider as an argument and why it is changed for one function only?

**Comment by tomhoefer** [comment]
First of all we injected the I18nProvider into the ConfigStatusProvider to make it convenient for our binding developers to provided localized ConfigStatusMessages.

I made it as mandatory dependency because we definitely need correct localized messages in our UI. So if the messages are provided in a wrong language then this will result in a bug.

**Comment by maggu2810** [comment]
A provided I18nProvider object does still not guarantee that a message could be localized. Using the non-localized message if there is no translation is a convenient method. So IMHO it should always be okay to use the non-localized message if there is no I18nPrivder.

There is a I18nProvider implementation in the org.eclipse.smarthome.core bundle, so I assume that every system has one.

I am just a little bit confused because this is the only function that inject a i18n provider to the function that should handle the translation.
Don't know if this fits to the other code or we should change this, too.

I would assume that the implementations that trigger the translation have to reference an I18nProvider implementation and not use an injected one.

If we want to inject the I18nProvider why only for that function and not for all?
Which I18nProvider should be used?
If my implementation uses a custom one, should I drop the given one and am I allowed to use another one?

**Comment by maggu2810** [comment]
> Fine with me. I leave the merging to @maggu2810, though :-)

@kaikreuzer as you are fine with this PR, perhaps you could give me some more details. It looks that this PR makes the current i18n handling a little bit inconsistent. Didn't it?

**Comment by maggu2810** [comment]
@tomhoefer I could be wrong, just to want ensure we use a consistent implementation. Perhaps it is more clear to me if we get into details.

**Comment by kaikreuzer** [comment]
It would probably be helpful to already have the PR with some example code...
This PR is only relevant for anybody implementing a `ConfigStatusProvider`, which so far is not yet the case within the ESH code.
The nice thing is that you can make your ThingHandler implement this interface and the Thing framework will automatically register you as a `ConfigStatusProvider` - so you do not have to deal with this yourself. As any implementation will need the I18NProvider though, there are two options:

1. Within your ThingHandlerFactory, you have to get hold of the I18NProvider and pass it yourself to the ThingHandler (which implements ConfigStatusProvider), e.g. through the constructor or a setter method.
2. You receive the I18NProvider service as a parameter to the method, where you are supposed to use it.

The second option is much more convenient for the developer.
Wrt "consistent implementation": For components that you declare through DS, I absolutely agree that you should declare this service dependency and get it injected directly. A ConfigStatusProvider is in 99% of all cases no DS component, though. So serving it the services that it needs through other means is imho ok.

**Comment by tomhoefer** [comment]
In our project we have to ensure that there are translations for each i18n key in every supported language. If there is a translation missing then this is a bug to be fixed. For this reason it will not be sufficient to use the non-localized message.

However the intention of this PR is to inject the I18nProvider into the ConfigStatusProvider operation to make it convenient for our binding developers to provide localized config status messages. If we don´t inject the I18nProvider into the ConfigStatusProvider operation then each binding developer would have to develope something like a I18nProviderServiceTracker or I18nProviderServiceBinder which would result in a lot of code duplicates in the context of bindings what I would like to avoid. In my opinion it makes absoultely sense to inject the I18nProvider.

Furthermore we cannot compare the concept of the ConfigStatusProvider with the existing providers and registries of ESH that handle translations. For this reason we should not change the injection / handling of the I18nProvider there.

**Comment by tomhoefer** [comment]
Haven´t seen Kai´s comment... Of course you could also inject the I18nProvider into the handler factory by means of DS...

**Comment by maggu2810** [comment]
All bindings I know are using DS. So adding a reference is not a big impact. And so every binding already uses OSGi functionalities.

The nice thing that a TingHandler could implement that interface and all is done automatically is fine, but as you pointed already out (point 1) the thing handler is created by the thing handler factory and the thing handler factory is already a DS.
If the ConfigStatusProvider is in 99% of all cases no DS component, I assume it is generated by a DS or the bundle activator.

Another point I do not understand (perhaps because of the missing code) if "every" config status should be localized (if possible), why is this not handled more generic.
The config status is returned by the binding and the core framework is using the i18n provider to translate it.
Is the config status build by multiple partitions that are translated separately?
The I18nProvider is using files in ESH-INF/i18n. So if you use this provider the translation is already part of files in that directory.

Can't we replace "return configStatusProvider.getConfigStatus(i18nProvider, loc);" in "ConfigStatusService.java" to something so the binding developer does not need to know I18nProvider at all (if you want to hide that stuff from the developers)?
getConfigStatus could return an object that contains the relevant information (the i18n provider already supports a method if additional arguments are to be injected into the localized text) and the translation is done in the ConfigStatusService by the information returned by getConfigStatus?


Last but not least, it will be up to you. In a binding I never used the I18nProvider directly. I used the ESH-INF/i18n files in bindings and the framework do the translation.
Without code it will be all a theoretical discussion and perhaps it is difficult to explain me all the points (why it can't be done by the framework the same way as it is done for ThingTypes, etc.).

**Comment by tomhoefer** [comment]
HI @maggu2810, I have updated this PR so that YahooWeather things provide a config status now. We can use this code as basis for our discussions...

Yes, we could also hide the I18nProvider for Binding Developers... Then the signature of ConfigStatusProvider#getConfigStatus would be without any parameter and we would have to introduce a new Type (e.g. ConfigStatusMessageDescription) containing the messageKey (for translation), the type of the message(ERROR, WARNING, ...) and optional parameters. Furthermore the ConfigStatusProvider would have to expose the bundle in order to be able to translate the messages. For this reason this would be the new ConfigStatusProvider interface:

```
Collection<ConfigStatusMessageDescription> getConfigStatus();
boolean supportsEntity(String entityId);
void setConfigStatusCallback(ConfigStatusCallback configStatusCallback);
Bundle getBundle();
```

**Comment by tomhoefer** [comment]
@maggu2810 Just a reminder ... I would like to get your feedback / opinion / comments regarding this PR ....

**Comment by kaikreuzer** [comment]
@tomhoefer Can we get rid of the `getBundle()` requirement if we would use `FrameworkUtil.getBundle()`?

**Comment by tomhoefer** [comment]
Sure... if this is the preferred solution ...

**Comment by maggu2810** [comment]
@tomhoefer I have not forgotten this PR, have to finish another project at the moment. Will continue this one as soon as possible.

**Comment by maggu2810** [comment]
@tomhoefer Does something speak against using the "generic" approach, so a binding does not need to use the i18n provider themselves at all? At the moment I see no real pro / cons for the different methods. I would prefer if the translation could be done in a more central way, because currently it is handled such way for the other translations. And I do not get the point why we should handle this differently for the config status now. But perhaps I do not see them.
If you would like to do more behind the scenes, so a binding developer does not need to know all details, I think this is also a pro hiding the i18n provider at all.

**Comment by tomhoefer** [comment]
@maggu2810 No, there is nothing that speaks against the generic approach. I will change the code in the manner that the I18nProvider (and also the locale) will not be longer injected into the getConfigStatus operation

I will close this PR and create a new one as soon as I have implemented the feature

Thank you very much for your feedback

**Pull request closed without merging**
