### PR TITLE
moved all Classic UI resources under /classicui and added some basic …

### PR DESCRIPTION
**Pull request by kaikreuzer**
…test setup

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
See also https://github.com/openhab/openhab/issues/2742

**Comment by dnobel** [comment]
Should this PR allow to use the Classic UI out-of-the-box with ESH?

Because if I use your branch and I´m starting ESH with the checked-in .launch file, on the one hand the logs says "15:51:09.259 INFO  o.e.s.u.c.i.s.WebAppServlet[:85] - Started Classic UI at /classicuiapp". I guess the path is "/classicui/app.

On the other hand, If I call "/classicui/app" a 500 is thrown, because that exception occurred: javax.servlet.ServletException: Sitemap 'default' could not be found

If I access "/classicui" I get a 403 Forbidden, without any logs.

So what is the path of the Classic UI and should it work?

**Comment by dnobel** [comment]
OK, think I got it. The UI is shown if use http://localhost:8080/classicui/app?sitemap=demo. But at least the log is wrong.

**Comment by dnobel** [comment]
Shouldn't we change the "default" sitemap name to "demo" or rename the "demo" sitemap to "default"?

**Comment by kaikreuzer** [comment]
Good points. I have corrected the logging message and set the default sitemap to "demo" in smarthome.cfg, so that you can now access it at http://localhost:8080/classicui/app

**Comment by dnobel** [comment]
Now it works like a charm :)

**Pull request merged**
