### PR TITLE
PaperUI updates/cleanup

### LINKED ISSUE #676: Minify PaperUI sources during build
In order to increase loading speed and reduce network traffic, the sources for the Paper UI should be minified in a build step.
Also, it makes sense to look into merging as many files together as possible, in order to reduce the number of HTTP requests.

### PR DESCRIPTION
**Pull request by GradyD**
This is the start of major cleanup coming to the PaperUI. It also fixes #676, granted 676 should probably be expanded so that all of the UI packages are built if needed.

Signed-off-by: Grady Duncan gradyduncan@gmail.com

### CODE REVIEW

**Comment by GradyD** [comment]
Note, I have added the signed off by in the original message of the PR as well as signing the CLA on https://projects.eclipse.org.

**Comment by hakan42** [comment]
Instead of checking in all the bower components, you could set up a packages.json or bower.json (sorry, the right name eludes me at the moment ) and run "bower install" as a build step in the maven pom. This works excellently in one of my other projects.

**Comment by kaikreuzer** [comment]
> This is the start of major cleanup coming to the PaperUI

Please discuss any major changes with @sja and @aounhaider1 to make sure that any ongoing development is synced with that.

> Instead of checking in all the bower components, you could set up a packages.json or bower.json

This is what is currently done - we should indeed not check in the stuff in the repo. @GradyD Any reason why you added them here?

**Comment by GradyD** [comment]
Sorry about that. I migrated all of the source files over a web-src so that when gulp builds it moves the 'compiled' files over to web. I forgot to update the .gitignore to add web-src, which has been updated with the last commit.

**Comment by GradyD** [comment]
Ok, I'm going to call this good. Can you tell me what I need to do so that the checks will pass?

**Comment by kaikreuzer** [comment]
> Can you tell me what I need to do so that the checks will pass?

You will need to squash your commits into a single one with the correct signed-off footer.
But you can wait until the PR is reviewed as you might need some additional changes first.

As I don't think I am the best choice for the review, I would like to ask either @sja or @aounhaider1 to do the review.

**Comment by kaikreuzer** [comment]
One fact that looks weird to me is that Github says this PR has "73 changed files with 8,673 additions and 78 deletions."

This sounds a bit odd - why should you have to add so many additional code without removing anything...?

**Comment by hakan42** [comment]
Most of those 78 deletions are in index.html

**Comment by GradyD** [comment]
Sounds good on waiting for review. 

As far as the additions/deletions go @hakan42 is correct. Most of the deletions are within the index.html as I adjusted to point to the minified files. 

I also converted most of the CSS over to SASS. This allows for cleaner CSS because it is broken out into sections. For example, all the CSS related to buttons can be found in buttons.scss. It also allows easier changes at build and helps prevent duplicate selectors. When I was going through I found a few instances where CSS selectors would be duplicated instead of combined into 1. 

I also took the current web folder and copied to and renamed it web-src. So all of the uncompiled files can be found in web-src but the final builds can be found in web, this probably caused most of the additions. The benefit of this is that your dist folder is not cluttered with things needed for your working directory. I haven't included all of the changes to clean up the dist folder as I did not want to break the dist folder until I knew this would work.

**Comment by kaikreuzer** [comment]
> As far as the additions/deletions go @hakan42 is correct.

Well, I wasn't worried about the 78 deletions, but rather about the 8673 additions!

> I also took the current web folder and copied to and renamed it web-src.

It should really better be a move and no copy, so that in git it is also reflected as s moved file and thus its history is kept. Since the web/bower_components is only filled during the Maven build, I think the rest of the web folder can be filled at the same time and we do not need any files committed to the repo. Having duplicate code in the repo is always a bad thing that should be avoided.

**Comment by hakan42** [comment]
Actually did you copy/add a new directory web-src or did you run a "git mv"? In the second case, git would keep all the necessary metadata to "know" where the file came from so the history of a file can be much easier be followed.

**Comment by GradyD** [comment]
I did a new directory named web-src. 

I'm still having some issues with my build environment that made me question doing a rename of /web ([should be resolved soon](https://www.eclipse.org/forums/index.php/t/1073385/))

@kaikreuzer you are correct in that /web is not needed until build and it should be created when you run gulp build from maven. I will crack open a new branch and work on migrating the changes over so that the history is kept.

**Pull request closed without merging**
