### PR TITLE
Xtext 2.8.4 update

### PR DESCRIPTION
**Pull request by R-Edelhoff**
Migrate to latest xtext version

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hi @R-Edelhoff, I have just tested this PR.
During the Maven build, it fails with the ScriptEngineOSGiTest - I didn't yet debug why.
But the good news is: When running the Maven build without tests, it succeeds now! So the problems with the Xtend generator seems to be solved.
Nonetheless, the build result seems to have some problems. Trying to run the Designer, I only get an error window saying "The SmartHome-Designer executable launcher was unable to locate its 
companion shared library."

**Comment by kaikreuzer** [comment]
I tried it on a different computer, still failing tests:
```
Running org.eclipse.smarthome.model.script.tests.scriptengine.ScriptEngineOSGiTest
log4j:WARN No appenders could be found for logger (org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser).
log4j:WARN Please initialize the log4j system properly.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.307 sec <<< FAILURE! - in org.eclipse.smarthome.model.script.tests.scriptengine.ScriptEngineOSGiTest
testInterpreter(org.eclipse.smarthome.model.script.tests.scriptengine.ScriptEngineOSGiTest)  Time elapsed: 0.961 sec  <<< ERROR!
org.eclipse.smarthome.model.script.engine.ScriptParsingException: 
			S ___ witch1.state = O ___ N
			Switch1.state = OFF
			Switch1.state = ON

			Switch1.state
		
   1. Couldn't resolve reference to JvmIdentifiableElement 'Switch1'.; line 2, column 4, length 7
   2. Couldn't resolve reference to JvmIdentifiableElement 'ON'.; line 2, column 20, length 2
   3. Couldn't resolve reference to JvmIdentifiableElement 'Switch1'.; line 3, column 26, length 7
   4. Couldn't resolve reference to JvmIdentifiableElement 'OFF'.; line 3, column 42, length 3
   5. Couldn't resolve reference to JvmIdentifiableElement 'Switch1'.; line 4, column 49, length 7
   6. Couldn't resolve reference to JvmIdentifiableElement 'ON'.; line 4, column 65, length 2
   7. Couldn't resolve reference to JvmIdentifiableElement 'Switch1'.; line 6, column 72, length 7
	at org.eclipse.smarthome.model.script.runtime.internal.engine.ScriptEngineImpl.parseScriptIntoXTextEObject(ScriptEngineImpl.java:108)
	at org.eclipse.smarthome.model.script.runtime.internal.engine.ScriptEngineImpl.newScriptFromString(ScriptEngineImpl.java:74)
	at org.eclipse.smarthome.model.script.engine.ScriptEngine$newScriptFromString.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.eclipse.smarthome.model.script.tests.scriptengine.ScriptEngineOSGiTest.testInterpreter(ScriptEngineOSGiTest.groovy:60)
```

**Comment by kaikreuzer** [comment]
@dnobel & @maggu2810: Could one of you try this PR locally to see if the maven build works smoothly? For me it fails, but @R-Edelhoff does not see any problems. Would be good to have somebody else test as well.

**Comment by kaikreuzer** [comment]
Oops - update: @R-Edelhoff CAN reproduce it, so there is no need for anyone else to check it. Sorry for bothering :-)

**Comment by kaikreuzer** [comment]
@R-Edelhoff Did you find any time to further investigate this problem?

**Comment by R-Edelhoff** [comment]
Im afraid i had no time to take a deeper look at it untill now due to some urgend tasks... I guess this week will be more time for this investigation

**Comment by kaikreuzer** [comment]
FTR: https://bugs.eclipse.org/bugs/show_bug.cgi?id=477973
We came across this problem when working on this PR as well. Let's hope that this will be solved on the Xtext side.

**Comment by kaikreuzer** [comment]
As just analyzed together:
The failing test is indeed correct. When parsing scripts, neither items nor types (like 'ON') can be resolved. Interestingly, rules can be parsed and their embedded scripts are executed successfully.

When launching "SmartHome Runtime" launch config, there is also a problem with parsing the demo.sitemap. The following exception is thrown:
```
5:10:19.724 INFO  o.e.s.m.c.i.ModelRepositoryImpl[:86] - Loading model 'demo.sitemap'
15:10:19.985 WARN  o.e.x.c.i.AbstractDeclarativeValueConverterService[:138] - Only terminal rules are supported by lexer based converters but got Icon which is an instance of ParserRule
java.lang.IllegalArgumentException: Only terminal rules are supported by lexer based converters but got Icon which is an instance of ParserRule
	at org.eclipse.xtext.conversion.impl.AbstractLexerBasedConverter.setRule(AbstractLexerBasedConverter.java:128)
	at org.eclipse.xtext.conversion.impl.AbstractDeclarativeValueConverterService.internalRegisterForClass(AbstractDeclarativeValueConverterService.java:128)
	at org.eclipse.xtext.conversion.impl.AbstractDeclarativeValueConverterService.getConverters(AbstractDeclarativeValueConverterService.java:95)
	at org.eclipse.xtext.conversion.impl.AbstractDeclarativeValueConverterService.getConverter(AbstractDeclarativeValueConverterService.java:83)
	at org.eclipse.xtext.conversion.impl.AbstractDeclarativeValueConverterService.toValue(AbstractDeclarativeValueConverterService.java:74)
	at org.eclipse.xtext.parser.DefaultEcoreElementFactory.getTokenValue(DefaultEcoreElementFactory.java:90)
	at org.eclipse.xtext.parser.DefaultEcoreElementFactory.set(DefaultEcoreElementFactory.java:69)
	at org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser.set(AbstractInternalAntlrParser.java:319)
	at org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser.setWithLastConsumed(AbstractInternalAntlrParser.java:330)
	at org.eclipse.smarthome.model.parser.antlr.internal.InternalSitemapParser.ruleSitemap(InternalSitemapParser.java:285)
	at org.eclipse.smarthome.model.parser.antlr.internal.InternalSitemapParser.ruleSitemapModel(InternalSitemapParser.java:183)
```

**Comment by kaikreuzer** [comment]
I've successfully tested the Maven build, the IDE and the the runtime - it all looks good.
Nonetheless, I would like to ask you for a further change in the PR: As time has passed, the version 2.8.4 will be outdated as of tomorrow: https://projects.eclipse.org/projects/modeling.tmf.xtext/releases/2.9.0
So it would be great if you could directly move to 2.9.0, hoping that this does not require any further code changes.

**Comment by kaikreuzer** [comment]
FTR: We just tried to update to Xtext 2.9.0, but found a bug that prevents us to do so: https://bugs.eclipse.org/bugs/show_bug.cgi?id=484018

So we will revert this PR back to Xtext 2.8.4 and will have to wait for Xtext 2.9.1 for the upgrade.

**Comment by kaikreuzer** [comment]
@maggu2810: Note that this merge will have quite some impact on the target platform some versions have changed; this will require an update of your shk features as soon as we create the next stable build. We should therefore synchronize us on when is the best moment.

**Comment by maggu2810** [comment]
Are the bundles of this Xtext version (all related ones) available using Maven (e.g. in the Eclipse Repository)?

**Comment by kaikreuzer** [comment]
It looks as if they even deploy their stuff to Maven Central: http://mvnrepository.com/artifact/org.eclipse.xtext/org.eclipse.xtext

**Comment by maggu2810** [comment]
I checked two artifacts now. Both are missing OSGi information, just a non-OSGi manifest...

http://mvnrepository.com/artifact/org.eclipse.xtext/org.eclipse.xtext/2.8.4
http://mvnrepository.com/artifact/org.eclipse.xtext/org.eclipse.xtext.xbase.lib/2.8.4

**Comment by kaikreuzer** [comment]
Indeed :-(
I wouldn't have expected that. I will ask at the Xtext forum why this is the case.

**Comment by kaikreuzer** [comment]
It seems to be solved on 2.9.0 already though: http://repo1.maven.org/maven2/org/eclipse/xtext/org.eclipse.xtext/2.9.0/org.eclipse.xtext-2.9.0.jar
So maybe we have to stay with your own repo for the moment, until 2.9.1 is released.

**Comment by maggu2810** [comment]
If you build Eclipse SmartHome the bundles fetched from p2 are added to the local maven repository using group id org.osgi.bundle, artifact id = bsn, version = bundle-version.

So I could use that one -- for the moment, as it is not the best solution.

There are the tree additional Equinox bundles I bumped, too.
Two of the three has been pushed (by someone other - non official IMHO) to Maven Central.
So only one file I need adding myself.

Could you have a look at the three bundles?
Perhaps they are available add some Eclipse repo (they are part of the official SDK).
* org.eclipse.equinox.common_3.7.0.v20150402-1709.jar
* org.eclipse.equinox.registry_3.6.0.v20150318-1503.jar
* org.eclipse.equinox.supplement_1.6.0.v20141009-1504.jar

If there is no maven repo but a p2 one, we could add (also for Xtext) a eclipse maven tycho configuration that will download that bundles and we could use it using org.osgi.bundle/.../...
For that Tycho stuff I need your help.

There is one exception that raised in the log if Karaf tries to restart bundles:
```text
Caused by: java.lang.ClassNotFoundException: org.eclipse.core.runtime.OperationCanceledException cannot be found by org.eclipse.xtext.xbase_2.8.4.v201508050135
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_66]
```

I added a question here:
https://www.eclipse.org/forums/index.php/m/1717267/#msg_1717267

But it seems to be working... Let's have a further look at...

**Comment by kaikreuzer** [comment]
Well, not official at all, but I found
http://repo1.maven.org/maven2/org/eclipse/scout/sdk/deps/
which contains common and registry and
http://repo1.maven.org/maven2/com/github/adedayo/eclipse/sdk/org.eclipse.equinox.supplement/1.6.0/

Does this help?

**Comment by kaikreuzer** [comment]
> There is one exception that raised in the log if Karaf tries to restart bundles

Which wasn't there with Xtext 2.6.2, right? So maybe we should investigate, what might have changed about xtext.xbase since then?

**Comment by maggu2810** [comment]
> http://repo1.maven.org/maven2/org/eclipse/scout/sdk/deps/
> which contains common and registry

That are already used in the shk feature.

> http://repo1.maven.org/maven2/com/github/adedayo/eclipse/sdk/org.eclipse.equinox.supplement/1.6.0/

Also already tested, but that does not seem to be an OSGi bundle.

**Comment by maggu2810** [comment]
> this will require an update of your shk features as soon as we create the next stable build. We should therefore synchronize us on when is the best moment.

All fine, you could proceed...

I worked around the CNFE:
* maggu2810/openhab2-mvn-repo@f0599dc
* maggu2810/shk@aa6d123a98937839bdcd71849b064036763f1327

**Comment by kaikreuzer** [comment]
Ok, I have just released a new ESH stable, so let's adapt openHAB accordingly. I'll have a look at the "normal" distro first.

**Comment by kaikreuzer** [comment]
>  I'll have a look at the "normal" distro first.

Argh, I of course now have the NCDFE there, because the targetplatform is resolved from the official Xtext site... What shall we do? Live with it for the moment as the exceptions do not seem to have any negative effect?

**Comment by kaikreuzer** [comment]
Just noticed that the Xtext upgrade also brought a bug in the sitemap parsing - in openHAB 2, many icons are now missing, since the sitemap rest resource is returning values in quotes.
I am tempted to revert the whole Xtext upgrade again for now. @maggu2810, what do you think?

**Comment by maggu2810** [comment]
> what do you think?

Drop Xtext :wink: 

> Argh, I of course now have the NCDFE there, because the targetplatform is resolved from the official Xtext site

Should we use a custom Xtext site for openHAB?

> many icons are now missing, since the sitemap rest resource is returning values in quotes

Hm, is this an upstream change? Will this also occur on Xtext 2.9?

> I am tempted to revert the whole Xtext upgrade again for now

Perhaps we should to that for the master and create an xtext branch, to prepare a migration

**Comment by kaikreuzer** [comment]
> Should we use a custom Xtext site for openHAB?

Quite some effort that I do not really want to invest.

> Hm, is this an upstream change? Will this also occur on Xtext 2.9?

This is because @R-Edelhoff thought that this code https://github.com/eclipse/smarthome/pull/456/files#diff-6477a62b80b253a3111f0e9b75b9737dL22 was without effect and has removed it... So this needs to be correctly ported in ESH.

I will revert this PR and hope that @R-Edelhoff could have a new try based on Xtext 2.9.1-SNAPSHOT.

**Comment by maggu2810** [comment]
If 2.8.4 is used by ESH master now, shouldn't we fix this for that version, too?
If you cannot use the current master for openHAB 2 now, it seems broken to me and this should be fixed soon.

**Comment by kaikreuzer** [comment]
> If you cannot use the current master for openHAB 2 now, it seems broken to me and this should be fixed soon.

That's why I am reverting ESH back to Xtext 2.6.2 again, so that we have something working for the time being...

**Comment by kaikreuzer** [comment]
Created https://github.com/eclipse/smarthome/pull/732 - somehow the build does not succeed locally for me, which I cannot really explain. Would be good if you could have a try as well.

**Comment by kaikreuzer** [comment]
It works on a second machine, so I am quite confident that #732 is fine.

**Pull request merged**
