### PR TITLE
fix automation's Java API demo

### PR DESCRIPTION
**Pull request by maggu2810**
Apply last changes to this bundle.

Bug: https://github.com/eclipse/smarthome/issues/929

### CODE REVIEW

**Comment by tomhoefer** [comment]
introduction of config description parameter builder looks good to me

**Comment by maggu2810** [comment]
I would like to add a second commit to this PR, that adds the Automation Java API Demo to the POM of the automation.
I don't this this needs to be squashed, because there is no (real) relevance.
But I need to force, that the integration is done after this one gets fixed...

**Comment by kaikreuzer** [comment]
Feel free to either add it here (squashed or as a separate commit) or as a follow-up PR. I am fine to merge it right away.

**Comment by maggu2810** [comment]
done

**Pull request merged**
