### PR TITLE
excluded not required roboto fonts as well as md-icons, which are not…

### PR DESCRIPTION
**Pull request by kaikreuzer**
… yet IP approved.

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@GradyD FYI: With https://github.com/eclipse/smarthome/pull/873/files#diff-5dbde33cf15f676a9df0bf6c07387089L12, you have included many more files than were included before.
With this PR, I at least addressed the fonts - this alone shrinks the jar size from > 4MB to 1.3MB.
Please check, if there is anything else that can/should be removed again.

**Comment by GradyD** [comment]
As far as I am aware the only things that can be removed are the fonts, since we can easily use a browser safe font and not include the font files. It just will not follow the material design spec. 

We could also reduce the number of font files that we are using by only using the 1 font type, http://caniuse.com/#feat=woff. WOFF seems to be the font that is supported across the most browsers.

The md-icons are not currently included but should be included to prevent #914.

**Comment by kaikreuzer** [comment]
> WOFF seems to be the font that is supported across the most browsers.

That could indeed safe quite some more space. Would be interesting to test if the woff files are enough.

> The md-icons are not currently included but should be included to prevent #914.

That's clear, but we are not yet allowed to include them. For the time being, solutions add them through a fragment like https://github.com/openhab/openhab2-addons/tree/master/addons/ui/org.openhab.ui.paperui/patch/web/fonts/md-icons

**Comment by kaikreuzer** [comment]
> this alone shrinks the jar size from > 4MB to 1.3MB.

Now that I have bower drawing all dependencies correctly again, the result is actually 5.6MB down to 2.4MB.
Which is still bad, since before the gulp introduction, the jar size was 2MB - I would have expected it to be even smaller now after the minifying. So @GradyD, please have a closer look what is in there that wasn't there before - there should be quite some room for improvement here (at least to reach the same situation as before).

**Comment by kaikreuzer** [comment]
Ok, most of that seemed to be the (new) svg versions of the fonts, which I did not exclude before - I have just updated the PR now.

**Comment by GradyD** [comment]
Hmm interesting. I thought I had excluded the svg fonts from being copied over. They shouldn't have ended up in the web folder. 

I'll look into updating gulp to make sure they are also excluded there as well as forcing only woff files to be copied over.

**Comment by maggu2810** [comment]
@kaikreuzer Ping me if you are finished.

**Comment by kaikreuzer** [comment]
@maggu2810 I am. If @GradyD finds some further improvements, he can create a follow-up PRs.

**Pull request merged**
