### PR TITLE
[Sonos] Tune-in radio started by Amazon Echo

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
@JueBag : please check this version of the binding. You should now have media information filled when radio station is started by Amazon Echo and your notifications should now be rendered. I am not yet sure that the radio station will be correctly restored at the end of the notification. Please let me know.
[org.eclipse.smarthome.binding.sonos-0.11.0-SNAPSHOT.zip](https://github.com/eclipse/smarthome/files/2717048/org.eclipse.smarthome.binding.sonos-0.11.0-SNAPSHOT.zip)

**Comment by JueBag** [comment]
?? Uninstalled the binding via PaperUI and dropped the .jar into the .addons folder, but...
```
Error while starting bundle: file:/usr/share/openhab2/addons/org.eclipse.smarthome.binding.sonos-0.11.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.smarthome.binding.sonos [242]
  Unresolved requirement: Import-Package: org.eclipse.jdt.annotation; resolution:="optional"
  Unresolved requirement: Import-Package: org.eclipse.smarthome.config.discovery.upnp

```
Same result after restart openHAB.

**Comment by lolodomo** [comment]
What version of openHAB are you running ?

**Comment by JueBag** [comment]
2.4 Stable

**Comment by lolodomo** [comment]
Maybe try this: suppress the jar file, reinstall the binding through Paper UI.
Check that you have only one Sonos binding:  `bundle:list | grep Sonos`
Then put the jar in the addons folder.
Run again  `bundle:list | grep Sonos`, you shoulkd now see two bindings. Finally run `bundle:stop XXX` to stop the old one.

**Comment by lolodomo** [comment]
That's weird, I tried your scenario and it works as expected for me:
* uninstall the Sonos binding with Paper UI and check there is no more Sonos binding installed: `bundle:list | grep Sonos`
* put the jar fille (**and not the ZIP file**) in the addons directory
* the binding starts with success and I see only one Sonos binding when I check with `bundle:list | grep Sonos`

**Comment by JueBag** [comment]
I didn't try to install the .zip!!
Retried the "normal" way to uninstall, check bundle:list (no Sonos), drop .jar, Error shows in log, bundle:list shows "248 │ Installed │  80 │ 0.10.0.201807181443    │ Sonos Binding"  BUT all things remain "UNINITIALIZED - HANDLER_MISSING_ERROR".  Sonos is not available for searching in the INBOX.
I do call that NOT WORKING.

After reinstalling Sonos binding I see also: 
```
250 │ Active   │  80 │ 0.10.0.oh240           │ Eclipse SmartHome Configuration UPnP Discovery
251 │ Active   │  80 │ 0.10.0.oh240           │ Eclipse SmartHome UPnP Transport Bundle
252 │ Active   │  80 │ 2.5.1                  │ JUPnP Library
```
When trying to drop the new .jar into the addons folder I only get this error:

`18:47:36.380 [ERROR] [org.eclipse.smarthome.binding.sonos  ] - bundle org.eclipse.smarthome.binding.sonos:0.10.0.201807181443 (254)[org.eclipse.smarthome.binding.sonos.internal.SonosHandlerFactory(249)] : The setDynamicStateDescriptionProvider method has thrown an exception....
`but the new binding isn't in the bundle list. 

This all may be caused by my system which is observing heavy loads (see [community thread](https://community.openhab.org/t/after-upgrade-to-2-4-stable-im-flooded-with-java-lang-illegalstateexception/61567))
Will try to solve that before looking into this one again.

**Comment by lolodomo** [comment]
You are trying to run a very old version of the binding dated 18th of July (org.eclipse.smarthome.binding.sonos:0.10.0.**20180718**1443) !!!
Did you download the ZIP file I joined in my message ? This binding version should look like org.eclipse.smarthome.binding.sonos:0.11.0.20181230xxxx

**Comment by JueBag** [comment]
Ups!  BIG MISTAKE!!!  I'm sorry!

Dropped in the really new .jar and it worked. After the notification sonos is playing the radio station as if it was from the app (the banner underneath the room, which stated " Started from amazon alexa" is gone!)

Thank you!

**Comment by lolodomo** [comment]
So PR ready for review and merge.

**Comment by lolodomo** [comment]
Fix #6752

**Comment by leffenke** [comment]
> 
> 
> I didn't try to install the .zip!!
> Retried the "normal" way to uninstall, check bundle:list (no Sonos), drop .jar, Error shows in log, bundle:list shows "248 │ Installed │ 80 │ 0.10.0.201807181443 │ Sonos Binding" BUT all things remain "UNINITIALIZED - HANDLER_MISSING_ERROR". Sonos is not available for searching in the INBOX.
> I do call that NOT WORKING.
> 
> After reinstalling Sonos binding I see also:
> 
> ```
> 250 │ Active   │  80 │ 0.10.0.oh240           │ Eclipse SmartHome Configuration UPnP Discovery
> 251 │ Active   │  80 │ 0.10.0.oh240           │ Eclipse SmartHome UPnP Transport Bundle
> 252 │ Active   │  80 │ 2.5.1                  │ JUPnP Library
> ```
> 
> When trying to drop the new .jar into the addons folder I only get this error:
> 
> `18:47:36.380 [ERROR] [org.eclipse.smarthome.binding.sonos ] - bundle org.eclipse.smarthome.binding.sonos:0.10.0.201807181443 (254)[org.eclipse.smarthome.binding.sonos.internal.SonosHandlerFactory(249)] : The setDynamicStateDescriptionProvider method has thrown an exception.... `but the new binding isn't in the bundle list.
> 
> This all may be caused by my system which is observing heavy loads (see [community thread](https://community.openhab.org/t/after-upgrade-to-2-4-stable-im-flooded-with-java-lang-illegalstateexception/61567))
> Will try to solve that before looking into this one again.

Hi! 

First, I am not an experienced programmer...
But tried to install 0.11.0.20181230 binding, and had exactly the same problem:
Unresolved requirement: Import-Package: org.eclipse.jdt.annotation; resolution:="optional"
Unresolved requirement: Import-Package: org.eclipse.smarthome.config.discovery.upnp

Maybe I need to add more .jar file not only this one....?
I have OH2.4 stable, and can install Sonos Binding 2.4 from PaperUI.

But I have problems when Sonos is controlled by Alexa, and trying to send a notification sound to the device, that is why I would like to try the newer version of Sonos binding.

Thanks for your help!

Best regards,
Levente

**Comment by redpages** [comment]
Hi Lolodomo,

I was trying to install the .jar library into my openhab from snapshot 11 and got the following error:

2019-03-12 16:15:53.633 [ERROR] [org.eclipse.smarthome.binding.sonos ] - FrameworkEvent ERROR - org.eclipse.smarthome.binding.sonos
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.smarthome.binding.sonos [260]
  Unresolved requirement: Import-Package: org.eclipse.jdt.annotation; resolution:="optional"
  Unresolved requirement: Import-Package: org.eclipse.smarthome.config.discovery.upnp

May I ask you to help me to find out what is going on?

Kind Regards,
Jan

**Comment by leffenke** [comment]
Hi All,

I guess I figured it out. UPnP feature set needs to be installed, which can be done from CLI:
feature:install esh-io-transport-upnp

After that, you can install the Sonos binding 2.5 snapshot.

Hope, this helps to everyone.

Br,
Levente

**Pull request merged**
