### PR TITLE
avoid ConcurrentModificationException

### PR DESCRIPTION
**Pull request by kaikreuzer**
fixes https://github.com/openhab/openhab-distro/issues/177

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
Are you sure this helps? The code should not modify the set at all (if I read it correctly).
IIRC I already have done the some some time ago, but this does not solve the CME.
Will have a look at, if I find my tests that time...

**Comment by maggu2810** [comment]
See eclipse/smarthome#502

**Comment by maggu2810** [comment]
I used a copy and also drop the usage of the "Iterables.filter" at that time but it fails same time again...

**Comment by kaikreuzer** [comment]
> Are you sure this helps?

No, but I had the strong hope.

> The code should not modify the set at all (if I read it correctly).

This is right, but the CME happens when you are using an iterator of a set that is changed by someone else meanwhile (in this case because new resources are loaded into the resourceset).

> but this does not solve the CME.

I would be interested in the exception that you have got there, since I assume it should at least be a different stacktrace then.

In any case, I would assume that even if this change does not fully solve the issue, it should at least improve the situation quite a bit.

**Comment by maggu2810** [comment]
It has been long time ago as I used the OpenJDK. Cannot reproduce it with Oracle JDK anymore.

**Pull request merged**
