### PR TITLE
Switch DS annotation processor to openhab/felix fork.

### LINKED ISSUE #4179: Component XML generation broken for services with a configuration-pid
https://community.openhab.org/t/oh-2-2-0-snapshots-1025-1028-zwave-npe/33711/65

### PR DESCRIPTION
**Pull request by htreu**
Fixes #4179.

This should be applied as soon as org.openhab:org.apache.felix.scr.ds-annotations:1.2.9-AG1 is available from the openHAB maven repo.

Signed-off-by: Henning Treu <henning.treu@telekom.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Here we go: https://jcenter.bintray.com/org/openhab/org.apache.felix.scr.ds-annotations/1.2.9-AG1/

**Comment by maggu2810** [comment]
What is `AG1`?

**Comment by htreu** [comment]
AG1 is the version provided by the patch. I was wondering myself but thought it would be best to adopt the patch and live with as less modifications as possible.

**Comment by kaikreuzer** [comment]
See https://issues.apache.org/jira/secure/attachment/12877585/maven-scr-plugin-ds-annot-1.3.patch

**Pull request merged**
