### PR TITLE
Added setter methods to config parameter

### PR DESCRIPTION
**Pull request by cdjackson**
I've added setter methods to this class as there are (currently) 15 parameters in the constructor which I think is too many - it makes the code difficult to read and is more prone to error.
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by tomhoefer** [comment]
Should we use a builder for this purpose? Then this calls would still keep its immutable behaviour...

**Comment by tomhoefer** [comment]
i meant class instead of calls ;-)

**Comment by kaikreuzer** [comment]
I would second @tomhoefer idea as the classes are meant to be immutable (otherwise it would lead to many question of what should happen if a "user" uses the set methods after having read the configuration). @cdjackson, would a builder approach solve your issue?

**Comment by cdjackson** [comment]
For sure - that would be fine - anything that doesn’t have 15 args on the constructor…

I’ll update the PR at some point today.

Thanks.
Chris

**Comment by cdjackson** [comment]
Updated...

**Comment by dnobel** [comment]
Thanks Chris, builder looks good. But I would additionally ask you to move the builder into a separate file called ConfigDescriptionParameterBuilder.

Instead of the public constructor please use a static create method as the other builders have (see https://github.com/eclipse/smarthome/blob/1ffc8d439476f69552130066faf634c8ec72a9d0/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/builder/ChannelBuilder.java#L45 for example) and make the constructor private.

**Comment by dnobel** [comment]
Just recognized that your modified source code contains tabs. Please make sure you are using the official code formatter (see https://github.com/eclipse/smarthome/blob/master/docs/sources/development/guidelines.md#a-code-style).

**Comment by cdjackson** [comment]
Sorry - forgot… Should be ok now...

**Comment by cdjackson** [comment]
Sorry - just seen your comments about the separate file - I’ll update...

**Comment by cdjackson** [comment]
Third time lucky (hopefully :) ).

**Comment by dnobel** [comment]
Thanks!

**Pull request merged**
