### PR TITLE
added org.eclipse.emf.ecore.change bundle to launch config

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@maggu2810 When trying out the updated setup, my launch config was complaining that it also needs that bundle.

Btw, I noticed that you reference version 2.11.0 [here](https://github.com/eclipse/smarthome/blob/master/features/karaf/esh-tp/src/main/feature/feature.xml#L167), while the IDE uses 2.12.0. Shouldn't the Karaf feature better use 2.12.0 as well?

**Comment by maggu2810** [comment]
Damn, missed to trigger some launch configurations...

It seems to work with 2.11, too. But I agree that we should keep them in sync and pump the version used in the Karaf feature.

**Comment by maggu2810** [comment]
Ah, now I remember...
There is no 2.12.0 of that bundle on Maven Central.

We can choose between 2.11.0 and 2.13.0...
See: https://search.maven.org/search?q=g:org.eclipse.emf%20AND%20a:org.eclipse.emf.ecore.change&core=gav

**Comment by kaikreuzer** [comment]
Hm, pretty weird, but indeed a compelling explanation ;-)

**Pull request merged**
