### PR TITLE
add m2e stuff

### PR DESCRIPTION
**Pull request by maggu2810**
If you open "org.eclipse.smarthome.io.console.karaf" in the Eclipse SmartHome IDE, the IDE shows three errors caused by missing lifecycle mappings.
Two of them have to be disabled in the IDE settings, for the maven-compiler-plugin a m2e connector should be installed.
The search for connectors identify four connectors as usable (in combination of other features) to be installed:
* m2e-wtp - Maven Integration for WTP
* M2E connector for the Eclipse JDT Compiler
* Maven Integration for Eclipse JDT APT
* Groovy-Eclipse M2E integration

### CODE REVIEW

**Comment by maggu2810** [comment]
I will add another commit that adds lifecycle mapping configuration(s).
We can then merge (if there are no veto) the changes in this single PR.

**Comment by maggu2810** [comment]
done

**Comment by kaikreuzer** [comment]
> The search for connectors identify four connectors as usable

So you added all for of them? Isn't one enough? What are they doing exactly here?

**Comment by maggu2810** [comment]
I would assume that are all related to the maven-compiler plugin because the Eclipse IDE install it using the Quick Fix + find m2e connectors.

* [Groovy Eclipse Maven plugin](https://github.com/groovy/groovy-eclipse/wiki/Groovy-Eclipse-Maven-plugin)
    Groovy-Eclipse provides a compiler plugin for Maven. Using the compiler plugin, it is possible to compile your maven projects using the Groovy-Eclipse compiler.
* [M2E connector for the Eclipse JDT Compiler](https://github.com/jbosstools/m2e-jdt-compiler)
    This m2e connector adds support for maven-compiler-plugin with compilerId=eclipse and compilerId=jdt (i.e. Eclipse JDT compiler)
* [Maven Integration for Eclipse JDT APT](https://marketplace.eclipse.org/content/m2e-apt)
    m2e-apt supports both Annotation Processing set on the maven-compiler-plugin or the maven-processor-plugin (the latter takes precedence over the former).
* [Maven Integration for WTP](https://www.eclipse.org/m2e-wtp/)
    Eclipse to Maven project conversion : maps Eclipse settings to their equivalent maven plugin configuration. Available for all Java EE projects.

I don't know which ones (I assume the Groovy one and the WTP one) are not really necessary.

**Comment by kaikreuzer** [comment]
I would claim that the "M2E connector for the Eclipse JDT Compiler" should be enough.

**Comment by maggu2810** [comment]
Changed to fulfil your wish.

**Comment by kaikreuzer** [comment]
Thanks.
It still feels weird though to require something from JBoss Tools to "connect" the Eclipse Project m2e with the Eclipse project JDT...

**Pull request merged**
