### PR TITLE
Update to jsonpath 2.2.0

### PR DESCRIPTION
**Pull request by cniweb**
See: https://github.com/jayway/JsonPath/issues/88
See: http://stackoverflow.com/questions/36964936/array-size-using-jsonpath-expression-stefan-goessner-jsonpath/36967669#36967669
Signed-off-by: Christian Häussler <c-n-i@web.de>

### CODE REVIEW

**Comment by cniweb** [comment]
I have a ECA: https://accounts.eclipse.org/users/chussler

**Comment by maggu2810** [comment]
I assume if you remove the trailing ` (github: @cniweb)` in the Signed-off-by line, the automatic validation will succeed.

**Comment by kaikreuzer** [comment]
FTR: This PR will require a CQ before it can be merged.

**Comment by cniweb** [comment]
I remove the trailing `(github: @cniweb)` in the Signed-off-by line.

**Comment by kaikreuzer** [comment]
@cniweb I was just about to create a CQ for this library, but I noticed that the current version is already 2.2.0 since more than a year: https://github.com/json-path/JsonPath/releases

Wouldn't it make sense to directly go to this one or is there a specific reason why you chose the older version?

**Comment by cniweb** [comment]
@kaikreuzer OK, I update to 2.2.0

**Comment by kaikreuzer** [comment]
Created CQ 13334 for Jsonpath 2.2.0.

**Comment by kaikreuzer** [comment]
Check-in approval granted.

**Comment by maggu2810** [comment]
Don't we need to change the version in the Karaf feature XML, too?
I would expect that the versions fit to the one we are using in the IDE / tycho target platform.
What about `./esh-ext/src/main/feature/feature.xml`?

**Comment by cniweb** [comment]
Do you mean this line:
https://github.com/eclipse/smarthome/blob/master/features/karaf/esh-ext/src/main/feature/feature.xml#L88

**Comment by kaikreuzer** [comment]
Yes, I think we missed that one. @cniweb Can you create a PR to adapt that file as well?

**Comment by kaikreuzer** [comment]
Never mind, I created one myself.

**Comment by kaikreuzer** [comment]
@cniweb FTR: The latest openHAB distro now (finally) contains JSONPath 2.1.0!

**Pull request merged**
