### PR TITLE
Did general refactoring of the Docs/features/rules.md file - improved…

### PR DESCRIPTION
**Pull request by AlexanderKostadinov28**
Improved content, added consistent punctuation and syntax, improved readability.

Signed-off-by: Alexander Kostadinov <alexander.g.kostadinov@gmail.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
Thanks! Would like to merge this one, but there are conflicts that must be resolved.

**Comment by AlexanderKostadinov28** [comment]
Hi, Markus, what causes the conflict is the change I applied to the same file yesterday in pull request **#1023**, which actually was one removed space causing wrong markdown rendering. Inside the current pull request, I re-applied this change (the removed space at line 50). So, what should I do so that we can merge these current improvements to the Rule Engine documentation?

**Comment by maggu2810** [comment]
There are different things you can do. If you are not familiar with that stuff, make a backup of your branch first (e.g. push the branch to your remote using another name ).

You could merge, rebase, ...

Here one example what you can do (I assume that the eclipse repo is named eclipse, if it is named origin or something else on your machine, you have to change that):
1. git fetch eclipse
1. git merge eclipse/master
1. resolve conflicts if there are any
1. git reset --soft eclipse/master
1. look the diff using 'git diff --cached'
1. if there are any changed to do (e.g. the space) do it and use 'git add ...' to add the change to your stage)
1. git commit -s
1. git push -f

**Comment by AlexanderKostadinov28** [comment]
Okay, I couldn't fix that up. You can decline the PR, delete the branch and I'll create another PR from an updated fork (I have my changes present).

**Comment by maggu2810** [comment]
Whatever you want, normally there is no need to create a new PR.
A PR keeps track of a special branch, so if you (force) push your new changes based on a fork to the branch tracked by this PR, all is fine.
If it is much easier for you to create a new one, I will close this one.

**Pull request closed without merging**
