### PR TITLE
made hue bridge handle empty username correctly

### LINKED ISSUE #1294: Hue Binding unable to detect if username in configuration is null
There is the following code in `HueBridgeHandler.java`
```
public void onNotAuthenticated(HueBridge bridge) {
        String userName = (String) getConfig().get(USER_NAME);
        if (userName == null) {
            createUser(bridge);
        } else {
            try {
                bridge.authenticate(userName);
            } catch (Exception e) {
                handleAuthenticationFailure(e, userName);
            }
        }
    }
```
userName is a Java String here. When it is a null string, the condition (`userName == null`) is not true. It should be handled as (`userName.trim().equals("") || userName == null`).

Without it, this code was not working for me and I was not able to link Hue Bridge even after pressing the Link button.

### PR DESCRIPTION
**Pull request by sjka**
fixes #1294
Signed-off-by: Simon Kaufmann <simon.kfm@googlemail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
I am not sure whether this is a valid fix for the problem, see https://github.com/eclipse/smarthome/issues/1294#issuecomment-203601274. What do you think?

**Comment by sjka** [comment]
Although I see your point, in my opinion this fix makes the hue bridge handler more robust. An empty string or just some spaces clearly are no valid usernames, therefore I don't see it would do any harm to consider them as "not being set".

**Comment by kaikreuzer** [comment]
> An empty string or just some spaces clearly are no valid usernames

Which means that we should actually add a "min=10" to the config parameter description and thus it would not even be possible to ever set an empty value (and thus this fix would not be relevant at all).

**Comment by maggu2810** [comment]
Should the configuration handling in the binding code handle / workaround a configuration that does not fit the requirements of the definition in the XML? Or should a binding rely on the fact that all configurations met the conditions defined in the XML? I think this should be answered in general.

Or I am missing something here. Should this be handled by the new validation code already?
Cannot have a look at the code ATM.

**Comment by kaikreuzer** [comment]
> Should the configuration handling in the binding code handle / workaround a configuration that does not fit the requirements of the definition in the XML?

I should be prepared that invalid configuration is passed and needs to validate it itself (for which it now can rely on (=use) the default validation implementations that already do the majority of the checks). But it should rather highlight a misconfiguration than quietly applying a workaround. That's why I think this fix is not the correct way to solve the issue.

**Comment by maggu2810** [comment]
> But it should rather highlight a misconfiguration than quietly applying a workaround.

Ok for me. "Quietly applying a workaround" is something like black magic and should be avoided.

**Comment by sjka** [comment]
From the discussion above, I conclude that treating an empty string in the same way as if there was no password set (i.e. ```NULL```) does not have a majority appeal. As #1301 is going to fix the root cause, I will close this PR.

**Pull request closed without merging**
