### PR TITLE
ChannelItemprovider: Shutdown executor in deactivate

### PR DESCRIPTION
**Pull request by triller-telekom**
Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
What about this code that is executed if the component is still enabled but the configuration state it should not act on:

```Java
            for (ProviderChangeListener<Item> listener : listeners) {
                for (Item item : getAll()) {
                    listener.removed(this, item);
                }
            }
```

Would it make sense to move the deactivation code to a separate function that is called on "active but disabled (so one of the two modified branches)" and on "deactivate (component)"?

**Comment by triller-telekom** [comment]
Close/reopen because of paperUI build failure which is independent of this change

**Comment by maggu2810** [comment]
@velichkos Would you like to have a look at? Okay for you?

**Comment by velichkos** [comment]
I like the disable logic in a separate method.
Looks good to me.

**Pull request merged**
