### PR TITLE
made designer working again after Xtext 2.9.2 upgrade

### LINKED ISSUE #1442: Designer 0.8.0 won't start - stack trace
version:  Current nightly snapshot
OS/Arch: Linux/64 - likely broken elsewhere too
possible cause: xtext 2.9.2 changes

current log attached.
[1462021857850.txt](https://github.com/eclipse/smarthome/files/243614/1462021857850.txt)

### PR DESCRIPTION
**Pull request by kaikreuzer**
Fixes #1442

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@maggu2810 I learned that the "Bundle-ActivationPolicy: lazy" is important for bundles that might not be automatically started, but where code within it relies on the fact that the bundle is started. 

There were other issues with the Designer startup, but I hope this is now solved. I only tested it on Mac though.
If it works, this fix needs to be cherry picked to the 0.8.x branch as well.

**Comment by maggu2810** [comment]
Created a separate PR for the 0.8.x branch and merged it myself.

**Comment by kaikreuzer** [comment]
Thanks!

**Comment by aisebastian** [comment]
Hello Kai,

Is it a mistake that this commit reverts some of the changes in 4cd5f00ab985fbac8bdba8f7387d24a7c57d5dfc ?
#1407 seems to be reoccuring

Thanks!

**Comment by kaikreuzer** [comment]
@aisebastian I don't know, this is rather long ago already. Why do you ask? Anything not working as expected?

**Comment by aisebastian** [comment]
Well,

When I try to activate the eclipse.smarthome.io.transport.mqtt feature I get an exception similar to the one that commit 4cd5f00 fixes, and it seems to me that those fixes are reverted by this merge. I encoutered this when I tried to build my own openhab2 from source

However, what I am trying to do - and this is where it gets offtopic - is use the eclipse.smarthome.io.transport.mqtt service in an OH2 binding. I have this running in IDE, but when I run my binding in a downloaded openhab 2.1.0 instance, the esh mqtt service just doesn't pick up config file and does not connect, only the openhab.io.transport.mqtt service does. And for some reason, I can't seem to be able to use this due to compile dependency issues. But I will try and find more documentation on how to do this. 

Thanks!

**Pull request merged**
