### PR TITLE
Remove static "for the next 3 hours" text

### PR DESCRIPTION
**Pull request by andreasscherbaum**
This is applied to every forecast, no matter how far in the future.

### CODE REVIEW

**Comment by cweitkamp** [comment]
May I ask why you want to change the labels? According to the [documentation](https://openweathermap.org/current#current_JSON) the API returns exactly those values.

**Comment by davidgraeff** [comment]
Shouldn't this fix be applied to the openhab2-addons repository instead?

**Comment by andreasscherbaum** [comment]
Ok, I was under the impression that this is the right repository for this change. Did not know that another repo is holding the ~~truth~~ original code.

@cweitkamp Do you have a pointer for me which README is affected? Then I can move this PR, and incorporate the change. Thanks

**Comment by cweitkamp** [comment]
No problem. The bindings have been moved recently.

[Here](https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.openweathermap/README.md) you are.

**Pull request closed without merging**
