### PR TITLE
Backport of https://github.com/openhab/openhab/pull/2880 which strips…

### PR DESCRIPTION
**Pull request by digitaldan**
… double quotes from the mapping command

Signed-off-by: Dan Cunningham dan@digitaldan.com

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks @digitaldan! Since you copied the code from https://github.com/openhab/openhab/issues/2880, which was created by @marcelerkel, you should add an "Also-By" footer to the commit message and we would hence also need a signed CLA from Marcel.

**Comment by digitaldan** [comment]
@kaikreuzer no problem.  @marcelerkel can you sign the eclipse CLA at https://projects.eclipse.org/user/sign/cla ?  And send me your name and email?  If you would like I can close this PR if you prefer to do the commit yourself.  Thanks.

**Comment by marcelerkel** [comment]
My apologies for the delay. I intended to pick this up already last year but it somehow dropped of the table. I signed CLA.
@digitaldan Thanks for your effort! I have no problem in you doing the commit because if I would need to do it, I'd need to setup the whole dev environment. Marcel Erkel is my real name. Email address is marcel@erkel.nl

**Comment by digitaldan** [comment]
Awesome, thanks for doing that!  I'll add you to the commit message here
soon.

On Thu, Feb 18, 2016 at 8:14 AM Marcel Erkel <notifications@github.com>
wrote:

> My apologies for the delay. I intended to pick this up already last year
> but it somehow dropped of the table. I signed CLA.
> @digitaldan <https://github.com/digitaldan> Thanks for your effort! I
> have no problem in you doing the commit because if I would need to do it,
> I'd need to setup the whole dev environment. Marcel Erkel is my real name.
> Email address is marcel@erkel.nl
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipse/smarthome/pull/809#issuecomment-185766180>.
>
-- 
Sent from my mobile.

**Comment by digitaldan** [comment]
@kaikreuzer I have amended the commit, thanks.

**Comment by digitaldan** [comment]
And I closed it, shoot. Reopening!

**Comment by kaikreuzer** [comment]
Thanks @digitaldan!

**Pull request merged**
