### PR TITLE
Align string item value on same row in ControlUI

### PR DESCRIPTION
**Pull request by aounhaider1**
Before:
screen shot 2016-11-03 at 18 02 29

After:
screen shot 2016-11-03 at 18 02 08

Signed-off-by: Aoun Bukhari <bukhari@itemis.de>

### CODE REVIEW

**Comment by aounhaider1** [comment]
Ok. But should it break to next line when there is not enough space in the second case?

**Comment by kaikreuzer** [comment]
Yes, that's why I called it a "text area".

**Comment by aounhaider1** [comment]
Updated.

**Comment by kaikreuzer** [comment]
Could you provide new screenshots of how it now looks like?

**Comment by aounhaider1** [comment]
Short text:
screen shot 2016-11-17 at 16 12 45

Long text:
screen shot 2016-11-17 at 16 12 26

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
