### PR TITLE
Add utility constructor without specifing uid of rule. See #882

### PR DESCRIPTION
**Pull request by danchom**
Signed-off-by: Yordan Mihaylov <j.mihailov@prosyst.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
Perhaps I didn't get the point, but as this constructor does nothing but calling another one with UID set to null, why we can't call the other one with a null argument ourself?

**Comment by kaikreuzer** [comment]
@danchom Gave an explanation on https://github.com/eclipse/smarthome/issues/882 - this constructor makes sense to make it available to "clients", because if they are asked to pass a UID they might be confused - directly giving an option to omit it in the constructor is imho very helpful.

**Comment by danchom** [comment]
Yes the purpose is exactly as Kai explained. Sorry for missing clean  description of the issue #882.

**Comment by maggu2810** [comment]
It is not about the description, but I cannot see no difference between using the already existing construction with "null" for the UID.
If I do not know if the UID can be omitted, I can have a look at all existing constructors or I can read the documentation that could state that null as UID is allowed.
The class contains seven public constructors, now.
If we ever add a new mandatory field, we have to change all of them.

Perhaps it is my personal view, but as it is already merged, ...

**Pull request merged**
