### PR TITLE
Bug #482188 modification :

### PR DESCRIPTION
**Pull request by clinique**
- LocationItem delegates distanceFrom calculation to PointType
- Moving distanceFrom calculation details in PointType
- Enhancing PointType constructor as in PR #3410 of OH1
- Splitted tests between respectives tests classes for LocationItem and PointType

Signed-off-by: Gaël L'hopital <glhopital@gmail.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=482188

**Comment by dnobel** [comment]
@kaikreuzer Why does mentioning a bug with a hash "#482188" creates a reference the the bug tracker, but not if you do it like proposed from our process with a "Bug: 482188" line (https://www.eclipse.org/smarthome/documentation/community/contributing.html#conventions-for-pull-requests) . Do we have to adapt the documentation?

**Comment by kaikreuzer** [comment]
@dnobel This is the official reference: https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#The_Commit_Record
The Bugzilla ref therefore has to be an url and not any of the two options you mention :-)

**Comment by dnobel** [comment]
OK, but the commit message in this PR does not contain a URL, or? So how did the github hook get the bug reference?

**Comment by dnobel** [comment]
maybe @eclipsewebmaster can help here :)

**Comment by kaikreuzer** [comment]
lgtm, thanks!

**Pull request merged**
