### PR TITLE
[core] Create channelUID instead of searching for the channel

### PR DESCRIPTION
**Pull request by cweitkamp**
- Create channelUID instead of searching for the channel

Signed-off-by: Christoph Weitkamp <github@christophweitkamp.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
Mhm. The current implementation checks if the channel exists before checking if it is linked and returns immediately if it is not existing.
So the question may be: is this check more or less efficient than searching for the link (i.e. how often is isLinked called for non existing channels and therefore this check saves resources for checking the link registry)

**Comment by cweitkamp** [comment]
For the current implementation of the `AbstractLinkRgistry` it does not matter if the channel really exists on a thing or not because it internally uses a `HashMap` to keep track of a reference between an `UID` and any existing links for it to an item. The check is very fast - a lot faster than querying the thing for the channel first.

**Comment by Hilbrand** [comment]
I noticed the construction with creating the object is used on more places in the class. I wouldn't prefer creating objects when not strictly needed. This method is probably used very often, so it would result in lots of object creation. But that might not be a big issue.

Furthermore, Is the creation in this change always correct? A channel can have a group id. Creating it like this would be without group Id unless the groupId is part of the string parameter channelId passed. Or is that always the case? Changing it here would assume that groupId is always part of it, which currently is not required as it just searched based on the id. For example a lot of calls in ESH alone look something like this: `isLinked(channel.getUID().getId())`. This doesn't include the group id. (I also wonder why not call it in the UID directly, which seems more efficient, legacy?)

**Comment by cweitkamp** [comment]
Thanks for your opinion on this. Deriving from it we have a couple of methods in the `BaseThingHandler` class which may lead to bugs if a binding uses channel groups. Nearly every important method has a version using the channel id as argument and create the channelUID from it. What do you propose? From my personal view we maybe should now leave this method like it is and deprecate it and the other ones.

> legacy?

Yes, the `isLinked(ChannelUID)` version has been introduced one year ago.

**Pull request merged**
