### PR TITLE
allows to start-stop-start-stop-... a reconnect strategy

### PR DESCRIPTION
**Pull request by maggu2810**
A MQTT Broker Connection must be able to handle start and stop iterations.

Related to: https://github.com/eclipse/smarthome/pull/3980#issuecomment-326222638

### CODE REVIEW

**Comment by maggu2810** [comment]
@davidgraeff WDYT about?

**Comment by davidgraeff** [comment]
I would like to adapt the unit test in a later pr, but I need a way to query the strategy if it is started. Should we introduce a isStarted() function?

**Comment by maggu2810** [comment]
I don't care. But IMHO this should be added to the specific implementation only because it should not be necessary to have such a method in general.

**Comment by davidgraeff** [comment]
Can you add it to the PeriodicStrategy?

**Comment by maggu2810** [comment]
> Can you add it to the PeriodicStrategy?

done

**Pull request merged**
