### PR TITLE
Change the name of the Java API Demo to the Rule Engine Extensions Demo

### PR DESCRIPTION
**Pull request by adimova**
Signed-off-by: Ana Dimova <a.dimova@prosyst.bg>

### CODE REVIEW

**Comment by adimova** [comment]
The new name is more proper because it shows how to extends module types, templates through the java api. (how to use spi interface)

**Comment by kaikreuzer** [comment]
As we already have the bundle `org.eclipse.smarthome.automation.sample.handler`, shouldn't we stick to the same prefix and maybe go for `org.eclipse.smarthome.automation.sample.extensions`?
Or shall we possibly even remove the sample.handler bundle, since it is a bit overlapping with the new demo?

**Comment by maggu2810** [comment]
There are different names (ATM + in PR):
* org.eclipse.smarthome.automation.rest.api.demo
* org.eclipse.smarthome.automation.sample.handler
* org.eclipse.smarthome.automation.rule.engine.extensions.demo

Should we use a naming scheme similar to the test bundles that use a ".tests" as postfix e.g. ".demo" or ".sample" for all that stuff?
I would prefer ".sample" because a demo could be a self running demonstration. A (ex)sample is already stated as a code example.

**Comment by marinmitev** [comment]
We should indeed unify the naming, so why not to use the following names for the demo/sample bundles
 
1.    org.eclipse.smarthome.automation.rest.api.sample
2.    org.eclipse.smarthome.automation.extension.json.sample
3.    org.eclipse.smarthome.automation.extension.java.sample
4.    org.eclipse.smarthome.automation.java.api.sample
	
	There is indeed an overlap in 2. and 3. above but it is only for the part with the automation handlers and the difference is that 2. provides rules with json resource files, while 3. demonstrates how to provide rules with Rules Provider
	And the purpose of 4. is to demonstrate usage of the RuleRegistry API

**Comment by kaikreuzer** [comment]
I don't like this naming scheme, because it seems to suggest that there are "normal" bundles of the names

org.eclipse.smarthome.automation.rest.api
org.eclipse.smarthome.automation.extension.json
org.eclipse.smarthome.automation.extension.java

as well.
I therefore rather prefer to have all samples prefixed with org.eclipse.smarthome.automation.sample.

**Comment by marinmitev** [comment]
OK, I agree with prefixes too. So it would be:
1. org.eclipse.smarthome.automation.sample.rest.api
2. org.eclipse.smarthome.automation.sample.extension.json
3. org.eclipse.smarthome.automation.sample.extension.java
4. org.eclipse.smarthome.automation.sample.java.api

**Comment by kaikreuzer** [comment]
Fine with me.

**Comment by maggu2810** [comment]
> I don't like this naming scheme, because it seems to suggest that there are "normal" bundles of the names

Why is this valid for "(ex)sample(s)" but not for "tests"?

If we know that all "*.tests" are tests and all "*.samples" are examples, this is much more common to me then state that all "*.samples.*" are samples.

I want to use org.eclipse.automation.sample.* before, but if we add other non-automation samples we get org.eclipse.foo1.sample.bar1, org.eclipse.another.sample.something, etc.
So I am assume to state all bundles ending with ".tests" are test bundles and all bundles ending with "*.sample" are examples is much more general.

But it is also okay for me to use org.eclipse.category.sample.* if this is more affectionate for you.

**Comment by kaikreuzer** [comment]
> Why is this valid for "(ex)sample(s)" but not for "tests"?

Why is is not valid for tests?
Every x.y.z.tests bundle directly refers to an (existing) x.y.z bundle.

So yes, if there were a bundle org.eclipse.smarthome.automation.rest.api, we could have a sample org.eclipse.smarthome.automation.rest.api.sample. But this is not the case.

**Comment by maggu2810** [comment]
I understand your above message (the part I replied to), that you don't want to use "*.sample" ("I don't like this naming scheme").
So my question was: Why is the naming scheme "using a postfix only" valid for tests and not for samples ("not valid" means "you don't like this").

**Comment by kaikreuzer** [comment]
I think you did not get me yet.

> "using a postfix only"

Using a postfix for what?
This is my point: Using a postfix for an existing bundle - yes, this is what the tests are doing
Using a postfix for a component - this is what the samples are doing by org.eclipse.smarthome.automation + postfix (= sample.xyz).

**Comment by maggu2810** [comment]
Perhaps I do not get you or I see it by another point of view.

If I build a list of all artifacts that are generated by the build process and want to remove all aritafacts that are tests and examples, it would be easy to filter that list by exclusion of all ones that ends with ".tests" and ".samples".
If a sample is for a component or a specific bundle does not matter in this case.

To get something like a tree hierarchy it is much more common to group samples after the component.
There is perhaps one corner case if we want a sample that demonstrates the interaction between two components.
So perhaps the prefix "org.eclipse.smarthome.sample." would be an option, too. For example "org.eclipse.smarthome.sample.automation.rest.api", ...

**Comment by kaikreuzer** [comment]
> So perhaps the prefix "org.eclipse.smarthome.sample." would be an option

It would be an option, but we should then probably also move them to bundles/samples. As we do not have any other samples than for the automation component, this would (atm) look a bit weird.
I'd therefore prefer to keep them with the component they belong to.

**Comment by maggu2810** [comment]
Ok

**Comment by adimova** [comment]
rename  the org.eclipse.smarthome.automation.sample.handler  and org.eclipse.smarthome.automation.rule.engine.extensions.demo with the new names:
org.eclipse.smarthome.automation.sample.extension.json
org.eclipse.smarthome.automation.sample.extension.java

**Pull request merged**
