### PR TITLE
Fix rule constructors

### PR DESCRIPTION
**Pull request by danchom**
Signed-off-by: Yordan Mihaylov <j.mihailov@prosyst.com>

1) remove unnecessary rule constructor parameters (configDescription and configuration) from constructors which creates rules by modules
2) remove unnecessary rule constructors
3) remove configDescription field from Rule class. Rules does not have configDescriptions

### CODE REVIEW

**Comment by kaikreuzer** [comment]
> Rules does not have configDescriptions

Hm, we currently did not support this yet, but I think we introduced this on purpose.
And I recently came across situations where I wanted to use exactly this.

Think of a rule that has been created based on a very complex template. In the template you have a configuration that e.g. allows to select you the sensor and actuator and maybe a temperature threshold on when the rule should act. As a user, you might want to be able to "play" with this threshold to optimize your rule - but it means that this needs to be available as a configuration somewhere on the rule. The template might have decided to hide the rule module which actually use this value (maybe there are even several) - so the natural place for this threshold config param is the rule itself. This would allow templates to actually hide ALL modules and just leave some simple configuration options for the user.

**Comment by danchom** [comment]
The role of template is to hide modules, their configuration, and links between them. After template resolution, there are not any marks that the rule is created by template, therefore there are not any links between rule and configuration descriptions parameters of template.
As I understand your use case, you want to reconfigure created rule without update rule operation.(IMHO this shouldn't be related how the rule was created - from template or not). May be this is a good option but there are following problems:
1) Configuration values are set in through constructor of  the module. We have to change Module interface. Also we already we have rejected  dynamic set of configuration values. 
2) New configuration values can be applied to module handlers. At the moment the handlers have access to configuration properties through the module parameter. We have to change the module handler interface.
3) The handler can go into not initialize state base on new configuration values. 
4) What will be  behavior of such rule when invalid configuration value is applied? 
5) What is a difference with the rule template?  Templates are not working rule, because they have to be configured, The rule can be configured too, but it works from time to time when a valid configuration properties are passed.
6) What will be state of the rule when the configuration is update? Idle - it is not working at the moment,  Not initialize - it is initialize because all handlers are available.  

At the moment to update module configuration you have to update module with new configuration values and then to update the rule. (which is not an easy task too)

Anyway I think this is topic of other discussion. The purpose of this PR is to improve rule's api. I can remove point 3)  from this PR or remove them now and add again when we decided what to do.

**Comment by kaikreuzer** [comment]
> IMHO this shouldn't be related how the rule was created - from template or not)

Absolutely correct.

> Anyway I think this is topic of other discussion. 

Agreed, I see your points and it is indeed nothing straight forward to implement.

> I can remove point 3) from this PR 

Aren't point 1+2 also about config(description)s on rules? That's why I stumbled over it.
Yes, it is right that currently this cannot be used, but if we agree that it makes sense and we should work on it, I wonder if it is worth the effort to refactor this code now, just to put it back later on? If there is stuff that clearly makes no sense or is obsolete, it is of course fine to remove it.

**Comment by danchom** [comment]
I think the rule constructors are confusing at the moment and calls each other in confused way.
When create a rule from modules we have to set always null for configuration  and configuration description parameters. Also there are separate constructors with/without visibility option. 
In the refactor rule we have:

**Comment by kaikreuzer** [comment]
Our decisions here:
- remove unnecessary rule constructors: Only keep minimal (ruleuid) and full constructor, let the rest of the pojo be filled by setters
- keep configuration and configDescription on Rules

**Comment by danchom** [comment]
Done

**Comment by kaikreuzer** [comment]
There is now some merge conflict - could you please rebase this branch? Thanks!

**Comment by danchom** [comment]
Conflicts are resolved.

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
