### PR TITLE
Remove commented code from SerialPortManager

### PR DESCRIPTION
**Pull request by wborn**
The commented code is more elegant but would throw exceptions. :slightly_frowning_face:

### CODE REVIEW

**Comment by maggu2810** [comment]
Has there something changed in the functions that are called? Where are the exceptions thrown?
The reason we could not use the more elegant commented code has been because we are using nullness checks without the EEAs and so the optional type parameter is not handled correctly on some of that functions.

**Comment by wborn** [comment]
Yes that indeed seems to be the reason why it was commented. I've jumped too early to conclusions because I've been exposed to lots of other code where it usually has other reasons. An additional comment would have helped. :wink:

**Comment by maggu2810** [comment]
You are right.
The comment exists not inline in the code but on GitHub on the first PR of that code.
See: https://github.com/eclipse/smarthome/pull/5313#discussion_r177573211
Regardless, perhaps you should not leave commented code at all, regardless of the reason.

**Comment by wborn** [comment]
The EEAs would certainly result in nicer code, fewer compiler warnings and less review comments. ;-)
Migrating existing code from `gnu.io` to the ESH serial transport is also easy (https://github.com/openhab/openhab2-addons/pull/4424). That's how I ran into this code. The nullness annotations also help! :+1:

**Pull request merged**
