### PR TITLE
Updates to default chart provider to support OnOff and OpenClose types.

### PR DESCRIPTION
**Pull request by cdjackson**
Added support for OnOff and OpenClose types and also updated chart provider to be inline with the changes on OH to allow a configurable chart size.
Note that I've only tested this with the OH runtime. I hope I've done everything right for the SmartHome merge :) 
Also, updated chart library to 2.3.2
Signed-off-by: Chris Jackson chris@cd-jackson.com

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@cdjackson, how shall we proceed with this PR?

**Comment by maggu2810** [comment]
@cdjackson Is this PR still in your queue?

**Comment by foxytocin** [comment]
Hey whats about that? OnOff and OpenClose type don't work for rrd4j charting in OH2. Did in OH1

**Comment by cdjackson** [comment]
> OnOff and OpenClose type don't work for rrd4j

This issue isn't related to rrd4 charting.

I will try and take a look at updating this PR over the coming days - I need remind myself about it as it's quite old.

**Comment by kaikreuzer** [comment]
> This issue isn't related to rrd4 charting.

... but about rendering charts from data persisted to rrd4j - and afaik, the persistence of OnOffType etc. work as expected, it is just the (new) charting that cannot handle it.

**Comment by maggu2810** [comment]
> I need remind myself about it 

Am I allowed to remind you :wink:

**Comment by sehroriginell** [comment]
@cdjackson Hi Chris! I just discovered this problem, too. So I'd be happy if you would find the time to look into that. Thanks!

**Comment by watou** [comment]
#2835 addresses the title of this PR, as well as the other changes that bring it in sync with openHAB 1.8.3's chart servlet and default chart provider.

**Comment by lolodomo** [comment]
When I take a look to the chart provide coder, my feeling is that OnOff and OpenClose types are already handled by the convertData method: https://github.com/eclipse/smarthome/blob/master/bundles/ui/org.eclipse.smarthome.ui/src/main/java/org/eclipse/smarthome/ui/internal/chart/DefaultChartProvider.java#L232
It looks like a similar code to this PR was merged. Can this be clarified ?

**Comment by sjka** [comment]
This PR seems to be more or less abandoned and probably superseded by #2835 - in any case, with the reverse commit it contains it has a diff of exactly "nothing" currently. Therefore I will close it. Feel free to re-open (or create another one) if you see something which has not been covered in the meantime.

**Pull request closed without merging**
