### PR TITLE
Add JsonPath transformation service

### PR DESCRIPTION
**Pull request by sja**
This add a TransformationService implementation for JsonPath (https://github.com/jayway/JsonPath). It can be used with TransformationServiceHelper by it's name `JSONPATH`.

JsonPath is licensed under APL 2.
Bugzilla ID [470283](https://bugs.eclipse.org/bugs/show_bug.cgi?id=470283)

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Isn't this a duplicate of https://github.com/eclipse/smarthome/pull/286?

**Comment by sja** [comment]
Indeed, it is. I'll talk to @clinique to coordinate this.

**Comment by kaikreuzer** [comment]
Thanks a lot, so I close this PR then.

**Comment by sja** [comment]
I cannot close this in BugZilla because I need a Bug-ID to mark as duplicate. Should I mark it other, e.g. NOT_ECLIPSE?

**Comment by kaikreuzer** [comment]
Well, just leave Bugzilla open and mark it as implemented with #286.

**Pull request closed without merging**
