### PR TITLE
improve I18nConfigOptionsProvider tests for Java 9

### PR DESCRIPTION
**Pull request by maggu2810**
Fixes: https://github.com/eclipse/smarthome/issues/6202

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Since this PR our build is failing: https://ci.eclipse.org/smarthome/job/SmartHomeDistribution-Nightly/2989/

I do not see how it could possibly linked to that change, but I also have no clue what else could have caused this. Any idea?

**Comment by maggu2810** [comment]
Hm, could it be related to the tycho bump that has been merged before?

**Comment by maggu2810** [comment]
```
[ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.12.0:compile (default) on project model: Execution default of goal org.eclipse.xtend:xtend-maven-plugin:2.12.0:compile failed: Plugin org.eclipse.xtend:xtend-maven-plugin:2.12.0 or one of its dependencies could not be resolved: Failed to collect dependencies at org.eclipse.xtend:xtend-maven-plugin:jar:2.12.0 -> org.eclipse.emf:org.eclipse.emf.codegen:jar:2.14.0 -> org.eclipse.emf:org.eclipse.emf.common:jar:[2.15.0,3.0.0): No versions available for org.eclipse.emf:org.eclipse.emf.common:jar:[2.15.0,3.0.0) within specified range -> [Help 1]
```

The artifact `org.eclipse.emf:org.eclipse.emf.codegen:jar:2.14.0` seems wrong to me.
Why 2.14.0?

**Comment by maggu2810** [comment]
I don't understand the failure ATM.
If I check out the current master it builds without any problem on my machines.

**Comment by kaikreuzer** [comment]
The build is green again. It failed next with signature issues, so I disabled the "sign" profile for now. Hope this is only a temporary issue with the Eclipse' signing infrastructure.

**Pull request merged**
