### PR TITLE
CronExpression: start using fixed test input

### PR DESCRIPTION
**Pull request by maggu2810**
The current test execution depends on the TimeZone and current time of
the system the test is executed. That is not optimal as tests could
succeed on the one machine but fail on the other one.
Added another test (currently ignored, too), that uses the TimeZone and
start time the error occurs.

Related to: https://github.com/eclipse/smarthome/issues/5294

### CODE REVIEW

**Comment by kaikreuzer** [comment]
This could be superseded by https://github.com/eclipse/smarthome/pull/5299 - If #5299 is successful, you might want to adapt this PR to not ignore the tests, but only add the new one to the suite.

**Comment by kaikreuzer** [comment]
@maggu2810 #5299 has been merged.

**Comment by maggu2810** [comment]
@kaikreuzer I changed the commit:

```text
    CronExpression: start using fixed test input
    
    The current test execution depends on the TimeZone and current time of
    the system the test is executed. That is not optimal as tests could
    succeed on the one machine but fail on the other one.
    Added another test (currently ignored, too), that uses a explicit set
    TimeZone and time.
    We use "millis from Epoc" to set the time, so we can easily difference
    between e.g. 2:30 nDST and 2:30 DST.
```

**Comment by maggu2810** [comment]
* `findNext` still exists and is perhaps useful to generate some random test input
* `findNextSpecial` will use some special / fixed test input, so we can add ("from time to time") known "difficult" input

**Pull request merged**
