### PR TITLE
Correction of toString() bug

### PR DESCRIPTION
**Pull request by clinique**
Signed-off-by: Gaël L'hopital <glhopital@gmail.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks! Did you test whether this change has any impact on the MapView widget in the ClassicUI (does it perhaps expect the old formatting)?

**Comment by clinique** [comment]
No, MapviewRenderer works using getLatitude and getLongitude, then no impact.

**Comment by kaikreuzer** [comment]
Ok, thanks, looks good! Will you also backport this to openHAB 1?

**Comment by clinique** [comment]
Yes, sure

**Pull request merged**
