### PR TITLE
Adjust hue binding to use username generated by bridge instead of custom username

### LINKED ISSUE #672: Adjust hue binding for hue API whitelist changes
The API of the username whitelist for the hue bridge will change in the coming months: http://www.developers.meethue.com/documentation/important-whitelist-changes

Starting in February 2016, it will probably not be possible anymore to whitelist custom users on the hue bridge. As the current binding implementation uses this functionality, it will be necessary to update the binding before the bridge update is rolled out.

Same as ticket openhab/openhab#3258.

### PR DESCRIPTION
**Pull request by dominicdesu**
Fixes #672 .

Signed-off-by: Dominic Lerbs <dominicdesu@hallojapan.de>

### CODE REVIEW

**Comment by dominicdesu** [comment]
One remark:
When a new Hue Bridge Thing is added to ESH, a username generated by the bridge is used. If the bridge thing is then deleted from ESH, the username remains on the whitelist of the bridge until it is manually removed. Rediscovering and adding the Hue bridge again will generate a new username.

It would be possible to automatically remove the username from the hue whitelist when the bridge thing is deleted from ESH. However, I didn't implement this in the current solution as this would also remove custom usernames (possibly used in other applications as well) from the whitelist (e.g. set via the settings page in PaperUI). Please let me know what you think about this, I can add the relevant code if necessary.

**Comment by dominicdesu** [comment]
I guess I need some more clarification: Just realized there is also a hue.cfg file. In which cases is this cfg file used?

**Comment by sjka** [comment]
cleaning up usernames that were generated by the bridge somehow seems like the right thing to do. I'd rate the possibility of having custom usernames with a length of more than 30 characters pretty low, so from my point of view they might be safe to delete on bridge removal.

Unfortunately, I can't make any sense of the hue.cfg file either.

**Comment by kaikreuzer** [comment]
> Unfortunately, I can't make any sense of the hue.cfg file either.

Hey, just RTFM, this is all nicely documented here ;-)
https://www.eclipse.org/smarthome/documentation/features/bindings/hue/readme.html#binding-configuration

This file used to have the user-defined password to use for the authentication. As this is exactly the feature that won't be possible anymore in the future, the hue.cfg file (and the documentation about it!) can be removed.

**Comment by sjka** [comment]
To me it seems like we need to update TFM already now... ;-)

**Comment by kaikreuzer** [comment]
Oops, so far the theory. @sjka just pointed out that the documentation does not match the code. While what I wrote above is the intention of the file, the current implementation actually does not use it. So one reason more to remove it then :-)

**Comment by dominicdesu** [comment]
@sjka 

> I'd rate the possibility of having custom usernames with a length of more than 30 characters pretty low, so from my point of view they might be safe to delete on bridge removal.

I agree that it would be nice to remove the user from the whitelist if the bridge is deleted from ESH. But on which condition? If the username >= 30 characters? This would be based on the assumption that a user does not choose custom usernames with more than 29 characters and that the Hue Bridge always generates usernames with more than 29 characters.
On the other hand, when I think about the various Hue Apps, I somehow doubt they remove the user from the bridge once the application is uninstalled.

About the hue.cfg, I will remove the file and update the documentation accordingly.

**Comment by sjka** [comment]
Valid point, the heuristic is not really great. As the number of users created by the binding is not that large, I don't really see a problem. And the bridge hopefully has some protection agains "user overflow".

**Comment by dominicdesu** [comment]
I have now removed the hue.cfg and adjusted the readme. Should I squash this into one commit?
Also, could you please check the readme if it makes sense? Do I understand it correctly that there are two ways to add things to the system? One using the PaperUI (is the resulting configuration stored in the mapdb?) and one using .thing files? What happens if I define the bridge in the .thing file and then the hue binding generates the username and saves it to the config? I guess it will not update the .thing file but save the username to the mapdb?

**Comment by sjka** [comment]
> I have now removed the hue.cfg and adjusted the readme. 

Thanks!

> Should I squash this into one commit?

Yes, please so so

> Also, could you please check the readme if it makes sense? 

Yes, I think so, looks good to me.

> Do I understand it correctly that there are two ways to add things to the system? One using the PaperUI (is the resulting configuration stored in the mapdb?) and one using .thing files? 

That's correct - and there can even be more... It essentially boils down to the ThingProvider implementations, where the ManagedThingProvider is the "PaperUI" one and the GenericThingProvider is the ".thing files" one. 

> What happens if I define the bridge in the .thing file and then the hue binding generates the username and saves it to the config? 

Really good point which I missed to spot so far: Currently your configuration change is not persisted at all! You need to use the editConfiguration() and updateConfiguration(...) methods. See https://www.eclipse.org/smarthome/documentation/development/bindings/thing-handler.html#updating-the-configuration 

> I guess it will not update the .thing file but save the username to the mapdb?

Yes, you are right - the *.thing files are read-only from the ThingProvider's perspective. Therefore storing the configuration will fail in that case. We need a better approach here in general, but that for sure exceeds the scope of this pull request! In order to keep things simple, how about the following solution: If the updateConfiguration(...) call fails for that reason, catch the corresponding Exception and log a huge, big warning for the user, giving instructions what has to be written into the *.thing file manually.

**Comment by dominicdesu** [comment]
Hi,

thanks for your detailed reply! I am currently switching to the updateConfiguration() approach. I like your suggestion to log a warning if the updateConfiguration() fails. 

Unfortunately I only get a [logger warning in AbstractManagedProvider](https://github.com/eclipse/smarthome/blob/db421ac801435d8a4dab7547a7268a21867a6bfd/bundles/core/org.eclipse.smarthome.core/src/main/java/org/eclipse/smarthome/core/common/registry/AbstractManagedProvider.java#L138) when using a .thing-configured bridge, so I don't really know how to differentiate between a successful and a failed update attempt:

```
2015-12-14 21:12:42 [INFO ] [b.hue.handler.HueBridgeHandler:315  ] - Creating new user on Hue bridge philips-hue - please press the pairing button on the bridge.
2015-12-14 21:12:42 [INFO ] [b.hue.handler.HueBridgeHandler:318  ] - User '2142b10724ae217f157962f7156e556f' has been successfully added to Hue bridge.
2015-12-14 21:13:11 [WARN ] [.c.c.r.AbstractManagedProvider:138  ] - Could not update element with key hue:bridge:1 in ManagedThingProvider, because it does not exists.
2015-12-14 21:13:12 [DEBUG] [b.hue.handler.HueBridgeHandler:86   ] - Connection to Hue Bridge philips-hue established.
```

One alternative to this approach could be to read the configuration directly after calling updateConfiguration() and check if the new username is set. If not, the log would print a warning stating that the username has to be manually set in the .thing files.

Or do you have some other suggestion...?

**Comment by kaikreuzer** [comment]
> Unfortunately I only get a logger warning in AbstractManagedProvider when using a .thing-configured bridge, so I don't really know how to differentiate between a successful and a failed update attempt

The cleaner way would probably to throw an exception, instead of swallowing the problem and only do the logging. @sjka, would you agree?

**Comment by sjka** [comment]
Valid point which indeed also surprised me a little. I agree with @kaikreuzer that throwing an exception would make sense here. 
I have created #748 for it. Does this make your implementation easier?

**Comment by dominicdesu** [comment]
@sjka thanks for the change! Yes, I can now catch the exception and log a related warning.
If this exception is thrown/catched, I am wondering if it is the right way to let the ThingStatus of the bridge change to ONLINE. If a user sees that the status is ONLINE, I doubt he will check the log files. After a restart, however, the username is lost and the bridge needs to be paired again.

Is it maybe better to set it to ONLINE.CONFIGURATION_PENDING or OFFLINE.CONFIGURATION_ERROR, so it is visible in the UI? Would need to check how this could be done in the hue binding as this seems to be a little bit difficult to realize with the current implementation. 

Also, the Configuration class (getConfig()) still contains the userName, even if the updateConfiguration() call fails because of the read-only .thing file. Are you aware of this and is this intended?

**Comment by sjka** [comment]
Ok, great.

> If a user sees that the status is ONLINE, I doubt he will check the log files.

Valid point! I doubt though that anyone would notice ONLINE.CONFIGURATION_PENDING though, especially when the binding actually works. OFFLINE.CONFIGURATION_ERROR would be better in that case, but yet again it's strange that the binding is working while the bridge claims it's offline.

In order to distinguish both cases, it would be good to have the roll-back in case of the configurationUpdate() failure, right?

> Also, the Configuration class (getConfig()) still contains the userName, even if the updateConfiguration() call fails because of the read-only .thing file. Are you aware of this and is this intended?

Yes, I'm aware of this, but to be honest I'm not quite sure about the rational... We could change that easily in the updateConfiguration() method by remembering the previous state and reverting it back in case the callback fails. @kaikreuzer @sbussweiler any thoughts?

**Comment by kaikreuzer** [comment]
> but yet again it's strange that the binding is working while the bridge claims it's offline.

It is only working because the new config is kept in memory and not reverted, right? So if we consider that as a bug, the right thing for the bridge is to go OFFLINE indeed.

> We could change that easily in the updateConfiguration() method by remembering the previous state and reverting it back in case the callback fails.

This probably makes sense - if the update failed, we should stick to the old values within the handler as well.

**Comment by dominicdesu** [comment]
The binding is working because once the bridge returns the generated username, the jue library is "connected". It doesn't care if ESH can persist the username afterwards or not. I have now added an additional check for the userName config value.
>In order to distinguish both cases, it would be good to have the roll-back in case of the configurationUpdate() failure, right?

Exactly, if the userName is not set in the configuration, we can set the ThingStatus to OFFLINE. 

Could you please check the updated PR?

**Comment by sjka** [comment]
looks good to me, thanks!

**Comment by kaikreuzer** [comment]
Thanks @dominicdesu!

**Pull request merged**
