### PR TITLE
implements issue #1569

### PR DESCRIPTION
**Pull request by adimova**
Signed-off-by: Ana Dimova <a.dimova@prosyst.bg>

### CODE REVIEW

**Comment by adimova** [comment]
this PR fixes the comments in #2070

**Comment by maggu2810** [comment]
What's the reason to create new PRs?
I think this makes it more complicated to see if all review points has been done etc.

**Comment by kaikreuzer** [comment]
Btw, @adimova, I would prefer if you could use a "speaking" tile for the PRs to make clear what it does. You can then add a comment like "fixes #xyz" or "resolves #xyz" to it, which will make the [auto close feature](https://help.github.com/articles/closing-issues-via-commit-messages/) kick in.

**Comment by adimova** [comment]
PR #2070 is recovered. So this PR can be closed

**Comment by maggu2810** [comment]
Thanks @adimova

**Pull request closed without merging**
