### PR TITLE
Add "gulp serve" with live reload to PaperUI

### PR DESCRIPTION
**Pull request by hoegertn**
This adds the gulp serve task to PaperUI to ease development of the UI without having to run maven and deploy the jar to a running server. It serves the sources under http://localhost:3000 and proxies requests to /rest to localhost:8080 so no CORS configuration and route changes are necessary.

This PR depends on PR #821

### CODE REVIEW

**Comment by GradyD** [comment]
I know that @sja has some concerns of adding gulp serve and proposed an alternative solution https://github.com/eclipse/smarthome/pull/800#issuecomment-170221083.

The reason I think gulp serve is a good improvement is because it breaks the barrier for UI devs. I myself am not well versed when it comes to massive java projects or jetty (only versed in single JAR/college projects). Currently if I want to see changes made I have to use maven to build my smarthome repo and then I can use eclipse to run openhab2. This takes ~5-10 minutes to accomplish, I could speed this up by building and coping the JAR of the paperUI as @hoegertn mentions, but with gulp serve I can make changes and view them right away without having to recompile any part of the stack.

Is there a way to accomplish what gulp serve is going to provide that is built into jetty/java?

**Comment by GradyD** [comment]
Looking at this, my biggest concern with this is that the gulp packages will start to balloon up instead of being lite and lean. There is a gulp package to do just about anything and I have seen projects that have tons of packages included and it makes it very bloated and hard to unwind and make edits/improvements. Having 15 packages I don't think is crazy but I do think that having more then 20 gets to the point where it can be hard to manage/improve. My personal opinion is you should use the least amount of packages possible, this applies to all aspects of web development. 

All that said I do feel that this has some good improvements added, like combining all of vendor static in vendor.js/css.

Outside of my concern this LGTM, once the merge conflicts have been resolved.

**Comment by kaikreuzer** [comment]
Am I correct that this PR is now outdated and can be closed?

**Comment by GradyD** [comment]
That is my understanding.

**Pull request closed without merging**
