### PR TITLE
Support html tags in item description

### PR DESCRIPTION
**Pull request by aounhaider1**
Allow html tags in description as described here: https://github.com/eclipse/smarthome/issues/565
Uses Angular library "angular-sanitize" version 1.3.13.

Signed-off-by: Aoun Bukhari <bukhari@itemis.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
I assume @kaikreuzer have to create a CQ for that library.

**Comment by kaikreuzer** [comment]
Will do (but btw, you should have all required rights to do the same :-))

**Comment by kaikreuzer** [comment]
@aounhaider1 Could you please check if version 1.4.8 is also compatible? There is already an approved CQ for that version, so it would simplify (and speed up) things for us.

**Comment by maggu2810** [comment]
@kaikreuzer I have found the 1.4.8 CQ, too. But I assume it would be better to use one version for all angular stuff (but I don't know).

> Will do (but btw, you should have all required rights to do the same :-))

You are right and I would like to do that. Have to handle some private stuff the next weeks and wait for a new internet connection, ... I will contact you and give it a try for the next CQ after April the 11th.
Okay, if you look at this until then?

**Comment by aounhaider1** [comment]
Version 1.4.8 worked fine. I have updated the pull request accordingly.

**Comment by kaikreuzer** [comment]
> But I assume it would be better to use one version for all angular stuff 

See https://github.com/eclipse/smarthome/issues/801#issuecomment-180422013 - we are very close to updating the rest to 1.4.8 as well!

> Okay, if you look at this until then?

It is even ok if I do it longer than that - you are already helping on enough other topics!

**Comment by kaikreuzer** [comment]
Submitted CQ 11144.

**Comment by kaikreuzer** [comment]
CQ has been approved as piggy-back.

**Pull request merged**
