### PR TITLE
applied code formatter Javascript files on Paper UI

### PR DESCRIPTION
**Pull request by kaikreuzer**
I had missed these files in #1160 since the formatter does not seem to work if it is executed on a folder and not on an individual file.

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
Strange, if I edit the files and press save, the formatter change them.
The new formatter should be active, correct? So I assume my Eclipse IDE is using it. And I assume you used the new formatter rules, too. What is going on here?

**Comment by kaikreuzer** [comment]
Can you check if your formatter is in line of what is defined in the .setup file?
I am not sure if the IDE automatically applies it or if you need to run "Perform Setup Tasks" manually once more?

**Comment by maggu2810** [comment]
The line length of JavaScript is still set to 120, so the formatter rules seems not to be up to date.
Running "Perform Setup Tasks" does not solve the problem.
I can import the formatter rules, but a developer that does not read all the PRs will not be noticed about that changes. Hm, a little bit wired.

**Comment by maggu2810** [comment]
The old and the new (#1084) formatter profiles are using version 11. Don't know if this can raise this bug.

**Comment by maggu2810** [comment]
The old and the new (#1084) formatter profiles are using version 11. Don't know if this can raise this bug.

**Comment by maggu2810** [comment]
@kaikreuzer I installed a fresh Eclipse IDE using the SmartHome setup.
The stuff between the head tags in "smarthome/extensions/ui/org.eclipse.smarthome.ui.paper/web-src/index.html" are indented.
If I format the file, the stuff between the head tag is not indented anymore.
Could you test this?

**Comment by maggu2810** [comment]
Also the fresh installation shows in the preferences 120 line width on
* Web, HTML Files, Editor

Are you sure your IDE setup is equal to the setup file :wink: 

I see that some preferences changed 120 to 999 but at least my fresh installation is not using this for HTML files.

**Comment by maggu2810** [comment]
Or my installer is buggy.
At least the setup file is correct.

**Comment by maggu2810** [comment]
~/.eclipse/org.eclipse.oomph.setup/cache/http___www.eclipse.org_setups_setups.zip

contains a file

./https/raw.githubusercontent.com/eclipse/smarthome/master/targetplatform/EclipseSmartHome.setup

that still shows the old value.

```text
grep -A1 '/instance/org.eclipse.wst.html.core/lineWidth' ./https/raw.githubusercontent.com/eclipse/smarthome/master/targetplatform/EclipseSmartHome.setup
          key="/instance/org.eclipse.wst.html.core/lineWidth"
          value="120"/>
```

**Comment by maggu2810** [comment]
I removed the cache directory, so the files are fetched again.
Still lineWidth=120 in the setup file in the zip.

**Comment by kaikreuzer** [comment]
Maybe the installer still uses an older revision? I do not exactly know myself, when/how this is updated...

I tested the ESH IDE setup and have the same problem as you.
I also tested the openHAB IDE and this shows already the correct settings. The PR that I did is afaik almost identical, so in general it seems to work...

**Comment by maggu2810** [comment]
openHAD is a Github product, Eclipse SmartHome a Eclipse product (as point of view of the Oomph plugin).

I think we need to know when the file "http://www.eclipse.org/setups/setups.zip" is updated.
I assume it is not created dynamical because the EclipseSmartHome.setup (in the archive under "/https/raw.githubusercontent.com/eclipse/smarthome/master/targetplatform/") has a timestamp "13. December 2015, 14:26".

**Comment by kaikreuzer** [comment]
I have asked the experts for help: https://bugs.eclipse.org/bugs/show_bug.cgi?id=470497#c10

**Comment by maggu2810** [comment]
After this is solved upstream, I installed the IDE using the setup file on a custom location in the filesystem.
I also using a startup script, that tries to download a new version of that file from Github. If the download fails the old one is used, if the download succeeded, the setup file is replaced.
This is IMHO very similar what Oomph does if an online location is used.
But so I can now use a up to date IDE :wink:

**Comment by maggu2810** [comment]
> I have asked the experts for help: https://bugs.eclipse.org/bugs/show_bug.cgi?id=470497#c10

There is still no answer from the experts.
If we decide to increase the line length for Java files to 160 (I agree with you that this is a good thing), then the setup should be updated for all users as it will affect much more files then the HTML stuff.

**Pull request merged**
