### PR TITLE
docs: Formatting

### PR DESCRIPTION
**Pull request by simon-koehler**
Rules Documentation: Trigger, Condition, Action were malformed and not correctly listed.

Signed-off-by: Simon Köhler <simon.koehler@accso.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
Do you know why the Github diff view shows every (but one) line changed?

Your commit message miss the Signed-off-by footer.

**Comment by simon-koehler** [comment]
@maggu2810 I have no idea, why every line is changed. I guess it's because I edited the file right on github.com. I was thinking this were a good idea - it seems not so.
Sorry for the missing footer. I was not aware..

**Comment by simon-koehler** [comment]
Malformed Commit message. Bad change-style - nearly every line is changed. I will retry with a new commit and pull request.

**Comment by maggu2810** [comment]
No problem.
Perhaps the line ending has been changed.

**Pull request closed without merging**
