### PR TITLE
Migrate IO SSE Tests from Groovy to Java

### PR DESCRIPTION
**Pull request by wborn**
Migrates the IO SSE Tests from Groovy to Java.

### CODE REVIEW

**Comment by maggu2810** [comment]
@wborn Here we could use `assertTrue` and `assertFalse` instead of `assert ... is(false)` etc.
So, no need for hamcrest there, too.

**Comment by wborn** [comment]
Are there already established conventions on when to use/not use Hamcrest? Then it would be really helpful if there was a handy conversion script/application to automate removing Hamcrest uses from the whole code base. Some smart regexps would already help a lot. It would save a lot of human effort and potential mistakes. ;-)

**Comment by maggu2810** [comment]
There isn't currently a conventions about the usage of Hamcrest.
IMHO with all the Java 8 features and the asserts that are part of JUnit itself, there is no really need for another dependency just to write the same logic differnt.

I agree that with a few line of code we could perhaps migrate from Hamcrest to JUnit without any human effort (except writing that migration code).

**Comment by maggu2810** [comment]
I retriggered Travis because it fails on some automation tests.

**Pull request merged**
