### PR TITLE
Interpret console command: fix #2493 #2494

### LINKED ISSUE #2493: Interpret console command with system interpreter displays null
My default HLI is set to "Rule-based interpreter".
When I run the command "interpret" in the console, I get just a "null" as result.
```
openhab> smarthome:voice interpret here is a test
null
```
Of course I have an item named VoiceCommand.
I tried to set my locale in Paper UI but no change.

### LINKED ISSUE #2494: Used locale by interpret console command
The "interpret" command considers only the default locale of your machine. Is it expected ?
I would have expected that it used the locale settings of openHAB if defined.
In my case for example, no chance to try with english as my machine is setup to a French locale.

An alternative would be to have the locale as a first optional argument of the command.
Any suggestion ?

### PR DESCRIPTION
**Pull request by lolodomo**
Update the interpret method prototype in the voice manager

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
With this change, we do not need line 87 & 88 anymore, right?

**Comment by lolodomo** [comment]
Yes you're right but if we suppress the null check here, it will be safer to add it in voicemanager.interpret.
I will update this PR to suppress the null check and include the null check in voicemanager.interpret in a next PR adding other little enhancement to voicemanager.interpret (having the hli id as argument).

**Comment by kaikreuzer** [comment]
You are right, the null check is missing in voicemanager.interpret - I would prefer if you could simply update this PR accordingly (feel free to add further improvements).

**Comment by lolodomo** [comment]
Ok

**Comment by lolodomo** [comment]
Ready for review.

**Comment by lolodomo** [comment]
Please wait again, I will fix the ussue #2493 in the same PR.

**Comment by lolodomo** [comment]
That(s time, it is really ok and ready for review and merge.

**Comment by lolodomo** [comment]
@kaikreuzer : tested today the snapshot 607 thinking this PR will be included. I already knew that Eclipse smarthome stuff is not automatically updated every bight. Is there a way for us to know what is the last PR considered from this repo in any nightly build of openHAB ?
Why not considering in the nightly build of openHAB the up-to-date version from Eclipse smarthome ?

**Comment by kaikreuzer** [comment]
> Is there a way for us to know what is the last PR considered from this repo in any nightly build of openHAB ?

Yes, here: https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/changes

> Why not considering in the nightly build of openHAB the up-to-date version from Eclipse smarthome ?

Because that would continuously break the openHAB distribution.

**Comment by maggu2810** [comment]
> Is there a way for us to know what is the last PR considered from this repo in any nightly build of openHAB ?

https://github.com/eclipse/smarthome/wiki/ESH-used-in-openHAB

**Comment by lolodomo** [comment]
Thanks guys

**Comment by kaikreuzer** [comment]
Thanks, @maggu2810, good idea 👍

**Pull request merged**
