### PR TITLE
Added X-Accel-Buffering=no header to SSE response in order to disable…

### PR DESCRIPTION
**Pull request by kolkoo**
… response buffering when using nginx as a proxy server.

This allows you to use nginx proxy buffering and still have working SSE.

Signed-off-by: IVAN GEORGIEV ILIEV <ivan.iliev@musala.com>

### CODE REVIEW

**Comment by kolkoo** [comment]
More info about this here http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering

**Comment by sjka** [comment]
lgtm

**Comment by maggu2810** [comment]
@kaikreuzer Do you wait for tests?

**Comment by maggu2810** [comment]
@kaikreuzer Do you wait for tests or Travis?

**Comment by kaikreuzer** [comment]
Was waiting for Travis to finish.

**Comment by BClark09** [comment]
This doesn't seem to be coming through for basicUI. Have tried a NGINX setup with and without buffering on the latest apt openhab. When buffering is off, eventsource items don't come through, and nothing is updated.

image

**Comment by kaikreuzer** [comment]
@kolkoo Could you check and comment?

**Comment by kolkoo** [comment]
@kaikreuzer will do

**Comment by kolkoo** [comment]
@kaikreuzer @BClark09  Correct me if I'm wrong but the basic UI seems to only be subscribing to rest/sitemaps/events and this PR is about /rest/events . 

I've tested PaperUI which uses /rest/events with and without nginx proxy and with or without buffering enabled and it works in all scenarios.

I'm not sure what the problem with BasicUI is but it's definitely not related to this PR.

**Comment by kolkoo** [comment]
@kaikreuzer Actually because this fix was only for /rest/events, naturally it won't work for sitemaps event as they are in a different resource. I also see that servlet 2.4 support will not work for them either, so perhaps it makes sense to decide if both fixes need to be transferred.

**Comment by BClark09** [comment]
Hi @kolkoo, thanks for explaining the issue and my misunderstanding. You are correct, this PR adresses only the events in Paper UI which are indeed now working correctly with buffering off. I had assumed that events from basic UI were obtained in the same way and therefore this PR would resolve this issue.

It's clear that a new issue needs to be created but what is the issue here? Is it that the sitemap events need to be updated to match the rest events or simply just that the same X-Accel-Buffering header needs to be set for sitemap events?

For reference the nginx proxy configuration to see this issue for sitemaps is:

```nginx
server {
        listen                          80;
        server_name                     ***.***.***.***;

        location / {
                proxy_pass                              http://localhost:8080/;
#               proxy_buffering                         off;    #uncomment to get live events.
                proxy_set_header Host                   $http_host;
                proxy_set_header X-Real-IP              $remote_addr;
                proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_$
                proxy_set_header X-Forwarded-Proto      $scheme;
        }
}
```

**Comment by kolkoo** [comment]
Hey @BClark09 if with proxy_buffering off; everything works fine for you, and it only breaks with buffering on then we just need to add the header to the sitemap events resource method for SSE, just as we've done here. Then it should work in both situations.

**Comment by BClark09** [comment]
That makes sense, I see that it should work with the same two lines in the relative place for [SitemapResource](https://github.com/eclipse/smarthome/blob/master/bundles/io/org.eclipse.smarthome.io.rest.sitemap/src/main/java/org/eclipse/smarthome/io/rest/sitemap/internal/SitemapResource.java) but don't know for certain. Would you be able to make a new PR for this? I'd be more than grateful.

**Comment by kaikreuzer** [comment]
> I also see that servlet 2.4 support will not work for them either, so perhaps it makes sense to decide if both fixes need to be transferred.

I do not really think that servlet 2.4 support is required in this UI, so if you could provide a fix for the buffering on the SitemapResource, it would be fine!

**Pull request merged**
