### PR TITLE
Changed creation of channels to not require a thing type

### PR DESCRIPTION
**Pull request by kaikreuzer**
This is my alternative suggestion to https://github.com/eclipse/smarthome/pull/1177

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
There is still a getBridgeIds, but you removed the bridge ids...

**Comment by kaikreuzer** [comment]
Good point - there are actually quite some further methods on ChannelUID that I did not remove/adapt...

**Comment by kaikreuzer** [comment]
updated PR.

**Comment by maggu2810** [comment]
Should we keep this open for further tests?
I don't know all the impacts of this PR.

The ChannelUID is used by bindings and so part of the API.
The constructors are marked deprecated but not removed (I assume to keep compatibility).
The public methods to get (u)ids (getThingTypeId, getThingId, getBridgeIds, getThingTypeUID) are removed now (so no backward compatibility, it could break third party bindings).
I am currently not informed which functions need to be kept and only marked deprecated and which one could be removed.

**Comment by cdjackson** [comment]
Quick test here looks good...

**Comment by kaikreuzer** [comment]
I kept the constructors, because it was possible to provide a valid functionality (a correctly created channel uid).
The methods that I removed were assuming a semantic behind the UID, which is something we removed from the ThingUID and thus it should have been removed from the ChannelUID as well. And with this change, there is e.g. simply no way to return a thing type UID for a channel.

I have done these changes in my openHAB workspace and no binding seems to have used any of these methods with the sole exception of rfxcom, which I will adapt when doing a stable ESH build.

**Comment by cdjackson** [comment]
> Should we keep this open for further tests?
> 
I don’t mind for a bit, but this is a major issue for the Z-Wave binding, so if you have a plan to do more tests, then no problem, but I wouldn’t want to see it open for too long...


> The ChannelUID is used by bindings and so part of the API.
> The constructors are marked deprecated but not removed (I assume to keep compatibility).
> 
They were only deprecated recently when the changeThingType was added. I thing un-deprecating them shouldn’t be an issue given the very short time?

> The public methods to get (u)ids (getThingTypeId, getThingId, getBridgeIds, getThingTypeUID) are removed now (so no backward compatibility, it could break third party bindings).
> I am currently not informed which functions need to be kept and only marked deprecated and which one could be removed.
> 
I did a quick search and didn’t find any bindings using this, but it might not be 100%. However, any bindings using these methods will not be guaranteed to work since they use the thingType, which as shown in my previous issue, doesn’t work.

**Comment by maggu2810** [comment]
> if you have a plan to do more tests, then no problem

Should we wait for some comments from @sjka?
I have no plans (time) at the moment to test this changes, but it seems to be very fundamental ones.

@cdjackson I do not complain about the un-deprecating. It has been more a general question. I do still not know which stuff must not be changed, because it could be used by third party companies and which one could be changed.

So, if you both think that this will not break to much stuff, I will merge it. I am fine with removing stuff / informations from a UID, but as stated above, I don't know the impacts.

**Comment by kaikreuzer** [comment]
I think we can wait for @sjka to comment tomorrow as well and I will prepare myself to do the new stable build tomorrow night, so that the Z-Wave binding gets back to a working state soon again.

**Comment by cdjackson** [comment]
Fine by me…

There may be further problems yet - I need to remind myself how I implemented the thing config provider as that’s also no working with things that have changed thing type….

**Comment by sjka** [comment]
lgtm
the way how the channel UIDs were constructed clearly was broken. No idea why I have missed that earlier...

Regarding compatibility: Yes, I indeed left the old constructors in there is to not break any existing bindings. As long as you don't intend to change the thing types, they are still valid somehow. And I agree with @kaikreuzer that it simply makes no sense to keep the methods in the ChannelUID class. If a 3rd party solution relies on them, the ugly workarounds should be implemented there, not in the ChannelUID class, I think.

**Comment by cdjackson** [comment]
Thanks. 

I assume we can now release a new ESH stable? If so, will this be in tonight's OH2 distro or will it take a day or two to flow through?

**Comment by kaikreuzer** [comment]
I'll make sure that the stuff is available in OH2 by midnight ☺️

**Comment by cdjackson** [comment]
Thanks Kai - much appreciated.

**Comment by kaikreuzer** [comment]
Done! The latest openHAB distribution should include all recent changes!

**Comment by cdjackson** [comment]
Thanks.

**Pull request merged**
