### PR TITLE
PaperUI: Collapse long string stateText

### PR DESCRIPTION
**Pull request by aounhaider1**
Before:

screen shot 2017-11-16 at 15 52 02

After:

screen shot 2017-11-20 at 16 14 17

Signed-off-by: Aoun Bukhari <bukhari@itemis.de>

### CODE REVIEW

**Comment by htreu** [comment]
Hi @aounhaider1 what is the reason for an item to have such a long state text? What device/channel does provide this text? Is it meant to be bound to an item?

**Comment by aounhaider1** [comment]
The zonegroup channel of Sonos have this stateText. This PR is just a boundry check in case an item has a long state text.

**Comment by kaikreuzer** [comment]
@htreu FYI: https://github.com/eclipse/smarthome/issues/4570

**Comment by htreu** [comment]
Although the implementation of the ellipsis feature here is okay from a coding pov, I guess we should close this PR since it fixes the "bug" in the wrong place.
Even when the sonos channel in question stays like it is it does not deliver end-user information when bound to an item. It should at least be filtered/transformed in on way or the other.

**Comment by aounhaider1** [comment]
Ok. But I think that at least the text should be wrapped inside the card. I'll close this PR.

**Comment by htreu** [comment]
@aounhaider1 yes, wrapping the text would actually make sense. I guess with XML there is the problem of not having whitespace separators to allow word wrap.

**Pull request closed without merging**
