### PR TITLE
Fix issues: #842(RuleRegistry storage issue and ) and #841(Fix - Crea…

### PR DESCRIPTION
**Pull request by danchom**
…tion of a rule from template fails #831)

Signed-off-by: Yordan Mihaylov <j.mihailov@prosyst.com>

### CODE REVIEW

**Comment by danchom** [comment]
Some changes from PR #841 was merged

**Comment by kaikreuzer** [comment]
Thanks, but unfortunately, #831 still isn't fixed through this :-(
When creating a rule from a template, the `/rest/rules` url still returns the "not-exploded` rule referencing the template.
Interestingly, when accessing `/rest/rules/rule_1` it gives the expected result. Could you please check?

**Comment by danchom** [comment]
I've miss to return correct rule after update. It is fixed with the last update.

**Comment by kaikreuzer** [comment]
Thanks, looks better, but there are still problems:
- the rule name is lost
- the rule description is lost
- the rule contains the "configuration" of the template, this should be removed (since it is added to the according modules already)

**Comment by danchom** [comment]
I'm not sure if it is good to remove configuration of template from the rule. There is not other way to define configuration properties of created rule. Otherwise the created rule will be always without configuration and can't be configured.
For example in the SampleTemplateDefinition
getRule 
should return 
    "conditions": [
      {
        "id": "SampleConditionTemplateID",
        "type": "SampleCondition",
        "configuration": {
          "operator": "$condition_operator",
          "constraint": "$condition_constraint"
        },
        "inputs": {
          "conditionInput": "CompositeSampleTriggerTemplateID.compositeTriggerOutput"
        }
      }
    ],

instead of hardcoded value.
    "conditions": [
      {
        "id": "SampleConditionTemplateID",
        "type": "SampleCondition",
        "configuration": {
          "operator": ">",
          "constraint": "0"
        },
        "inputs": {
          "conditionInput": "CompositeSampleTriggerTemplateID.compositeTriggerOutput"
        }
      }
    ],

**Comment by kaikreuzer** [comment]
> There is not other way to define configuration properties of created rule.

A rule does not have any configuration by itself.
If you want to add this, you are introducing a completely new concept. We can certainly discuss adding such a feature, but I would prefer to do this out of scope of this bug report / PR.

**Comment by danchom** [comment]
Rule has a configuration and configuration description. They exists in the rule interface. This configuration is entry point to update configuration of the modules. 
As I remember we have following process:
1) rule1 = getRule(uid)
2) rule1.setConfiguration(map);
3) ruleRegistry.updateRule(rule1)

the rule update links between modules and new configuration properties

**Comment by kaikreuzer** [comment]
> Rule has a configuration and configuration description.

No, they don't. See your own example at https://github.com/eclipse/smarthome/blob/master/docs/documentation/features/rules.md#sample-rules.

> They exists in the rule interface. 

Only in order to allow rule instantiation from a template (see https://github.com/eclipse/smarthome/blob/master/docs/documentation/features/rules.md#rule-templates). The rule interface also has a templateID and this has to be erased when instantiating a rule from this definition. We probably should have better introduced two different interfaces (for "pure rules" and for "rules from template") to make this clear. The "rule from template" version is ONLY valid for the POJO that represents the JSON structure, but not for the runtime rule instance.

Please let us first fix this issue and then discuss if we need to support configurations in rule in general and how this should be sync'ed with the module configuration without duplicating or contradicting it. We would also need to define how such a functionality should be integrated in a UI, so that it is clear to the user what happens there. This will need some more conceptional work.

Btw, the links on https://github.com/eclipse/smarthome/blob/master/docs/documentation/features/rules.md#defining-rules-via-json are broken - could you possibly add the schemas to the documentation folder and adjust the links?

**Comment by marinmitev** [comment]
created issue for the json schemas:
https://github.com/eclipse/smarthome/issues/893
probably Ana Dimova has copies of these files and will restore them

**Comment by danchom** [comment]
Fix the issue according Kai's comments, 
except this one: the rule name is lost
Template does not have a name and I can't set it to the created rule.

**Comment by kaikreuzer** [comment]
> I can't set it to the created rule.

What do you mean by this?
Look at the sample at https://github.com/eclipse/smarthome/blob/master/docs/documentation/features/rules.md#rule-templates
What happens to the line
```
    "name": "RuleByTemplate"
```
Do you throw this away? Why is this not kept as the name of the rule?

**Comment by danchom** [comment]
Sorry my fault. It is fixed.

**Comment by kaikreuzer** [comment]
Works wonderfully now - thanks :+1:

**Pull request merged**
