### PR TITLE
[1452] MapDB database corruption

### PR DESCRIPTION
**Pull request by pwolfart**
Updated mapdb from version 1.0.2 to 1.0.9.

Forum: https://www.eclipse.org/forums/index.php?t=msg&th=1075047&goto=1724448&#msg_1724448

Bug: https://github.com/eclipse/smarthome/issues/1452

Signed-off-by: Patrick Wolfart <p.wolfart@jung.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=1452

**Comment by maggu2810** [comment]
Thank you very much for the test you have done. Good work.

**Comment by kaikreuzer** [comment]
I'll create a CQ for it soon.

**Comment by kaikreuzer** [comment]
Created CQ 11322. Now waiting for IP team approval.

**Comment by kaikreuzer** [comment]
CQ has been approved!

**Pull request merged**
