### PR TITLE
added possibility to manage group functions through REST API

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@maggu2810 Ok for you to merge? Some other PRs depend on this, so I would like to merge this by tonight, if you do not veto. I think the changes don't have a huge impact, so all should be safe to also review in detail after being merged.

**Comment by kaikreuzer** [comment]
Thanks, all addressed.

**Comment by maggu2810** [comment]
> I think the changes don't have a huge impact, so all should be safe to also review in detail after being merged.

A not-so-detailed review has been done, so let's merge it... :wink:

**Comment by kaikreuzer** [comment]
Thanks :-)

**Pull request merged**
