### PR TITLE
Add size()-Method to StringListType.java

### PR DESCRIPTION
**Pull request by maihacke**
Possible fix / enhancement for #5970

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks for this!
But please let me first try to understand the use case here: You are saying that there are state updates for CallItems that only have one instead of two elements in the list, right?

Looking at the [openHAB 1 version of CallType](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.compat1x/src/main/java/org/openhab/library/tel/types/CallType.java) (which has been "generified" in ESH to the StringListType), it should be clear that for CallItems it is expected that there are always exactly two parts in the state.

So if you are saying you come across situations where this is not the case, I would consider this a bug, which should be fixed instead, wdyt?

**Comment by maihacke** [comment]
The problems occurs when using the Fritzbox TR064 binding.
When the caller has no id the CallItem/StringListItems has only one element.
See discussion here https://community.openhab.org/t/fritzbox-binding-tr064-getting-and-staying-last-caller-in-openhab/37645/6?u=maihacke

**Comment by kaikreuzer** [comment]
So would you agree that it would be much nicer if this binding would always provide two elements, so you can rely on the fact that you can access the called number as element (1) of the list?

**Comment by kaikreuzer** [comment]
Digging into it, I actually found that this is a bug in ESH - I have created #5994 as a fix.
With this fix applied, you should actually have no longer the need for the size() method, so assuming your agreement, I close this PR.

**Comment by maihacke** [comment]
That's perfectly fine and even simpler for end users. Thanks a lot.

**Pull request closed without merging**
