### PR TITLE
Select only GSON 2.7 in SmartHome launch config

### PR DESCRIPTION
**Pull request by htreu**
* Both versions 2.4 and 2.7 of Google GSON where selected before.

Signed-off-by: Henning Treu <henning.treu@telekom.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
AFAIK we used 2.3.1 (see also https://github.com/eclipse/smarthome/issues/3680#issue-236529529)
Why do we want to use 2.7 in the launch configuration (used for testing) now?

**Comment by kaikreuzer** [comment]
@maggu2810 See https://github.com/eclipse/smarthome/issues/4440. GSON 2.7 is required by the LSP feature, but only for this. So "plain" ESH is meant to be compatible with GSON 2.3.1, only solutions that have LSP installed will require 2.7.
We do not have an easy way to reflect that in the target platform - in order to allow LSP development&debugging, it is imho ok to have 2.7 in the IDE; the downside is that we won't notice if any other code accidentially starts using 2.7 features...

**Comment by htreu** [comment]
Yes, @maggu2810 you are right.
First: 2.4 was my mistake, I was referring to Version 2.2.4 which is what our targetplatform defines right now, see https://github.com/eclipse/smarthome/blob/master/targetplatform/smarthome.target#L7

In the comment (https://github.com/eclipse/smarthome/issues/3680#issue-236529529) @kaikreuzer mentioned 2.3.1 but it seems that this version never made it into our targetplatform.
The 2.7.0 I selected in this PR is a transient dependency for LSP support, namely the `org.eclipse.lsp4j.jsonrpc` bundle. It requires GSON to be in a range [2.7.0,3.0.0).

How should we resolve this issue?
/cc @sjka

**Comment by htreu** [comment]
FTR: the original issue I'm trying to fix is my IDE complaining about the version constraint for GSON is not matched when LSP support comes up. Sometimes only GSON 2.2.4 is available at that time.

**Comment by maggu2810** [comment]
For me it would be okay bump the GSON requirements 2.7 for the whole ESH or just state that we officially don't support older versions anymore.
I don't like to keep compatibility for version x in the one part of the bundles but version y in the other ones.
If GSON is used by ESH bundles one version should be choosen.
Isn't it what we do for e.g. Jetty already? As we introduced a function that has been present in a more recent version, we used the more recent version for the whole third party dependency.
Sure, there could be a difference between "ESH core" and "ESH extensions" but in the long run, one requirement would be simpler to maintain and handle then different requirements for different parts of ESH.

**Comment by kaikreuzer** [comment]
In general I agree, but please note that we had a lot of special stuff in the target platform for the designer in the past and no ESH bundle was supposed to make use of them.
In some way the LSP feature is the successor of the designer and it is probably used by only very few solutions that are built on ESH. Furthermore, it merely is a transitive dependency of those LSP libs that won't be required if you don't deploy LSP.

> For me it would be okay bump the GSON requirements to 2.7 for the whole ESH or just state that we officially don't support older versions anymore.

As always: If our code does not have any reason for this as it works with 2.2.4, we should be conservative and not require people to upgrade.

**Comment by htreu** [comment]
My suggestion would be to select only 2.2.4 in the launch config and disable the LSP feature. In case you depend on the LSP feature during development you have to maintain a local launch config with the required dependencies.

**Comment by maggu2810** [comment]
> As always: If our code does not have any reason for this as it works with 2.2.4, we should be conservative and not require people to upgrade.

Our (ESH) code includes the LSP feature (the successor of the designer) that is perhaps used by very few solutions and all the other one.
So, our code (the LSP one) does have any reasons for. In this case (let's repeat it) it is only one bundle of the dozen ones and this one bundle is mostly not used.
But I still think it is similar to the Jetty bump that has been done because (IIRC so correct my if I am wrong) one place -- the proxy servlet in the esh.ui bundle -- needs it (which is also optional for at least a few products I know).

At least I don't prefer any GSON version, I just don't like to use different ones in the ESH code base.
Regardless if there are solutions that don't need LSP or there are solutions that don't use the proxy servlet and are affected by the Jetty bump.

**Comment by htreu** [comment]
I will change this PR to do the opposite of the original proposal: Select only the 2.2.4 version of Google GSON and also deselect the LSP bundle for now. My intent was to "fix" the startup behaviour in the IDE.
Lats take the GSON version bump discussion to a new issue.

**Comment by htreu** [comment]
In fact, the ESH LSP bundle was not selected but only the org.eclipse.lsp* bundles.

**Comment by htreu** [comment]
Moved discussion about supported versions here: #5077.

**Pull request merged**
