### PR TITLE
updated license header plugin to use correct headers for the different c...

### PR DESCRIPTION
**Pull request by kaikreuzer**
...omponents

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@marinmitev, please check that this is ok for you. I have changed the license plugin so that it correctly puts license information on the automation component as well when doing a ```mvn license:format```. For this, I have slightly modified your license headers to be in line with the headers of other components.

**Comment by marinmitev** [comment]
Hi Kai,
sorry but we cannot accept such change, the copyright header should not be replaced with a script and each individual source file should carry its own copyright info in order to track the history of changes.
This will allow you to change the source files and in such cases to add others to the copyright in next version of the changed files. But we need to have the initial version with this original copyright statement, because it will be used also in our ProSyst product..
Best regards,
Marin

**Comment by kaikreuzer** [comment]
Marin, the agreed process in this project to track changes is through the author tags, which you have also added, so this information is actually duplicated in the header and thus should be removed.
Changing the copyright headers for your product can simply be done through the license plugin as well - you have full control there.

Note that the license plugin in the official way to add correct license headers (see A.2 in https://github.com/eclipse/smarthome/blob/master/docs/sources/development/guidelines.md#a-code-style). So when contributors use this plugin, the automation classes would be updated with the default license header, if not covered by the scripts.

**Comment by marinmitev** [comment]
after internal discussion, we agree to accept this change

**Comment by kaikreuzer** [comment]
Great, thanks a lot!

**Pull request merged**
