### PR TITLE
Basic/Classic UI: support for HTTP Live Stream

### PR DESCRIPTION
**Pull request by lolodomo**
Add support for HLS in compatible WEB browsers
Use encoding="HLS" in the video sitemap element.

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
I tested it with Chrome on Android.
I can't test with Apple devices but it should work in Safari (Mac or iOs).

**Comment by lolodomo** [comment]
As an example, this change allows the rendering of video from the Netatmo Welcome camera.

You can find compatible browsers with HLS in wikipedia: https://en.wikipedia.org/wiki/HTTP_Live_Streaming

**Comment by lolodomo** [comment]
I tested with the 5 m3u8 links proposed on this page: https://bitmovin.com/mpeg-dash-hls-examples-sample-streams/

It is working well in Chrome (Android) and in Microsoft Edge (Windows 10).

Unfortunately Netatmo welcome links are not working in Microsoft Edge.

**Comment by lolodomo** [comment]
Even if I am very confident, it would be cool if someone can test with Safari browser on iOS and Mac.

**Comment by sjka** [comment]
At lest the middle one works on Safari @ macOS and Safaris @ iOS. I'm not sure whether it's just that the others are simply not available/overloaded right now or it that points to some other issues.

None of them works in Chrome @ macOS/Windows 10, which is expected though if I read [this Wikipedia page](https://en.wikipedia.org/wiki/HTTP_Live_Streaming) correctly.

This is according to your expectations, right?

**Comment by lolodomo** [comment]
Are your tests really done with the updated UIs from this PR ?
The 5 links were available yesterday and I am expecting that they all works in Safari with my changes.
As a reminder, they all work in Chrome/Android anec Edge/Windows 10 with this PR.

**Comment by sjka** [comment]
Ouch, my bad - got the IPs mixed up, sorry. 
They are indeed _all_ good on Safari on both OSes!

**Comment by sjka** [comment]
Just one question regarding the encoding configuration - unfortunately we have no documentation about sitemaps here, so the best I could find was the one from [openHAB](http://docs.openhab.org/configuration/sitemaps.html#element-type-video). There it says that the encoding attribute "can stay left empty for auto selection". This does not hold true not anymore, right? Is it somehow possible to auto-detect HLS streams?

**Comment by lolodomo** [comment]
I will update this documentation once this PR is merged to explain that "hls" has to be set for m3u8 files (HLS).

**Comment by lolodomo** [comment]
Thank you for your additional tests @sjka . I think you tested wit success on all compatible WEB browsers. Note that it should work in Chrome/iOS too.

**Pull request merged**
