### PR TITLE
PaperUI handle multiple linked items in a channel

### PR DESCRIPTION
**Pull request by aounhaider1**
fixes https://github.com/eclipse/smarthome/issues/867 and https://github.com/eclipse/smarthome/issues/1140
Signed-off-by: Aoun Bukhari <bukhari@itemis.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
@lolodomo As you created the linked issues, can you test that fix?

**Comment by aounhaider1** [comment]
@maggu2810 its a new feature not a fix, so you can also test it. 😄

**Comment by kaikreuzer** [comment]
But @lolodomo requested the feature, so he should indeed have the honor to say whether it lgth.

**Comment by lolodomo** [comment]
I don't know what files I have to deploy and where to deploy them ?
Is there a jar file for Paper UI  like for a binding?

**Comment by kaikreuzer** [comment]
@aounhaider1 Due to merging another PR, there are now merge conflicts - could you please rebase this branch?

**Comment by aounhaider1** [comment]
Updated!

**Comment by kaikreuzer** [comment]
Looks nice!
Just some small wishes:
1. If there is a single item linked, could the separator underneath it be avoided?
2. Could we add a navigation to the items? E.g. by clicking on the circle and the item text.
3. Shall we change the item text to "LabelOfItem (id_of_item)"?
4. Shall we change the selection list entries when choosing an item to link as well to "LabelOfItem (id_of_item)"?

**Comment by aounhaider1** [comment]
3) & 4) I think we should. That will make it consistent throughout PaperUI. We are currently rendering it Label (Id) in all the configurations, so I think it makes sense.

**Comment by aounhaider1** [comment]
Updated accordingly.

**Pull request merged**
