### PR TITLE
Classic UI: escape HTML characters

### LINKED ISSUE #3743: Classic UI: bad display when value contains XML
This can be checked for example with the zonegroup channel of the Sonos binding.
Some character escaping is probably missing.

### PR DESCRIPTION
**Pull request by lolodomo**
Fix #3743

Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by lolodomo** [comment]
For information, I was not able to fix the particular case of the selection element: when you open the sub-page to select amongs a list, if your label is defined as "TV <TV-ok>" in the sitemap mapping, only "TV" will be displayed.

**Comment by lolodomo** [comment]
As a side note, I replaced the code in escapeURLPath by the code from Basic UI. Using `new URI(null, null, path, null).toString();`was failing with the exception in cases when `URLEncoder.encode(path, "UTF-8");`is working. Of course, icons are still displayed correctly.

**Comment by lolodomo** [comment]
@resetnow : could you please review this PR ? The changes are more or less the same changes you already reviewed for Basic UI.

**Comment by lolodomo** [comment]
How do you enter a console command when you start OH from Eclipse ?

An alternative to test your case would be to define a rule.

**Comment by resetnow** [comment]
I think console for input is already allocated in the default run configuration, just paste the command where the output is.

**Comment by lolodomo** [comment]
I was not aware that it was possible ! But it works.I can confirm your test case.

**Comment by lolodomo** [comment]
@resetnow : what's wrong with that HTML code: `<title set="wa0201" style="">Message test &lt;i&gt;test&lt;/i&gt;</title>`
The text betwen <i> and </i> appears in italic

**Comment by lolodomo** [comment]
Same problem with an hardcoded label in sitemap like this one:
```
Text label="Group <i>Demo</i>" icon="firstfloor" {
}
```

**Comment by lolodomo** [comment]
It seems to be exactly the same problem I found in the selection list and I was not able to fix !
I hope you can tell me what's wrong with this HTML code and what to do to fix it.

**Comment by 9037568** [comment]
I'm curious why you'd ask something to be rendered in italics and then be surprised when it's rendered in italics?

**Comment by lolodomo** [comment]
We just want to display the value of an item that can contain anything without any interpretation by the HTML browser. Italic was just an example but the problem is in fact with any XML tag.
I don"t understand why escaping is working everywhere except in the title tag. Probably something obvious but I am not a confirmed HTML developer.

**Comment by 9037568** [comment]
[Maybe this](https://stackoverflow.com/questions/3848664/prevent-browse-to-render-html-when-using-htmlentities-function-in-php) has a solution?

**Comment by lolodomo** [comment]
I will have to try how Basic UI handles that case. As the escaping code is the same in Basic UI and Classic UI, U would not understand why it us correct in Basic UI and not in Classic UI.

**Comment by resetnow** [comment]
One possible case is that the data transferred in a long-lining request are escaped only once. Since long-polling response is an XML document itself and "title" element doesn't have CDATA escaping, all the HTML entities are transformed back into their respective symbols once the document tree is parsed in broswer. https://github.com/eclipse/smarthome/blob/067bd5122b4666452bda319cb4e1de13eda9ab00/extensions/ui/org.eclipse.smarthome.ui.classic/snippets/layer.html#L216:56, July 4, 2017, lolodomo <notifications@github.com>:I will have to try how Basic UI handles that case. As the escaping code is the same in Basic UI and Classic UI, U would not understand why it us correct in Basic UI and not in Classic UI. —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.     --Sent from Yandex.Mail for mobile

**Comment by lolodomo** [comment]
I just checked the layer.html in Basic UI and I can find this:
`<title><![CDATA[ %label% ]]></title>`
while in Classic UI: 
`<title set="wa%id%" style="%labelstyle%">%label%</title>`
Il will try to add CDATA...

**Comment by lolodomo** [comment]
Problem with title is now fixed.

**Comment by sjka** [comment]
Thank you all!

**Pull request merged**
