### PR TITLE
ESH Formatter: force block usage

### PR DESCRIPTION
**Pull request by maggu2810**
I am using two commits and prefer to keep them separated.

The first one should change no setup rule, but using a reformatted XML file only. If you using e.g. the import settings or the record settings option of Oomph it changes the layout of the XML. I cannot find any stuff that is broken using this layout, but perhaps someone could test this, too.

The second commit set the save action "use blocks (always)".

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Can you provide the same for the openHAB 2 setup to have that in sync?

**Comment by maggu2810** [comment]
Have you seen the question about JS indentation (which one do we want to use)?
What identation would we like to use for XML?

**Comment by kaikreuzer** [comment]
Yes, sure, just didn't yet find the time to answer!

**Comment by maggu2810** [comment]
Ok, fine. I will start to change the OH setup changes after the remaining stuff is done for the ESH one. I do not like to sync them multiple times :wink:

**Comment by kaikreuzer** [comment]
@maggu2810, btw, doesn't this change require to also update https://github.com/eclipse/smarthome/blob/master/targetplatform/EclipseSmartHome.setup#L419?

**Comment by maggu2810** [comment]
Yes, it should be changed :grin: 
I changed this, but the other PR (JavaScript, HTML, ...) pointed me to a recorder properties loss (or I don't understand it).
Will have a look at this one again.

**Pull request merged**
