### PR TITLE
Renamed a few packages to internal in the org.eclipse.smarthome.io.re…

### PR DESCRIPTION
**Pull request by VelinYordanov**
…st.core bundle.

See openhab/static-code-analysis#100

Signed-off-by: VelinYordanov <velin.iordanov@gmail.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
I myself imported stuff of the REST bundle some time ago because I would like to reuse existing code. But this was not about the resources but the DTO and the mappers (and one service).
But also about this ones, I stop doing it.

About the REST resources:
I don't know if it make sense to reuse the REST resources at all.
I agree we should use the same approach for all RESTResources.
IMHO we could make them internal

**Comment by kaikreuzer** [comment]
I'd agree - let's keep the RESTResources private, while exporting the DTOs and mappers.

@VelinYordanov Would you be able to refactor the code accordingly?

**Comment by VelinYordanov** [comment]
@kaikreuzer Would that suffice?

**Comment by kaikreuzer** [comment]
Yes, thanks, I think this looks good as it is (@maggu2810, do you agree?).
So all there is left to do is to adapt the unit tests accordingly.

**Comment by kaikreuzer** [comment]
We already have this: The SitemapResource uses the ItemDTOs (and yes, potential side effects are expected and wanted ;-)).

**Comment by maggu2810** [comment]
My comment has been about non-ESH bundles that reuse the DTOs -- so ones that are not under our control.

**Comment by VelinYordanov** [comment]
@kaikreuzer The tests should be ok now.

**Comment by sjka** [comment]
Would have been nice if _all_ `<implementation...` tags were adapted in the XMLs. Now many resources are broken 😒

**Pull request merged**
