### PR TITLE
Use thingTypeUID field for thing's icon character

### PR DESCRIPTION
**Pull request by aounhaider1**
fixes https://github.com/eclipse/smarthome/issues/2182
Signed-off-by: Aoun Bukhari <bukhari@itemis.de>

### CODE REVIEW

**Comment by aounhaider1** [comment]
No. But is it possible for thing to not have a thingtype uid at all? In that case we can show the first letter of thing's label itself.

**Comment by kaikreuzer** [comment]
Yes, this is possible. Also ok to leave it empty in such a case, I just want to make sure that there isn't an error thrown.

**Comment by aounhaider1** [comment]
Updated!

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
