### PR TITLE
Fixes #1483. Improve RuleRegistry, ModuleTypeRegistry and TemplateReg…

### LINKED ISSUE #1483: Proposal for improvements of Automation engine API
1) Replace ModuleTypeRegistry.getAll(Class) with following method:  getTriggers(), getTriggers(Locale), getConditions(), getConditions(Locale) and getActions(), getActions(Locale)
--  same for TemplateRegistry
2) Change parameter of getByTags(Set<String> tags) mehtod -> getByTags(String[] tags) - It is simple to use i.e. getByTags(String[]{"tag1", "tag2"}). This change has to be applied to  RuleRegistry, ModuleTypeRegistry and TemplateRegistry.
3) RuleRegistry: getStatus(String ruleUID); -> getStatusInfo(String ruleUID) - the return object is StatusInfo object not just a Status object.
4) Check rule's constructors. Remove configuration description and configuration from rule without template. Check all constructors.
5) Check if it is suitable to set name and tags of rule without update the rule. In this way the rule resolutio will be skipped.
6) Add ruleId into RuleStatusInfo object. The receivers must know what was the source of this status info object. At the moment this relation is done in RuleStatusInfoEvent, but IMHO it has to be part of RuleStatusInfo object. (see RuleStatusInfoEvent)

### PR DESCRIPTION
**Pull request by danchom**
…istry APIs

Signed-off-by: Yordan Mihaylov <j.mihailov@prosyst.com>

### CODE REVIEW

**Comment by danchom** [comment]
I'm not sure if these method signatures are ok
ModuleTypeRegistry.getByTags(Locale locale, String... tags);
TemlpateRegistry.getByTags(Locale locale, String... tags);
In all other places locale is the last parameter.

**Comment by maggu2810** [comment]
@kaikreuzer I have tested Travis CI using this PR. Build succeeded: https://travis-ci.org/maggu2810/smarthome/builds/141445231

**Comment by kaikreuzer** [comment]
Cool, I didn't expect that travis accepts such huge builds with tons of Eclipse RCP artifacts.

Great that it works - so feel free to request the required github hook from the Eclipse Webmaster.

**Comment by danchom** [comment]
How can I restart the continues integration build? As I see the fail is not related to the PR.

**Comment by kaikreuzer** [comment]
try to force push your branch.

**Comment by danchom** [comment]
Hi Kai, could you please check this PR, it contains API changes related to our meeting in Sofia.

**Comment by kaikreuzer** [comment]
> I'm not sure if these method signatures are ok
> In all other places locale is the last parameter.

Fine for me, since there isn't really another option when using varargs.

**Pull request merged**
