### PR TITLE
Bug 482684 - ConfigDescriptionParameter methods should not return null

### PR DESCRIPTION
**Pull request by chriskn**
Changes:
ConfigDescriptionParameter.java contains only boolean attributes (no Boolean attributes anymore).
ConfigDescriptionParameterBuilder.java performs null safe conversation from Boolean to boolean values.

Implemented ConfigDescriptionParameterBuilderTest.groovy to clarify usage of ConfigDescriptionParameterBuilder.java and ConfigDescriptionParameter.java

Signed-off-by: Christoph Knauf  <christoph.knauf@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=482684

**Comment by maggu2810** [comment]
@kaikreuzer 
Have we already talked about braces for one-liner (e.g. for if-else-branches)?

**Comment by kaikreuzer** [comment]
Yes, in general, we have them. Doesn't the formatter even add them? Looking at the PR, it does not seem so... (can it be changed?)

**Comment by maggu2810** [comment]
It can be changed in the clean up profile and the save actions.
If I add the options to the EclipseSmartHome.setup file, the "Setup Editor" changes all the "Global Preferences" to "User Preferences".
Don't know why.

**Comment by chriskn** [comment]
It is not configured in the formatter. I will change my implementation tomorrow.

**Pull request closed without merging**
