### PR TITLE
adds kW·h as Unit

### LINKED ISSUE #5341: kWh are not recognized as Energy values
The recently introduced unit support has an "Energy" dimension defined, which uses by default the SI unit "J" (Joule).
In practice, the alternative "Wh" are used much more frequently and thus I would expect this unit to be usable for items with `Energy` dimension.

I defined an Item like this:
```
Number:Energy Energie			"Energie [%.1f kWh]"
```
Sending a value on the console
```
smarthome send Energie 123.456
```
results in
```
2018-04-03 13:27:05.491 [DEBUG] [.e.s.core.types.util.UnitUtils:108  ] - Unknown unit from pattern: kWh
```
and no unit being assigned to the item state.

As energy is likely the most common use case besides weather for units, I'd consider this a rather critical issue that needs to be addressed quickly. See also https://github.com/openhab/openhab2-addons/pull/2167#discussion_r178578851.

### PR DESCRIPTION
**Pull request by J-N-K**
fixes #5341

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by J-N-K** [comment]
Travis fails in unrelkated JSON storage test.

**Comment by J-N-K** [comment]
Retriggering build

**Comment by J-N-K** [comment]
I don‘t understand why so many builds fail lately. This is clearly unrelated, unfortunately before the core tests.

**Comment by maggu2810** [comment]
I assume this error is raised because of #5318.
NPEs in tests are not catched anymore.
IMHO this change is correct but it identify that some tests need more love (e.g. the related one seems to be very timing dependent).

I assume this one (the JSON storage one) will be fixed by #5353

**Comment by J-N-K** [comment]
retriggering build after tests are finally fixed

**Comment by J-N-K** [comment]
done. and integrated in #5336 to avoid merge conflicts

**Pull request closed without merging**
