### PR TITLE
use toFullString when creating GroupItemStateChangeEvent

### PR DESCRIPTION
**Pull request by BenediktNiehues**
fix for #3408
Signed-off-by: Benedikt Niehues <benedikt.niehues@itemis.de>

### CODE REVIEW

**Comment by sjka** [comment]
Could you please also adapt [ItemEventFactoryTest](https://github.com/eclipse/smarthome/blob/3ae5d7b1b284f2bde6199bfe8dad950fd38cae39/bundles/core/org.eclipse.smarthome.core.test/src/test/groovy/org/eclipse/smarthome/core/items/events/ItemEventFactoryTest.groovy#L60)? (And maybe even make it _really_ test this behavior while you're there?  Although I have to admit that the culpable negligence is not on your side...)

**Comment by BenediktNiehues** [comment]
@sjka I added a test...

**Comment by sjka** [comment]
Thanks. Just one question, as this is meant to be a regression test:

When just using the test case from your PR, but leaving ItemEventFactory.java as it was before - what would you expect to happen when running ItemEventFactoryTest? 😉

**Comment by BenediktNiehues** [comment]
@sjka in factory.createEvent I expect an IllegalArgumentException and the test will fail.

**Comment by sjka** [comment]
Thanks

**Pull request merged**
