### PR TITLE
Fixed issues found by Static Code Analysis Tool (OnlyTabIdentationInXmlFilesCheck)

### PR DESCRIPTION
**Pull request by tanyatanyatanya**
Changed spaces to tabs for some xml files.

Signed-off-by: Tanya D. Georgieva <tanya.dancheva.georgieva@gmail.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
Should we use the same XML indentation style for really all XML files also if specific ones have their own style defined?

E.g. Maven has its own style for XML files:

```
The Maven style for XML files is mainly:

Indentation: Always use 2 space indents, unless you're wrapping a new XML tags line in which case you should indent 4 spaces.
```

**Comment by J-N-K** [comment]
Please do not change the DMX binding files. This is alrteady incoroporated in #4812.

**Comment by tanyatanyatanya** [comment]
@kaikreuzer wdyt? Should we change spaces to tabs for all XML files or leave the ones pointed out by @maggu2810?

**Comment by kaikreuzer** [comment]
I'd agree with @maggu2810 that we do not have to enforce that rule on Maven files - we mainly defined that rule for XML files, which end up in the binary jars, e.g. everything we put under ESH-INF.

So the easiest thing might be to exclude any "pom.xml" from this check (sorry, as you have apparently invested quite some time in changing all of them for this PR...).

**Comment by tanyatanyatanya** [comment]
@kaikreuzer I updated the PR and set suppression for any "pom.xml" files for OnlyTabIdentationInXmlFilesCheck instead of changing the logic for it. Also do you think its a good idea to change the severity from "warning" to "error" for this check?

**Comment by J-N-K** [comment]
Another thing: The Eclipse formatter does not end up with XML files that follow these guidelines.

**Comment by kaikreuzer** [comment]
@maggu2810 Good point about the license headers in XML. I don't know whether this can be addressed by the license Maven plugin. @tanyatanyatanya Would you like to have a look into that?
Once this works, I'd agree that the severity could be changed to error.

**Comment by tanyatanyatanya** [comment]
@kaikreuzer @maggu2810 I have checked the documentation about the license maven plugin and I only found an option for changing the number of spaces with indentSize parameter. I do not think it is possible to change the indentation with this plugin to tabs. 

I have tried to find if it is possible with another plugin but the one that have an option for changing spaces to tabs is no longer maintainable.

And as for the license header in the XML files I managed to change the header style and set tab before each line. I will upload one more PR with changed files and I could change the pom because of the headers if you think that is a good idea and also to set the severity level to error.

**Comment by maggu2810** [comment]
Let's give it a try. Thanks for your efforts.

**Pull request merged**
