### PR TITLE
Added superclass fields and configuration type conversion

### PR DESCRIPTION
**Pull request by gerrieg**
Suggestion for type converting the fields in configuration classes and support for fields in superclasses.
Also fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=456320

Signed-off-by: Gerhard Riegler <gerhard.riegler@gmail.com>

### CODE REVIEW

**Comment by dnobel** [comment]
Thanks for the PR!

But I don´t think that we need type converting inside the configuration class. The configuration class already contains typed properties. ESH knows three different configuration data types: String, Boolean and BigDecimal. Thats why the value is an object and not a String. If a thing type properly defines the data type, the configuration class should contain a Boolean or BigDecimal instead of String. So it makes no sense to convert it to String and then back to the original data type.

The conversation from BigDecimal into Integer, Float, Double and Long could make sense, because handling BigDecimal is not that easy as just handling an integers for example. The process would be to check if the configuration value is a BigDecimal and then convert it to the decimal type that is specified in the binding configuration class.

Could you please change the PR accordingly?

**Comment by dnobel** [comment]
I forgot: please add yourself as an author to the class JavaDoc with a short sentence, what you have changed. Thanks!

**Comment by gerrieg** [comment]
Sure, that makes no sense. It was my fault, i had all thing config parameters in quotation marks so i only saw String values. Now only BigDecimal values are converted.

**Comment by kaikreuzer** [comment]
@marcelrv : Feel free to create another PR for this (and don't forget "long", "float" and "double" either ;-))

**Comment by gerrieg** [comment]
long, float and double primitive types are supported, it's only integer because it's the only type with another primitive name (int). I will do a PR soon.

**Comment by kaikreuzer** [comment]
Merged https://github.com/eclipse/smarthome/pull/143
Thanks!

**Pull request merged**
