### PR TITLE
added tests for time based module handlers

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by danchom** [comment]
Missing test for triggering of time of date trigger
LGTM

**Comment by kaikreuzer** [comment]
> Missing test for triggering of time of date trigger

I couldn't think of a way to do this without potentially causing the test to run about a minute.
If you have ideas, feel free to add such a test!

**Comment by danchom** [comment]
Yes I agree with you that there is no other way. If the seconds was an optional configuration parameter to the TimeOfDayTrigger, i mean to accept time of day in form HH:mm or HH:mm:ss, then the test can stop for a few seconds. Anyway this must not be done only for the test, but I think it will useful to have ability to set timers with precise of seconds.

**Comment by danchom** [comment]
LGTM

**Pull request merged**
