### PR TITLE
Fixed all warnings by the ConstantNameCheck

### PR DESCRIPTION
**Pull request by VelinYordanov**
Removed static from some loggers.
See openhab/static-code-analysis#267

### CODE REVIEW

**Comment by maggu2810** [comment]
Can you add a "Signed-off-by" footer?

**Comment by VelinYordanov** [comment]
@maggu2810 All good now.

**Comment by maggu2810** [comment]
Thanks

**Comment by wborn** [comment]
Why is the scheduler in the `AbstractDiscoveryService` static

https://github.com/eclipse/smarthome/blob/d528161591298f1669b6e444cb1eea7bfdc39904/bundles/config/org.eclipse.smarthome.config.discovery/src/main/java/org/eclipse/smarthome/config/discovery/AbstractDiscoveryService.java#L60-L61

Whereas the scheduler in the `BaseThingHandler` not static?

https://github.com/eclipse/smarthome/blob/d528161591298f1669b6e444cb1eea7bfdc39904/bundles/core/org.eclipse.smarthome.core.thing/src/main/java/org/eclipse/smarthome/core/thing/binding/BaseThingHandler.java#L74-L75

**Comment by kaikreuzer** [comment]
Valdi question @wborn - I have created https://github.com/eclipse/smarthome/pull/5227.

**Pull request merged**
