### PR TITLE
Initial contribution of the Paper UI.

### PR DESCRIPTION
**Pull request by dnobel**
Also-by: Timon Reinhard <timon.reinhard@telekom.de>
Also-by: Markus Rathgeb <maggu2810@gmail.com>
Also-by: Christoph Schauer <christoph@schauer-itconsulting.de>
Also-by: Simon Kaufmann <simon.kfm@googlemail.com>
Also-by: Sebastian Janzen <sebastian@janzen.it>
Also-by: Joep Admiraal  <joep@groovytunes.nl>
Signed-off-by: Dennis Nobel <d.nobel@external.telekom.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Created CQ 10214.

**Comment by sja** [comment]
Is there any state or progress of this CQ? I don't have access to IPZilla.

**Comment by dnobel** [comment]
The IP Team is working on that. They have some questions I have to answer. But no idea yet when it will be approved.

**Comment by dnobel** [comment]
As discussed: I updated the PR and removed the md-icons files.

**Comment by maggu2810** [comment]
So, no CQ blockers anymore?

**Comment by kaikreuzer** [comment]
No, I'll merge today. We discussed to add the icon files in the openHAB fragment instead for now.

**Comment by kaikreuzer** [comment]
Check in approval for CQ 10214 has been granted according to Parallel IP.

**Pull request merged**
