### PR TITLE
JsonStorage: do not cache storage instances

### LINKED ISSUE #6295: "Scan for Things" is causing issues in the log
For me the issue #6266 that should be fixed with #6216 is still there.
I tested with openhabian and openHAB build 1378.
At least with the binding AVMFRITZ!Box, HUE, Harmony and Onkyo the issue is still there:

```
2018-10-01 14:59:29.907 [ERROR] [nternal.DiscoveryServiceRegistryImpl] - Cannot notify the DiscoveryListener org.eclipse.smarthome.config.discovery.internal.PersistentInbox on Thing discovered event!
java.lang.ClassCastException: org.eclipse.smarthome.config.discovery.internal.DiscoveryResultImpl cannot be cast to org.eclipse.smarthome.config.discovery.DiscoveryResult
        at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.get(PersistentInbox.java:422) ~[97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.notifyListeners(PersistentInbox.java:488) ~[97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.add(PersistentInbox.java:191) ~[97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.thingDiscovered(PersistentInbox.java:345) ~[97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$1.run(DiscoveryServiceRegistryImpl.java:268) ~[97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl$1.run(DiscoveryServiceRegistryImpl.java:1) ~[97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.thingDiscovered(DiscoveryServiceRegistryImpl.java:265) [97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.thingDiscovered(AbstractDiscoveryService.java:278) [97:org.eclipse.smarthome.config.discovery:0.10.0.201809271800]
        at org.eclipse.smarthome.config.discovery.upnp.internal.UpnpDiscoveryService.remoteDeviceAdded(UpnpDiscoveryService.java:190) [196:org.eclipse.smarthome.config.discovery.upnp:0.10.0.201809271800]
        at org.jupnp.registry.RemoteItems$1.run(RemoteItems.java:114) [198:org.jupnp:2.4.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
2018-10-01 14:59:53.992 [WARN ] [mmon.WrappedScheduledExecutorService] - Scheduled runnable ended with an exception:
java.lang.ClassCastException: org.eclipse.smarthome.config.discovery.internal.DiscoveryResultImpl cannot be cast to org.eclipse.smarthome.config.discovery.DiscoveryResult
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.PersistentInbox.getAll(PersistentInbox.java:295) ~[?:?]
        at org.eclipse.smarthome.config.discovery.internal.PersistentInbox$TimeToLiveCheckingThread.run(PersistentInbox.java:114) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:?]
```

I noticed something else, when I have installed these bindings, the spinning circle for busy remains forever.
I have to go to another menue and then back to Add-ons->Bindings to see that the binding is installed.

### PR DESCRIPTION
**Pull request by htreu**
* Always provide a new storage instance when JsonStorageService#getStorage is called to always run with the given ClassLoader.
* Fixes #6295.

Signed-off-by: Henning Treu <henning.treu@telekom.de>

### CODE REVIEW

**Comment by htreu** [comment]
This also came to my mind over the weekend.
Maybe the first version was already the better one (without caching) and we can assume that only one instance of a specific storage is used.

**Comment by htreu** [comment]
I would indeed make the statement that a specific storage (specific by `name`) must have a dedicated StorageService instance. Otherwise state would be shared using storage which is to be avoided.

wdyt @sjka?

**Comment by htreu** [comment]
Since the issue #6295 is marked critical, my suggestion is to role this one back to the initial version. This will solve the problem at hand. Right now there is no code (at least in ESH) which uses multiple instances of the same storage.

wdyt @maggu2810?

**Comment by maggu2810** [comment]
@htreu Okay for me. But perhaps you can open a new issue to track the question
* if a storage provider should return the always same storage if the classloader and the name is equal
* the consumer should release a storage
* only one storage per name is allowed and the other previous used storage should be made unusable (internal flag that is checked by the storage implementations)
* ...

**Comment by htreu** [comment]
The latest commit brings back almost the original behaviour with the difference that always a new JsonStorage instance is returned. As of now only one instance per name is requested by ESH bundles this should be sufficient. All other questions should be discussed in #6335.

**Pull request merged**
