### PR TITLE
Make sure the workaround for Osram lightbulb is not applied to other lights as well

### LINKED ISSUE #686: Hue binding: Workaround for Osram Lightify PAR16 is applied to all lights
Recently, a workaround for Osram Lightify PAR16 has been added (#518). 
However, because [this check in HueLightHandler](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.hue/src/main/java/org/eclipse/smarthome/binding/hue/handler/HueLightHandler.java#L91) always evaluates to true, this workaround is applied to all lights.

The tests do no catch this issue because in the tests the initialize() method is only called for the Osram Lightify PAR16.

### PR DESCRIPTION
**Pull request by dominicdesu**
Fixes #686 .

Signed-off-by: Dominic Lerbs <dominicdesu@hallojapan.de>

### CODE REVIEW

**Comment by dominicdesu** [comment]
@kaikreuzer, I saw your [review comment](https://github.com/eclipse/smarthome/pull/518#discussion_r44876957) in #518 after I've implemented this fix.

You had concerns about the equals comparison and string replace. Unfortunately I cannot see the original code anymore for which the comment has been made, but I don't think my solution is very expensive and we can avoid the class variable. Yet, if you still prefer the variable approach let me know and I'll adjust the code.

**Comment by kaikreuzer** [comment]
Thanks, looks good to me.

> but I don't think my solution is very expensive and we can avoid the class variable.

Still, the code is called on every single command that is received by the handler. All information (=the thing UID) is already available when running the initialize method, that's why I suggested to do this test only once there and then keep it as an instance field. Why do you feel that this isn't a good idea?

**Comment by dominicdesu** [comment]
Hi,
I don't think it isn't a good idea and I can understand the reasoning behind it. If I had seen your review comment before my commit, I wouldn't have changed it. As the commit was already done, however, I thought I put it up for debate here :-)

It is probably a trade-off between clean code and performance. When I saw the code, I had the feeling that the exceptional handling for the Osram light is scattered too much throughout the code (member variable, initialize() method, handleCommand() method, additional call to initialize() method in test classes). 

Acting on the assumption that a method call/String compare has a low impact on the performance whenever an OnOff command is triggered for Brightness/ColorTemp channel, I applied the boy scout rule and tried to clean it up a little bit while fixing the bug.

Again, this is just my personal preference. I am not relucatant to change it back for performance reasons :rocket:

**Comment by maggu2810** [comment]
So, we could use a boolean member variable "isOsramPar16Tw" (and initialize it on the initialize method) or a type enum  (and initialize it on the initialize method).

**Comment by kaikreuzer** [comment]
I also don't think the current version is a problem, so I don't have a strong opinion.
So I leave the decision to @maggu2810 on what he prefers :-)

**Comment by maggu2810** [comment]
The one string compare is ok, but a boolean could be better. :wink: 

> additional call to initialize() method in test classes

Shouldn't the test call initialize regardless of the current change?
Isn't it wrong to use an uninitialized thing handler (perhaps another issue / PR)?

**Comment by dominicdesu** [comment]
Hello,
I just saw there is another pull request #673 which also seems to fix this issue. As the boolean solution is preferred I'd suggest we discard my pull request and go with #673. This would also minimize merge conflicts. Maybe I'll just add some comments to PR #673 regarding the test classes.

Do you agree?

**Comment by kaikreuzer** [comment]
#673 might take a bit more time due to discussions, so I would prefer to update this PR to have the bug fixed asap.

**Comment by dominicdesu** [comment]
@kaikreuzer @maggu2810 I have updated the PR to revert to using the boolean flag and always call the initialize method in the test class. Could you please check again?

**Comment by maggu2810** [comment]
LGTM

**Comment by kaikreuzer** [comment]
To me as well - thanks @dominicdesu!

**Pull request merged**
