### PR TITLE
added blog post about smart home day @ ece

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
Hm, is there something missing?

I can see the `Blog` link here: https://www.eclipse.org/smarthome/getting-started.html
I cannot see the `Blog` link here: https://www.eclipse.org/smarthome/documentation/index.html

**Comment by kaikreuzer** [comment]
Good question. @sjka Did you maybe not deploy all updated pages?

**Comment by sjka** [comment]
Nice spot! Looks like I missed to copy a file... Will fix it immediately.

**Comment by sjka** [comment]
fixed

**Comment by maggu2810** [comment]
Thanks you

**Pull request merged**
