### PR TITLE
Refactor org.eclipse.smarthome.core.thing.xml.internal 

### PR DESCRIPTION
**Pull request by cdjackson**
In order to allow bindings to extend the current thing descriptions, we need to export org.eclipse.smarthome.core.thing.xml.internal. As it's bad practice to export an 'internal' package, I have refactored the package - leaving the 'real' internal classes where they were, and moving the exportable classes into org.eclipse.smarthome.core.thing.xml. This is now also consistent with the structure of org.eclipse.smarthome.config.xml which has all the converters, and org.eclipse.smarthome.config.xml.internal which has the internal OSGi and reader classes.

Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
> In order to allow bindings to extend the current thing descriptions

Is this now something that you want to investigate on or do you already regard that as a pattern that bindings should apply? I'd just like to make sure that we are not opening a can of worms that we would rather like to keep closed...

**Comment by cdjackson** [comment]
I would say two things here - firstly, this structure is consistent with the structure used in the config description package with the same split of class in the internal and 'external' package... So, in my mind it's a better structure anyway in that it makes the packages consistent.....

However, to answer your question,  I think this is a good way forward. It allows two possible options (as per our discussion on the Eclipse forum).
1. It allows a binding to produce a custom reader that effectively does the same thing as the current reader, but allows the binding to provide the configuration provider, thus dynamically modifying the data.
2. It allows the binding to produce a custom reader that is different to the base extender, but still uses the same channel/config parameter/thing definition classes - or to override them and do something different. In this case though we can use the same classes where they are the same, but override where different (which hopefully will be minimal).

I've spent some time looking at what I want to do on the zwave and have done a number of iterations on the XML format (and have a converter to convert the OH1 database to the new ESH XML format) which makes it as consistent as possible with the current XML files, but adds some additional parameters, and modifies the channel definitions to also add some parameters (as per the discussion we had a month or so back).

So, with this change to export the thing reader classes, I will be able to extend the thing reader and just modify/add a couple of classes. As I'm also reading this myself, I have the option to dynamically add parameters rather than defining everything into the XML.

So, for me, I think this is a good way forward for zwave at least.

**Comment by dnobel** [comment]
Hi Chris,

the reason for the export in the config.xml package is, that it is reused in the the thing and binding xml bundles. But I agree that we can change it here to be consistent.

But I am also a little bit afraid of, that bindings begin to implement their own XML readers. Maybe it is needed for really complex bindings like z-wave. But the consequence is, that you need to put the XML into another directory, so that the framework reader will not parse it. Moreover if bindings can extend the XML to their needs, we loose the common XML format. We can not longer use the XML files for documentation generation for example.

This should be at least an edge case for z-wave. But if one binding does it, others will maybe mimic this.

**Comment by kaikreuzer** [comment]
>  But I agree that we can change it here to be consistent.

Well, it only needs to be consistent, if we want to allow reuse (and thus export) it.

> This should be at least an edge case for z-wave. But if one binding does it, others will maybe mimic this.

This is why I wanted to discuss, whether this should become a "common pattern". If there is a need for "custom XMLs", we might want to provide some more dedicated services to do so instead of simply exposing some XML beans and hope that people will be able to build their own parser.
But having each binding using a different XML format does not sound appealing to me - as Dennis says, we wanted to be able to generate (online and offline) documentation from this this and thus would to have clear rules on where to find them and how they look like.

**Comment by cdjackson** [comment]
Well, as I said above, I see there are two needs here - this PR meets these needs... When we discussed on Eclipse forum, you recommended I produce a custom reader if I remember correctly.  

Without this PR I will need to duplicate the XML reader and we'd still have the same problem with where we put the custom files. To me it doesn't make sense to require people to write their own readers, and not provide the ability to override the existing reader. To do this will mean everyone will do something different. The easiest thing for me with the zwave binding is to re-use the database that I have in OH1 and provide the custom reader for this, however I've spent quite a lot of time trying to work out the best way to make the zwave database consistent with the ESH XML with just a few change - but I really didn't want to have to duplicate everything again :(

We discussed adding the extra things I needed into the standard XML (eg properties in channels, and 'property' groups to allow grouping of configuration data), but you weren't keen on that (there was no reply to my last message about this on the forum 6 weeks ago). I accept that this isn't something you want in the core XML, but I think that being able to extend the XML is a good compromise - otherwise I need to start from scratch (or actually I will just stick with the old format).

My thought moving forward was to be able to extend the XML file to add these extra bits - then we could either look to add them into the main XML if you like, or they can be kept separate, but at least people will have an example of an extended XML.

**Comment by kaikreuzer** [comment]
>  I've spent quite a lot of time trying to work out the best way to make the zwave database consistent with the ESH XML with just a few change

My goal would be to make it consistent with NO change - then there would be no need for custom files and custom parsers.

> but you weren't keen on that (there was no reply to my last message about this on the forum 6 weeks ago)

This is a wrong conclusion. Very sorry for having not answered, there are simply too many different discussions going on and I do not succeed in following up on all of them always - especially not on the ones where I do not have any brilliant idea and thus no answer. I think this is the indeed the thread that we need to continue: Can we enhance the XML schema, so that it fully suits your needs or is there no way around a custom parsing?

FTR: The thread in question is https://www.eclipse.org/forums/index.php/t/1015656/. I would suggest to pick it up again right now (together with @dnobel) and come to a conclusion before going down the road of your own Z-Wave parser. Is that ok for you?

**Comment by cdjackson** [comment]
Hi Kai,
That's fine - I'm happy to pick this discussion back up. I can provide my current schema for the new format and we can discuss. I think it's a reasonable solution (but then I would :) ) and provides a good flexibility, however, I also think that it's maybe naive to think someone even more troublesome than me won't come along one day and want to extend it in a different way... You have (I think) stated that custom readers are one way to do this, and I do think that a custom reader that extends a current format is still better than a custom reader that's a totally different format (hence why I'm trying to be a good player and move the zwave database format into the ESH format rather than just use the old database).

Given the (perceived) resistance to changing the XML when we discussed it in March, my plan was to implement my changes and then discuss further - ie present a concrete use case since we seemed to be going around in circles with trying to convince you and Dennis on what my use case was...

Anyway, let's pick it up over on Eclipse...

**Comment by kaikreuzer** [comment]
Thanks Chris, I very much appreciate your efforts and your willingness for doing compromises in order to please us all :-)
I promise to come back on the forum thread latest by tomorrow!

**Comment by kaikreuzer** [comment]
Let's close this and wait for a solution on our forum discussion first - we can then reopen this PR any time.

**Pull request closed without merging**
