### PR TITLE
updated jupnp version to 2.2.0

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
Hi @kaikreuzer, I am not such familiar with Eclipse target platform files, but should the sequence number be bumped, too? IIRC the Eclipse IDE relies on that number if it should refresh the target platform.

**Comment by kaikreuzer** [comment]
You are absolutely right, I have updated the PR accordingly.

**Comment by maggu2810** [comment]
Any reason you created the branch in this repo?

**Comment by kaikreuzer** [comment]
That happened because I used the Github web editor for creating it...

**Pull request merged**
