### PR TITLE
Add support for Roberts Stream 93i Radio

### PR DESCRIPTION
**Pull request by garthy**

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Could you add this info to https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.fsinternetradio/README.md#supported-things as well?

**Comment by garthy** [comment]
OK I've updated the README

I've reformatted the list as it is easier to add to and will stop merge conflicts

**Comment by kaikreuzer** [comment]
Thanks! It seems you have missed the sign-off on the second commit - but as it is a small doc change only, I'll squash it into the first commit when merging.

**Comment by garthy** [comment]
Agrh sorry. i edited the readme in the github UI  as an update to my NAS
has broken many things so development is on hold till my environment is
back and working.

**Pull request merged**
