### PR TITLE
rename I18nProvider to TranslationProvider

### PR DESCRIPTION
**Pull request by maggu2810**
WRT https://github.com/eclipse/smarthome/pull/3587#discussion_r120869757

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Did you check at how many places in the docs & tutorials this would need to be changed?

And do you have any idea of how much existing code out there in solutions will have to be adapted for this breaking change?

**Comment by maggu2810** [comment]
> Did you check at how many places in the docs & tutorials this would need to be changed?

It should be changed in all places that are part of the repository.

> And do you have any idea of how much existing code out there in solutions will have to be adapted for this breaking change?

No, how should I?

**Comment by maggu2810** [comment]
> Would you dare such a refactoring?

You asked me if I dare such a refactoring. And I dared it.

**Comment by kaikreuzer** [comment]
You are a daring guy ;-)

Ok, I have checked the openhab2 repo and it doesn't seem to have any significant impact.
Also checked with DT colleagues which are fine with the renaming. So I'd hope that any other ESH consumer will also be able to cope with it easily.
But I added "API Breaking" label to highlight that.

**Comment by kaikreuzer** [comment]
Nonetheless, reading https://github.com/eclipse/smarthome/blob/master/docs/documentation/features/internationalization.md#i18n-text-provider-api, I am wondering if "Translation" is really the right word. This service does not translate anything, but it provides texts in a given locale for a key. So it really is about l10n...

**Comment by cdjackson** [comment]
If this change goes ahead please can we synchronise it so we don’t break bindings that use the current provider.

**Comment by tomhoefer** [comment]
It is ok for me ... we will take care of the changes required by this PR once it has been merged

**Comment by kaikreuzer** [comment]
> I am wondering if "Translation" is really the right word. This service does not translate anything, but it provides texts in a given locale for a key. 

Ok, as no one (including myself) has a better suggestion, let's keep it.

**Pull request merged**
