### PR TITLE
use new HashMap<>() instead of Maps.newHashMap()

### PR DESCRIPTION
**Pull request by triller-telekom**
As discussed [here](https://github.com/eclipse/smarthome/pull/3804#pullrequestreview-50601832)

Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by sjka** [comment]
Please also fix the other occurrences and remove the package import.

**Comment by triller-telekom** [comment]
I can't. The ´GenericEventTriggerHandler` uses `com.google.common.collect.ImmutableSet` which is not available in standard JDK afaik.

**Comment by sjka** [comment]
> I can't.

You can!

```java
this.types = Collections.unmodifiableSet(new HashSet<>(Arrays.asList(((String) module.getConfiguration().get(CFG_EVENT_TYPES)).split(","))));
```

**Comment by triller-telekom** [comment]
Thanks! Done...

**Comment by maggu2810** [comment]
Just for your interest for the ones that would like to operate on streams:

```Java
final String[] strs = new String[] { "1", "2" };

final Set<String> set1 = Arrays.stream(strs).collect(Collectors.collectingAndThen(Collectors.toSet(), Collections::unmodifiableSet));

final Set<String> set2 = Collections.unmodifiableSet(new HashSet<>(Arrays.asList(strs)));
```

**Comment by triller-telekom** [comment]
Thanks for the hint with streams. I'm still not used to them but the more often I see them I might get more familiar with them :)

**Pull request merged**
