### PR TITLE
Added missing import for javax.xml.bind

### PR DESCRIPTION
**Pull request by satish-nikam**
Lifx binding uses class javax.xml.bind.DatatypeConverter, but does not import javax.xml.bind in manifest xml. This causes issue when running ESH in karaf (using project https://github.com/maggu2810/shk).

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks! Could you please [sign-off your commit](https://github.com/eclipse/smarthome/blob/master/CONTRIBUTING.md#legal-considerations)?

**Comment by kaikreuzer** [comment]
@kgoderis As we are heading for Java 8 CP2 in future, is there any chance to get rid off the dependency on javax.xml.bind?

**Comment by satish-nikam** [comment]
Raised another pull request with required settings..closing this one.

**Comment by maggu2810** [comment]
Reference to new PR: #1589

@satish-nikam It is fine to create a new PR, but it is not necessary.
A PR tracks the branch it has been created for. So every change on that branch, changes the PR. You can e.g. force push to that branch (if the history has been changed -- e.g. because of a changed commit message). Last you have to add a comment on Github that the changes has been done (Github does not send a notification if a branch of the PR has been changed).

**Comment by kgoderis** [comment]
@kaikreuzer we use in a single line of code 

            this.bytes = ByteBuffer.wrap(DatatypeConverter.parseHexBinary(string));

Some are suggesting to use the Apache Commons Codec lib. Is that a valid option?

The actual code behind the parseHexBinary is

```
public byte[] parseHexBinary(String s) {
    final int len = s.length();

    // "111" is not a valid hex encoding.
    if( len%2 != 0 )
        throw new IllegalArgumentException("hexBinary needs to be even-length: "+s);

    byte[] out = new byte[len/2];

    for( int i=0; i<len; i+=2 ) {
        int h = hexToBin(s.charAt(i  ));
        int l = hexToBin(s.charAt(i+1));
        if( h==-1 || l==-1 )
            throw new IllegalArgumentException("contains illegal character for hexBinary: "+s);

        out[i/2] = (byte)(h*16+l);
    }

    return out;
}

private static int hexToBin( char ch ) {
    if( '0'<=ch && ch<='9' )    return ch-'0';
    if( 'A'<=ch && ch<='F' )    return ch-'A'+10;
    if( 'a'<=ch && ch<='f' )    return ch-'a'+10;
    return -1;
}
```

**Comment by kaikreuzer** [comment]
> Some are suggesting to use the Apache Commons Codec lib. Is that a valid option?

Yes, it is even already part of the target platform.
The other option would be to simply reimplement this method, this would completely avoid the dependency on external code.

**Comment by maggu2810** [comment]
The bundle org.eclipse.smarthome.io.net already uses apache.commons.codec

**Comment by kaikreuzer** [comment]
... which is an optional bundle that is not considered to be a mandatory part of the core framework.

**Comment by maggu2810** [comment]
> ... which is an optional bundle that is not considered to be a mandatory part of the core framework.

Okay, I assume there is some reason to write your comments today as short as possible.

The same comment "is an optional bundle that is not considered to be a mandatory part of the core framework" is valid for the LIFX binding, so if a bundle that is not a mandatory part of the core framework can use the "Apache Commons Codec lib" could you tell me what differs a binding from and io bundle?

**Comment by kaikreuzer** [comment]
I answered above:
>> Is that a valid option?
> Yes

So I am not sure if there is anything further to discuss here? The general tendency should be to keep the number of dependencies of every bundle as low as possible, so if only a simple method is used as in this case here, it sounds to be an appropriate measure to just implement it yourself.

**Comment by kgoderis** [comment]
Since we can not copy the code from the core lib (do we?), here is an alternative implementation

```
public byte[] parseHexBinary(final String encoded) {
    if ((encoded.length() % 2) != 0)
        throw new IllegalArgumentException("Input string must contain an even number of characters");

    final byte result[] = new byte[encoded.length()/2];
    final char enc[] = encoded.toCharArray();
    for (int i = 0; i < enc.length; i += 2) {
        StringBuilder curr = new StringBuilder(2);
        curr.append(enc[i]).append(enc[i + 1]);
        result[i/2] = (byte) Integer.parseInt(curr.toString(), 16);
    }
    return result;
}
```

**Pull request closed without merging**
