### PR TITLE
Added Nullannotations on Binding API

### PR DESCRIPTION
**Pull request by triller-telekom**
Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by triller-telekom** [comment]
If I do not add the optional import to all the bindings the following "problem" occurs: In the binding to have a handler that derives from the `BaseThingHandler`. Inside my handler I can call `updateProperty(@NonNull String name, String value)` from the `BaseThingHandler` with `updateProperty(null, "test")` and there won't be any warning or error.

However, if I do add the optional import, the null analysis starts and I see the error. So to me it seems like every bundle has to be aware of the annotations, otherwise the null analysis ignores it.

Regarding the position of the annotation on return values of methods I made it consistent with the documentation of Eclipse: https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_null_annotations.htm

But If you find the other position more intuitive I can change that.

**Comment by maggu2810** [comment]
> Regarding the position of the annotation on return values of methods I made it consistent with the documentation of Eclipse: https://help.eclipse.org/oxygen/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_null_annotations.htm

Can you point me to the location you refer on that page?
The return type should be annotated.
So, `public @Nullable Object foo()` is more intuitive then `@Nullable public Object foo()`.
There is an example using a static method and a generic, the annotation is used after the static keyword and not before.
public / protected / private are modifiers for the function and so in front of the return type.

**Comment by triller-telekom** [comment]
I was referring to the very first example:
```
@NonNull String getString(String maybeString) {
        if (maybeString != null)
            return maybeString;                         // the above null check is required
        else
            return "<n/a>";
    }
```

But you are right the public / protected / private modifiers are not in these examples.

Also I just noticed that Kai has done it like you suggested in his PR too.

So I will change it in my PR.

**Comment by triller-telekom** [comment]
Done

**Comment by maggu2810** [comment]
Thanks for your work

**Pull request merged**
