### PR TITLE
Added documentation how to contribute.

### PR DESCRIPTION
**Pull request by dnobel**
Moved How-To Contribute documentation from https://www.eclipse.org/smarthome/community.html#HowToContribute into markdown file and added more infos for bug tracking.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
thanks!

**Comment by maggu2810** [comment]
> Discuss your Design on the mailing list

Should we change the words "mailing list" here, as it is done (already correct in the description) using the issue tracker on bugilla?

**Comment by maggu2810** [comment]
> Add a "Signed-off-by" line to very commit you do - see the Eclipse wiki for details.

This is point 7 of topic "Conventions for Pull Requests".
The Eclipse wiki already states this, but as we document that for every feature / bug a buzilla entry should be created, we could change this line to

Add a "Signed-off-by" and a "Bug" (referring the issue link) line to every commit you do - see the Eclipse wiki for details.

So, there is also a typo "very" => "every".

**Comment by kaikreuzer** [comment]
Thanks for the suggestions, @maggu2810, I have created https://github.com/eclipse/smarthome/pull/282 for it. Note that I changed the "mailing list" to the forum, not to Bugzilla, as I think that this is the better place for upfront discussions.

**Pull request merged**
