### PR TITLE
Rule based parsing and grammar generation

### PR DESCRIPTION
**Pull request by tilmankamp**
Signed-off-by: Tilman Kamp <tilmankamp@posteo.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
I think now we are at a point where we should also talk about adding some documentation and test cases  for the implemented features, don't you think?

**Comment by tilmankamp** [comment]
Agree. One question regarding documentation: Should this be done as markdown within the voice module or as a new Eclipse SmartHome Wiki page?

**Comment by kaikreuzer** [comment]
My suggestion would be to add a new page voice.md in https://github.com/eclipse/smarthome/tree/master/docs/documentation/features for describing features that are offered here and a new folder "voice" in https://github.com/eclipse/smarthome/tree/master/docs/documentation/development for how to implement new voice extensions (tts,stt, hli services), this is probably not a part of this PR here.

**Comment by kaikreuzer** [comment]
@tilmankamp Any progress here?

**Comment by tilmankamp** [comment]
@kaikreuzer Yes and no. There is a more up-to-date version already. At some point I'll update this PR with that new code. It's probably better to close this PR for the moment.

**Pull request closed without merging**
