### PR TITLE
[MQTT] fix number formattting

### PR DESCRIPTION
**Pull request by J-N-K**
fixes an issue where numbers are always send as integers, regardless of the isDecimal setting

Signed-off-by: Jan N. Klug <jan.n.klug@rub.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@davidgraeff fyi

**Comment by kaikreuzer** [comment]
@davidgraeff Thanks. What's your opinion about https://github.com/eclipse/smarthome/pull/6613#issuecomment-443511671?

**Comment by davidgraeff** [comment]
@kaikreuzer  @J-N-K 
`isDecimal` is a better name for it, sure.

**Comment by J-N-K** [comment]
I can create  a PR for that.

**Pull request merged**
