### PR TITLE
Correct package name of ScriptedRuleProvider

### LINKED ISSUE #3790: Correction for ScriptedRuleProvider.xml
In the file `ScriptedRuleProvider.xml` the following definition

`<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" immediate="true" name="org.eclipse.smarthome.automation.module.script.rulesupport.internal.shared.ScriptedRuleProvider">`

should be replaced with

`<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" immediate="true" name="org.eclipse.smarthome.automation.module.script.rulesupport.shared.ScriptedRuleProvider">`

(... false `.internal.shared` in the name definition)

### PR DESCRIPTION
**Pull request by triller-telekom**
Fixes #3790

Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by triller-telekom** [comment]
closed and reopened for new ip valication check.... had a wrong email address in my commit

**Comment by sjka** [comment]
@danchom as it concerns the script support, I don't expect you are relying on the component name anywhere on your side, do you?

**Comment by danchom** [comment]
No, I don't.

**Comment by sjka** [comment]
Good. Thanks!

**Pull request merged**
