### PR TITLE
fixed FolderObserverTest for hidden files on windows systems

### PR DESCRIPTION
**Pull request by frhei**
PR #3483 solves the root cause of issue #3481, so that the test 'test ignore hidden files with extension that is registered' can execute in general.
Unfortunately, the test still fails on windows systems, because the way of creating the file triggers the obervation mechanism and the assertion fails.
In windows a hidden file cannot be created with a single api call (at least not with the Java api).
The file must be created and afterwards it needs a filesystem property set for a file to be hidden.
But the initial creation already triggers the folder observer mechanism, therefore the following strategy can solve the problem:

- create a file  in an unobserved directory
- hide it
- afterwards move it to the observed directory

P.S.: Needed to change file FolderObserverTestsConfiguration.launch to be able to execute test in eclipse and debug.

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Thanks @frhei!
Please note that you need to have an ECA and sign-off your commits in order for us to be able to accept your PR. Please see https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#Eclipse_Contributor_Agreement for details.

**Comment by frhei** [comment]
Thanks for the hint!
I am pretty new to this topic and was not aware of the need having an signed ECA.
Meanwhile I did so.
What are the next steps? Do I have to re-commit? (Email-adresses of ECA and the one used in commit are different!)

**Comment by sjka** [comment]
Thanks for your patience with the little bureaucracy we unfortunately have to apply 😄 

Yes, since the email address is different we need to ask you to please do so. Just  amend your commit and also don't forget to add a "signed-off-by" line (git actually does it for your with the `-s` argument). 

In order to change everything you first need to configure git to use the correct email in this repository with

```
git config user.email "email@address.com"
```

and then fix the existing commit by doing a 

```
git commit --amend -s --author "New Author Name <email@address.com>" 
```

then you should be all set and simply need to force-push the branch again.

**Comment by frhei** [comment]
No worries and thanks for your support :)
Seems to have worked, so ready to go ahead...

**Comment by sjka** [comment]
Indeed, all good now, thanks for the fix.
Congratulations to your first contribution!

**Pull request merged**
