### PR TITLE
Added bar unit to SmartHomeUnits.java

### PR DESCRIPTION
**Pull request by vzorglub**
Signed-off-by: Vincent Regaud <vzorglub@gmail.com>

### CODE REVIEW

**Comment by vzorglub** [comment]
Silly typo on first commit.
Resubmitted

**Comment by vzorglub** [comment]
Done

**Comment by vzorglub** [comment]
@htreu 
I had a look at the Travis log but this time I can't see an error related to the PR

**Comment by htreu** [comment]
Yes, not related. I restarted the build. lets wait and see..

**Pull request merged**
