### PR TITLE
add capabilities to feature because it is missing in the bundle manifest

### PR DESCRIPTION
**Pull request by maggu2810**
Please have a look at:
* https://lists.apache.org/thread.html/ee80f8bc2f03b368ca20beffa8f41c12ce6b12959992d4ef6a75ed0e@%3Cdev.karaf.apache.org%3E
* https://lists.apache.org/thread.html/20524e4ecde622cc9e263ced9ac2ac3f2c3c90dcfc516165ae2b41c8@%3Cdev.karaf.apache.org%3E

### CODE REVIEW

**Comment by maggu2810** [comment]
Wait for merge, I have to add others capabilities, too.
Just added the PR already if someone wants to give some feedback.

**Comment by kaikreuzer** [comment]
Thanks a lot for testing Karaf 4.0.6 before its release - I am not sure if I fully get which capabilities must be defined; do we now need such an entry in the feature for EVERY ds service that we introduce? That would indeed be very awkward...

**Comment by maggu2810** [comment]
The best thing would be if our bundles contains a provide-capability for every service regardless if it is a DS or a programmatically created one. Independent if someone require that service the bundle provide it...
If the manifest and the DS files are generated using annotations it is a very transparent task and no manual work needs to be done.
For the "Manifest First" approach and handwritten stuff it is work...

I added the capabilities to the feature file (ATM I don't like to add the entries to the bundle's manifest until we decided how to handle it at all) where services of my own (shk) complains about not resolvable requirements. So it is (very) far from complete, but a starting point.
Adding new ones because a consumer misses an entry is easy, but it should also be maintained if a service is removed at all.
But as long as we handle it in the feature XML I don't see any problem.

**Comment by kaikreuzer** [comment]
Ok, thanks. I am fine with adding the capabilities also (manually for now) to the manifests, but having it in the feature definition is a good starting point as well.
Maybe we move to bnd and annotation processing one day, then this would be solved once and for all.
Btw, do you know if OH2 can be upgraded with these changes to K406 or might other capability definitions be required?

**Comment by maggu2810** [comment]
> Btw, do you know if OH2 can be upgraded with these changes to K406 or might other capability definitions be required?

Sorry, I don't. Have you already moved away from "manifest first" in OH2? If you don't, then I assume you don't use "Require-Capability" and so it doesn't matter.

**Comment by kaikreuzer** [comment]
> Have you already moved away from "manifest first" in OH2?

No, I haven't. Ok, so this is nothing to worry about for me then, thanks.

**Pull request merged**
