### PR TITLE
Drop Jetty v8 in launch configuration

### PR DESCRIPTION
**Pull request by maggu2810**
This PR removes the usage of Jetty v8 in the Eclipse SmartHome Runtime
launch configuration.
It also removes unneeded p2 bundles from the launch config etc.
At least it renames the launch configuration from "SmartHome Runtime" to
"SmartHome-Runtime" because the launch configuration's name is used as
working directory for the OSGi container and whitespaces should be
avoided (at least for the jetty home bundle path).

Fixes: https://github.com/eclipse/smarthome/issues/2032

### CODE REVIEW

**Comment by maggu2810** [comment]
@svilenvul Can you have a look at, too?

**Comment by svilenvul** [comment]
I have applied the patch and resolved the Target Platform. 
In Eclipse I see now even more jetty bundles with different versions -  jetty.server, jetty.servlet, jetty.security,jetty.continuation. 
The bundle org.eclipse.equinox.http.jetty with version 3.0.2 that  requires version in the range of [8.0.0,9.0.0) of the jetty bundles is excluded from the launch configuration. This does not solve the problem in the target platform that was described in #2032.
I doubt that these new bundles will be used at all, because they are not compatible with the  org.eclipse.equinox.http.jetty bundle.

**Comment by maggu2810** [comment]
Okay, you are right. It does not solve the multiple bundles in the target platform.
But as a first step we need to remove the dependency on that bundles.

If you have a look at the changed launch configuration you will see, that there is not need to use org.eclipse.equinox.http.jetty anymore.

**Comment by svilenvul** [comment]
Sorry, I missed the org.eclipse.jetty.osgi.httpservice bundle 
Than, I am ok with these changes

**Comment by svilenvul** [comment]
And thanks, that you are working on that !

**Comment by maggu2810** [comment]
@svilenvul Can you point me to the branch with the non-working Junit Plug-in test? I will have a look at.

**Comment by svilenvul** [comment]
Hm, it is not public for now, these tests are still not implemented.

**Comment by maggu2810** [comment]
Can you create a dummy Junit Plug-in test with the similar problem but without any non-to-publish code, so I can have a look at if using another bundle set will solve the problem?

**Comment by svilenvul** [comment]
Yes, of course, if you want to experiment with different sets.
I could do it for you, if you want, with the set in this PR? 
Let me know, what do you prefer.

**Comment by maggu2810** [comment]
I don't care which branch you base work on. There is no need to use this one. Start your work on the master branch of the main repo and send me a link to your repo and your branch name.
I will first have a test so I am sure this PR solves the problem you have.

**Comment by svilenvul** [comment]
OK, this is the [branch] (https://github.com/svilenvul/smarthome/tree/dummy-osgi-test-with-jetty/extensions/binding/org.eclipse.smarthome.binding.wemo.test).

Running the WemoHandlerOSGiTest.launch file in Eclipse should end with errors like this one:

> !ENTRY org.eclipse.jetty.security 4 0 2016-08-29 18:15:12.921
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.jetty.security [3]
  Unresolved requirement: Import-Package: org.eclipse.jetty.http; version="[8.1.0,9.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

**Comment by maggu2810** [comment]
@svilenvul I merged your changed to a branch based on this PR.
See here: https://github.com/maggu2810/smarthome/commits/dummy-osgi-test-with-jetty
I added one further commit: 8c98d5e42bcaa0b441bb33067ef107cb59f7fbbf
The commit changes the launch configuration for your test and it succeeded now.

So, this PR introduces the bundles that are necessary to solve your issue. You just need to use the v9 and drop the v8 from your launch config. All fine?

**Comment by svilenvul** [comment]
Great ! Issue is solved.

**Pull request merged**
