### PR TITLE
updated jsonpath to 2.1.0

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
same as #3140, but now updating to 2.1.0 only.

**Comment by sjka** [comment]
how about the [karaf feature](https://github.com/eclipse/smarthome/blob/master/features/karaf/esh-ext/src/main/feature/feature.xml#L88)?

**Comment by maggu2810** [comment]
This PR handles the branch that is used for the third party repo.
The Karaf feature is part of #3422

**Comment by sjka** [comment]
oic

**Pull request merged**
