### PR TITLE
Paper UI: handle advanced attribute for channel-group-type (fix #1497)

### LINKED ISSUE #1497: advanced attribute for channel-group-type ignored by Paper UI
Could we have an attribute "advanced" for channel group type that will lead to masking/unmasking the channel group in Paper UI ?

### PR DESCRIPTION
**Pull request by lolodomo**
Signed-off-by: Laurent Garnier <lg.hc@free.fr>

### CODE REVIEW

**Comment by maggu2810** [comment]
@aounhaider1 Can you have a look at?

**Comment by aounhaider1** [comment]
This lgtm. 
But we need to have a better way to show advanced channels. Currently, there is no way of knowing which channels are advanced once the "show more" button is clicked. Maybe we should show them in a similar way as we are showing advanced configuration parameters? Wdyt @maggu2810 @kaikreuzer?

**Comment by lolodomo** [comment]
Before merging, please wait for the end of the discussion in issue #3156 as the concept of advanced channel group type is disputed.

**Comment by lolodomo** [comment]
I close this PR as the general wish is to suppress the advanced flag on the channel group type.

**Pull request closed without merging**
