### PR TITLE
make sure mDNS services are fully started under Karaf

### PR DESCRIPTION
**Pull request by kaikreuzer**
Hopefully fixes https://github.com/openhab/openhab-distro/issues/162

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
LGTM, but if the modified method is not available shouldn't the framework do a deactivate, activate?
ATM I do not know if I understand the "unsatisfied" in the specification correctly.

**Comment by kaikreuzer** [comment]
Good question, I wasn't sure how it behaves without it myself, so I put it there, just in case...

**Comment by maggu2810** [comment]
In my setup I have another component that reference the mDNS service. mDNS is working all the time (immediate could be false in this setup, it is started because it is used).
So I would expect that immediate = true is sufficient.

As long as modified only calls deactivate, activate I don't think that it is necessary, but we could leave it here and implement a "handle configuration change without reactivate" later.

Okay for you? Then I will merge.

**Comment by kaikreuzer** [comment]
Ok, I have removed the `modified`method again.

**Pull request merged**
