### PR TITLE
Add ability to find out when a timer will fire

### PR DESCRIPTION
**Pull request by evansj**
This commit adds the method Timer#getScheduledFireTime(), returning an AbstractInstant if the timer has not yet fired, or null if it has already fired.

Also:

* updated the tests so that the MockScheduler gets reset before each test
* reset the Quartz subsystem back to defaults when the test class is finished

Signed-off-by: Jon Evans <jon.evans@pobox.com>

### CODE REVIEW

**Comment by evansj** [comment]
Hi @kaikreuzer 

I'd be happy to take a look at both of those.

Regarding getting rid of joda-time - currently `org.joda.time.DateTime.now` is injected into the rules. Wdyt about also replacing that with `java.time.ZonedDateTime.now`? The APIs are different but I think all of the most common methods are still there, (`plusSeconds()`, `plusMinutes()` etc.)

If we leave that as org.joda.time.DateTime.now then I think we'd also need to keep compatible methods in the ScriptExecution class, e.g. `createTimer(joda Instant)`.

**Comment by maggu2810** [comment]
> I think we should dare to break the compatibility here for having a clean API again.

Me, too. :wink:

**Comment by evansj** [comment]
I finished replacing `org.joda.time` with `java.time`.

Some questions:

I've introduced a new `JavaTime` class with two static methods to be injected into the scripts. I did this because previously *all* static methods of `org.joda.time.DateTime` were added, but that was only 5 methods. `java.time.ZonedDateTime` has 13 static methods and I thought that they would just pollute the namespace (e.g. `parse(CharSequence)` etc.). I chose to add just `now()` and `now(ZoneId)`, but I'm open to suggestions.

In `ScriptImportSectionNamespaceScopeProvider` I also replaced the implicit import of `org.joda.time` with `java.time`. Thoughts?

**Comment by kaikreuzer** [comment]
@evansj Please see https://community.openhab.org/t/oh2-4-1428-java-8-datetime-api/56909/6 - it looks as if the `now` has lost some widely used methods. Would it makes sense to bring them back (and maybe mark them deprecated)?

**Comment by evansj** [comment]
I’m not near a computer at the moment - I will possibly have some time to look into this tomorrow. The problem with “bringing the methods back” is that as far as I can tell from the javadocs, `java.time.ZonedDateTime` is a `final` class, so we can’t extend it.

**Comment by mhilbush** [comment]
Maybe it would be a good idea to revert this change until we can get things sorted out. It's likely that there are ways to accomplish the same thing using ZonedDateTime.

Maybe we could talk @rkoshak into developing a migration guide for the forum. 😉  🤞 

Here are some examples (thanks to Udo for some of these):
```
now.plusMillis(150)  -> plus(150, ChronoUnit.MILLISECONDS) would work, but java.util.concurrent.ChronoUnit is not available in rules
```
```
now.getHourOfDay -> now.getHour should work
```
```
now.withTimeAtStartOfDay -> now.truncatedTo(ChronoUnit.DAYS) might work, but java.util.concurrent.ChronoUnit is not available in rules
```
```
Constructs like now.isAfter((DawnStart_Time.state as DateTimeType).zonedDateTime.toInstant().toEpochMilli) needs to be replaced with now.isAfter((DawnStart_Time.state as DateTimeType).zonedDateTime)
```

**Comment by rkoshak** [comment]
I definitely will write something up. I thought I had more time though. 5iver have me the heads up a couple days ago this was coming.

I've been focusing mostly on the first draft of the experimental rules guide. I didn't realize this change had already made it into OH.

I'll hold off until a decision is made re backing it out or extending now somehow since it's final.

Im with Kai. If we make everyone have to change

**Comment by kaikreuzer** [comment]
@mhilbush & @rkoshak Yeah, sorry, I didn't look close enough into this change and wasn't aware that method names had actually changed.

I'd be ok with reverting the change and maybe even postpone it to after the openHAB 2.4 release. This would leave us some time wrt migration process & documentation and I had discussed with @openhab-5iver that I'd like to do a plan with both of you how we can get the new rule engine out of the experimental state and remove the old one after the 2.4 release. So as bigger changes are anyway ahead, we might want to postpone this change until then. Wdyt?

**Comment by mhilbush** [comment]
Everything you say makes sense. I'm good with reverting the change until after 2.4.

**Comment by kaikreuzer** [comment]
@evansj Hope this is fine with you as well if we wait a few more weeks!

**Comment by kaikreuzer** [comment]
Created https://github.com/eclipse/smarthome/pull/6528

**Comment by evansj** [comment]
@kaikreuzer totally fine with me! Sorry I wasn’t around today to help.

**Comment by maggu2810** [comment]
IIRC I already request to define the API (provide interfaces and documentation) about the methods (static and object related ones) that can be used by the rule engine.
Wouldn't it make sense to start with such an definition?
Wouldn't it make sense to use a custom ESH rule / script API that wraps the internal implementation so the API keeps the same and we use internally whatever we want (for time e.g. Joda, Java's Date / Time API, ...). So, if we ever went to another implementation all rules can stay untouched.

For the moment we could revert the "drop Joda improvement" but IMHO this would definitely make sense to break existing stuff (hopefully) only once.

**Comment by rkoshak** [comment]
For the curious I've started some docs on the Next Gen RE [here](https://community.openhab.org/t/experimental-next-gen-rules-engine-documentation-1-of-introduction/54669) (it's a series of posts, follow the links at the bottom to navigate).

They are not complete and are a bit unorganized. Help is appreciated.

I have a running list of stuff that is either broken or not possible, some of which probably need to be addressed before we take it out of experimental. I've already been working with David on ideas for Timers, see #6519. I look forward to the discussion.

**Pull request merged**
