### PR TITLE
added HTTP client dependency to Karaf feature

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by maggu2810** [comment]
I try to understand that change...
If the Bose SoundTouch binding requires that feature, why does the feature verification succeed without that feature?

**Comment by kaikreuzer** [comment]
That's a very good question, @maggu2810! I also have no clue, why the feature validation actually succeeds - as we have the "jetty http client" as an optional dependency and a feature that is not mandatory for an ESH solution, I would actually expect that the validation should fail unless this dependency is declared.

My problem at hand is that I get this error, when installing the binding on Karaf:
```
07:51:08.692 [ERROR] [.core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-binding-bosesoundtouch': Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-binding-bosesoundtouch; type=karaf.feature; version="[2.3.0.SNAPSHOT,2.3.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-binding-bosesoundtouch)(type=karaf.feature)(version>=2.3.0.SNAPSHOT)(version<=2.3.0.SNAPSHOT))" [caused by: Unable to resolve openhab-binding-bosesoundtouch/2.3.0.SNAPSHOT: missing requirement [openhab-binding-bosesoundtouch/2.3.0.SNAPSHOT] osgi.identity; osgi.identity=esh-binding-bosesoundtouch; type=karaf.feature [caused by: Unable to resolve esh-binding-bosesoundtouch/0.10.0.SNAPSHOT: missing requirement [esh-binding-bosesoundtouch/0.10.0.SNAPSHOT] osgi.identity; osgi.identity=org.eclipse.smarthome.binding.bosesoundtouch; type=osgi.bundle; version="[0.10.0.201805151356,0.10.0.201805151356]"; resolution:=mandatory [caused by: Unable to resolve org.eclipse.smarthome.binding.bosesoundtouch/0.10.0.201805151356: missing requirement [org.eclipse.smarthome.binding.bosesoundtouch/0.10.0.201805151356] osgi.wiring.package; filter:="(osgi.wiring.package=org.eclipse.jetty.websocket.client)" [caused by: Unable to resolve org.eclipse.jetty.websocket.client/9.3.21.v20170918: missing requirement [org.eclipse.jetty.websocket.client/9.3.21.v20170918] osgi.identity; osgi.identity=pax-jetty-condition-pax_http_whiteboard; type=karaf.feature; version="[9.3.21.v20170918,9.3.21.v20170918]"; resolution:=mandatory [caused by: Unable to resolve pax-jetty-condition-pax_http_whiteboard/9.3.21.v20170918: missing requirement [pax-jetty-condition-pax_http_whiteboard/9.3.21.v20170918] osgi.identity; osgi.identity=pax-http-whiteboard; type=karaf.feature; condition:=true]]]]]
```
Not sure if this change here would really help - maybe it is again some interference of the pax-web feature...?

**Comment by maggu2810** [comment]
I build a custom distribution without any ESH feature installed on start.

```text
karaf@root()> feature:list | grep ^esh
esh-binding-astro                           │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-bluetooth                       │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-bluetooth-bluez                 │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-bluetooth-blukii                │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-bosesoundtouch                  │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-digitalstrom                    │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-dmx                             │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-hue                             │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-fsinternetradio                 │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-lifx                            │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-lirc                            │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-ntp                             │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-serialbutton                    │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-sonos                           │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-tradfri                         │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-weatherunderground              │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-wemo                            │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-binding-yahooweather                    │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-extensionservice-marketplace            │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-extensionservice-marketplace-automation │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-transform-exec                          │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │ Exec Transformation
esh-transform-javascript                    │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │ Javascript Transformation
esh-transform-jsonpath                      │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │ JSONPath Transformation
esh-transform-map                           │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │ Map Transformation
esh-transform-regex                         │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │ RegEx Transformation
esh-transform-scale                         │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │ Scale Transformation
esh-transform-xpath                         │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │ XPath Transformation
esh-transform-xslt                          │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │ XSLT Transformation
esh-ui-basic                                │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-ui-classic                              │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-ui-paper                                │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-ui-iconset-classic                      │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │
esh-io-mqttembeddedbroker                   │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │ Embedded MQTT Broker
esh-io-javasound                            │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │ JavaSound Audio Support
esh-io-webaudio                             │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │ Web Audio Support
esh-voice-mactts                            │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-ext-0.10.0-SNAPSHOT  │ MacOS Text-to-Speech
esh-tp                                      │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │ Eclipse SmartHome Target Platform
esh-tp-apache-commons                       │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │
esh-tp-coap                                 │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │ Californium CoAP library
esh-tp-httpclient                           │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │
esh-tp-jax-rs                               │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │
esh-tp-jax-rs-min                           │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │
esh-kat.cpy-jersey-min-2.22.2               │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │
esh-kat.cpy-swagger-jersey2-1.5.8           │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │
esh-tp-jax-rs-provider-security             │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │ Security provider for jaxrs
esh-tp-jax-rs-provider-swagger              │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │ JAX-RS provider for Swagger integration
esh-tp-jupnp                                │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │ UPnP/DLNA library for Java
esh-tp-jmdns                                │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │ An implementation of multi-cast DNS in Java.
esh-tp-measurement                          │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │
esh-tp-paho                                 │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │ MQTT v3 Client
esh-tp-serial-javacomm                      │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │
esh-tp-serial-rxtx                          │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │
esh-tp-xtext                                │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │ Xtext - Language Engineering Made Easy
esh-tp-xtext-ide                            │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │ Xtext - IDE Support
esh-tp-lsp4j                                │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-tp-0.10.0-SNAPSHOT   │ Eclipse LSP4J
esh-base                                    │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │ ESH
esh-auth-jaas                               │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-automation-api                          │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-automation-commands                     │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-automation-core                         │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-automation-module-core                  │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-automation-module-script                │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-automation-module-script-defaultscope   │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-automation-module-script-rulesupport    │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-automation-module-media                 │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-automation-module-timer                 │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-automation-parser-gson                  │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-automation-providers                    │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-automation-rest                         │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-config-serial                           │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-config-discovery-usbserial              │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-io-console-karaf                        │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │ Karaf Console support for SmartHome stuff
esh-io-rest-auth                            │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-io-rest-auth-basic                      │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-io-rest-log                             │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-io-rest-sitemap                         │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-io-rest-voice                           │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-io-rest-mdns                            │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-io-transport-coap                       │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-io-transport-dbus                       │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-io-transport-mdns                       │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-io-transport-mqtt                       │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-io-transport-http                       │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-io-transport-serial                     │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-io-transport-serial-javacomm            │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-io-transport-serial-rxtx                │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-io-transport-upnp                       │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-item                              │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-item-runtime                      │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-item-ide                          │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-persistence                       │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-persistence-runtime               │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-persistence-ide                   │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-rule                              │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-rule-runtime                      │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-rule-ide                          │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-script                            │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-script-runtime                    │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-script-ide                        │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-sitemap                           │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-sitemap-runtime                   │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-sitemap-ide                       │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-thing                             │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-thing-runtime                     │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-thing-ide                         │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-model-lsp                               │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-storage-mapdb                           │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-storage-json                            │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-ui                                      │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
esh-ui-icon                                 │ 0.10.0.SNAPSHOT  │          │ Uninstalled │ esh-core-0.10.0-SNAPSHOT │
```

There is also no Jetty bundle installed:

```text
karaf@root()> bundle:list -t 0 -l | grep jetty
karaf@root()>
```

After that I installed the Bose SoundTouch binding
```text
karaf@root()> feature:install esh-binding-bosesoundtouch
```

Karaf did not complain about missing wiring information or similar.
So, I assume this is not a problem in general but perhaps by your setup.
WDYT?

**Comment by kaikreuzer** [comment]
Bose SoundTouch defines [those mandatory package imports](https://github.com/eclipse/smarthome/blob/master/extensions/binding/org.eclipse.smarthome.binding.bosesoundtouch/META-INF/MANIFEST.MF#L18-L22) - could you check how these can be possibly resolved in your example?

**Comment by maggu2810** [comment]
The feature `esh-binding-bosesoundtouch` (https://github.com/eclipse/smarthome/blob/b5839c8e835bcc8b519e5d86f61807adb109dae2/features/karaf/esh-ext/src/main/feature/feature.xml#L40) trigger an installation of the feature `esh-base` (https://github.com/eclipse/smarthome/blob/b5839c8e835bcc8b519e5d86f61807adb109dae2/features/karaf/esh-ext/src/main/feature/feature.xml#L41).

The `esh-base` feature brings the target platform into the game:
https://github.com/eclipse/smarthome/blob/b5839c8e835bcc8b519e5d86f61807adb109dae2/features/karaf/esh-core/src/main/feature/feature.xml#L20

There is a target platform feature for httpclient stuff:
https://github.com/eclipse/smarthome/blob/b5839c8e835bcc8b519e5d86f61807adb109dae2/features/karaf/esh-tp/src/main/feature/feature.xml#L24

This one brings in the necessary bundles:
https://github.com/eclipse/smarthome/blob/b5839c8e835bcc8b519e5d86f61807adb109dae2/features/karaf/esh-tp/src/main/feature/feature.xml#L59

**Comment by kaikreuzer** [comment]
Which again shows us that there is a mess wrt dependencies of the features to the tp.

The tp should imho only define core capabilities that must be present on an system in order to run a minimal ESH (i.e. the `esh-base` feature). All the rest should be optional and be referenced by the features that need it, like we ask bindings to declare in the Karaf feature that they need mNDS, UPnP, etc.). Not sure though, how we can best get there...

**Comment by maggu2810** [comment]
It is already optional.

The current situation is that the tp features contains the same feature set (at least it has been the intention) as the TP in the Eclipse IDE.
Bundles will be installed automatically to fulfill the requirements of the ESH bundles.

Only if there are requirements that are not expressed by package imports e.g. we would like to force an implementation instead of the API be present only, the feature is explicitly listened (by a requirement in the resp. feature and a capability in a TP feature).

We could use custom esh-tp `capability` and `requirements` only (and just use dependency=true for the a fallback feature) in all our features.
I will agree on that.

Just need someone with a few spare time that would like to do that job.

**Comment by maggu2810** [comment]
This would also link to #5140

**Comment by kaikreuzer** [comment]
Replaced by #5612.

**Pull request closed without merging**
