### PR TITLE
Use configurationPid instead of name in OSGI services

### PR DESCRIPTION
**Pull request by triller-telekom**
Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by maggu2810** [comment]
Isn't the configuration PID equal to the name of the component if not explicitly set?
Has it been different on 4.2?

Could we please add the reason (e.g. link to a bug report, forum entry, etc.) why a PR / change is done?
For me it is not clear.

**Comment by maggu2810** [comment]
Ah okay, will continue reading https://github.com/eclipse/smarthome/pull/4113

**Comment by kaikreuzer** [comment]
> Could we please add the reason (e.g. link to a bug report, forum entry, etc.) why a PR / change is done?

We definitely should - @triller-telekom, please always add some comments about the "why" on such PRs, thanks!

**Comment by triller-telekom** [comment]
Sorry @maggu2810 next time I will include a link to the discussion

**Comment by maggu2810** [comment]
@triller-telekom All fine, thank you :wink:

**Pull request merged**
