### PR TITLE
added Logging configuration to testing documentation

### PR DESCRIPTION
**Pull request by BenediktNiehues**
Signed-off-by: Benedikt Niehues <b.niehues@external.telekom.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
This new XML section contains the same content as the section above it, plus some additional infos. Might it make sense to merge the two sections into one, assuming that everybody actually wants to enable the logging?

**Comment by BenediktNiehues** [comment]
We should keep it separated as there are two different use-cases and different error-sources. This way I think it is easier to look up and search for the cases in the documentation.

**Comment by kaikreuzer** [comment]
Well, we should document how we want people to do it. And is there really a situation where we would not want to have the logging configured correctly?
And even if, then the new section should concentrate on the parts that need to be added for logging and not include equinox.ds etc. again in it.

**Comment by BenediktNiehues** [comment]
It is now integrated in the overall surefire configuration section

**Comment by kaikreuzer** [comment]
Thanks a lot!

**Pull request merged**
