### PR TITLE
for annotated methods the cardinality is implicit mandatory

### PR DESCRIPTION
**Pull request by maggu2810**
Related to #4738

@lpapazow Can you check your formatter, it seems to work not reliable.
There are missing spaces `immediate=true`, tabs are used for intention instead of spaces, ...

@kaikreuzer Shouldn't SAT break the build if tabs are used for indentation?

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@lpapazow might actually be the one with the better knowledge about this.
What [I can see](https://github.com/openhab/static-code-analysis/pull/235/files#diff-63767b6e0071833a15e9215a887b807cR73) is that we have a check for XMLs, but even this will only issue a warning (and thus not break the build. Afaik, we do not have a check for Java files in place as we expect the format-on-save option to take care of that.

If you think we should enforce the spaces, we can discuss this.

**Comment by maggu2810** [comment]
> If you think we should enforce the spaces, we can discuss this.

We should discuss some time, how we could enforce that the correct formatter (IDE setup) is used.

**Comment by kaikreuzer** [comment]
Not sure if it is possible to have the full IDE formatting settings checked in the build.
Checking tabs vs. spaces might be a simple new check, though.

**Comment by svilenvul** [comment]
Regarding the indentation.

As long as I remember we have two checks already for spacing:
- FileTabCharacter does not allow tabs in java files (it is a checkstyle  one);
- OnlyTabIdentationInXmlFilesCheck for xml files (our implementation);

As long I see the classes that have tabs are not in "src/main/java" folder. Currently Checkstyle will skip them.

**Pull request merged**
