### PR TITLE
Updated documentation for thing properties

### PR DESCRIPTION
**Pull request by tomhoefer**
Signed-off-by: Thomas Höfer <t.hoefer@telekom.de>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
@maggu2810 As you are building your own solution as well as bindings on ESH and this documentation targets these two use cases, would you want to review the text and provide your feedback whether it is clear, too fuzzy or lacking something?

**Comment by maggu2810** [comment]
Have read it and it sounds okay. Will have a better understanding after I first used this feature.

**Comment by dnobel** [comment]
I think the description how to update properties from a binding, should be moved to the "Thing Handler" chapter. It takes too much space in the binding tutorial. It would be better to mention and link it there.

**Comment by kaikreuzer** [comment]
@dnobel, agreed, especially as it does not specifically ask binding developers to do something, it is a bit distractive from the essential parts of the tutorial.

**Comment by tomhoefer** [comment]
Updated the documentation

**Comment by kaikreuzer** [comment]
Thanks!

**Pull request merged**
